#ifndef RUNNER_D_CODE_ADDRESSES
#define RUNNER_D_CODE_ADDRESSES

#define runner_d_start_task_initialization_task		(0x14)
#define runner_d_initialization_task		(0x14)
#define runner_d_start_task_timer_scheduler_set		(0x1AD4)
#define runner_d_timer_scheduler_set		(0x1AD4)
#define runner_d_start_task_flow_cache_wakeup_request		(0xC44)
#define runner_d_flow_cache_wakeup_request		(0xC44)
#define runner_d_start_task_lan_dispatch_wakeup_request		(0x1834)
#define runner_d_lan_dispatch_wakeup_request		(0x1834)
#define runner_d_start_task_debug_routine		(0x6C)
#define runner_d_debug_routine		(0x6C)
#define runner_d_start_task_free_skb_index_wakeup_request		(0x1C50)
#define runner_d_free_skb_index_wakeup_request		(0x1C50)
#define runner_d_free_skb_index_tx_abs_done		(0x1C50)
#define runner_d_gpe_sop_push_replace_ddr_sram_32		(0x11E8)
#define runner_d_gpe_sop_push_replace_sram_32_64		(0x125C)
#define runner_d_gpe_sop_push_replace_sram_64		(0x1270)
#define runner_d_gpe_sop_push_replace_sram_64_32		(0x1284)
#define runner_d_gpe_sop_pull_replace_ddr_sram_32		(0x1298)
#define runner_d_gpe_sop_pull_replace_sram_32_64		(0x130C)
#define runner_d_gpe_sop_pull_replace_sram_64		(0x135C)
#define runner_d_gpe_sop_pull_replace_sram_64_32		(0x1398)
#define runner_d_gpe_replace_pointer_32_ddr		(0x13E8)
#define runner_d_gpe_replace_pointer_32_sram		(0x140C)
#define runner_d_gpe_replace_pointer_64_sram		(0x1430)
#define runner_d_gpe_replace_16		(0x1454)
#define runner_d_gpe_replace_32		(0x1488)
#define runner_d_gpe_replace_bits_16		(0x14AC)
#define runner_d_gpe_copy_add_16_cl		(0x14D8)
#define runner_d_gpe_copy_add_16_sram		(0x14E4)
#define runner_d_gpe_copy_bits_16_cl		(0x152C)
#define runner_d_gpe_copy_bits_16_sram		(0x1538)
#define runner_d_gpe_insert_16		(0x1580)
#define runner_d_gpe_delete_16		(0x15E8)
#define runner_d_gpe_decrement_8		(0x1628)
#define runner_d_gpe_apply_icsum_16		(0x164C)
#define runner_d_gpe_apply_icsum_nz_16		(0x1670)
#define runner_d_gpe_compute_csum_16_cl		(0x16AC)
#define runner_d_gpe_compute_csum_16_sram		(0x16B8)
#define runner_d_gpe_buffer_copy_16_sram		(0x16F8)
#define runner_d_gpe_buffer_copy_16_ddr		(0x1720)
#define runner_d_upstream_ingress_rate_limiter_budget_allocate		(0x1B54)
#define runner_d_upstream_quasi_budget_allocate		(0x1BD4)
#define runner_d_schedule_free_skb_index		(0x1C34)

#endif
