#ifndef RUNNER_D_CODE_ADDRESSES
#define RUNNER_D_CODE_ADDRESSES

#define runner_d_start_task_initialization_task		(0x14)
#define runner_d_initialization_task		(0x14)
#define runner_d_start_task_timer_scheduler_set		(0x19A4)
#define runner_d_timer_scheduler_set		(0x19A4)
#define runner_d_start_task_flow_cache_wakeup_request		(0xB40)
#define runner_d_flow_cache_wakeup_request		(0xB40)
#define runner_d_start_task_lan_dispatch_wakeup_request		(0x175C)
#define runner_d_lan_dispatch_wakeup_request		(0x175C)
#define runner_d_start_task_lan_cpu_wakeup_request		(0x154)
#define runner_d_lan_cpu_wakeup_request		(0x154)
#define runner_d_start_task_debug_routine		(0x6C)
#define runner_d_debug_routine		(0x6C)
#define runner_d_start_task_free_skb_index_wakeup_request		(0x1B20)
#define runner_d_free_skb_index_wakeup_request		(0x1B20)
#define runner_d_free_skb_index_tx_abs_done		(0x1B20)
#define runner_d_start_task_dhd_rx_complete_wakeup_request		(0x1BF4)
#define runner_d_dhd_rx_complete_wakeup_request		(0x1BF4)
#define runner_d_gpe_sop_push_replace_ddr_sram_32		(0x1118)
#define runner_d_gpe_sop_push_replace_sram_32_64		(0x1188)
#define runner_d_gpe_sop_push_replace_sram_64		(0x119C)
#define runner_d_gpe_sop_push_replace_sram_64_32		(0x11B0)
#define runner_d_gpe_sop_pull_replace_ddr_sram_32		(0x11C4)
#define runner_d_gpe_sop_pull_replace_sram_32_64		(0x1234)
#define runner_d_gpe_sop_pull_replace_sram_64		(0x1284)
#define runner_d_gpe_sop_pull_replace_sram_64_32		(0x12C0)
#define runner_d_gpe_replace_pointer_32_ddr		(0x1310)
#define runner_d_gpe_replace_pointer_32_sram		(0x1334)
#define runner_d_gpe_replace_pointer_64_sram		(0x1358)
#define runner_d_gpe_replace_16		(0x137C)
#define runner_d_gpe_replace_32		(0x13B0)
#define runner_d_gpe_replace_bits_16		(0x13D4)
#define runner_d_gpe_copy_add_16_cl		(0x1400)
#define runner_d_gpe_copy_add_16_sram		(0x140C)
#define runner_d_gpe_copy_bits_16_cl		(0x1454)
#define runner_d_gpe_copy_bits_16_sram		(0x1460)
#define runner_d_gpe_insert_16		(0x14A8)
#define runner_d_gpe_delete_16		(0x1510)
#define runner_d_gpe_decrement_8		(0x1550)
#define runner_d_gpe_apply_icsum_16		(0x1574)
#define runner_d_gpe_apply_icsum_nz_16		(0x1598)
#define runner_d_gpe_compute_csum_16_cl		(0x15D4)
#define runner_d_gpe_compute_csum_16_sram		(0x15E0)
#define runner_d_gpe_buffer_copy_16_sram		(0x1620)
#define runner_d_gpe_buffer_copy_16_ddr		(0x1648)
#define runner_d_upstream_ingress_rate_limiter_budget_allocate		(0x1A24)
#define runner_d_upstream_quasi_budget_allocate		(0x1AA4)
#define runner_d_schedule_free_skb_index		(0x1B04)

#endif
