#!/bin/sh -e
# SPDX-License-Identifier: 0BSD

trap 'rm -f "$tmpf"' EXIT INT
tmpf="$(mktemp -t "netstat-nat.XXXXXXXXXX")"
netstat_nat="./netstat-nat"
command -v diff > /dev/null && alias cmp='diff -u'


in_szarotka() { NETSTAT_NAT_LOCAL_ADDRS='fc00:e355:e73f:b463:a28e:529d:7838:65be 127.0.0.1       192.168.1.1'                                "$netstat_nat" "$@" test-data/nf_conntrack.szarotka; }
in_tarta()    { NETSTAT_NAT_LOCAL_ADDRS='                                        127.000.000.001 192.168.1.250 ::1 fe80::226:b9ff:fe86:fdce' "$netstat_nat" "$@" test-data/nf_conntrack.tarta   ; }


printf '%-5s %-30s %-30s %s\n' 'Proto' 'Source Address' 'Destination Address' 'State'                                  \
                               'icmp'  'fc00:e355:e73f:b463:a28e:529d:' 'fc00:4ae7:d829:fd6c:10d:92f0:f' 'ESTABLISHED' \
                               'tcp'   '192.168.1.1:43356'              '192.168.1.250:3493'             'ESTABLISHED' \
                               'tcp'   '192.168.1.1:53818'              '192.168.1.250:445'              'ESTABLISHED' \
                               'tcp'   '192.168.1.1:853'                '192.168.1.250:2049'             'ESTABLISHED' \
                               'tcp'   '192.168.1.109:63651'            '192.168.1.1:22'                 'ESTABLISHED' \
                               'tcp'   '192.168.1.250:1016'             '192.168.1.1:2049'               'ESTABLISHED' \
                               'tcp'   '192.168.1.250:48834'            '192.168.1.1:19999'              'TIME_WAIT'   \
                               'tcp'   '192.168.1.250:50964'            '192.168.1.1:9050'               'CLOSE'       \
                               'tcp'   '192.168.1.250:54752'            '192.168.1.1:9050'               'CLOSE'       \
                               'tcp'   '192.168.1.250:54888'            '192.168.1.1:19999'              'TIME_WAIT'   \
                               'tcp'   '192.168.1.250:775'              '192.168.1.1:2049'               'ESTABLISHED' \
                               'tcp'   '[fc00:e355:e73f:b463:a2]:34012' '[fc00:4ae7:d829:fd6c:10d:]:443' 'ESTABLISHED' \
                               'udp'   '192.168.1.250:56575'            '192.168.1.1:53'                 'UNREPLIED'   > "$tmpf"
in_szarotka -nL | cmp - "$tmpf"

printf '%-5s %-40s %-40s %s\n' 'Proto' 'Source Address' 'Destination Address' 'State'                                                        \
                               'icmp'  'fc00:e355:e73f:b463:a28e:529d:7838:65be'  'fc00:4ae7:d829:fd6c:10d:92f0:f19d:851b'   'ESTABLISHED'   \
                               'tcp'   '192.168.1.250:1016'                       '192.168.1.1:2049'                         'ESTABLISHED'   \
                               'tcp'   '[fc00:e355:e73f:b463:a28e:529d:78]:34012' '[fc00:4ae7:d829:fd6c:10d:92f0:f19d:]:443' 'ESTABLISHED'   \
                               'tcp'   '192.168.1.1:43356'                        '192.168.1.250:3493'                       'ESTABLISHED'   \
                               'tcp'   '192.168.1.250:48834'                      '192.168.1.1:19999'                        'TIME_WAIT'     \
                               'tcp'   '192.168.1.250:50964'                      '192.168.1.1:9050'                         'CLOSE'         \
                               'tcp'   '192.168.1.1:53818'                        '192.168.1.250:445'                        'ESTABLISHED'   \
                               'tcp'   '192.168.1.250:54752'                      '192.168.1.1:9050'                         'CLOSE'         \
                               'tcp'   '192.168.1.250:54888'                      '192.168.1.1:19999'                        'TIME_WAIT'     \
                               'tcp'   '192.168.1.109:63651'                      '192.168.1.1:22'                           'ESTABLISHED'   \
                               'tcp'   '192.168.1.250:775'                        '192.168.1.1:2049'                         'ESTABLISHED'   \
                               'tcp'   '192.168.1.1:853'                          '192.168.1.250:2049'                       'ESTABLISHED'   \
                               'udp'   '192.168.1.250:56575'                      '192.168.1.1:53'                           'UNREPLIED'     > "$tmpf"
in_szarotka -nNLxr src-port | cmp - "$tmpf"

printf '%-5s %-30s %-30s %s\n' 'Proto' 'Source Address' 'Destination Address' 'State' > "$tmpf"
in_szarotka -nR | cmp - "$tmpf"


printf '%-5s %-30s %-30s %s\n' 'Proto' 'NATed Address' 'Destination Address' 'State'  \
                               'tcp'   '192.168.1.250:45660'            '142.132.234.132:2016'           'ESTABLISHED' \
                               'tcp'   '192.168.1.250:43860'            '162.159.135.234:443'            'ESTABLISHED' \
                               'tcp'   '192.168.1.250:39862'            '34.107.243.93:443'              'ESTABLISHED' \
                               'tcp'   '192.168.1.250:50616'            '34.107.243.93:443'              'ESTABLISHED' \
                               'tcp'   '192.168.1.250:53462'            '142.250.186.196:443'            'TIME_WAIT'   \
                               'udp'   '192.168.1.250:12337'            '108.162.192.220:53'             ''            \
                               'udp'   '192.168.1.250:52464'            '108.162.193.176:53'             ''            \
                               'udp'   '192.168.1.250:11044'            '173.245.58.220:53'              ''            \
                               'udp'   '192.168.1.250:17210'            '216.239.32.10:53'               ''            \
                               'udp'   '192.168.1.250:22504'            '216.239.32.10:53'               ''            \
                               'udp'   '192.168.1.250:45830'            '216.239.36.10:53'               ''            \
                               'udp'   '192.168.1.250:59949'            '216.239.38.10:53'               ''            \
                               'udp'   '192.168.1.250:51413'            '18.190.61.127:6881'             'ASSURED'     \
                               'udp'   '192.168.1.250:51413'            '186.10.181.37:1337'             'ASSURED'     \
                               'udp'   '192.168.1.250:51413'            '23.168.232.9:1337'              'ASSURED'     \
                               'udp'   '192.168.1.250:51413'            '54.194.124.68:6882'             'ASSURED'     \
                               'udp'   '192.168.1.250:51413'            '95.82.96.230:57264'             'ASSURED'     \
                               'udp'   '192.168.1.147:49361'            '255.255.255.255:6667'           'UNREPLIED'   > "$tmpf"
in_tarta -nSDr state | cmp - "$tmpf"

printf '%-5s %-30s %-30s %-30s %s\n' 'tcp' '10.103.54.126:36996' '45.55.70.6:36996' '192.168.1.250:5900' 'TIME_WAIT' \
                                     'tcp' '10.103.54.126:38714' '45.55.70.6:38714' '192.168.1.250:5900' 'TIME_WAIT' \
                                     'tcp' '10.103.54.126:42354' '45.55.70.6:42354' '192.168.1.250:5900' 'TIME_WAIT' \
                                     'tcp' '10.103.54.126:43728' '45.55.70.6:43728' '192.168.1.250:5900' 'TIME_WAIT' \
                                     'tcp' '10.103.54.126:48134' '45.55.70.6:48134' '192.168.1.250:5900' 'TIME_WAIT' \
                                     'tcp' '10.103.54.126:50652' '45.55.70.6:50652' '192.168.1.250:5900' 'TIME_WAIT' \
                                     'tcp' '10.103.54.126:54304' '45.55.70.6:54304' '192.168.1.250:5900' 'TIME_WAIT' \
                                     'tcp' '10.103.54.126:54528' '45.55.70.6:54528' '192.168.1.250:5900' 'TIME_WAIT' \
                                     'tcp' '10.103.54.126:57288' '45.55.70.6:57288' '192.168.1.250:5900' 'TIME_WAIT' > "$tmpf"
in_tarta -nSoN -g 165.22.181.167,45.55.70.6 -s 10.103.54.126 -s 10.153.205.11 | cmp - "$tmpf"
