#! /bin/sh

APPS_MOUNTED_PATH=`nvram get apps_mounted_path`
APPS_INSTALL_FOLDER=`nvram get apps_install_folder`
APPS_INSTALL_PATH=$APPS_MOUNTED_PATH/$APPS_INSTALL_FOLDER

#rm -rf $APPS_INSTALL_PATH/bin/asus_lighttpd
#rm -rf $APPS_INSTALL_PATH/lib/mod_*
#rm -rf $APPS_INSTALL_PATH/etc/asus_conf.d
#rm -rf $APPS_INSTALL_PATH/etc/asus_script
#rm -rf $APPS_INSTALL_PATH/etc/asus_*
#rm -rf $APPS_INSTALL_PATH/etc/downloadmaster
#rm -rf $APPS_INSTALL_PATH/etc/init.d/S50asuslighttpd
#rm -rf /tmp/asus_router.conf
#rm -rf /tmp/APPS/Lighttpd/
#rm -rf /tmp/http_info
#rm -rf /tmp/http_info_changed
