#!/bin/sh
echo "ipkg-opt,2,preinst start" >>/tmp/tina
apps_ipkg_old=`nvram get apps_ipkg_old`
is_arm_machine=`uname -m |grep arm`

APPS_PATH=/opt
CONF_FILE=$APPS_PATH/etc/ipkg.conf
ASUS_SERVER=`nvram get apps_ipkg_server`
wget_timeout=`nvram get apps_wget_timeout`
#wget_options="-nv -t 2 -T $wget_timeout --dns-timeout=120"
wget_options="-q -t 2 -T $wget_timeout"
apps_from_internet=`nvram get rc_support |grep appnet`
apps_local_space=`nvram get apps_local_space`
APPS_INSTALL_FOLDER=`nvram get apps_install_folder`
APPS_MOUNTED_PATH=`nvram get apps_mounted_path`
APPS_INSTALL_PATH=$APPS_MOUNTED_PATH/$APPS_INSTALL_FOLDER
ASUS_LIGHTTPD_VER=3.1.0.91
CPFLAG="NO"

#2016.11.7 tina add for staging old environment{
APPS_INSTALL_FOLDER_BAK=$APPS_INSTALL_FOLDER".bak"
APPS_INSTALL_PATH_BAK=$APPS_MOUNTED_PATH/$APPS_INSTALL_FOLDER_BAK
ASUS_UCLIBC_VER=1.0.15-1
download_file=
APP_LIB=$APPS_INSTALL_PATH/lib
APP_LINK_DIR=/tmp/opt
APP_LINK_LIB=$APP_LINK_DIR/lib
install_log2=$APPS_INSTALL_PATH/ipkg_log2.txt
install_log=$APPS_INSTALL_PATH/ipkg_log.txt

_remove_old_ipk(){
	REMOVE_LIST="libcurl openssl libxml2 wxbase zlib libevent libpar2 libsigc++ pcre spawn-fcgi expat readline libstdc++ bzip2 asuslighttpd ncurses"
	for remove_file in $REMOVE_LIST; do
		echo "ipkg-opt,preinst,34,ipkg remove $remove_file -force-depends 1 >> $APPS_INSTALL_PATH/ipkg_log_2.txt" >>/tmp/tina
		ipkg remove $remove_file -force-depends 1>> $APPS_INSTALL_PATH/ipkg_log_1.txt
		wait
	done
	echo "ipkg-opt preinst,38" >>/tmp/tina
	rm -rf $APPS_INSTALL_PATH/ipkg_log_1.txt
}
echo "ipkg-opt,preinst,41" >>/tmp/tina


#ipkg_ready=`which ipkg`
#if [ -n "$ipkg_ready" ]; then	
	#_remove_old_ipk
#fi
echo "ipkg-opt preinst,48,preinst end" >>/tmp/tina
#end tina}
