0,/#include "rdd_data_structures_auto.h"/p
/>>>RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR /,/<<<RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR /p
/>>>RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR /,/<<<RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR /p
/>>>RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR /,/<<<RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR /p
/>>>RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR /,/<<<RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR /p
/>>>RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR /,/<<<RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR /p
/>>>RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR /,/<<<RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR /p
/>>>RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR /,/<<<RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR /p
/>>>RDD_CPU_TX_RING_TABLE_ADDRESS_ARR /,/<<<RDD_CPU_TX_RING_TABLE_ADDRESS_ARR /p


