# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2009 Freescale Semiconductor, Inc.

obj-y			+= mx51evk.o
obj-$(CONFIG_VIDEO)	+= mx51evk_video.o
