# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2011 - 2013 CompuLab, Ltd. <www.compulab.co.il>
#
# Author: Igor Grinberg <grinberg@compulab.co.il>

obj-y				+= common.o
obj-$(CONFIG_SYS_I2C)		+= eeprom.o
obj-$(CONFIG_LCD)		+= omap3_display.o
obj-$(CONFIG_SMC911X)		+= omap3_smc911x.o
