# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2004-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2007 Wind River Systems Inc <www.windriver.com>.
# Added support for Wind River SBC8548 board

obj-y	+= sbc8548.o
obj-y	+= law.o
obj-y	+= tlb.o
obj-$(CONFIG_SYS_FSL_DDR2) += ddr.o
