ifdef BCM_KF # defined(CONFIG_BCM_KF_OPTEE_414_BACKPORTS)
# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_OPTEE) += optee.o
optee-objs += core.o
optee-objs += call.o
optee-objs += rpc.o
optee-objs += supp.o
endif
