# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2015 Thomas Chou <thomas@wytron.com.tw>

obj-y += timer-uclass.o
obj-$(CONFIG_AG101P_TIMER) += ag101p_timer.o
obj-$(CONFIG_ALTERA_TIMER)	+= altera_timer.o
obj-$(CONFIG_ARC_TIMER)	+= arc_timer.o
obj-$(CONFIG_AST_TIMER)	+= ast_timer.o
obj-$(CONFIG_ATCPIT100_TIMER) += atcpit100_timer.o
obj-$(CONFIG_ATMEL_PIT_TIMER) += atmel_pit_timer.o
obj-$(CONFIG_CADENCE_TTC_TIMER)	+= cadence-ttc.o
obj-$(CONFIG_DESIGNWARE_APB_TIMER)	+= dw-apb-timer.o
obj-$(CONFIG_MPC83XX_TIMER) += mpc83xx_timer.o
obj-$(CONFIG_OMAP_TIMER)	+= omap-timer.o
obj-$(CONFIG_RENESAS_OSTM_TIMER) += ostm_timer.o
obj-$(CONFIG_RISCV_TIMER) += riscv_timer.o
obj-$(CONFIG_ROCKCHIP_TIMER) += rockchip_timer.o
obj-$(CONFIG_SANDBOX_TIMER)	+= sandbox_timer.o
obj-$(CONFIG_STI_TIMER)		+= sti-timer.o
obj-$(CONFIG_STM32_TIMER)	+= stm32_timer.o
obj-$(CONFIG_X86_TSC_TIMER)	+= tsc_timer.o
obj-$(CONFIG_MTK_TIMER)		+= mtk_timer.o
obj-$(CONFIG_BCM6XXX_TIMER)	+= bcm6xxx_timer.o
