#ifndef RUNNER_D_CODE_ADDRESSES
#define RUNNER_D_CODE_ADDRESSES

#define runner_d_start_task_initialization_task		(0x14)
#define runner_d_initialization_task		(0x14)
#define runner_d_start_task_timer_scheduler_set		(0x1A68)
#define runner_d_timer_scheduler_set		(0x1A68)
#define runner_d_start_task_flow_cache_wakeup_request		(0xBD8)
#define runner_d_flow_cache_wakeup_request		(0xBD8)
#define runner_d_start_task_lan_dispatch_wakeup_request		(0x17C8)
#define runner_d_lan_dispatch_wakeup_request		(0x17C8)
#define runner_d_start_task_debug_routine		(0x6C)
#define runner_d_debug_routine		(0x6C)
#define runner_d_start_task_free_skb_index_wakeup_request		(0x1BE4)
#define runner_d_free_skb_index_wakeup_request		(0x1BE4)
#define runner_d_free_skb_index_tx_abs_done		(0x1BE4)
#define runner_d_gpe_sop_push_replace_ddr_sram_32		(0x117C)
#define runner_d_gpe_sop_push_replace_sram_32_64		(0x11F0)
#define runner_d_gpe_sop_push_replace_sram_64		(0x1204)
#define runner_d_gpe_sop_push_replace_sram_64_32		(0x1218)
#define runner_d_gpe_sop_pull_replace_ddr_sram_32		(0x122C)
#define runner_d_gpe_sop_pull_replace_sram_32_64		(0x12A0)
#define runner_d_gpe_sop_pull_replace_sram_64		(0x12F0)
#define runner_d_gpe_sop_pull_replace_sram_64_32		(0x132C)
#define runner_d_gpe_replace_pointer_32_ddr		(0x137C)
#define runner_d_gpe_replace_pointer_32_sram		(0x13A0)
#define runner_d_gpe_replace_pointer_64_sram		(0x13C4)
#define runner_d_gpe_replace_16		(0x13E8)
#define runner_d_gpe_replace_32		(0x141C)
#define runner_d_gpe_replace_bits_16		(0x1440)
#define runner_d_gpe_copy_add_16_cl		(0x146C)
#define runner_d_gpe_copy_add_16_sram		(0x1478)
#define runner_d_gpe_copy_bits_16_cl		(0x14C0)
#define runner_d_gpe_copy_bits_16_sram		(0x14CC)
#define runner_d_gpe_insert_16		(0x1514)
#define runner_d_gpe_delete_16		(0x157C)
#define runner_d_gpe_decrement_8		(0x15BC)
#define runner_d_gpe_apply_icsum_16		(0x15E0)
#define runner_d_gpe_apply_icsum_nz_16		(0x1604)
#define runner_d_gpe_compute_csum_16_cl		(0x1640)
#define runner_d_gpe_compute_csum_16_sram		(0x164C)
#define runner_d_gpe_buffer_copy_16_sram		(0x168C)
#define runner_d_gpe_buffer_copy_16_ddr		(0x16B4)
#define runner_d_upstream_ingress_rate_limiter_budget_allocate		(0x1AE8)
#define runner_d_upstream_quasi_budget_allocate		(0x1B68)
#define runner_d_schedule_free_skb_index		(0x1BC8)

#endif
