/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: $
 * $Copyright: (c) 2020 Broadcom.
 *
 * <:label-BRCM:2022:DUAL/GPL:standard
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as published by
 * the Free Software Foundation (the "GPL").
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * 
 * A copy of the GPL is available at http://www.broadcom.com/licenses/GPLv2.php, or by
 * writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 * 
 * :>
 * File:        bcm68880.c
 * Purpose:     bcm68880 chip specific information (register, memories, formats etc)
 */
#include "macsec_defs.h"
#include "macsec_types.h"
#include "macsec_macros.h"
#include "macsec_dev.h"
#include "soc/mcm/intenum_68880.h"
#include "soc/memory.h"
#include <soc/mcm/allenum.h>
#include "soc/68880/macsec_fields_68880.h"

soc_mem_info_t soc_mem_list[] =
{
#include "allmems_68880.i"
    {0} /* Extra empty entry for compiler */
}; /* soc_mem_list array */

soc_mem_info_t *soc_memories[] = {
    &soc_mem_list[SOC_MEM_INT_MACSEC_TDM_CALENDARm],
    &soc_mem_list[SOC_MEM_INT_MACSEC_TDM_2_CALENDARm],
    &soc_mem_list[SOC_MEM_INT_ESEC_SA_EXPIRE_STATUSm],
    &soc_mem_list[SOC_MEM_INT_ISEC_SA_EXPIRE_STATUSm],
    &soc_mem_list[SOC_MEM_INT_ESEC_MIB_ROLLOVER_FIFOm],
    &soc_mem_list[SOC_MEM_INT_ISEC_MIB_ROLLOVER_FIFOm],
    &soc_mem_list[SOC_MEM_INT_ESEC_SC_TABLEm],
    &soc_mem_list[SOC_MEM_INT_ESEC_SA_TABLEm],
    &soc_mem_list[SOC_MEM_INT_ESEC_SA_HASH_TABLEm],
    &soc_mem_list[SOC_MEM_INT_SUB_PORT_MAP_TABLEm],
    &soc_mem_list[SOC_MEM_INT_SUB_PORT_POLICY_TABLEm],
    &soc_mem_list[SOC_MEM_INT_ISEC_SC_TABLEm],
    &soc_mem_list[SOC_MEM_INT_ISEC_SA_TABLEm],
    &soc_mem_list[SOC_MEM_INT_ISEC_SA_HASH_TABLEm],
    &soc_mem_list[SOC_MEM_INT_ISEC_SP_TCAM_KEYm],
    &soc_mem_list[SOC_MEM_INT_ISEC_SP_TCAM_MASKm],
    &soc_mem_list[SOC_MEM_INT_ISEC_SC_TCAMm],
    &soc_mem_list[SOC_MEM_INT_ESEC_MIB_MISCm],
    &soc_mem_list[SOC_MEM_INT_ESEC_MIB_SC_UNCTRLm],
    &soc_mem_list[SOC_MEM_INT_ESEC_MIB_SC_CTRLm],
    &soc_mem_list[SOC_MEM_INT_ESEC_MIB_SCm],
    &soc_mem_list[SOC_MEM_INT_ESEC_MIB_SAm],
    &soc_mem_list[SOC_MEM_INT_ISEC_SPTCAM_HIT_COUNTm],
    &soc_mem_list[SOC_MEM_INT_ISEC_SCTCAM_HIT_COUNTm],
    &soc_mem_list[SOC_MEM_INT_ISEC_PORT_COUNTERSm],
    &soc_mem_list[SOC_MEM_INT_ISEC_MIB_SP_UNCTRLm],
    &soc_mem_list[SOC_MEM_INT_ISEC_MIB_SP_CTRL_1m],
    &soc_mem_list[SOC_MEM_INT_ISEC_MIB_SP_CTRL_2m],
    &soc_mem_list[SOC_MEM_INT_ISEC_MIB_SCm],
    &soc_mem_list[SOC_MEM_INT_ISEC_MIB_SAm]
}; /* soc_memories_bcm68880 */

soc_driver_t soc_driver_bcm68880 = 
{
    soc_memories /* mem_info               */
};  /* soc_driver             */

macsec_dev_t msec_devs[SOC_MAX_NUM_DEVICES][CMBB_FL_MACSEC_MAX_PORT_NUM] = {};
soc_control_t *soc_control[SOC_MAX_NUM_DEVICES];

/* End of chip specific bottom matter */
