#!/bin/sh
if [ -z "$3" ] ; then
  echo "Usage: $0 <i2c_addr(7-bit address in hex)> <offset(hex)> <length(1-4)> [val]: Access i2c device"
else
  if [ -z "$4" ] ; then
    echo a $1 $2 $3 > /proc/i2c_gpon/gponPhyTest
  else
    echo a $1 $2 $3 $4 > /proc/i2c_gpon/gponPhyTest
  fi
fi
