# Cirrus CI configuration
# https://cirrus-ci.com/github/libexif/libexif

task:
  name: FreeBSD
  freebsd_instance:
    matrix:
      image_family: freebsd-13-1
      image_family: freebsd-12-3

  env:
    # Set to 10 instead of 1 to avoid problems when new commits are submitted
    # during a run.
    CIRRUS_CLONE_DEPTH: 10
    CFLAGS: -Wall -Wextra -O2
    MAKE_FLAGS: -j 2

  pkginstall_script:
    - pkg install -y autoconf automake libtool gettext-tools gettext-runtime
  configure_script:
    - autoreconf -sivf
    - ./configure --disable-dependency-tracking CFLAGS="$CFLAGS" || { tail -300 config.log; false; }
  compile_script:
    - make V=1
  test_script:
    - make V=1 check
  install_script:
    - make V=1 install
