#!/bin/sh

. ../support/simple_eval_tools.sh

HEADER Agent uses clientaddr for trapsess source

SKIPIF NETSNMP_DISABLE_SNMPV2C

. ./S180trapaddrinfra

INITV4

CONFIGAGENT "[snmp] clientaddr ${localhost}"
CONFIGAGENT trapsess -v 2c -c public ${SNMP_TRANSPORT_SPEC}:${SNMP_TEST_DEST}${SNMP_SNMPTRAPD_PORT}

RUNTEST
