# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2011 Jana Rapava <fermata7@gmail.com>

obj-$(CONFIG_USB_ULPI)		+= ulpi.o
obj-$(CONFIG_USB_ULPI_VIEWPORT)	+= ulpi-viewport.o
obj-$(CONFIG_USB_ULPI_VIEWPORT_OMAP)	+= omap-ulpi-viewport.o
