#! /bin/sh

APPS_DEV=`/userfs/bin/tcapi get Apps_Entry apps_dev`
APPS_MOUNTED_PATH=`/userfs/bin/tcapi get Apps_Entry apps_mounted_path`
APPS_INSTALL_FOLDER=`/userfs/bin/tcapi get Apps_Entry apps_install_folder`
APPS_INSTALL_PATH=$APPS_MOUNTED_PATH/$APPS_INSTALL_FOLDER

PRODUCTID=`/userfs/bin/tcapi get SysInfo_Entry ProductName`
MACADDR=`/userfs/bin/tcapi get Info_Ether mac`
MACLASTWORD=`echo $MACADDR | sed '/^.*/s/://g'`
#MACLASTWORD=${MACLASTWORD:8}
MACLASTWORD=`echo $MACLASTWORD | cut -c 9-12`


MS_ITUNES=`/userfs/bin/tcapi get Apps_Entry ms_itunes`
if [ -n "$MS_ITUNES" ]; then
	DAAPD_NAME=$MS_ITUNES
else
	DAAPD_NAME=$PRODUCTID-$MACLASTWORD
fi

#daapd
DAAPD_PW=`/userfs/bin/tcapi get Account_Entry0 web_passwd`
RUN_NAME=`/userfs/bin/tcapi get Account_Entry0 username`

dir_control_file=$APPS_INSTALL_PATH/etc/mes_general.conf

_generate_itune_service_config(){
	if [ ! -d "/tmp/avahi/services" ]; then
		mkdir -p /tmp/avahi/services
	fi
	chmod -R 777 /tmp/avahi/services

	if [ ! -f "/tmp/avahi/services/mt-daap.service" ]; then
		cd /tmp/avahi/services
		touch mt-daap.service
		chmod 777 /tmp/avahi/services/mt-daap.service
		echo "<service-group>" >/tmp/avahi/services/mt-daap.service
		echo "<name replace-wildcards=\"yes\">$PRODUCTID-$MACLASTWORD</name>" >>/tmp/avahi/services/mt-daap.service
		echo "<service>" >>/tmp/avahi/services/mt-daap.service
		echo "<type>_daap._tcp</type>" >>/tmp/avahi/services/mt-daap.service
		echo "<port>3689</port>" >>/tmp/avahi/services/mt-daap.service
		echo "<txt-record>txtvers=1 iTShVersion=131073 Version=196610</txt-record>" >>/tmp/avahi/services/mt-daap.service
		echo "</service>" >>/tmp/avahi/services/mt-daap.service	
		echo "</service-group>" >>/tmp/avahi/services/mt-daap.service
	else
		chmod 777 /tmp/avahi/services/mt-daap.service
		sed -i "2s/^.*$/<name replace-wildcards=\"yes\">$MS_ITUNES<\/name>/" /tmp/avahi/services/mt-daap.service
	fi
}

if [ "$1" != "stop" ]; then
	#nvram recover
	MS_DLNA_ENABLE=`/userfs/bin/tcapi get Apps_Entry ms_dlna`
	MS_DAAPD_ENABLE=`/userfs/bin/tcapi get Apps_Entry ms_daapd`
	MS_PATH=`/userfs/bin/tcapi get Apps_Entry ms_path`
	MS_TYPE=`/userfs/bin/tcapi get Apps_Entry ms_path_type`
	MS_NAME=`/userfs/bin/tcapi get Apps_Entry ms_name`
	MS_DIR_MANUAL=`/userfs/bin/tcapi get Apps_Entry ms_dir_manual`

	if [ ! -d "/tmp/Mediaserver" ]; then
	mkdir -p /tmp/Mediaserver
	fi
	chmod -R 777 /tmp/Mediaserver

	if [ ! -d "/tmp/asus_app" ]; then
	mkdir -p /tmp/asus_app
	fi
	chmod -R 777 /tmp/asus_app	

	if [ ! -f "/tmp/Mediaserver/ports.conf" ]; then
	cd /tmp/Mediaserver
	touch ports.conf
	fi

	chmod 777 /tmp/Mediaserver/ports.conf

	#nvram recover
	if [ "$MS_DLNA_ENABLE" = "no attribute information" ] && [ "$MS_DAAPD_ENABLE" = "no attribute information" ] && [ "$MS_PATH" = "no attribute information" ]; then
		/userfs/bin/tcapi set Apps_Entry ms_dlna 1
		/userfs/bin/tcapi set Apps_Entry ms_daapd 0
		/userfs/bin/tcapi set Apps_Entry ms_path "</tmp/mnt"
		/userfs/bin/tcapi set Apps_Entry ms_path_type "<APV"
		/userfs/bin/tcapi set Apps_Entry ms_name $PRODUCTID-$MACLASTWORD
		/userfs/bin/tcapi set Apps_Entry ms_itunes $PRODUCTID-$MACLASTWORD
		/userfs/bin/tcapi set Apps_Entry ms_dir_manual 0
		/userfs/bin/tcapi commit Apps
		/userfs/bin/tcapi save
		echo "dms_enable=1" >/opt/etc/Mediaserver.conf
		echo "daapd_enable=0" >>/opt/etc/Mediaserver.conf
		echo "mediasever_path=</tmp/mnt/" >>/opt/etc/Mediaserver.conf
		echo "ms_type=<APV" >>/opt/etc/Mediaserver.conf
		echo "friendly_name=$PRODUCTID-$MACLASTWORD" >>/opt/etc/Mediaserver.conf
		echo "itunes_name=$PRODUCTID-$MACLASTWORD" >>/opt/etc/Mediaserver.conf
		echo "dms_dir_manual=0" >>/opt/etc/Mediaserver.conf		
		sed -n "/media_dir/d" /opt/etc/minidlna.conf
		sed -i "12s/^.*$/media_dir=\/tmp\/mnt/" /opt/etc/minidlna.conf
	elif [ "$MS_NAME" = "no attribute information" ]; then
		/userfs/bin/tcapi set Apps_Entry ms_path "<$MS_PATH"
		/userfs/bin/tcapi set Apps_Entry ms_path_type "<APV"
		/userfs/bin/tcapi set Apps_Entry ms_name $PRODUCTID-$MACLASTWORD
		/userfs/bin/tcapi set Apps_Entry ms_itunes $PRODUCTID-$MACLASTWORD
		/userfs/bin/tcapi set Apps_Entry ms_dir_manual 1
		/userfs/bin/tcapi commit Apps
		/userfs/bin/tcapi save
		echo "dms_enable=$MS_DLNA_ENABLE" >/opt/etc/Mediaserver.conf
		echo "daapd_enable=$MS_DAAPD_ENABLE" >>/opt/etc/Mediaserver.conf
		echo "mediasever_path=<$MS_PATH" >>/opt/etc/Mediaserver.conf
		echo "ms_type=<APV" >>/opt/etc/Mediaserver.conf
		echo "friendly_name=$PRODUCTID-$MACLASTWORD" >>/opt/etc/Mediaserver.conf
		echo "itunes_name=$PRODUCTID-$MACLASTWORD" >>/opt/etc/Mediaserver.conf
		echo "dms_dir_manual=1" >>/opt/etc/Mediaserver.conf
		sed -n "/media_dir/d" /opt/etc/minidlna.conf
		MS_PATH_TMP=`echo $MS_PATH|sed -n 's/\//\\\\\//pg'`
		sed -i "12s/^.*$/media_dir=$MS_PATH_TMP/" /opt/etc/minidlna.conf
	else
		echo "dms_enable=$MS_DLNA_ENABLE" >/opt/etc/Mediaserver.conf
		echo "daapd_enable=$MS_DAAPD_ENABLE" >>/opt/etc/Mediaserver.conf
		echo "mediasever_path=$MS_PATH" >>/opt/etc/Mediaserver.conf
		echo "ms_type=$MS_TYPE" >>/opt/etc/Mediaserver.conf
		echo "friendly_name=$MS_NAME" >>/opt/etc/Mediaserver.conf
		echo "itunes_name=$MS_ITUNES" >>/opt/etc/Mediaserver.conf
		echo "dms_dir_manual=$MS_DIR_MANUAL" >>/opt/etc/Mediaserver.conf
		
		sed -i "/^media_dir/d" /opt/etc/minidlna.conf
		path_type=`echo $MS_TYPE | awk 'BEGIN {FS="<"} {for(i=2;i<=NF;i++)print $i}'`
		j=2
		for i in $path_type
		do
			if [ $j -le 11 ]; then
				path_real=`echo $MS_PATH | awk 'BEGIN {FS="<"} {print $'$j'}'`
			fi
			j=$(($j+1))
			if [ "$i" = "APV" ]; then
				echo "media_dir=$path_real/" >> /opt/etc/minidlna.conf
			else
				echo "media_dir=$i,$path_real/" >>/opt/etc/minidlna.conf
			fi 
		done
	fi		
fi

if [ ! -f "$dir_control_file" ] || [ "$1" = "start" ] || [ "$1" = "restart" ];then
	sh /opt/etc/apps_asus_script/mes_check_general general-check&
fi

#minidlna
HWADDR=`/userfs/bin/tcapi get Info_Ether mac`
LAN_IPADDR=`/userfs/bin/tcapi get Lan_Entry0 IP`
DLNA_NAME=`/userfs/bin/tcapi get Apps_Entry ms_name`

#avahi
WAN_PRIMARY=`/userfs/bin/tcapi get Wanduck_Common wan_primary`
WAN_IFNAME=`/userfs/bin/tcapi get Wanduck_Common wan$WAN_PRIMARY"_ifname"`
if [ "$1" != "stop" ]; then
	
	MS_ITUNES=`/userfs/bin/tcapi get Apps_Entry ms_itunes`
	#daapd
	if [ -f "/opt/etc/mt-daapd.conf" ]; then
		sed -i "9s/^.*$/admin_pw    $DAAPD_PW/" /opt/etc/mt-daapd.conf
		sed -i "11s/^.*$/servername   $DAAPD_NAME/" /opt/etc/mt-daapd.conf
		sed -i "12s/^.*$/runas   $RUN_NAME/" /opt/etc/mt-daapd.conf
	fi
	
	#avahi
	_generate_itune_service_config
	if [ ! -d "/tmp/avahi" ]; then
		mkdir -p /tmp/avahi
	fi
	chmod -R 777 /tmp/avahi
	if [ -f "/tmp/avahi/avahi-daemon.conf" ]; then
		sed -i "2s/^.*$/host-name=$MS_ITUNES/" /tmp/avahi/avahi-daemon.conf
		sed -i "3s/^.*$/aliases=$PRODUCTID/" /tmp/avahi/avahi-daemon.conf
		sed -i "4s/^.*$/aliases_llmnr=$PRODUCTID/" /tmp/avahi/avahi-daemon.conf
		sed -i "7s/^.*$/deny-interfaces=$WAN_IFNAME/" /tmp/avahi/avahi-daemon.conf
	else
		echo "[Server]" >/tmp/avahi/avahi-daemon.conf
		echo "host-name=$PRODUCTID-$MACLASTWORD" >>/tmp/avahi/avahi-daemon.conf
		echo "aliases=$PRODUCTID" >>/tmp/avahi/avahi-daemon.conf
		echo "aliases_llmnr=$PRODUCTID" >>/tmp/avahi/avahi-daemon.conf
		echo "use-ipv4=yes" >>/tmp/avahi/avahi-daemon.conf
		echo "use-ipv6=no" >>/tmp/avahi/avahi-daemon.conf
		echo "deny-interfaces=$WAN_IFNAME" >>/tmp/avahi/avahi-daemon.conf
		echo "ratelimit-interval-usec=1000000" >>/tmp/avahi/avahi-daemon.conf
		echo "ratelimit-burst=1000" >>/tmp/avahi/avahi-daemon.conf
		echo "" >>/tmp/avahi/avahi-daemon.conf
		echo "[publish]" >>/tmp/avahi/avahi-daemon.conf
		echo "publish-a-on-ipv6=no" >>/tmp/avahi/avahi-daemon.conf
		echo "publish-aaaa-on-ipv4=no" >>/tmp/avahi/avahi-daemon.conf
		echo "" >>/tmp/avahi/avahi-daemon.conf
		echo "[wide-area]" >>/tmp/avahi/avahi-daemon.conf
		echo "enable-wide-area=yes" >>/tmp/avahi/avahi-daemon.conf
		echo "" >>/tmp/avahi/avahi-daemon.conf
		echo "[rlimits]" >>/tmp/avahi/avahi-daemon.conf
		echo "rlimit-core=0" >>/tmp/avahi/avahi-daemon.conf
		echo "rlimit-data=4194304" >>/tmp/avahi/avahi-daemon.conf
		echo "rlimit-fsize=0" >>/tmp/avahi/avahi-daemon.conf
		echo "rlimit-nofile=768" >>/tmp/avahi/avahi-daemon.conf
		echo "rlimit-stack=4194304" >>/tmp/avahi/avahi-daemon.conf
		echo "rlimit-nproc=3" >>/tmp/avahi/avahi-daemon.conf
	fi
	echo "$RUN_NAME" >/tmp/avahi/http_username
	
	#minidlna
	if [ -f "/opt/etc/minidlna.conf" ]; then
		sed -i "2s/^.*$/friendly_name=$DLNA_NAME/" /opt/etc/minidlna.conf
		sed -i "9s/^.*$/presentation_url=http:\/\/$LAN_IPADDR\:8200/" /opt/etc/minidlna.conf
		sed -i "11s/^.*$/serial=$HWADDR/" /opt/etc/minidlna.conf
	fi

	#ports
	sed -i "/ehci_ports/d" /tmp/Mediaserver/ports.conf
	echo "ehci_ports=1-1 1-2/" >>/tmp/Mediaserver/ports.conf
	sed -i "/ohci_ports/d" /tmp/Mediaserver/ports.conf
	echo "ohci_ports=2-1 2-2/" >>/tmp/Mediaserver/ports.conf

fi

MINIDLNA=`/userfs/bin/tcapi get Apps_Entry ms_dlna`
DAAPD=`/userfs/bin/tcapi get Apps_Entry ms_daapd`

APP_BIN=$APPS_INSTALL_PATH/bin
APP_LIB=$APPS_INSTALL_PATH/lib

APP_LINK_DIR=/tmp/opt
APP_LINK_BIN=$APP_LINK_DIR/bin
APP_LINK_LIB=$APP_LINK_DIR/lib

case "$1" in
  start)
	rm -rf /tmp/have_ms
	sh /opt/etc/apps_asus_script/mes_check

	APPS_MOUNTED_TYPE=`mount |grep "/dev/$APPS_DEV on " |awk '{print $5}'`

	touch /tmp/asus_app/mediaserver_start
	asuslighttpdnum=`ps | grep "asus_lighttpd" | grep -v "$0" | grep -v "grep" | awk '{printf $5}'`

	if [ "$asuslighttpdnum" != "./asus_lighttpd" ]; then
		sh /opt/etc/init.d/S50asuslighttpd start
	fi
if [ "$APPS_MOUNTED_TYPE" != "vfat" ] && [ "$APPS_MOUNTED_TYPE" != "tfat" ]; then
	if [ ! -f "$APP_LIB/libjpeg.so.62" ]; then
		ln -sf 	$APP_LIB/libjpeg.so.62.0.0 $APP_LIB/libjpeg.so.62
	fi

	if [ ! -f "$APP_LIB/libjpeg.so.0" ]; then
		ln -sf 	$APP_LIB/libjpeg.so.62.0.0 $APP_LIB/libjpeg.so.0
	fi

	if [ ! -f "$APP_LIB/libid3tag_ms.so.0" ]; then
		ln -sf 	$APP_LIB/libid3tag_ms.so.0.3.0 $APP_LIB/libid3tag_ms.so.0
		ln -sf 	$APP_LIB/libid3tag_ms.so.0.3.0 $APP_LIB/libid3tag_ms.so
	fi
	
	if [ ! -f "$APP_LIB/libsqlite3.so.0" ]; then
		ln -sf 	$APP_LIB/libsqlite3.so.0.8.6 $APP_LIB/libsqlite3.so.0
	fi

	if [ ! -f "$APP_LIB/libexif.so.12" ]; then
		ln -sf 	$APP_LIB/libexif.so.12.3.1 $APP_LIB/libexif.so.12
	fi
	
	if [ ! -f "$APP_LIB/libFLAC.so.8" ]; then
		ln -sf 	$APP_LIB/libFLAC.so.8.2.0 $APP_LIB/libFLAC.so.8
	fi

	if [ ! -f "$APP_LIB/libogg.so.0" ]; then
		ln -sf 	$APP_LIB/libogg.so.0.7.1 $APP_LIB/libogg.so.0
	fi

	if [ ! -f "$APP_LIB/libvorbis.so.0" ]; then
		ln -sf 	$APP_LIB/libvorbis.so.0.4.5 $APP_LIB/libvorbis.so.0
	fi

	if [ ! -f "$APP_LIB/libgdbm.so.3" ]; then
		ln -sf 	$APP_LIB/libgdbm.so.3.0.0 $APP_LIB/libgdbm.so.3
	fi

	if [ ! -f "$APP_LIB/libpcre.so.1" ] && [ ! -f "$APP_LIB/libpcre.so.1.0.0" ]; then
		ln -sf 	$APP_LIB/libpcre.so.0.0.1 $APP_LIB/libpcre.so.1
	fi

	if [ ! -f "$APP_LIB/libpcre.so.0" ] && [ ! -f "$APP_LIB/libpcre.so.0.0.1" ]; then
		ln -sf 	$APP_LIB/libpcre.so.1.0.0 $APP_LIB/libpcre.so.0
	fi

	if [ "$MINIDLNA" = "1" ]; then
	killall -SIGTERM minidlna
	sleep 3
	/opt/bin/minidlna -f /opt/etc/minidlna.conf -r &
	else
	killall -SIGTERM minidlna
	fi
	
	if [ "$DAAPD" = "1" ]; then
	killall -9 mt-daapd
	killall -9 avahi-daemon
	sleep 3
	/opt/bin/avahi-daemon &
	/opt/bin/mt-daapd -mc /opt/etc/mt-daapd.conf &
	else
	killall -9 mt-daapd
	killall -9 avahi-daemon
	fi
	echo "have_ms" > /tmp/have_ms
	exit 0
fi

#libdaemon
DAEMON_VER=`ls $APP_LIB/libdaemon.so.* |awk 'BEGIN {FS="libdaemon.so."} {print $2}'`
ln -sf $APP_LIB/libdaemon.so.$DAEMON_VER $APP_LINK_LIB/libdaemon.so
ln -sf $APP_LIB/libdaemon.so.$DAEMON_VER $APP_LINK_LIB/libdaemon.so.0

#AVAHI
AVAHI_COMMON_VER=`ls $APP_LIB/libavahi-common.so.* |awk 'BEGIN {FS="libavahi-common.so."} {print $2}'`
ln -sf $APP_LIB/libavahi-common.so.$AVAHI_COMMON_VER $APP_LINK_LIB/libavahi-common.so.3
AVAHI_CORE_VER=`ls $APP_LIB/libavahi-core.so.* |awk 'BEGIN {FS="libavahi-core.so."} {print $2}'`
ln -sf $APP_LIB/libavahi-core.so.$AVAHI_CORE_VER $APP_LINK_LIB/libavahi-core.so.7
EXPAT_VER=`ls $APP_LIB/libexpat.so.* |awk 'BEGIN {FS="libexpat.so."} {print $2}'`
ln -sf $APP_LIB/libexpat.so.$EXPAT_VER $APP_LINK_LIB/libexpat.so.1

# zlib
ZLIB_VER=`ls $APP_LIB/libz.so.* |awk 'BEGIN {FS="libz.so."} {print $2}'`
ln -sf $APP_LIB/libz.so.$ZLIB_VER $APP_LINK_LIB/libz.so.1
ln -sf $APP_LIB/libz.so.$ZLIB_VER $APP_LINK_LIB/libz.so

# sqlite3
SQLITE3_VER=`ls $APP_LIB/libsqlite3.so.* |awk 'BEGIN {FS="libsqlite3.so."} {print $2}'`
ln -sf $APP_LIB/libsqlite3.so.$SQLITE3_VER $APP_LINK_LIB/libsqlite3.so.0

#ogg
OGG_VER=`ls $APP_LIB/libogg.so.* |awk 'BEGIN {FS="libogg.so."} {print $2}'`
ln -sf $APP_LIB/libogg.so.$OGG_VER $APP_LINK_LIB/libogg.so.0

#gdbm
GDBM_VER=`ls $APP_LIB/libgdbm.so.* |awk 'BEGIN {FS="libgdbm.so."} {print $2}'`
ln -sf $APP_LIB/libgdbm.so.$GDBM_VER $APP_LINK_LIB/libgdbm.so.3

#avcodec
AVCODEC_VER=`ls $APP_LIB/libavcodec_asus.so.* |awk 'BEGIN {FS="libavcodec_asus.so."} {print $2}'`
ln -sf $APP_LIB/libavcodec_asus.so.52 $APP_LINK_LIB/libavcodec_asus.so.52  #have two version libs ,cannot find right lib 

#avformat
AVFORMAT_VER=`ls $APP_LIB/libavformat_asus.so.* |awk 'BEGIN {FS="libavformat_asus.so."} {print $2}'`
ln -sf $APP_LIB/libavformat_asus.so.52 $APP_LINK_LIB/libavformat_asus.so.52  

#avutil
AVUTIL_VER=`ls $APP_LIB/libavutil_asus.so.* |awk 'BEGIN {FS="libavutil_asus.so."} {print $2}'`
ln -sf $APP_LIB/libavutil_asus.so.50 $APP_LINK_LIB/libavutil_asus.so.50

#exif
EXIF_VER=`ls $APP_LIB/libexif.so.* |awk 'BEGIN {FS="libexif.so."} {print $2}'`
ln -sf $APP_LIB/libexif.so.$EXIF_VER $APP_LINK_LIB/libexif.so.12

#flac
FLAC_VER=`ls $APP_LIB/libFLAC.so.* |awk 'BEGIN {FS="libFLAC.so."} {print $2}'`
ln -sf $APP_LIB/libFLAC.so.$FLAC_VER $APP_LINK_LIB/libFLAC.so.8

#id3tag
ID3TAG_VER=`ls $APP_LIB/libid3tag_ms.so.* |awk 'BEGIN {FS="libid3tag_ms.so."} {print $2}'`
ln -sf $APP_LIB/libid3tag_ms.so.$ID3TAG_VER $APP_LINK_LIB/libid3tag_ms.so.0
ln -sf $APP_LIB/libid3tag_ms.so.$ID3TAG_VER $APP_LINK_LIB/libid3tag_ms.so

#jpeg
JPEG_VER=`ls $APP_LIB/libjpeg.so.* |awk 'BEGIN {FS="libjpeg.so."} {print $2}'`
ln -sf $APP_LIB/libjpeg.so.$JPEG_VER $APP_LINK_LIB/libjpeg.so.62

#vorbis
VORBIS_VER=`ls $APP_LIB/libvorbis.so.* |awk 'BEGIN {FS="libvorbis.so."} {print $2}'`
ln -sf $APP_LIB/libvorbis.so.$VORBIS_VER $APP_LINK_LIB/libvorbis.so.0

#vorbisfile
VORBISFILE_VER=`ls $APP_LIB/libvorbisfile.so.* |awk 'BEGIN {FS="libvorbisfile.so."} {print $2}'`
ln -sf $APP_LIB/libvorbisfile.so.$VORBISFILE_VER $APP_LINK_LIB/libvorbisfile.so.3

	if [ "$MINIDLNA" = "1" ]; then
	killall -SIGTERM minidlna
	sleep 3
	/opt/bin/minidlna -f /opt/etc/minidlna.conf -r &
	else
	killall -SIGTERM minidlna
	fi
	
	if [ "$DAAPD" = "1" ]; then
	killall -9 mt-daapd
	killall -9 avahi-daemon
	sleep 3
	/opt/bin/mt-daapd -mc /opt/etc/mt-daapd.conf &
	/opt/bin/avahi-daemon &
	else
	killall -9 mt-daapd
	killall -9 avahi-daemon
	fi
	echo "have_ms" > /tmp/have_ms	
	;;
  dlna-restart)
	echo "dlna-restart"
	rm -f /tmp/Mediaserver/scantag
	killall -SIGTERM minidlna
	sleep 3
	/opt/bin/minidlna -f /opt/etc/minidlna.conf -r &
	;;
  dlna-stop)
	echo "dlna-stop"
	rm -f /tmp/Mediaserver/scantag
	killall -SIGTERM minidlna
	;;
  daapd-restart)
	echo "daapd-restart"
	killall -9 mt-daapd
	killall -9 avahi-daemon
	#killall -9 mDNSResponder
	sleep 3
	/opt/bin/mt-daapd -mc /opt/etc/mt-daapd.conf &
	/opt/bin/avahi-daemon &
	;;
  daapd-stop)
	echo "daapd-stop"
	killall -9 mt-daapd
	killall -9 avahi-daemon
	;;
  server-stop)
	killall -SIGTERM minidlna
	killall -9 mt-daapd
	killall -9 avahi-daemon
	;;
  stop)
	rm -rf /tmp/have_ms
	echo -n "Stopping MediaServer"
	if [ -f "/tmp/username_pw_MS.txt" ] ; then
	rm -rf /tmp/username_pw_MS.txt
	fi
	rm -f /tmp/asus_app/mediaserver_start
	rm -f /tmp/Mediaserver/scantag
	dm2_control="/opt/lib/ipkg/info/downloadmaster.control"
	if [ ! -f "$dm2_control" ]; then
		dm2_exist="no"
	else 
		dm2_exist_tmp=`cat "$dm2_control" |grep "Enabled:"`
		dm2_exist=`echo $dm2_exist_tmp |awk 'BEGIN {FS=": "} {print $2}'`
	fi
	APP_CHECK=`ls -l /tmp/asus_app/`
	if [ -z "$APP_CHECK" ] && [ "$dm2_exist" = "no" ]; then
		killall -SIGTERM asus_lighttpd&
	fi
	killall -9 mt-daapd
	killall -SIGTERM minidlna
	killall -9 avahi-daemon
	;;
  restart)
	echo "restart"
	rm -rf /tmp/have_ms
	killall -9 mt-daapd
	killall -SIGTERM minidlna
	killall -9 avahi-daemon
	sleep 3
	sh /opt/etc/init.d/S50mediaserver start
	;;
  firewall-start|firewall-restart)
  	echo "MS firewall-start"
	killall -9 mt-daapd
	killall -SIGTERM minidlna
	killall -9 avahi-daemon
	LAN_IPADDR=`/userfs/bin/tcapi get Lan_Entry0 IP`
	MS_ITUNES=`/userfs/bin/tcapi get Apps_Entry ms_itunes`
	sed -i "9s/^.*$/presentation_url=http:\/\/$LAN_IPADDR\:8200/" /opt/etc/minidlna.conf
	sed -i "15s/^.*$/LAN_IP=$LAN_IPADDR/" /opt/etc/mes_general.conf
	sed -i "15s/^.*$/LAN_IP=$LAN_IPADDR/" /opt/etc/mes_general_bak.conf
	sleep 3
	if [ "$MS_DLNA_ENABLE" = "1" ]; then
		/opt/bin/minidlna -f /opt/etc/minidlna.conf -r &
	fi
	if [ "$MS_DAAPD_ENABLE" = "1" ]; then
		sed -i "9s/^.*$/admin_pw    $DAAPD_PW/" /opt/etc/mt-daapd.conf
		sed -i "11s/^.*$/servername   $DAAPD_NAME/" /opt/etc/mt-daapd.conf
		sed -i "12s/^.*$/runas   $RUN_NAME/" /opt/etc/mt-daapd.conf
		sed -i "2s/^.*$/host-name=$MS_ITUNES/" /tmp/avahi/avahi-daemon.conf
		sed -i "3s/^.*$/aliases=$PRODUCTID/" /tmp/avahi/avahi-daemon.conf
		sed -i "4s/^.*$/aliases_llmnr=$PRODUCTID/" /tmp/avahi/avahi-daemon.conf
		sed -i "7s/^.*$/deny-interfaces=$WAN_IFNAME/" /tmp/avahi/avahi-daemon.conf
		_generate_itune_service_config
		echo "$RUN_NAME" >/tmp/avahi/http_username
		/opt/bin/mt-daapd -mc /opt/etc/mt-daapd.conf &
		/opt/bin/avahi-daemon &
	fi
	exit 2
	;;
  *)

  exit 1
  ;;
esac
