/*
  <:copyright-BRCM:2023:DUAL/GPL:standard 

  Copyright (c) 2023 Broadcom 
  All Rights Reserved

  Unless you and Broadcom execute a separate written software license
  agreement governing use of this software, this software is licensed
  to you under the terms of the GNU General Public License version 2
  (the "GPL"), available at http://www.broadcom.com/licenses/GPLv2.php,
  with the following added to such license:

  As a special exception, the copyright holders of this software give
  you permission to link this software with independent modules, and
  to copy and distribute the resulting executable under terms of your
  choice, provided that you also meet, for each linked independent
  module, the terms and conditions of the license of that module.
  An independent module is a module which is not derived from this
  software.  The special exception does not apply to any modifications
  of the software.

  Not withstanding the above, under no circumstances may you combine
  this software in any way with any other Broadcom software provided
  under a license other than the GPL, without Broadcom's express prior
  written consent.

  :>
*/

#ifndef __6765_CROSSBOW_H__
#define __6765_CROSSBOW_H__

#include "6765_crossbow_rdb.h"

#define FIELD_MASK(bits, shift)  ( ( (1ULL<<(bits)) - 1 ) << shift )

#define SYSPORT_INTC_TO_INTRL2(_intc) ( (_intc) >> 1 )

#define SYSPORT_INTC_TO_INTRL2_INTR(_intc) ( (_intc) & 0x1 )

static inline int sysport_intc_to_irq_index(int intc)
{
    int irq_index = (intc >> 1); // 0..4

    if(intc & 0x1)
    {
        irq_index += 5; // 5..9
    }

    return irq_index;
}

typedef struct {
    uint32_t SYSTEMPORT_INTR_CPU_STATUS;
    uint32_t SYSTEMPORT_INTR_CPU_SET;
    uint32_t SYSTEMPORT_INTR_CPU_CLEAR;
    uint32_t SYSTEMPORT_INTR_CPU_MASK_STATUS;
    uint32_t SYSTEMPORT_INTR_CPU_MASK_SET;
    uint32_t SYSTEMPORT_INTR_CPU_MASK_CLEAR;
} SYSTEMPORT_INTRL2;

typedef struct {
    SYSTEMPORT_INTRL2 intr[2];
    uint8_t reserved[16];
} SYSTEMPORT_INTRL2_DUAL;

#define SYSPORT_INTC_MAPPING_TDMA_MULTI_BUFFER_DONE_INTR  0
#define SYSPORT_INTC_MAPPING_RDMA_MULTI_BUFFER_DONE_INTR  3 // INTRs 24, 16, 0 only
#define SYSPORT_INTC_MAPPING_CSB_DONE_INTR                2
#define SYSPORT_INTC_MAPPING_RECYCLE_RING_INTR            6

#define SYSPORT_INTC_MAPPING_CROSSBOW_RXQ_INTR            1
#define SYSPORT_INTC_MAPPING_CROSSBOW_MISC1_INTR          4
#define SYSPORT_INTC_MAPPING_CROSSBOW_STQ_INTR            3
#define SYSPORT_INTC_MAPPING_CROSSBOW_FWQ_INTR            1
#define SYSPORT_INTC_MAPPING_CROSSBOW_STQ_5_INTR          7
#define SYSPORT_INTC_MAPPING_CROSSBOW_FWQ_5_INTR          7

#define SYSPORT_INTC_MAPPING_INT_SEL_S(_index) ( ((_index) % 8) * 4 )

#define SYSPORT_INTC_MISC1_CBOW_CM7_1_MAILBOX_M    FIELD_MASK(8,12)
#define SYSPORT_INTC_MISC1_CBOW_CM7_1_MAILBOX_S    12
#define SYSPORT_INTC_MISC1_CBOW_CM7_0_MAILBOX_M    FIELD_MASK(8,4)
#define SYSPORT_INTC_MISC1_CBOW_CM7_0_MAILBOX_S    4
#define SYSPORT_INTC_MISC1_CBOW_CM7_SYSRESETREQ_M  FIELD_MASK(2,2)
#define SYSPORT_INTC_MISC1_CBOW_CM7_SYSRESETREQ_S  2
#define SYSPORT_INTC_MISC1_TIMER1_TIMEOUT_M        FIELD_MASK(1,1)
#define SYSPORT_INTC_MISC1_TIMER0_TIMEOUT_M        FIELD_MASK(1,0)

typedef struct {
    uint32_t SYSTEMPORT_INTC_INTC_MAPPING_31_24;//0x80498300
    uint32_t SYSTEMPORT_INTC_INTC_MAPPING_23_16;//0x80498304
    uint32_t SYSTEMPORT_INTC_INTC_MAPPING_15_8;//0x80498308
    uint32_t SYSTEMPORT_INTC_INTC_MAPPING_7_0;//0x8049830C
    uint32_t SYSTEMPORT_INTC_INTC_PSB_EN;//0x80498310
    uint32_t SYSTEMPORT_INTC_INTC_CSB_EN;//0x80498314
    uint32_t SYSTEMPORT_INTC_INTC_RRING_CSB_INTR_SRC_EN;//0x80498318
    uint8_t  reserved[36];
} SYSTEMPORT_INTC;

#define SYSPORT_RDMA_CTRL_RDMA_EN_M             FIELD_MASK(1,0)
#define SYSPORT_RDMA_CTRL_RING_CFG_M            FIELD_MASK(2,1)
#define SYSPORT_RDMA_CTRL_RING_CFG_bit0_M       FIELD_MASK(1,1)
#define SYSPORT_RDMA_CTRL_RING_CFG_bit1_M       FIELD_MASK(1,2)
#define SYSPORT_RDMA_CTRL_DISCARD_EN_M          FIELD_MASK(1,3)
#define SYSPORT_RDMA_CTRL_BUF_DATA_OFFSET_M     FIELD_MASK(10,4)
#define SYSPORT_RDMA_CTRL_BUF_DATA_OFFSET_S     4
#define SYSPORT_RDMA_CTRL_DDR_DESC_WR_EN_M      FIELD_MASK(1,15)
#define SYSPORT_RDMA_CTRL_MPM_EN_M              FIELD_MASK(1,19)

#define SYSPORT_RDMA_STATUS_RDMA_DISABLED_M     FIELD_MASK(1,0)
#define SYSPORT_RDMA_STATUS_DESC_RAM_BUSY_M     FIELD_MASK(1,1)

#define SYSTEMPORT_RDMA_LOCRAM_DESCRING_SIZE_MAX            32
#define SYSTEMPORT_RDMA_LOCRAM_DESCRING_SIZE_RING_FLUSH_M   FIELD_MASK(1,16)
#define SYSTEMPORT_RDMA_LOCRAM_DESCRING_SIZE_RING_EN_M      FIELD_MASK(1,17)

#define SYSPORT_RDMA_MPM_CFG_BUF_ADDR_TYPE_M       FIELD_MASK(3,0)
#define SYSPORT_RDMA_MPM_CFG_BUF_ADDR_TYPE_S       0
#define SYSPORT_RDMA_MPM_CFG_ALLOC_FIX_BUF_EN_M    FIELD_MASK(1,3)
#define SYSPORT_RDMA_MPM_CFG_ALLOC_FIX_BUF_EN_S    3
#define SYSPORT_RDMA_MPM_CFG_FIX_BUF_SIZE_M        FIELD_MASK(8,4)
#define SYSPORT_RDMA_MPM_CFG_FIX_BUF_SIZE_S        4
#define SYSPORT_RDMA_MPM_CFG_BUF_ALLOC_OVERHEAD_M  FIELD_MASK(8,12)
#define SYSPORT_RDMA_MPM_CFG_BUF_ALLOC_OVERHEAD_S  12

typedef struct {
    uint32_t SYSTEMPORT_RDMA_DESCRIPTOR[1024]; // 0x80212000
    uint32_t SYSTEMPORT_RDMA_DESC_WRITE_PORT[16]; // 0x80213000
    uint32_t SYSTEMPORT_RDMA_DESC_READ_PORT[16]; // 0x80213040
    uint32_t SYSTEMPORT_RDMA_CONTROL; // 0x80213080
    uint32_t SYSTEMPORT_RDMA_STATUS;
    uint32_t SYSTEMPORT_RDMA_RESERVED_0;
    uint32_t SYSTEMPORT_RDMA_SWITCH_PORT_BP_EN;
    uint32_t SYSTEMPORT_RDMA_RXQ_TO_SWITCH_EGRESS_QUEUES_BP_MAP[8]; // 0x80213090
    uint32_t SYSTEMPORT_RDMA_LOCRAM_DESCRING_SIZE[8]; // 0x802130B0
    uint32_t SYSTEMPORT_RDMA_PKTBUF_SIZE[8]; // 0x802130D0
    uint32_t SYSTEMPORT_RDMA_PINDEX[8];
    uint32_t SYSTEMPORT_RDMA_CINDEX[8];
    uint32_t SYSTEMPORT_RDMA_BUFDONE_INTR_CFG[8]; // 0x80213130
    uint32_t SYSTEMPORT_RDMA_XON_XOFF_CFG[8];
    uint32_t SYSTEMPORT_RDMA_DDR_DESC_RING_START[16]; // 0x80213170
    uint32_t SYSTEMPORT_RDMA_DDR_DESC_RING_SIZE[8];
    uint32_t SYSTEMPORT_RDMA_DDR_DESC_RING_CTRL[8];
    uint32_t SYSTEMPORT_RDMA_DDR_DESC_RING_WR_PUSH_TIMER[8];
    uint32_t SYSTEMPORT_RDMA_DISCARD_CNT[8]; // 0x80213210
    uint32_t SYSTEMPORT_RDMA_BP_STATUS;
    uint32_t SYSTEMPORT_RDMA_DESC_RAM_ARB_CONTROL;
    uint32_t SYSTEMPORT_RDMA_DESC_RAM_RD_ARB_CFG;
    uint32_t SYSTEMPORT_RDMA_DESC_RAM_WR_ARB_CFG; // 0x8021323C
    uint32_t SYSTEMPORT_RDMA_RESERVED_1;
    uint32_t SYSTEMPORT_RDMA_RESERVED_2;
    uint32_t SYSTEMPORT_RDMA_RESERVED_3;
    uint32_t SYSTEMPORT_RDMA_MPM_CFG; // 0x8021324C
    uint32_t SYSTEMPORT_RDMA_TEST;
    uint32_t SYSTEMPORT_RDMA_DEBUG; // 0x80213254
    uint32_t SYSTEMPORT_RDMA_RESERVED_4;
    uint32_t SYSTEMPORT_RDMA_RESERVED_5;
    uint32_t SYSTEMPORT_RDMA_SYSRAM_DESC_RINGS_RD_ARB_CFG; // 0x80213260
    uint32_t SYSTEMPORT_RDMA_SYSRAM_DESC_RINGS_WR_ARB_CFG;
} SYSTEMPORT_RDMA;

#define SYSPORT_RBUF_CTRL_RSB_MODE_M          FIELD_MASK(2,0)
#define SYSPORT_RBUF_CTRL_RSB_MODE_S          0
#define SYSPORT_RBUF_CTRL_4B_ALIGN_M          FIELD_MASK(1,2)
#define SYSPORT_RBUF_CTRL_BTAG_STRIP_M        FIELD_MASK(1,3)
#define SYSPORT_RBUF_CTRL_BAD_PKT_DISCARD_M   FIELD_MASK(1,4)
#define SYSPORT_RBUF_CTRL_CUTTHROUGH_EN_M     FIELD_MASK(1,6)
#define SYSPORT_RBUF_CTRL_CRC_REPLACE_M       FIELD_MASK(1,21)
#define SYSPORT_RBUF_CTRL_ACPI_EN_M           FIELD_MASK(1,25)

#define SYSPORT_RBUF_CTRL_RSB_MODE_NO_RSB     0
#define SYSPORT_RBUF_CTRL_RSB_MODE_RSB8       1
#define SYSPORT_RBUF_CTRL_RSB_MODE_RSB32      2

#define SYSPORT_RBUF_PACKET_READY_THRESHOLD_PKT_RDY_THRESHOLD_M   FIELD_MASK(10,0)
#define SYSPORT_RBUF_PACKET_READY_THRESHOLD_PKT_RDY_THRESHOLD_S   0
#define SYSPORT_RBUF_PACKET_READY_THRESHOLD_RESUME_THRESHOLD_M    FIELD_MASK(10,16)
#define SYSPORT_RBUF_PACKET_READY_THRESHOLD_RESUME_THRESHOLD_S    16

#define SYSPORT_RBUF_STATUS_WOL_M           FIELD_MASK(1,0)
#define SYSPORT_RBUF_STATUS_WOL_S           0
#define SYSPORT_RBUF_STATUS_MPD_ACTIVE_M    FIELD_MASK(1,1)
#define SYSPORT_RBUF_STATUS_MPD_ACTIVE_S    1
#define SYSPORT_RBUF_STATUS_ARP_ACTIVE_M    FIELD_MASK(1,2)
#define SYSPORT_RBUF_STATUS_ARP_ACTIVE_S    2

typedef struct {
    uint32_t SYSTEMPORT_RBUF_RBUF_CONTROL; // 0x80210400
    uint32_t SYSTEMPORT_RBUF_RBUF_PACKET_READY_THRESHOLD;
    uint32_t SYSTEMPORT_RBUF_RBUF_STATUS;
    uint32_t SYSTEMPORT_RBUF_RBUF_OVERFLOW_PACKET_DISCARD_COUNT;
    uint32_t SYSTEMPORT_RBUF_RBUF_ERROR_PACKET_COUNT;
} SYSTEMPORT_RBUF;

typedef struct {
    uint32_t SYSTEMPORT_TBUF_TBUF_CONTROL;
    uint32_t SYSTEMPORT_TBUF_PKT_RDY_THRESHOLD;
    uint32_t SYSTEMPORT_TBUF_TBUF_STATUS;
} SYSTEMPORT_TBUF;

#define SYSTEMPORT_TDMA_DESC_RING_MAX        24
#define SYSTEMPORT_TDMA_LOCRAM_DESCRING_MAX  1536 // 8B Descriptors

#define SYSTEMPORT_TDMA_TIMEOUT_TICK_NSEC    1000 // tick = 1 usec (internal timer)

typedef struct systemport_tdma_descriptor_write_port {
    uint32_t SYSTEMPORT_TDMA_DESCRIPTOR_XX_WRITE_PORT_LO;
    uint32_t SYSTEMPORT_TDMA_DESCRIPTOR_XX_WRITE_PORT_HI;
} systemport_tdma_descriptor_write_port;

typedef struct systemport_tdma_descriptor_read_port {
    uint32_t SYSTEMPORT_TDMA_DESCRIPTOR_XX_READ_PORT_LO;
    uint32_t SYSTEMPORT_TDMA_DESCRIPTOR_XX_READ_PORT_HI;
} systemport_tdma_descriptor_read_port;

#define SYSTEMPORT_TDMA_DESC_RING_XX_PRODUCER_CONSUMER_INDEX_CONSUMER_INDEX_S      16
#define SYSTEMPORT_TDMA_DESC_RING_XX_PRODUCER_CONSUMER_INDEX_CONSUMER_INDEX_M      FIELD_MASK(16,16)
#define SYSTEMPORT_TDMA_DESC_RING_XX_PRODUCER_CONSUMER_INDEX_PRODUCER_INDEX_M      FIELD_MASK(16,0)

#define SYSPORT_TDMA_CONTROL_TDMA_EN_M                  FIELD_MASK(1,0)
#define SYSPORT_TDMA_CONTROL_TSB_EN_M                   FIELD_MASK(1,1)
#define SYSPORT_TDMA_CONTROL_VLAN_EN_M                  FIELD_MASK(1,15)
#define SYSPORT_TDMA_CONTROL_SW_BRCM_TAG_M              FIELD_MASK(1,16)
#define SYSPORT_TDMA_CONTROL_WNC_PKT_SIZE_UPDATE_MODE   FIELD_MASK(1,17)
#define SYSPORT_TDMA_CONTROL_SYNC_PKT_SIZE_UPDATE_MODE  FIELD_MASK(1,18)
#define SYSPORT_TDMA_CONTROL_RING_CFG_M                 FIELD_MASK(1,19)
#define SYSPORT_TDMA_CONTROL_MAX_INFLIGHT_PBUFDMA       FIELD_MASK(5,22)
#define SYSPORT_TDMA_CONTROL_ACB_EN_M                   FIELD_MASK(1,27)
#define SYSPORT_TDMA_CONTROL_CSB_WR_EN                  FIELD_MASK(1,28)
#define SYSPORT_TDMA_CONTROL_TPD_16b_EN                 FIELD_MASK(1,29)
#define SYSPORT_TDMA_CONTROL_MPM_EN                     FIELD_MASK(1,30)

#define SYSPORT_TDMA_DESC_RING_CONTROL_FLUSH_M          FIELD_MASK(1,0)
#define SYSPORT_TDMA_DESC_RING_CONTROL_RING_EN_M        FIELD_MASK(1,1)

#define SYSPORT_TDMA_DESC_RING_INTR_CONTROL_THRESHOLD_S      0
#define SYSPORT_TDMA_DESC_RING_INTR_CONTROL_EMPTY_INTR_EN_M  FIELD_MASK(1,15)
#define SYSPORT_TDMA_DESC_RING_INTR_CONTROL_TIMEOUT_S        16

#define SYSPORT_TDMA_DESC_RING_MAPPING_QID_M            FIELD_MASK(3,0)
#define SYSPORT_TDMA_DESC_RING_MAPPING_QID_S            0
#define SYSPORT_TDMA_DESC_RING_MAPPING_PORT_ID_M        FIELD_MASK(3,3)
#define SYSPORT_TDMA_DESC_RING_MAPPING_PORT_ID_S        3
#define SYSPORT_TDMA_DESC_RING_MAPPING_IGNORE_STATUS_M  FIELD_MASK(1,6)
#define SYSPORT_TDMA_DESC_RING_MAPPING_CREDIT_M         FIELD_MASK(16,8)
#define SYSPORT_TDMA_DESC_RING_MAPPING_CREDIT_S         8

#define SYSTEMPORT_TDMA_ARBITER_MODE_SP           0
#define SYSTEMPORT_TDMA_ARBITER_MODE_RR           1
#define SYSTEMPORT_TDMA_ARBITER_MODE_WRR          2
#define SYSTEMPORT_TDMA_ARBITER_MODE_DRR          3

#define SYSPORT_TDMA_STATUS_TDMA_DISABLED_M       FIELD_MASK(1,0)
#define SYSPORT_TDMA_STATUS_LL_RAM_INIT_BUSY_M    FIELD_MASK(1,1)

#define SYSTEMPORT_TDMA_DDR_DESC_RING_PUSH_TIMER_TIMEOUT_M  FIELD_MASK(16,0)

#define SYSTEMPORT_TDMA_LS_CFG_LIGHT_STACKING_EN_M  FIELD_MASK(1,31)
#define SYSTEMPORT_TDMA_LS_CFG_OPCODE_M             FIELD_MASK(3,17)
#define SYSTEMPORT_TDMA_LS_CFG_OPCODE_S             17
#define SYSTEMPORT_TDMA_LS_CFG_TC_M                 FIELD_MASK(3,14)
#define SYSTEMPORT_TDMA_LS_CFG_TC_S                 14
#define SYSTEMPORT_TDMA_LS_CFG_PORT_MAP_M           FIELD_MASK(9,0)
#define SYSTEMPORT_TDMA_LS_CFG_PORT_MAP_S           0

#define SYSTEMPORT_TDMA_TIER1_ARBITER_CTRL_CREDIT_M             FIELD_MASK(16,4)
#define SYSTEMPORT_TDMA_TIER1_ARBITER_CTRL_CREDIT_S             4
#define SYSTEMPORT_TDMA_TIER1_ARBITER_CTRL_IGNORE_CONGESTION_M  FIELD_MASK(1,2)
#define SYSTEMPORT_TDMA_TIER1_ARBITER_CTRL_IGNORE_CONGESTION_S  2
#define SYSTEMPORT_TDMA_TIER1_ARBITER_CTRL_ARB_MODE_M           FIELD_MASK(2,0)
#define SYSTEMPORT_TDMA_TIER1_ARBITER_CTRL_ARB_MODE_S           0

#define SYSTEMPORT_TDMA_TIER2_ARBITER_CTRL_ARB_MODE_M           FIELD_MASK(2,0)
#define SYSTEMPORT_TDMA_TIER2_ARBITER_CTRL_ARB_MODE_S           0

#define SYSPORT_TDMA_CSB_INTR_CFG_THRESHOLD_M     FIELD_MASK(16,0)
#define SYSPORT_TDMA_CSB_INTR_CFG_THRESHOLD_S     0
#define SYSPORT_TDMA_CSB_INTR_CFG_TIMEOUT_M       FIELD_MASK(16,16)
#define SYSPORT_TDMA_CSB_INTR_CFG_TIMEOUT_S       16

#define SYSPORT_TDMA_SHAPERS_COMMON_CFG_T_REFRESH_M             FIELD_MASK(9,0)
#define SYSPORT_TDMA_SHAPERS_COMMON_CFG_T_REFRESH_S             0
#define SYSPORT_TDMA_SHAPERS_COMMON_CFG_TOKEN_SIZE_EXP_M        FIELD_MASK(3,9)
#define SYSPORT_TDMA_SHAPERS_COMMON_CFG_TOKEN_SIZE_EXP_S        9

#define SYSPORT_TDMA_QSHAPER_REFRESH_CIR_M        FIELD_MASK(16,0)
#define SYSPORT_TDMA_QSHAPER_REFRESH_CIR_S        0
#define SYSPORT_TDMA_QSHAPER_REFRESH_EIR_M        FIELD_MASK(16,16)
#define SYSPORT_TDMA_QSHAPER_REFRESH_EIR_S        16

#define SYSPORT_TDMA_PSHAPER_CFG_MAX_REFRESH_M    FIELD_MASK(16,0)
#define SYSPORT_TDMA_PSHAPER_CFG_MAX_REFRESH_S    0
#define SYSPORT_TDMA_PSHAPER_CFG_MAX_RATE_EN_M    FIELD_MASK(1,16)
#define SYSPORT_TDMA_PSHAPER_CFG_MAX_RATE_EN_S    16

#define SYSPORT_TDMA_PSHAPER_MAX_THRESHOLD_M      FIELD_MASK(29,0)
#define SYSPORT_TDMA_PSHAPER_MAX_THRESHOLD_S      0

#define SYSPORT_TDMA_DDR_DESC_RING_SIZE_M         FIELD_MASK(4,0)
#define SYSPORT_TDMA_DDR_DESC_RING_SIZE_S         0

#define SYSPORT_TDMA_QSHAPER_CIR_BUCKET_COUNT_M   FIELD_MASK(29,0)
#define SYSPORT_TDMA_QSHAPER_CIR_BUCKET_COUNT_S   0
#define SYSPORT_TDMA_QSHAPER_CIR_BUCKET_IN_PROFILE_M    FIELD_MASK(1,29)
#define SYSPORT_TDMA_QSHAPER_CIR_BUCKET_IS_GREEN_M      FIELD_MASK(1,30)
#define SYSPORT_TDMA_QSHAPER_CIR_BUCKET_BELOW_MIN_M     FIELD_MASK(1,31)

#define SYSPORT_TDMA_QSHAPER_EIR_BUCKET_COUNT_M   FIELD_MASK(29,0)
#define SYSPORT_TDMA_QSHAPER_EIR_BUCKET_COUNT_S   0

#define SYSPORT_TDMA_PSHAPER_STS_BUCKET_COUNT_M   FIELD_MASK(29,0)
#define SYSPORT_TDMA_PSHAPER_STS_BUCKET_COUNT_S   0
#define SYSPORT_TDMA_PSHAPER_STS_BUCKET_IN_PROFILE_M    FIELD_MASK(1,29)

typedef struct {
    systemport_tdma_descriptor_write_port SYSTEMPORT_TDMA_DESCRIPTOR_WRITE_PORT[32];
    systemport_tdma_descriptor_read_port  SYSTEMPORT_TDMA_DESCRIPTOR_READ_PORT[32];
    uint32_t SYSTEMPORT_TDMA_DESC_RING_CONTROL[32]; // 0x80214200
    uint32_t SYSTEMPORT_TDMA_DESC_RING_HEAD_TAIL_PTR[32]; // 0x80214280
    uint32_t SYSTEMPORT_TDMA_DESC_RING_COUNT[32];
    uint32_t SYSTEMPORT_TDMA_DESC_RING_MAX_THRESHOLD[32];
    uint32_t SYSTEMPORT_TDMA_DESC_RING_INTR_CONTROL[32];
    uint32_t SYSTEMPORT_TDMA_DESC_RING_PRODUCER_CONSUMER_INDEX[32];
    uint32_t SYSTEMPORT_TDMA_DESC_RING_MAPPING[32];
    uint32_t SYSTEMPORT_TDMA_DESC_RING_PCP_DEI_VID[32];
    uint32_t SYSTEMPORT_TDMA_DDR_DESC_RING_START[64]; // 0x80214600
    uint32_t SYSTEMPORT_TDMA_DDR_DESC_RING_SIZE[32];
    uint32_t SYSTEMPORT_TDMA_DDR_DESC_RING_CTRL[32];
    uint32_t SYSTEMPORT_TDMA_DDR_DESC_RING_PUSH_TIMER[32];
    uint32_t SYSTEMPORT_TDMA_LS_CFG[32];
    uint32_t SYSTEMPORT_TDMA_DESC_READ_CMD; // 0x80214900
    uint32_t SYSTEMPORT_TDMA_CONTROL;
    uint32_t SYSTEMPORT_TDMA_STATUS;
    uint32_t SYSTEMPORT_TDMA_RESERVED_0;
    uint32_t SYSTEMPORT_TDMA_TIER1_ARBITER_CTRL[8]; // 0x80214910
    uint32_t SYSTEMPORT_TDMA_TIER1_ARBITER_QUEUE_ENABLE[8];
    uint32_t SYSTEMPORT_TDMA_TIER2_ARBITER_CTRL; // 0x80214950
    uint32_t SYSTEMPORT_TDMA_OVER_MAX_THRESHOLD_STATUS;
    uint32_t SYSTEMPORT_TDMA_OVER_HYST_THRESHOLD_STATUS;
    uint32_t SYSTEMPORT_TDMA_TPID;
    uint32_t SYSTEMPORT_TDMA_FREE_LIST_HEAD_TAIL_PTR;
    uint32_t SYSTEMPORT_TDMA_FREE_LIST_COUNT;
    uint32_t SYSTEMPORT_TDMA_CSB_INTR_CFG;
    uint32_t SYSTEMPORT_TDMA_CSB_ADDR_LO;
    uint32_t SYSTEMPORT_TDMA_CSB_ADDR_HI;
    uint32_t SYSTEMPORT_TDMA_MPM_CFG;
    uint32_t SYSTEMPORT_TDMA_RRING_PRODUCER_INDEX;
    uint32_t SYSTEMPORT_TDMA_RRING_CONSUMER_INDEX;
    uint32_t SYSTEMPORT_TDMA_RRING_ADDR_LO;
    uint32_t SYSTEMPORT_TDMA_RRING_ADDR_HI;
    uint32_t SYSTEMPORT_TDMA_RRING_SIZE;
    uint32_t SYSTEMPORT_TDMA_RRING_BURST_CTRL;
    uint32_t SYSTEMPORT_TDMA_RRING_WR_PUSH_TIMER;
    uint32_t SYSTEMPORT_TDMA_RRING_CTRL;
#define SYSTEMPORT_TDMA_RRING_CTRL_FLUSH_M    FIELD_MASK(1,0)
#define SYSTEMPORT_TDMA_RRING_CTRL_RING_EN_M  FIELD_MASK(1,1)
    uint32_t SYSTEMPORT_TDMA_RRING_INTR_CFG;
    uint32_t SYSTEMPORT_TDMA_RESERVED_1;
    uint32_t SYSTEMPORT_TDMA_TEST;
    uint32_t SYSTEMPORT_TDMA_DEBUG;
    uint32_t SYSTEMPORT_TDMA_RRING_BP_COUNT; // 0x802149A8
    uint32_t SYSTEMPORT_TDMA_RESERVED_2;
    uint32_t SYSTEMPORT_TDMA_SYSRAM_DESC_RINGS_RD_ARB_CFG; // 0x802149B0
    uint32_t SYSTEMPORT_TDMA_SYSRAM_RECYCLE_RING_WR_ARB_CFG; // 0x802149B4
    uint32_t SYSTEMPORT_TDMA_RESERVED_3[14];
    uint32_t SYSTEMPORT_TDMA_SHAPERS_COMMON_CFG; // 0x802149F0
    uint32_t SYSTEMPORT_TDMA_RESERVED_4[3];
    uint32_t SYSTEMPORT_TDMA_QSHAPER_CTRL[32]; // 0x80214A00
    uint32_t SYSTEMPORT_TDMA_QSHAPER_REFRESH[32];
    uint32_t SYSTEMPORT_TDMA_QSHAPER_EBS_THRESHOLD[32];
    uint32_t SYSTEMPORT_TDMA_QSHAPER_CBS_THRESHOLD[32];
    uint32_t SYSTEMPORT_TDMA_QSHAPER_PKT_OVERHEAD[32];
    uint32_t SYSTEMPORT_TDMA_QSHAPER_WEIGHT_BOOST[32];
    uint32_t SYSTEMPORT_TDMA_QSHAPER_EIR_BUCKET_COUNT[32];
    uint32_t SYSTEMPORT_TDMA_QSHAPER_CIR_BUCKET_COUNT[32];
    uint32_t SYSTEMPORT_TDMA_PSHAPER_CFG[8]; // 0x80214E00
    uint32_t SYSTEMPORT_TDMA_PSHAPER_MAX_THRESHOLD[8];
    uint32_t SYSTEMPORT_TDMA_PSHAPER_STATUS[8]; // 0x80214E40
} SYSTEMPORT_TDMA;

#define SYSPORT_SPE_SPE_CNTRL_SPE_EN_M                      FIELD_MASK(1,0)

#define SYSTEMPORT_SPE_SPE_CACHE_CMD_COMMAND_LIST_INDEX_M   FIELD_MASK(16,0)
#define SYSTEMPORT_SPE_SPE_CACHE_CMD_CMD_M                  FIELD_MASK(2,16)
#define SYSTEMPORT_SPE_SPE_CACHE_CMD_CMD_S                  16
#define SYSTEMPORT_SPE_SPE_CACHE_CMD_START_BUSY_M           FIELD_MASK(1,18)

#define SYSTEMPORT_SPE_SPE_CACHE_CMD_CMD_INVALIDATE         0
#define SYSTEMPORT_SPE_SPE_CACHE_CMD_CMD_SET_STATIC         1
#define SYSTEMPORT_SPE_SPE_CACHE_CMD_CMD_CLEAR_STATIC       2

#define SYSTEMPORT_SPE_SPE_CACHE_CMD_COMMAND_LIST_INDEX_INVALID  0xFFFF

typedef struct {
    uint32_t SYSTEMPORT_SPE_SPE_CNTRL;
    uint32_t SYSTEMPORT_SPE_SPE_LFU_AW_MIN_PKT_COUNT;
    uint32_t SYSTEMPORT_SPE_SPE_LFU_AW_CNTRL_PERIOD;
    uint8_t  dummy_1[64];
    uint32_t SYSTEMPORT_SPE_SPE_CACHE_ENTRY_VALID_STATUS;
    uint32_t SYSTEMPORT_SPE_SPE_CACHE_CMD;
    uint32_t SYSTEMPORT_SPE_SPE_DDR_CMD_LIST_ARRAY_START_ADDR_LOW;
    uint32_t SYSTEMPORT_SPE_SPE_DDR_CMD_LIST_ARRAY_START_ADDR_HIGH;
    uint32_t SYSTEMPORT_SPE_RESERVED_0;
    uint32_t SYSTEMPORT_SPE_SPE_CACHE_MISS_COUNTER;
    uint32_t SYSTEMPORT_SPE_SPE_CACHE_HIT_COUNTER;
    uint8_t  dummy_2[152];
    uint32_t SYSTEMPORT_SPE_SPE_CACHE_ENTRY_KEY[32];
    uint8_t  dummy_3[128];
    uint32_t SYSTEMPORT_SPE_SPE_REFERENCE_COUNT[32];
} SYSTEMPORT_SPE;

#define SYSPORT_TOPCTRL_MISC_CNTL_PM_CLK_DIV_M            FIELD_MASK(8,8)
#define SYSPORT_TOPCTRL_MISC_CNTL_PM_CLK_DIV_S            8

#define SYSPORT_TOPCTRL_PM_CNTL_EEE_EN_M                  FIELD_MASK(1,0)
#define SYSPORT_TOPCTRL_PM_CNTL_TX_PM_EN_M                FIELD_MASK(1,1)
#define SYSPORT_TOPCTRL_PM_CNTL_RX_PM_EN_M                FIELD_MASK(1,2)

#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_RSB_SWAP_M          FIELD_MASK(2,0)
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_RSB_SWAP_S          0
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_TSB_SWAP_M          FIELD_MASK(2,2)
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_TSB_SWAP_S          2
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_RX_DDR_DESC_SWAP_M  FIELD_MASK(2,4)
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_RX_DDR_DESC_SWAP_S  4
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_TX_DDR_DESC_SWAP_M  FIELD_MASK(2,6)
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_TX_DDR_DESC_SWAP_S  6
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_PSB_SWAP_M          FIELD_MASK(3,8)
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_PSB_SWAP_S          8
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_CSB_SWAP_M          FIELD_MASK(3,11)
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_CSB_SWAP_S          11
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_SPE_SWAP_M          FIELD_MASK(2,14)
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_SPE_SWAP_S          14
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_RRING_ENTRY_SWAP_M  FIELD_MASK(1,16)
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_RRING_ENTRY_SWAP_S  16

#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_SWAP_NONE    0
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_SWAP_32      1
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_SWAP_64      2
#define SYSPORT_TOPCTRL_MISC_SWAP_CFG_SWAP_32_64   3

#define SYSTEMPORT_CLOCK_FREQUENCY  417  // 416.67MHz

typedef struct {
    uint32_t SYSTEMPORT_TOPCTRL_REV_CNTL;
    uint32_t SYSTEMPORT_TOPCTRL_RX_FLUSH_CNTL;
    uint32_t SYSTEMPORT_TOPCTRL_TX_FLUSH_CNTL;
    uint32_t SYSTEMPORT_TOPCTRL_MISC_CNTL;
    uint32_t SYSTEMPORT_TOPCTRL_PM_CNTL;
    uint32_t SYSTEMPORT_TOPCTRL_PM_STATUS;
    uint32_t SYSTEMPORT_TOPCTRL_TIMER_TICK_CNTL;
    uint32_t SYSTEMPORT_TOPCTRL_RESERVED_0;
    uint32_t SYSTEMPORT_TOPCTRL_MISC_SWAP_CFG;
    uint32_t SYSTEMPORT_TOPCTRL_RESERVED_1;
    uint32_t SYSTEMPORT_TOPCTRL_RESERVED_2;
    uint32_t SYSTEMPORT_TOPCTRL_TIMER0_TIMEOUT_PERIOD;
    uint32_t SYSTEMPORT_TOPCTRL_TIMER1_TIMEOUT_PERIOD;
} SYSTEMPORT_TOPCTRL;

#define SYSTEMPORT_RXCHK_ETHERTYPE_REMAP_MAX  32

typedef struct {
    uint32_t SYSTEMPORT_RXCHK_CONTROL;
    uint32_t SYSTEMPORT_RXCHK_BRCM_TAG[8];
    uint32_t SYSTEMPORT_RXCHK_BRCM_TAG_MASK[8];
    uint32_t SYSTEMPORT_RXCHK_BRCM_TAG_MATCH_STATUS; // 0x80210244
    uint32_t SYSTEMPORT_RXCHK_ETHERTYPE0;
    uint32_t SYSTEMPORT_RXCHK_ETHERTYPE1;
    uint32_t SYSTEMPORT_RXCHK_WAN_PORT_AND_HOST_CPU_MAPPING;
    uint32_t SYSTEMPORT_RXCHK_MLT_CONFIG;
    uint32_t SYSTEMPORT_RXCHK_RESERVED_0;
    uint32_t SYSTEMPORT_RXCHK_MLT_CMDDATA1;
    uint32_t SYSTEMPORT_RXCHK_MLT_DATA0;
    uint32_t SYSTEMPORT_RXCHK_BAD_CHECKSUM_PACKET_DISCARD_COUNTER;
    uint32_t SYSTEMPORT_RXCHK_OTHER_PACKET_DISCARD_COUNTER;
    uint32_t SYSTEMPORT_RXCHK_RSB32BX_CFG1;
    uint32_t SYSTEMPORT_RXCHK_RSB32BX_CFG2;
    uint32_t SYSTEMPORT_RXCHK_RSB32BX_CFG3; // FIXME
    uint8_t  dummy_0[8];
    uint32_t SYSTEMPORT_RXCHK_ETHERTYPE_REMAP[SYSTEMPORT_RXCHK_ETHERTYPE_REMAP_MAX]; // 0x80210280
    uint32_t SYSTEMPORT_RXCHK_DEFAULT_ETYPE_ID;
    uint32_t SYSTEMPORT_RXCHK_DUMMY_802P3_ETHERTYPE;
    uint32_t SYSTEMPORT_RXCHK_PHYSICAL_TO_LOGICAL_PORT_REMAP[4]; // 0x80210308
} SYSTEMPORT_RXCHK;

#define SYSPORT_RXCHK_CONTROL_RCHK_EN_M                   FIELD_MASK(1,0)
// FIXME
#define SYSPORT_RXCHK_CONTROL_SKIP_FCS_M                  FIELD_MASK(1,1)
#define SYSPORT_RXCHK_CONTROL_BAD_CHKSUM_DISCARD_EN_M     FIELD_MASK(1,2)
#define SYSPORT_RXCHK_CONTROL_BRCM_TAG_EN_M               FIELD_MASK(1,3)
#define SYSPORT_RXCHK_CONTROL_BRCM_TAG_MATCH_EN_M         FIELD_MASK(8,4)
#define SYSPORT_RXCHK_CONTROL_PARSE_TUNNELED_IP_M         FIELD_MASK(1,12)
#define SYSPORT_RXCHK_CONTROL_STRUCT_VIOL_EN_M            FIELD_MASK(1,13)
#define SYSPORT_RXCHK_CONTROL_STRUCT_VIOL_ACT_M           FIELD_MASK(1,14)
#define SYSPORT_RXCHK_CONTROL_INCOMPLETE_PACKET_ACT_M     FIELD_MASK(1,15)
#define SYSPORT_RXCHK_CONTROL_IPV6_DUP_EXTHDR_EN_M        FIELD_MASK(1,16)
#define SYSPORT_RXCHK_CONTROL_IPV6_DUP_EXTHDR_ACT_M       FIELD_MASK(1,17)
#define SYSPORT_RXCHK_CONTROL_UNEXPECTED_ETHTYPE_ACT_M    FIELD_MASK(1,18)
#define SYSPORT_RXCHK_CONTROL_LLCSNAP_HDR_ERR_ACT_M       FIELD_MASK(1,19)
#define SYSPORT_RXCHK_CONTROL_PPPOE_HDR_ERR_ACT_M         FIELD_MASK(1,20)
#define SYSPORT_RXCHK_CONTROL_L3_HDR_ERR_ACT_M            FIELD_MASK(1,21)
#define SYSPORT_RXCHK_CONTROL_MAC_RX_ERR_ACT_M            FIELD_MASK(1,22)
#define SYSPORT_RXCHK_CONTROL_PARSE_AUTH_M                FIELD_MASK(1,23)
#define SYSPORT_RXCHK_CONTROL_USE_IPV4DATALEN_M           FIELD_MASK(1,24)
#define SYSPORT_RXCHK_CONTROL_USE_IPV6DATALEN_M           FIELD_MASK(1,25)
#define SYSPORT_RXCHK_CONTROL_MLT_EN_M                    FIELD_MASK(1,27)
  // FIXME
#define SYSPORT_RXCHK_CONTROL_SWPKT_DISCARD_MODE          FIELD_MASK(1,28)

#define SYSPORT_RXCHK_MLT_CONFIG_DEFAULT_SRC_PORT_M       FIELD_MASK(3,0)
#define SYSPORT_RXCHK_MLT_CONFIG_DEFAULT_SRC_PORT_S       0
#define SYSPORT_RXCHK_MLT_CONFIG_LAN_DLF_RXQ_M            FIELD_MASK(3,4)
#define SYSPORT_RXCHK_MLT_CONFIG_LAN_DLF_RXQ_S            4
#define SYSPORT_RXCHK_MLT_CONFIG_WAN_DLF_RXQ_M            FIELD_MASK(3,8)
#define SYSPORT_RXCHK_MLT_CONFIG_WAN_DLF_RXQ_S            8

#define SYSPORT_RXCHK_MLT_CMDDATA1_MACDA_HIGH_M           FIELD_MASK(16,0)
#define SYSPORT_RXCHK_MLT_CMDDATA1_MACDA_HIGH_S           0
#define SYSPORT_RXCHK_MLT_CMDDATA1_VALID_M                FIELD_MASK(1,16)
#define SYSPORT_RXCHK_MLT_CMDDATA1_VALID_S                16
#define SYSPORT_RXCHK_MLT_CMDDATA1_MATCH_STATUS_M         FIELD_MASK(1,17)
#define SYSPORT_RXCHK_MLT_CMDDATA1_INDEX_M                FIELD_MASK(8,20)
#define SYSPORT_RXCHK_MLT_CMDDATA1_INDEX_S                20
#define SYSPORT_RXCHK_MLT_CMDDATA1_CMD_M                  FIELD_MASK(3,28)
#define SYSPORT_RXCHK_MLT_CMDDATA1_CMD_S                  28
#define SYSPORT_RXCHK_MLT_CMDDATA1_START_BUSY_M           FIELD_MASK(1,31)

#define SYSPORT_RXCHK_MLT_CMDDATA1_CMD_WRIDX              0
#define SYSPORT_RXCHK_MLT_CMDDATA1_CMD_CAMWR              1
#define SYSPORT_RXCHK_MLT_CMDDATA1_CMD_RDIDX              2
#define SYSPORT_RXCHK_MLT_CMDDATA1_CMD_SEARCH             3
#define SYSPORT_RXCHK_MLT_CMDDATA1_CMD_CLR                4
#define SYSPORT_RXCHK_MLT_CMDDATA1_CMD_CLRIDX             5
#define SYSPORT_RXCHK_MLT_CMDDATA1_CMD_INIT_CAM           7

#define SYSPORT_RXCHK_RSB32BX_CFG1_MAC_SA_EN_M            FIELD_MASK(1,0)
#define SYSPORT_RXCHK_RSB32BX_CFG1_MAX_VLAN_M             FIELD_MASK(3,1)
#define SYSPORT_RXCHK_RSB32BX_CFG1_MAX_VLAN_S             1
#define SYSPORT_RXCHK_RSB32BX_CFG1_L3_FORCE_M             FIELD_MASK(1,4)
#define SYSPORT_RXCHK_RSB32BX_CFG1_TCP_PURE_ACK_EN_M      FIELD_MASK(1,23)

#define SYSPORT_RXCHK_RSB32BX_CFG2_L3UCAST_TOS_EN_VECT_M      FIELD_MASK(8,0)
#define SYSPORT_RXCHK_RSB32BX_CFG2_L3UCAST_TOS_EN_VECT_S      0
#define SYSPORT_RXCHK_RSB32BX_CFG2_L2UCAST_TOS_EN_VECT_M      FIELD_MASK(8,8)
#define SYSPORT_RXCHK_RSB32BX_CFG2_L2UCAST_TOS_EN_VECT_S      8
#define SYSPORT_RXCHK_RSB32BX_CFG2_VLAN_DEI_EN_M              FIELD_MASK(1,16)
#define SYSPORT_RXCHK_RSB32BX_CFG2_VLAN_PCP_EN_M              FIELD_MASK(1,17)
#define SYSPORT_RXCHK_RSB32BX_CFG2_UCAST_L2_IP_TOS_UNKNOWN_M  FIELD_MASK(8,18)
#define SYSPORT_RXCHK_RSB32BX_CFG2_UCAST_L2_IP_TOS_UNKNOWN_S  18

#define SYSPORT_RXCHK_WAN_PORT_AND_HOST_CPU_MAPPING_WAN0_PORT_ID_M            FIELD_MASK(3,0)
#define SYSPORT_RXCHK_WAN_PORT_AND_HOST_CPU_MAPPING_WAN0_PORT_ID_S            0
#define SYSPORT_RXCHK_WAN_PORT_AND_HOST_CPU_MAPPING_WAN0_PORT_ENABLE_M        FIELD_MASK(1,4)
#define SYSPORT_RXCHK_WAN_PORT_AND_HOST_CPU_MAPPING_WAN1_PORT_ID_M            FIELD_MASK(3,8)
#define SYSPORT_RXCHK_WAN_PORT_AND_HOST_CPU_MAPPING_WAN1_PORT_ID_S            8
#define SYSPORT_RXCHK_WAN_PORT_AND_HOST_CPU_MAPPING_WAN1_PORT_ENABLE_M        FIELD_MASK(1,12)

#define SYSPORT_RXCHK_ETHERTYPE_REMAP_ETHTYPE0_M   FIELD_MASK(16,0)
#define SYSPORT_RXCHK_ETHERTYPE_REMAP_ETHTYPE0_S   0
#define SYSPORT_RXCHK_ETHERTYPE_REMAP_ETHTYPE1_M   FIELD_MASK(16,16)
#define SYSPORT_RXCHK_ETHERTYPE_REMAP_ETHTYPE1_S   16

typedef struct sysport {
    union {
        SYSTEMPORT_TOPCTRL SYSTEMPORT_TOPCTRL;
        uint8_t SYSTEMPORT_TOPCTRL_buf[512]; // 0x80210000
    };
    union {
        SYSTEMPORT_RXCHK SYSTEMPORT_RXCHK;
        uint8_t SYSTEMPORT_RXCHK_buf[512]; // 0x80210200
    };
    union {
        SYSTEMPORT_RBUF SYSTEMPORT_RBUF;
        uint8_t SYSTEMPORT_RBUF_buf[512]; // 0x80210400
    };
    union {
        SYSTEMPORT_TBUF SYSTEMPORT_TBUF;
        uint8_t SYSTEMPORT_TBUF_buf[6656]; // 0x80210600
    };
    union {
        SYSTEMPORT_RDMA SYSTEMPORT_RDMA;
        uint8_t SYSTEMPORT_RDMA_buf[8192]; // 0x80212000
    };
    union {
        SYSTEMPORT_TDMA SYSTEMPORT_TDMA;
        uint8_t SYSTEMPORT_TDMA_buf[8192]; // 0x80214000
    };
    union {
        SYSTEMPORT_SPE SYSTEMPORT_SPE;
        uint8_t SYSTEMPORT_SPE_buf[8704]; // 0x80216000
    };
    union {
        SYSTEMPORT_INTRL2_DUAL SYSTEMPORT_INTRL2_DUAL[5]; // 0x80218200
        uint8_t SYSTEMPORT_INTRL2_buf[512];
    };
    union {
        SYSTEMPORT_INTC SYSTEMPORT_INTC[5]; // 0x80218400
        uint8_t SYSTEMPORT_INTC_buf[512];
    };
    union {
        SYSTEMPORT_INTRL2 SYSTEMPORT_INTRL2_MISC0;
        uint8_t SYSTEMPORT_INTRL2_MISC_RX_buf[256];//0x80218600
    };
    union {
        SYSTEMPORT_INTRL2 SYSTEMPORT_INTRL2_MISC1;
        uint8_t SYSTEMPORT_INTRL2_MISC_TX_buf[256];//0x80218700
    };
} sysport;

#endif /* __6765_CROSSBOW_H__ */
