# SPDX-License-Identifier: GPL-2.0+
#
# Author: Srinath R <srinath@mistralsolutions.com>
#
# Based on logicpd/am3517evm/Makefile
#
# Copyright (C) 2011 Mistral Solutions Pvt Ltd

obj-y	:= am3517crane.o
