# 
# Copyright 2014 Trend Micro Incorporated 
# Redistribution and use in source and binary forms, with or without modification, 
# are permitted provided that the following conditions are met: 
# 1. Redistributions of source code must retain the above copyright notice, 
#    this list of conditions and the following disclaimer. 
# 2. Redistributions in binary form must reproduce the above copyright notice, 
#    this list of conditions and the following disclaimer in the documentation 
#    and/or other materials provided with the distribution. 
# 3. Neither the name of the copyright holder nor the names of its contributors 
#    may be used to endorse or promote products derived from this software without 
#    specific prior written permission. 
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
# OF SUCH DAMAGE. 
# 

# 
# Auto-generated. 
# Plz fix the variables to fit your env :D. Thank you. 
# 

ifeq ($(RTCONFIG_QCA),y)
TMCFG_KERN_ARCH := arm
TMCFG_TC_PFX := arm-openwrt-linux-uclibcgnueabi-
else ifeq ($(RTCONFIG_RALINK),y)
TMCFG_KERN_ARCH := mips
TMCFG_TC_PFX := mips-linux-uclibc-
else ifeq ($(RTCONFIG_BCMARM),y)
ifeq ($(HND_ROUTER),y)
TMCFG_KERN_ARCH := arm64
TMCFG_TC_PFX := aarch64-linux-
+else
ifeq ($(RTCONFIG_BCMARM),y)
TMCFG_KERN_ARCH := arm
TMCFG_TC_PFX := arm-brcm-linux-uclibcgnueabi-
else ifeq ($(RTCONFIG_BCM_ARM_GCLIBC),y)
TMCFG_KERN_ARCH := arm
TMCFG_TC_PFX := arm-buildroot-linux-gnueabi-
else ifeq ($(RTCONFIG_SOC_IPQ8064),y)
TMCFG_TC_PFX := arm-openwrt-linux-uclibcgnueabi-
else
TMCFG_KERN_ARCH := mips
TMCFG_TC_PFX := mipsel-uclibc-
endif
endif
endif

TMCFG_APP_U_EXTRA_CFLAGS := -I$(SRCBASE)/include -I$(SRCBASE)/common/include -I$(TDTS_KMOD_DIR)/../../include
