/*
    Copyright 2000-2018 Broadcom Corporation

    <:label-BRCM:2011:DUAL/GPL:standard
    
    Unless you and Broadcom execute a separate written software license
    agreement governing use of this software, this software is licensed
    to you under the terms of the GNU General Public License version 2
    (the "GPL"), available at http://www.broadcom.com/licenses/GPLv2.php,
    with the following added to such license:
    
       As a special exception, the copyright holders of this software give
       you permission to link this software with independent modules, and
       to copy and distribute the resulting executable under terms of your
       choice, provided that you also meet, for each linked independent
       module, the terms and conditions of the license of that module.
       An independent module is a module which is not derived from this
       software.  The special exception does not apply to any modifications
       of the software.
    
    Not withstanding the above, under no circumstances may you combine
    this software in any way with any other Broadcom software provided
    under a license other than the GPL, without Broadcom's express prior
    written consent.
    
    :>
*/

#include "bp_defs.h"
#include "boardparms.h"




bp_pinmux_fn_defs_t g_pinmux_fn_defs[] = {
  { BP_PINMUX_FNTYPE_NAND, 33 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_NAND, 34 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_NAND, 35 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_NAND, 36 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_NAND, 37 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_NAND, 38 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_NAND, 41 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_NAND, 42 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_NAND, 43 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_NAND, 44 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_NAND, 45 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_NAND, 46 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_NAND, 47 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_NAND, 48 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_EMMC, 39 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_EMMC, 40 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_EMMC, 44 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_EMMC, 45 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_EMMC, 46 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_EMMC, 47 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_EMMC, 48 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_EMMC, 33 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_EMMC, 34 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_EMMC, 35 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_HS_SPI, 102 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_HS_SPI, 103 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_HS_SPI, 104 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_LPORT, 98 | BP_PINMUX_VAL_7 },
  { BP_PINMUX_FNTYPE_LPORT, 99 | BP_PINMUX_VAL_7 },
  { BP_PINMUX_FNTYPE_xMII | 4, 86 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 4, 87 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 4, 88 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 4, 89 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 4, 90 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 4, 91 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 4, 92 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 4, 93 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 4, 94 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 4, 95 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 4, 96 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 4, 97 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 5, 62 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 5, 63 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 5, 64 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 5, 65 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 5, 66 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 5, 67 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 5, 68 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 5, 69 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 5, 70 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 5, 71 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 5, 72 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 5, 73 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 6, 74 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 6, 75 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 6, 76 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 6, 77 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 6, 78 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 6, 79 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 6, 80 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 6, 81 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 6, 82 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 6, 83 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 6, 84 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 6, 85 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 11, 80 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_xMII | 12, 80 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_PCM, 0 | BP_PINMUX_VAL_2 },
  { BP_PINMUX_FNTYPE_PCM, 1 | BP_PINMUX_VAL_2 },
  { BP_PINMUX_FNTYPE_PCM, 2 | BP_PINMUX_VAL_2 },
  { BP_PINMUX_FNTYPE_PCM, 3 | BP_PINMUX_VAL_2 },
  { BP_PINMUX_FNTYPE_DEFAULT, 113 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_DEFAULT, 114 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_DEFAULT, 115 | BP_PINMUX_VAL_1 },
  { BP_PINMUX_FNTYPE_DEFAULT, 116 | BP_PINMUX_VAL_1 },
};

bp_pinmux_defs_t g_pinmux_defs_0[] = {
  { bp_ReservedAnyGpio, -1, -1, BP_PINMUX_VAL_5 },
  { bp_usNetLed0, 0, 0, 0 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(0)},
  { bp_usNetLed1, 0, 1, 1 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(1)},
  { bp_usNetLed2, 0, 2, 2 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(2)},
  { bp_usNetLed3, 0, 21, 21 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(21)},
  { bp_usNetLed0, 1, 3, 3 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(3)},
  { bp_usNetLed1, 1, 4, 4 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(4)},
  { bp_usNetLed2, 1, 5, 5 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(5)},
  { bp_usNetLed3, 1, 22, 22 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(22)},
  { bp_usNetLed0, 2, 6, 6 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(6)},
  { bp_usNetLed1, 2, 7, 7 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(7)},
  { bp_usNetLed2, 2, 8, 8 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(8)},
  { bp_usNetLed3, 2, 23, 23 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(23)},
  { bp_usNetLed0, 3, 9, 9 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(9)},
  { bp_usNetLed1, 3, 10, 10 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(10)},
  { bp_usNetLed2, 3, 11, 11 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(11)},
  { bp_usNetLed3, 3, 28, 28 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(24)},
  { bp_usNetLed0, 4, 12, 12 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(12)},
  { bp_usNetLed1, 4, 13, 13 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(13)},
  { bp_usNetLed2, 4, 14, 14 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(14)},
  { bp_usNetLed3, 4, 29, 29 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(25)},
  { bp_usNetLed0, 5, 15, 15 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(15)},
  { bp_usNetLed1, 5, 16, 16 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(16)},
  { bp_usNetLed2, 5, 17, 17 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(17)},
  { bp_usNetLed3, 5, 30, 30 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(26)},
  { bp_usNetLed0, 6, 18, 18 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(18)},
  { bp_usNetLed1, 6, 19, 19 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(19)},
  { bp_usNetLed2, 6, 20, 20 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(20)},
  { bp_usNetLed3, 6, 31, 31 | BP_PINMUX_VAL_4 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(27)},
  { bp_usNetLed0, 0, 62, 62 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(0)},
  { bp_usNetLed1, 0, 63, 63 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(1)},
  { bp_usNetLed2, 0, 64, 64 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(2)},
  { bp_usNetLed3, 0, 32, 32 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(21)},
  { bp_usNetLed0, 1, 65, 65 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(3)},
  { bp_usNetLed1, 1, 66, 66 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(4)},
  { bp_usNetLed2, 1, 67, 67 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(5)},
  { bp_usNetLed3, 1, 29, 29 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(22)},
  { bp_usNetLed0, 2, 68, 68 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(6)},
  { bp_usNetLed1, 2, 69, 69 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(7)},
  { bp_usNetLed2, 2, 70, 70 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(8)},
  { bp_usNetLed3, 2, 30, 30 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(23)},
  { bp_usNetLed0, 3, 71, 71 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(9)},
  { bp_usNetLed1, 3, 72, 72 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(10)},
  { bp_usNetLed2, 3, 73, 73 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(11)},
  { bp_usNetLed3, 3, 31, 31 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(24)},
  { bp_usNetLed0, 4, 3, 3 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(12)},
  { bp_usNetLed1, 4, 4, 4 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(13)},
  { bp_usNetLed2, 4, 5, 5 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(14)},
  { bp_usNetLed3, 4, 22, 22 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(25)},
  { bp_usNetLed0, 5, 6, 6 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(15)},
  { bp_usNetLed1, 5, 7, 7 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(16)},
  { bp_usNetLed2, 5, 8, 8 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(17)},
  { bp_usNetLed3, 5, 23, 23 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(26)},
  { bp_usNetLed0, 6, 9, 9 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(18)},
  { bp_usNetLed1, 6, 10, 10 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(19)},
  { bp_usNetLed2, 6, 11, 11 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(20)},
  { bp_usNetLed3, 6, 28, 28 | BP_PINMUX_VAL_6 | BP_PINMUX_HWLED | BP_PINMUX_OPTLED_NUM(27)},
  { bp_usUart1Sdin, -1, 27, 27 | BP_PINMUX_VAL_1},
  { bp_usUart1Sdout, -1, 28, 28 | BP_PINMUX_VAL_1},
  { bp_usUart1Sdin, -1, 55, 55 | BP_PINMUX_VAL_3},
  { bp_usUart1Sdout, -1, 56, 56 | BP_PINMUX_VAL_3},
  { bp_usGpioUart2Sdin, -1, 0, 0 | BP_PINMUX_VAL_1},
  { bp_usGpioUart2Sdout,-1, 1, 1 | BP_PINMUX_VAL_1},
  { bp_usGpioUart2Cts, -1, 2, 2 | BP_PINMUX_VAL_1},
  { bp_usGpioUart2Rts, -1, 3, 3 | BP_PINMUX_VAL_1},
  { bp_usGpioUart2Sdin, -1, 16, 16 | BP_PINMUX_VAL_2},
  { bp_usGpioUart2Sdout,-1, 17, 17 | BP_PINMUX_VAL_2},
  { bp_usGpioUart2Cts, -1, 18, 18 | BP_PINMUX_VAL_2},
  { bp_usGpioUart2Rts, -1, 19, 19 | BP_PINMUX_VAL_2},
  { bp_usGpioUart2Sdin, -1, 27, 27 | BP_PINMUX_VAL_3},
  { bp_usGpioUart2Sdout,-1, 28, 28 | BP_PINMUX_VAL_3},
  { bp_usGpioUart2Cts, -1, 25, 25 | BP_PINMUX_VAL_3},
  { bp_usGpioUart2Rts, -1, 26, 26 | BP_PINMUX_VAL_3},
  { bp_usPcmSdin, -1, 0, 0 | BP_PINMUX_VAL_2},
  { bp_usPcmSdout, -1, 1, 1 | BP_PINMUX_VAL_2},
  { bp_usPcmClk, -1, 2, 2 | BP_PINMUX_VAL_2},
  { bp_usPcmFs, -1, 3, 3 | BP_PINMUX_VAL_2},
  { bp_usPcmSdin, -1, 58, 58 | BP_PINMUX_VAL_1},
  { bp_usPcmSdout, -1, 59, 59 | BP_PINMUX_VAL_1},
  { bp_usPcmClk, -1, 60, 60 | BP_PINMUX_VAL_1},
  { bp_usPcmFs, -1, 61, 61 | BP_PINMUX_VAL_1},
  { bp_usSpiSlaveSelectNum, 0, 105, 105 | BP_PINMUX_VAL_1},
  { bp_usSpiSlaveSelectNum, 1, 106, 106 | BP_PINMUX_VAL_1},
  { bp_usSpiSlaveSelectNum, 2, 0, 0 | BP_PINMUX_VAL_3},
  { bp_usSpiSlaveSelectNum, 2, 14, 14 | BP_PINMUX_VAL_1},
  { bp_usSpiSlaveSelectNum, 2, 51, 51 | BP_PINMUX_VAL_2},
  { bp_usSpiSlaveSelectNum, 3, 1, 1 | BP_PINMUX_VAL_3},
  { bp_usSpiSlaveSelectNum, 3, 13, 13 | BP_PINMUX_VAL_1},
  { bp_usSpiSlaveSelectNum, 3, 52, 52 | BP_PINMUX_VAL_2},
  { bp_usSpiSlaveSelectNum, 4, 2, 2 | BP_PINMUX_VAL_3},
  { bp_usSpiSlaveSelectNum, 4, 12, 12 | BP_PINMUX_VAL_1},
  { bp_usSpiSlaveSelectNum, 4, 53, 53 | BP_PINMUX_VAL_2},
  { bp_usSpiSlaveSelectNum, 5, 3, 3 | BP_PINMUX_VAL_3},
  { bp_usSpiSlaveSelectNum, 5, 11, 11 | BP_PINMUX_VAL_1},
  { bp_usSpiSlaveSelectNum, 5, 54, 54 | BP_PINMUX_VAL_2},
  { bp_usSerialLedData, -1, 4, 4 | BP_PINMUX_VAL_1 },
  { bp_usSerialLedClk, -1, 5, 5 | BP_PINMUX_VAL_1 },
  { bp_usSerialLedMask, -1, 6, 6 | BP_PINMUX_VAL_1 },
  { bp_usSerialLedData, -1, 29, 29 | BP_PINMUX_VAL_2 },
  { bp_usSerialLedClk, -1, 30, 30 | BP_PINMUX_VAL_2 },
  { bp_usSerialLedMask, -1, 31, 31 | BP_PINMUX_VAL_2 },
  { bp_usTsync1pps, -1, 11, 11 | BP_PINMUX_VAL_2 },
  { bp_usTsync1pps, -1, 32, 32 | BP_PINMUX_VAL_1 },
  { bp_usSimDat, -1, 16, 16 | BP_PINMUX_VAL_1 },
  { bp_usSimClk, -1, 17, 17 | BP_PINMUX_VAL_1 },
  { bp_usSimPresence, -1, 18, 18 | BP_PINMUX_VAL_1 },
  { bp_usSimVccEn, -1, 19, 19 | BP_PINMUX_VAL_1 },
  { bp_usSimVccVolSel, -1, 20, 20 | BP_PINMUX_VAL_1 },
  { bp_usSimRst, -1, 21, 21 | BP_PINMUX_VAL_1 },
  { bp_usSimVppEn, -1, 22, 22 | BP_PINMUX_VAL_1 },
  { bp_usSimDat, -1, 90, 90 | BP_PINMUX_VAL_3 },
  { bp_usSimClk, -1, 91, 91 | BP_PINMUX_VAL_3 },
  { bp_usSimPresence, -1, 92, 92 | BP_PINMUX_VAL_3 },
  { bp_usSimVccEn, -1, 86, 86 | BP_PINMUX_VAL_3 },
  { bp_usSimVccVolSel, -1, 87, 87 | BP_PINMUX_VAL_3 },
  { bp_usSimRst, -1, 88, 88 | BP_PINMUX_VAL_3 },
  { bp_usSimVppEn, -1, 89, 89 | BP_PINMUX_VAL_3 },
  { bp_usGpioI2cSda, -1, 25, 25 | BP_PINMUX_VAL_1 },
  { bp_usGpioI2cScl, -1, 26, 26 | BP_PINMUX_VAL_1 },
  { bp_usGpioI2cSda, -1, 39, 39 | BP_PINMUX_VAL_2 },
  { bp_usGpioI2cScl, -1, 40, 40 | BP_PINMUX_VAL_2 },
  { bp_usGpioI2c2Sda, -1, 24, 24 | BP_PINMUX_VAL_1 },
  { bp_usGpioI2c2Scl, -1, 23, 23 | BP_PINMUX_VAL_1 },
  { bp_usI2sSdata, -1, 31, 31 | BP_PINMUX_VAL_1 },
  { bp_usI2sSclk, -1, 30, 30 | BP_PINMUX_VAL_1 },
  { bp_usI2sLrck, -1, 29, 29 | BP_PINMUX_VAL_1 },
  { bp_usI2sSdata, -1, 59, 59 | BP_PINMUX_VAL_2 },
  { bp_usI2sSclk, -1, 60, 60 | BP_PINMUX_VAL_2 },
  { bp_usI2sLrck, -1, 61, 61 | BP_PINMUX_VAL_2 },
  { bp_usRogueOnuEn, -1, 32, 32 | BP_PINMUX_VAL_3 },
  { bp_usRogueOnuEn, -1, 56, 56 | BP_PINMUX_VAL_2 },
  { bp_usWanNcoProgMClk, -1, 55, 55 | BP_PINMUX_VAL_2 },
  { bp_usWanNco10MClk, -1, 58, 58 | BP_PINMUX_VAL_3 },
  { bp_usPmdMACEwakeEn, -1, 55, 55 | BP_PINMUX_VAL_6 },
  { bp_usPmdMACEwakeEn, -1, 56, 56 | BP_PINMUX_VAL_6 },
  { bp_usGpioWanSignalDetected, -1, 49, 49 | BP_PINMUX_VAL_5 },
  { bp_usUsbPwrOn0, -1, 113, 113 | BP_PINMUX_VAL_1 },
  { bp_usUsbPwrFlt0, -1, 114, 114 | BP_PINMUX_VAL_1 },
  { bp_usUsbPwrOn1, -1, 115, 115 | BP_PINMUX_VAL_1 },
  { bp_usUsbPwrFlt1, -1, 116, 116 | BP_PINMUX_VAL_1 },
  { bp_usGpioTxDis0, -1, 52, 52 | BP_PINMUX_VAL_5 },
  { bp_usSFPSerdesSIGDET0, -1, 57, 57|BP_PINMUX_VAL_6},
  { bp_usSFPSerdesSIGDET1, -1, 58, 58|BP_PINMUX_VAL_6},
  { bp_usSFPSerdesSIGDET2, -1, 59, 59|BP_PINMUX_VAL_6},
  { bp_usSFPSerdesSIGDET3, -1, 60, 60|BP_PINMUX_VAL_6},
  { bp_usSFPSerdesMODDEF0, -1, 24, 24|BP_PINMUX_VAL_7},
  { bp_usSFPSerdesMODDEF1, -1, 25, 25|BP_PINMUX_VAL_7},
  { bp_usSFPSerdesMODDEF2, -1, 26, 26|BP_PINMUX_VAL_7},
  { bp_usSFPSerdesMODDEF3, -1, 27, 27|BP_PINMUX_VAL_7},
  { bp_ReservedAnyLed, -1, 0, 0 |BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(0) },
  { bp_ReservedAnyLed, -1, 1, 1 |BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(1) },
  { bp_ReservedAnyLed, -1, 2, 2 |BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(2) },
  { bp_ReservedAnyLed, -1, 3, 3 |BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(3) },
  { bp_ReservedAnyLed, -1, 4, 4 |BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(4) },
  { bp_ReservedAnyLed, -1, 5, 5 |BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(5) },
  { bp_ReservedAnyLed, -1, 6, 6 |BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(6) },
  { bp_ReservedAnyLed, -1, 7, 7 |BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(7) },
  { bp_ReservedAnyLed, -1, 8, 8 |BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(8) },
  { bp_ReservedAnyLed, -1, 9, 9 |BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(9) },
  { bp_ReservedAnyLed, -1, 10, 10|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(10) },
  { bp_ReservedAnyLed, -1, 11, 11|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(11) },
  { bp_ReservedAnyLed, -1, 12, 12|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(12) },
  { bp_ReservedAnyLed, -1, 13, 13|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(13) },
  { bp_ReservedAnyLed, -1, 14, 14|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(14) },
  { bp_ReservedAnyLed, -1, 15, 15|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(15) },
  { bp_ReservedAnyLed, -1, 16, 16|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(16) },
  { bp_ReservedAnyLed, -1, 17, 17|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(17) },
  { bp_ReservedAnyLed, -1, 18, 18|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(18) },
  { bp_ReservedAnyLed, -1, 19, 19|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(19) },
  { bp_ReservedAnyLed, -1, 20, 20|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(20) },
  { bp_ReservedAnyLed, -1, 21, 21|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(21) },
  { bp_ReservedAnyLed, -1, 22, 22|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(22) },
  { bp_ReservedAnyLed, -1, 23, 23|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(23) },
  { bp_ReservedAnyLed, -1, 28, 28|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(24) },
  { bp_ReservedAnyLed, -1, 29, 29|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(25) },
  { bp_ReservedAnyLed, -1, 30, 30|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(26) },
  { bp_ReservedAnyLed, -1, 31, 31|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(27) },
  { bp_ReservedAnyLed, -1, 50, 50|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(28) },
  { bp_ReservedAnyLed, -1, 51, 51|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(29) },
  { bp_ReservedAnyLed, -1, 52, 52|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(30) },
  { bp_ReservedAnyLed, -1, 53, 53|BP_PINMUX_VAL_4 | BP_PINMUX_OPTLED_NUM(31) },
  { bp_ReservedAnyLed, -1, 62, 62 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(0) },
  { bp_ReservedAnyLed, -1, 63, 63 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(1) },
  { bp_ReservedAnyLed, -1, 64, 64 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(2) },
  { bp_ReservedAnyLed, -1, 65, 65 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(3) },
  { bp_ReservedAnyLed, -1, 66, 66 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(4) },
  { bp_ReservedAnyLed, -1, 67, 67 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(5) },
  { bp_ReservedAnyLed, -1, 68, 68 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(6) },
  { bp_ReservedAnyLed, -1, 69, 69 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(7) },
  { bp_ReservedAnyLed, -1, 70, 70 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(8) },
  { bp_ReservedAnyLed, -1, 71, 71 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(9) },
  { bp_ReservedAnyLed, -1, 72, 72 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(10) },
  { bp_ReservedAnyLed, -1, 73, 73 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(11) },
  { bp_ReservedAnyLed, -1, 3, 3 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(12) },
  { bp_ReservedAnyLed, -1, 4, 4 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(13) },
  { bp_ReservedAnyLed, -1, 5, 5 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(14) },
  { bp_ReservedAnyLed, -1, 6, 6 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(15) },
  { bp_ReservedAnyLed, -1, 7, 7 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(16) },
  { bp_ReservedAnyLed, -1, 8, 8 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(17) },
  { bp_ReservedAnyLed, -1, 9, 9 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(18) },
  { bp_ReservedAnyLed, -1, 10, 10 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(19) },
  { bp_ReservedAnyLed, -1, 11, 11 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(20) },
  { bp_ReservedAnyLed, -1, 32, 32 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(21) },
  { bp_ReservedAnyLed, -1, 29, 29 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(22) },
  { bp_ReservedAnyLed, -1, 30, 30 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(23) },
  { bp_ReservedAnyLed, -1, 31, 31 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(24) },
  { bp_ReservedAnyLed, -1, 22, 22 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(25) },
  { bp_ReservedAnyLed, -1, 23, 23 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(26) },
  { bp_ReservedAnyLed, -1, 28, 28 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(27) },
  { bp_ReservedAnyLed, -1, 20, 20 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(28) },
  { bp_ReservedAnyLed, -1, 21, 21 |BP_PINMUX_VAL_6 | BP_PINMUX_OPTLED_NUM(29) },
  { bp_usTsync8khz, -1, 12, 12 | BP_PINMUX_VAL_2},
  { bp_usTsync8khz, -1, 57, 57 | BP_PINMUX_VAL_1},
  { bp_last, -1, -1, 0 },
};

bp_pinmux_defs_t *g_pinmux_defs_tables[] = { g_pinmux_defs_0 } ;

int g_pinmux_fn_defs_size = sizeof(g_pinmux_fn_defs);
