# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2010
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-y	+= boot.o
obj-y	+= hwinit.o
obj-y	+= emif.o
obj-y	+= sdram.o
obj-y	+= prcm-regs.o
obj-y	+= hw_data.o
obj-y	+= abb.o
obj-y	+= fdt.o
obj-$(CONFIG_IODELAY_RECALIBRATION) += dra7xx_iodelay.o
obj-$(CONFIG_DRA7XX) += sec_entry_cpu1.o
