/*
   Copyright (c) 2015 Broadcom
   All Rights Reserved

    <:label-BRCM:2015:DUAL/GPL:standard
    
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License, version 2, as published by
    the Free Software Foundation (the "GPL").
    
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    
    
    A copy of the GPL is available at http://www.broadcom.com/licenses/GPLv2.php, or by
    writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
    
:>
*/


#ifndef _XRDP_NATC_INDIR_AG_H_
#define _XRDP_NATC_INDIR_AG_H_

#include "ru_types.h"

#define NATC_INDIR_ADDR_REG_NATC_ENTRY_FIELD_MASK 0x000003FF
#define NATC_INDIR_ADDR_REG_NATC_ENTRY_FIELD_WIDTH 10
#define NATC_INDIR_ADDR_REG_NATC_ENTRY_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec NATC_INDIR_ADDR_REG_NATC_ENTRY_FIELD;
#endif
#define NATC_INDIR_ADDR_REG_W_R_FIELD_MASK 0x00000400
#define NATC_INDIR_ADDR_REG_W_R_FIELD_WIDTH 1
#define NATC_INDIR_ADDR_REG_W_R_FIELD_SHIFT 10
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec NATC_INDIR_ADDR_REG_W_R_FIELD;
#endif
extern const ru_reg_rec NATC_INDIR_ADDR_REG_REG;
#define NATC_INDIR_ADDR_REG_REG_OFFSET 0x00000000

#define NATC_INDIR_DATA_REG_DATA_FIELD_MASK 0xFFFFFFFF
#define NATC_INDIR_DATA_REG_DATA_FIELD_WIDTH 32
#define NATC_INDIR_DATA_REG_DATA_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec NATC_INDIR_DATA_REG_DATA_FIELD;
#endif
extern const ru_reg_rec NATC_INDIR_DATA_REG_REG;
#define NATC_INDIR_DATA_REG_REG_OFFSET 0x00000010
#define NATC_INDIR_DATA_REG_REG_RAM_CNT 41

#define NATC_INDIR_NATC_FLOW_CNTR_INDIR_ADDR_REG_FLOW_CNTR_ENTRY_FIELD_MASK 0x0000007F
#define NATC_INDIR_NATC_FLOW_CNTR_INDIR_ADDR_REG_FLOW_CNTR_ENTRY_FIELD_WIDTH 7
#define NATC_INDIR_NATC_FLOW_CNTR_INDIR_ADDR_REG_FLOW_CNTR_ENTRY_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec NATC_INDIR_NATC_FLOW_CNTR_INDIR_ADDR_REG_FLOW_CNTR_ENTRY_FIELD;
#endif
#define NATC_INDIR_NATC_FLOW_CNTR_INDIR_ADDR_REG_W_R_FIELD_MASK 0x00000400
#define NATC_INDIR_NATC_FLOW_CNTR_INDIR_ADDR_REG_W_R_FIELD_WIDTH 1
#define NATC_INDIR_NATC_FLOW_CNTR_INDIR_ADDR_REG_W_R_FIELD_SHIFT 10
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec NATC_INDIR_NATC_FLOW_CNTR_INDIR_ADDR_REG_W_R_FIELD;
#endif
extern const ru_reg_rec NATC_INDIR_NATC_FLOW_CNTR_INDIR_ADDR_REG_REG;
#define NATC_INDIR_NATC_FLOW_CNTR_INDIR_ADDR_REG_REG_OFFSET 0x000000C0

#define NATC_INDIR_NATC_FLOW_CNTR_INDIR_DATA_REG_DATA_FIELD_MASK 0xFFFFFFFF
#define NATC_INDIR_NATC_FLOW_CNTR_INDIR_DATA_REG_DATA_FIELD_WIDTH 32
#define NATC_INDIR_NATC_FLOW_CNTR_INDIR_DATA_REG_DATA_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec NATC_INDIR_NATC_FLOW_CNTR_INDIR_DATA_REG_DATA_FIELD;
#endif
extern const ru_reg_rec NATC_INDIR_NATC_FLOW_CNTR_INDIR_DATA_REG_REG;
#define NATC_INDIR_NATC_FLOW_CNTR_INDIR_DATA_REG_REG_OFFSET 0x000000D0
#define NATC_INDIR_NATC_FLOW_CNTR_INDIR_DATA_REG_REG_RAM_CNT 2

extern const ru_block_rec NATC_INDIR_BLOCK;

#endif
