/*!\file wlcsm_dm_mngr_structoff.c
 * \brief Automatically generated header file wlcsm_dm_mngr_structoff.c
 */

#include "wlcsm_dm_generic.h"

WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI[]={
{"radio_number",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_WIFI_STRUCT,radio_number),                       WLCSM_DT_UINT,                -1        },
{"bssid_number",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_WIFI_STRUCT,bssid_number),                       WLCSM_DT_UINT,                -1        },
{"ssid_number",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_WIFI_STRUCT,ssid_number),                        WLCSM_DT_UINT,                -1        },
{"sta_number",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_WIFI_STRUCT,sta_number),                         WLCSM_DT_UINT,                -1        },
{"nvram",                      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_WIFI_STRUCT,nvram),                              WLCSM_DT_STRING,              -1        },
{"wlnvramversion",             WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_WIFI_STRUCT,wlNvramVersion),                     WLCSM_DT_UINT,                -1        },
{"x_cablelabs_com_ssidsteeringenable",WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_WIFI_STRUCT,X_CABLELABS_COM_SSIDSteeringEnable), WLCSM_DT_BOOL,                0         },
{"wlbridgeinfo",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_WIFI_STRUCT,wlBridgeInfo),                       WLCSM_DT_STRING,              1         },
};

WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_RADIO[]={
{"wlenbl",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlEnbl),                            WLCSM_DT_BOOL,                2         },
{"status",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,status),                            WLCSM_DT_STRING,              -1        },
{"ralias",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,rAlias),                            WLCSM_DT_STRING,              -1        },
{"name",                       WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,name),                              WLCSM_DT_STRING,              -1        },
{"lastchange",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,lastChange),                        WLCSM_DT_UINT,                -1        },
{"maxbitrate",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,maxBitRate),                        WLCSM_DT_UINT,                -1        },
{"wlfreqbands",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlFreqBands),                       WLCSM_DT_STRING,              -1        },
{"wlhasapsta",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlHasApsta),                        WLCSM_DT_BOOL,                3         },
{"wlcountry",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlCountry),                         WLCSM_DT_STRING,              4         },
{"wlssididx",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlSsidIdx),                         WLCSM_DT_SINT32,              -1        },
{"wlregrev",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlRegRev),                          WLCSM_DT_SINT32,              5         },
{"wlatf",                      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAtf),                             WLCSM_DT_SINT32,              6         },
{"wltaf",                      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlTaf),                             WLCSM_DT_SINT32,              7         },
{"wlband",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlBand),                            WLCSM_DT_STR2INT,             8         },
{"supportedstandards",         WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,supportedStandards),                WLCSM_DT_STRING,              -1        },
{"operatingstandards",         WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,operatingStandards),                WLCSM_DT_STRING,              9         },
{"wlphytype",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlPhyType),                         WLCSM_DT_STRING,              10        },
{"possiblechannels",           WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,possibleChannels),                  WLCSM_DT_STRING,              -1        },
{"channelsinuse",              WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,channelsInUse),                     WLCSM_DT_STRING,              -1        },
{"wlchannel",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlChannel),                         WLCSM_DT_UINT,                11        },
{"wlcurrentchannel",           WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlCurrentChannel),                  WLCSM_DT_UINT,                -1        },
{"autochannelsupported",       WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,autoChannelSupported),              WLCSM_DT_BOOL,                -1        },
{"autochannelenable",          WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,autoChannelEnable),                 WLCSM_DT_BOOL,                12        },
{"autochannelrefreshperiod",   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,autoChannelRefreshPeriod),          WLCSM_DT_UINT,                13        },
{"wlnmcsidx",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlNMcsidx),                         WLCSM_DT_SINT32,              -1        },
{"wlnbwcap",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlNBwCap),                          WLCSM_DT_SINT32,              -1        },
{"wlnbw",                      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlNBw),                             WLCSM_DT_STR2INT,             14        },
{"wlnctrlsb",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlNCtrlsb),                         WLCSM_DT_STR2INT,             15        },
{"guardinterval",              WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,guardInterval),                     WLCSM_DT_STRING,              16        },
{"mcs",                        WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,MCS),                               WLCSM_DT_SINT32,              17        },
{"transmitpowersupported",     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,transmitPowerSupported),            WLCSM_DT_STRING,              -1        },
{"wltxpwrpcnt",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlTxPwrPcnt),                       WLCSM_DT_SINT32,              -1        },
{"ieee80211hsupported",        WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,IEEE80211hSupported),               WLCSM_DT_BOOL,                -1        },
{"ieee80211henabled",          WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,IEEE80211hEnabled),                 WLCSM_DT_BOOL,                -1        },
{"radarthreshold",             WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,radarThreshold),                    WLCSM_DT_STRING,              18        },
{"wlcountryrev",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlCountryRev),                      WLCSM_DT_STRING,              -1        },
{"retrylimit",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,retryLimit),                        WLCSM_DT_UINT,                19        },
{"longretrylimit",             WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,longRetryLimit),                    WLCSM_DT_UINT,                20        },
{"operationaldatatransmitrates",WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,operationalDataTransmitRates),      WLCSM_DT_STRING,              -1        },
{"supporteddatatransmitrates", WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,supportedDataTransmitRates),        WLCSM_DT_STRING,              -1        },
{"bsdprimary",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,bsdPrimary),                        WLCSM_DT_STRING,              21        },
{"bsdhelper",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,bsdHelper),                         WLCSM_DT_STRING,              22        },
{"bsdhport",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,bsdHport),                          WLCSM_DT_SINT32,              23        },
{"bsdpport",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,bsdPport),                          WLCSM_DT_SINT32,              24        },
{"bsdrole",                    WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,bsdRole),                           WLCSM_DT_SINT32,              25        },
{"wltxbfcapable",              WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlTXBFCapable),                     WLCSM_DT_SINT32,              -1        },
{"wlregmode",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlRegMode),                         WLCSM_DT_SINT32,              26        },
{"wlintfertcptxfail",          WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlIntferTcptxfail),                 WLCSM_DT_SINT32,              27        },
{"wlintferperiod",             WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlIntferPeriod),                    WLCSM_DT_SINT32,              28        },
{"wlintfercnt",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlIntferCnt),                       WLCSM_DT_SINT32,              29        },
{"wlintfertxfail",             WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlIntferTxfail),                    WLCSM_DT_SINT32,              30        },
{"wlacsdfsrimmediate",         WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAcsDfsrImmediate),                WLCSM_DT_STRING,              31        },
{"wlacsexclchannels",          WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAcsExclChannels),                 WLCSM_DT_STRING,              32        },
{"wlacsdfsrdeferred",          WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAcsDfsrDeferred),                 WLCSM_DT_STRING,              33        },
{"wlacsdfsractivity",          WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAcsDfsrActivity),                 WLCSM_DT_STRING,              34        },
{"wlacsprefchannels",          WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAcsPrefChannels),                 WLCSM_DT_STRING,              35        },
{"wlacsfcsmode",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAcsFcsMode),                      WLCSM_DT_SINT32,              36        },
{"wlacsdfs",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAcsDfs),                          WLCSM_DT_SINT32,              37        },
{"wlacsciscantimer",           WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAcsCiScanTimer),                  WLCSM_DT_SINT32,              38        },
{"wlacsciscantimeout",         WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAcsCiScanTimeout),                WLCSM_DT_SINT32,              39        },
{"wlacsscanentryexpire",       WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAcsScanEntryExpire),              WLCSM_DT_SINT32,              40        },
{"wlacstxidlecnt",             WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAcsTxIdleCnt),                    WLCSM_DT_SINT32,              41        },
{"wlacschandwelltime",         WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAcsChanDwellTime),                WLCSM_DT_SINT32,              42        },
{"wlacschanflopperiod",        WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAcsChanFlopPeriod),               WLCSM_DT_SINT32,              43        },
{"wlmode",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlMode),                            WLCSM_DT_STRING,              44        },
{"wlcorerev",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlCoreRev),                         WLCSM_DT_SINT32,              45        },
{"wlbasicrate",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlBasicRate),                       WLCSM_DT_STRING,              46        },
{"wlprotection",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlProtection),                      WLCSM_DT_STRING,              47        },
{"wlpreambletype",             WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlPreambleType),                    WLCSM_DT_STRING,              48        },
{"wlframeburst",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlFrameBurst),                      WLCSM_DT_STRING,              49        },
{"wlfrgthrshld",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlFrgThrshld),                      WLCSM_DT_SINT32,              50        },
{"wlrtsthrshld",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlRtsThrshld),                      WLCSM_DT_SINT32,              51        },
{"wldtmintvl",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlDtmIntvl),                        WLCSM_DT_SINT32,              52        },
{"wlbcnintvl",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlBcnIntvl),                        WLCSM_DT_SINT32,              53        },
{"wlrate",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlRate),                            WLCSM_DT_SINT32,              54        },
{"wlgmode",                    WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlgMode),                           WLCSM_DT_SINT32,              55        },
{"wlmcastrate",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlMCastRate),                       WLCSM_DT_SINT32,              56        },
{"wlinfra",                    WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlInfra),                           WLCSM_DT_SINT32,              57        },
{"wlantdiv",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAntDiv),                          WLCSM_DT_SINT32,              58        },
{"wldfspreism",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlDfsPreIsm),                       WLCSM_DT_SINT32,              59        },
{"wldfspostism",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlDfsPostIsm),                      WLCSM_DT_SINT32,              60        },
{"wltpcdb",                    WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlTpcDb),                           WLCSM_DT_SINT32,              61        },
{"wlcsscantimer",              WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlCsScanTimer),                     WLCSM_DT_SINT32,              -1        },
{"wlmbands",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlMBands),                          WLCSM_DT_SINT32,              62        },
{"wlversion",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlVersion),                         WLCSM_DT_STRING,              63        },
{"wlnumbss",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlNumBss),                          WLCSM_DT_SINT32,              -1        },
{"wlmaxmbss",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlMaxMbss),                         WLCSM_DT_SINT32,              -1        },
{"wlsupportmbss",              WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlSupportMbss),                     WLCSM_DT_BOOL,                -1        },
{"wlnprotection",              WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlNProtection),                     WLCSM_DT_STRING,              64        },
{"wlampdusupported",           WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAmpduSupported),                  WLCSM_DT_SINT32,              -1        },
{"wlamsdusupported",           WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAmsduSupported),                  WLCSM_DT_SINT32,              -1        },
{"wlampdu",                    WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAmpdu),                           WLCSM_DT_STRING,              65        },
{"wlamsdu",                    WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlAmsdu),                           WLCSM_DT_STRING,              66        },
{"wlnmode",                    WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlNmode),                           WLCSM_DT_STRING,              67        },
{"wlstbctx",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlStbcTx),                          WLCSM_DT_SINT32,              68        },
{"wlstbcrx",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlStbcRx),                          WLCSM_DT_SINT32,              69        },
{"wllazywds",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlLazyWds),                         WLCSM_DT_SINT32,              70        },
{"wlhasafterburner",           WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlHasAfterburner),                  WLCSM_DT_SINT32,              -1        },
{"wlhaswmf",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlHasWmf),                          WLCSM_DT_SINT32,              -1        },
{"wlhaswme",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlHasWme),                          WLCSM_DT_SINT32,              -1        },
{"wlobsscoex",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlObssCoex),                        WLCSM_DT_SINT32,              71        },
{"wlrxchainpwrsaveenable",     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlRxChainPwrSaveEnable),            WLCSM_DT_SINT32,              72        },
{"wlrxchainpwrsavequiettime",  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlRxChainPwrSaveQuietTime),         WLCSM_DT_SINT32,              73        },
{"wlrxchainpwrsavepps",        WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlRxChainPwrSavePps),               WLCSM_DT_SINT32,              74        },
{"wlradiopwrsaveenable",       WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlRadioPwrSaveEnable),              WLCSM_DT_SINT32,              75        },
{"wlradiopwrsavequiettime",    WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlRadioPwrSaveQuietTime),           WLCSM_DT_SINT32,              76        },
{"wlradiopwrsavepps",          WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlRadioPwrSavePps),                 WLCSM_DT_SINT32,              77        },
{"wlradiopwrsavelevel",        WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlRadioPwrSaveLevel),               WLCSM_DT_SINT32,              78        },
{"wlwds",                      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlWds),                             WLCSM_DT_STRING,              79        },
{"wlwdssec",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlWdsSec),                          WLCSM_DT_SINT32,              80        },
{"wlwdstimeout",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlWdsTimeout),                      WLCSM_DT_SINT32,              81        },
{"wlwdskey",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlWdsKey),                          WLCSM_DT_STRING,              -1        },
{"wlwdssecenable",             WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlWdsSecEnable),                    WLCSM_DT_SINT32,              82        },
{"wlenableure",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlEnableUre),                       WLCSM_DT_SINT32,              -1        },
{"wlglobalmaxassoc",           WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlGlobalMaxAssoc),                  WLCSM_DT_SINT32,              83        },
{"wltxbfbfecap",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlTxbfBfeCap),                      WLCSM_DT_SINT32,              84        },
{"wltxbfbfrcap",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlTxbfBfrCap),                      WLCSM_DT_SINT32,              85        },
{"wlebosenable",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlEbosEnable),                      WLCSM_DT_SINT32,              86        },
{"wlshortretrylimitacbe",      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlShortRetryLimitAcBe),             WLCSM_DT_UINT,                -1        },
{"wllongretrylimitacbe",       WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlLongRetryLimitAcBe),              WLCSM_DT_UINT,                -1        },
{"wlshortretrylimitacbk",      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlShortRetryLimitAcBk),             WLCSM_DT_UINT,                -1        },
{"wllongretrylimitacbk",       WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlLongRetryLimitAcBk),              WLCSM_DT_UINT,                -1        },
{"wlshortretrylimitacvi",      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlShortRetryLimitAcVi),             WLCSM_DT_UINT,                -1        },
{"wllongretrylimitacvi",       WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlLongRetryLimitAcVi),              WLCSM_DT_UINT,                -1        },
{"wlshortretrylimitacvo",      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlShortRetryLimitAcVo),             WLCSM_DT_UINT,                -1        },
{"wllongretrylimitacvo",       WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlLongRetryLimitAcVo),              WLCSM_DT_UINT,                -1        },
{"wlrxchain",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlRxChain),                         WLCSM_DT_UINT,                87        },
{"wltxchain",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlTxChain),                         WLCSM_DT_UINT,                88        },
{"wlbandutilization",          WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlBandUtilization),                 WLCSM_DT_UINT,                -1        },
{"wlnpreambletype",            WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlNPreambleType),                   WLCSM_DT_STRING,              89        },
{"wlboottime",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,wlBootTime),                        WLCSM_DT_UINT,                90        },
{"dcsdwelltime",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STRUCT,dcsDwelltime),                      WLCSM_DT_UINT,                91        },
};

WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_RADIO_STATS[]={
{"bytessent",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STATS_STRUCT,bytesSent),                   WLCSM_DT_UINT64,              -1        },
{"bytesreceived",              WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STATS_STRUCT,bytesReceived),               WLCSM_DT_UINT64,              -1        },
{"packetssent",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STATS_STRUCT,packetsSent),                 WLCSM_DT_UINT64,              -1        },
{"packetsreceived",            WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STATS_STRUCT,packetsReceived),             WLCSM_DT_UINT64,              -1        },
{"errorssent",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STATS_STRUCT,errorsSent),                  WLCSM_DT_UINT,                -1        },
{"errorsreceived",             WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STATS_STRUCT,errorsReceived),              WLCSM_DT_UINT,                -1        },
{"discardpacketssent",         WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STATS_STRUCT,discardPacketsSent),          WLCSM_DT_UINT,                -1        },
{"discardpacketsreceived",     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_RADIO_STATS_STRUCT,discardPacketsReceived),      WLCSM_DT_UINT,                -1        },
};

WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_SSID[]={
{"wlenblssid",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_BSSID_STRUCT,wlEnblSsid),                        WLCSM_DT_BOOL,                92        },
{"status",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_BSSID_STRUCT,status),                            WLCSM_DT_STRING,              -1        },
{"salias",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_BSSID_STRUCT,sAlias),                            WLCSM_DT_STRING,              -1        },
{"name",                       WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_BSSID_STRUCT,name),                              WLCSM_DT_STRING,              93        },
{"wlbssid",                    WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_BSSID_STRUCT,wlBssid),                           WLCSM_DT_STRING,              94        },
{"wlssid",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_BSSID_STRUCT,wlSsid),                            WLCSM_DT_STRING,              95        },
{"wlenablewmf",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_BSSID_STRUCT,wlEnableWmf),                       WLCSM_DT_SINT32,              96        },
{"wlifname",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_BSSID_STRUCT,wlIfname),                          WLCSM_DT_STRING,              -1        },
{"wlbrname",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_BSSID_STRUCT,wlBrName),                          WLCSM_DT_STRING,              -1        },
};

WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_SSID_STATS[]={
{"bytessent",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,bytesSent),                    WLCSM_DT_UINT64,              -1        },
{"bytesreceived",              WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,bytesReceived),                WLCSM_DT_UINT64,              -1        },
{"packetssent",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,packetsSent),                  WLCSM_DT_UINT64,              -1        },
{"packetsreceived",            WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,packetsReceived),              WLCSM_DT_UINT64,              -1        },
{"errorssent",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,errorsSent),                   WLCSM_DT_UINT,                -1        },
{"errorsreceived",             WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,errorsReceived),               WLCSM_DT_UINT,                -1        },
{"unicastpacketssent",         WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,unicastPacketsSent),           WLCSM_DT_UINT64,              -1        },
{"unicastpacketsreceived",     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,unicastPacketsReceived),       WLCSM_DT_UINT64,              -1        },
{"discardpacketssent",         WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,discardPacketsSent),           WLCSM_DT_UINT,                -1        },
{"discardpacketsreceived",     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,discardPacketsReceived),       WLCSM_DT_UINT,                -1        },
{"multicastpacketssent",       WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,multicastPacketsSent),         WLCSM_DT_UINT64,              -1        },
{"multicastpacketsreceived",   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,multicastPacketsReceived),     WLCSM_DT_UINT64,              -1        },
{"broadcastpacketssent",       WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,broadcastPacketsSent),         WLCSM_DT_UINT64,              -1        },
{"broadcastpacketsreceived",   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,broadcastPacketsReceived),     WLCSM_DT_UINT64,              -1        },
{"unknownprotopacketsreceived",WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_SSID_STATS_STRUCT,unknownProtoPacketsReceived),  WLCSM_DT_UINT,                -1        },
};

WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_ACCESS_POINT[]={
{"apenable",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,apEnable),                             WLCSM_DT_BOOL,                -1        },
{"status",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,status),                               WLCSM_DT_STRING,              -1        },
{"apalias",                    WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,apAlias),                              WLCSM_DT_STRING,              -1        },
{"ssidreference",              WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,SSIDReference),                        WLCSM_DT_STRING,              -1        },
{"wlhide",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,wlHide),                               WLCSM_DT_BOOLREV,             97        },
{"wmmcapability",              WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,WMMCapability),                        WLCSM_DT_BOOL,                -1        },
{"uapsdcapability",            WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,UAPSDCapability),                      WLCSM_DT_BOOL,                -1        },
{"wldisablewme",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,wlDisableWme),                         WLCSM_DT_BOOLREV,             98        },
{"wlwmeapsd",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,wlWmeApsd),                            WLCSM_DT_SINT32,              99        },
{"numstations",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,numStations),                          WLCSM_DT_UINT,                -1        },
{"wlmaxassoc",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,wlMaxAssoc),                           WLCSM_DT_UINT,                100       },
{"wlapisolation",              WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,wlAPIsolation),                        WLCSM_DT_BOOL,                101       },
{"wlwme",                      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,wlWme),                                WLCSM_DT_SINT32,              102       },
{"wlwmenoack",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,wlWmeNoAck),                           WLCSM_DT_SINT32,              103       },
{"wlenablehspot",              WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,wlEnableHspot),                        WLCSM_DT_SINT32,              104       },
{"wlnreqd",                    WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,wlNReqd),                              WLCSM_DT_SINT32,              105       },
{"wlfltmacmode",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,wlFltMacMode),                         WLCSM_DT_STRING,              106       },
{"wlfltmaclist",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,wlFltMacList),                         WLCSM_DT_STRING,              107       },
{"wlbeaconrate",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STRUCT,wlBeaconRate),                         WLCSM_DT_UINT,                -1        },
};

WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_ACCESS_POINT_SECURITY[]={
{"reset",                      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,reset),                       WLCSM_DT_BOOL,                -1        },
{"modessupported",             WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,modesSupported),              WLCSM_DT_STRING,              -1        },
{"wlauthmode",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlAuthMode),                  WLCSM_DT_STRING,              108       },
{"wlwep",                      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlWep),                       WLCSM_DT_STRING,              109       },
{"wepkey",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,WEPKey),                      WLCSM_DT_HEXBINARY,           -1        },
{"presharedkey",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,preSharedKey),                WLCSM_DT_HEXBINARY,           -1        },
{"wlwpapsk",                   WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlWpaPsk),                    WLCSM_DT_STRING,              110       },
{"wlwpagtkrekey",              WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlWpaGTKRekey),               WLCSM_DT_UINT,                111       },
{"wlradiusserverip",           WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlRadiusServerIP),            WLCSM_DT_STRING,              112       },
{"secondaryradiusserveripaddr",WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,secondaryRadiusServerIPAddr), WLCSM_DT_STRING,              -1        },
{"wlradiusport",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlRadiusPort),                WLCSM_DT_UINT,                113       },
{"secondaryradiusserverport",  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,secondaryRadiusServerPort),   WLCSM_DT_UINT,                -1        },
{"wlradiuskey",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlRadiusKey),                 WLCSM_DT_STRING,              114       },
{"secondaryradiussecret",      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,secondaryRadiusSecret),       WLCSM_DT_STRING,              -1        },
{"wlkey1",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlKey1),                      WLCSM_DT_HEXBINARY,           115       },
{"wlkey2",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlKey2),                      WLCSM_DT_HEXBINARY,           116       },
{"wlkey3",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlKey3),                      WLCSM_DT_HEXBINARY,           117       },
{"wlkey4",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlKey4),                      WLCSM_DT_HEXBINARY,           118       },
{"wlkeyindex",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlKeyIndex),                  WLCSM_DT_SINT32,              119       },
{"wlwpa",                      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlWpa),                       WLCSM_DT_STRING,              120       },
{"wlauth",                     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlAuth),                      WLCSM_DT_SINT32,              121       },
{"wlpmf",                      WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlPmf),                       WLCSM_DT_SINT32,              122       },
{"wlpreauth",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlPreauth),                   WLCSM_DT_SINT32,              123       },
{"wlnetreauth",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlNetReauth),                 WLCSM_DT_SINT32,              124       },
{"wlproberesponsemf",          WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_SECURITY_STRUCT,wlProbeResponseMF),           WLCSM_DT_SINT32,              125       },
};

WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_ACCESS_POINT_WPS[]={
{"wpsenable",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_WPS_STRUCT,wpsEnable),                        WLCSM_DT_BOOL,                -1        },
{"configmethodssupported",     WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_WPS_STRUCT,configMethodsSupported),           WLCSM_DT_STRING,              -1        },
{"configmethodsenabled",       WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_WPS_STRUCT,configMethodsEnabled),             WLCSM_DT_STRING,              126       },
{"wlwscapmode",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_WPS_STRUCT,wlWscAPMode),                      WLCSM_DT_STRING,              127       },
{"wlwscmode",                  WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_WPS_STRUCT,wlWscMode),                        WLCSM_DT_STRING,              128       },
{"wlwscdevpin",                WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_WPS_STRUCT,wlWscDevPin),                      WLCSM_DT_STRING,              129       },
};

WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_ASSOCIATED_DEVICE[]={
{"macaddress",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STA_STRUCT,macAddress),                       WLCSM_DT_STRING,              -1        },
{"authorized",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STA_STRUCT,authorized),                       WLCSM_DT_BOOL,                -1        },
{"lastdatadownlinkrate",       WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STA_STRUCT,lastDataDownlinkRate),             WLCSM_DT_UINT,                -1        },
{"lastdatauplinkrate",         WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STA_STRUCT,lastDataUplinkRate),               WLCSM_DT_UINT,                -1        },
{"signalstrength",             WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STA_STRUCT,signalStrength),                   WLCSM_DT_SINT32,              -1        },
{"retransmissions",            WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STA_STRUCT,retransmissions),                  WLCSM_DT_UINT,                -1        },
{"associated",                 WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STA_STRUCT,associated),                       WLCSM_DT_BOOL,                -1        },
{"ssid",                       WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STA_STRUCT,ssid),                             WLCSM_DT_STRING,              -1        },
{"ifcname",                    WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STA_STRUCT,ifcname),                          WLCSM_DT_STRING,              -1        },
{"snr",                        WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STA_STRUCT,snr),                              WLCSM_DT_SINT32,              -1        },
{"operstandard",               WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STA_STRUCT,operStandard),                     WLCSM_DT_STRING,              -1        },
{"operbandwidth",              WLCSM_DM_VAR_POSOFF(WLCSM_WLAN_AP_STA_STRUCT,operBandwidth),                    WLCSM_DT_UINT,                -1        },
};

unsigned int g_WLMNGR_OIDS[6]={1250,1251,1253,1255,1256,1257}; 	/**<these are OIDs objects which carries wireless configuration */
unsigned int g_WLMNGR_OIDS_NUM=6; 		/**< total number of objects which carries wireless configuration */

unsigned int g_WLMNGR_RUNTIME_OIDS[3]={1252,1254,1258};	/**< these are OIDs objects that are runtime info, such as statistics */
unsigned int g_WLMNGR_RUNTIME_OIDS_NUM=3;			/**< total number of OIDs objects that are runtime info*/

WLCSM_DM_OID_MAPPING g_WLMNGR_OID_MAPPER[9]= {
{ 1250,	g_WLMNGR_STRUCT_DEV2_WIFI		,8},
{ 1251,	g_WLMNGR_STRUCT_DEV2_WIFI_RADIO		,132},
{ 1252,	g_WLMNGR_STRUCT_DEV2_WIFI_RADIO_STATS		,8},
{ 1253,	g_WLMNGR_STRUCT_DEV2_WIFI_SSID		,9},
{ 1254,	g_WLMNGR_STRUCT_DEV2_WIFI_SSID_STATS		,15},
{ 1255,	g_WLMNGR_STRUCT_DEV2_WIFI_ACCESS_POINT		,19},
{ 1256,	g_WLMNGR_STRUCT_DEV2_WIFI_ACCESS_POINT_SECURITY		,25},
{ 1257,	g_WLMNGR_STRUCT_DEV2_WIFI_ACCESS_POINT_WPS		,6},
{ 1258,	g_WLMNGR_STRUCT_DEV2_WIFI_ASSOCIATED_DEVICE		,12}
};
