#ifndef RUNNER_D_CODE_ADDRESSES
#define RUNNER_D_CODE_ADDRESSES

#define runner_d_start_task_initialization_task		(0x14)
#define runner_d_initialization_task		(0x14)
#define runner_d_start_task_timer_scheduler_set		(0x1B1C)
#define runner_d_timer_scheduler_set		(0x1B1C)
#define runner_d_start_task_flow_cache_wakeup_request		(0xCB4)
#define runner_d_flow_cache_wakeup_request		(0xCB4)
#define runner_d_start_task_lan_dispatch_wakeup_request		(0x18C4)
#define runner_d_lan_dispatch_wakeup_request		(0x18C4)
#define runner_d_start_task_lan_cpu_wakeup_request		(0x154)
#define runner_d_lan_cpu_wakeup_request		(0x154)
#define runner_d_start_task_debug_routine		(0x6C)
#define runner_d_debug_routine		(0x6C)
#define runner_d_start_task_free_skb_index_wakeup_request		(0x1C98)
#define runner_d_free_skb_index_wakeup_request		(0x1C98)
#define runner_d_free_skb_index_tx_abs_done		(0x1C98)
#define runner_d_start_task_dhd_rx_complete_wakeup_request		(0x1D6C)
#define runner_d_dhd_rx_complete_wakeup_request		(0x1D6C)
#define runner_d_gpe_sop_push_replace_ddr_sram_32		(0x1278)
#define runner_d_gpe_sop_push_replace_sram_32_64		(0x12EC)
#define runner_d_gpe_sop_push_replace_sram_64		(0x1300)
#define runner_d_gpe_sop_push_replace_sram_64_32		(0x1314)
#define runner_d_gpe_sop_pull_replace_ddr_sram_32		(0x1328)
#define runner_d_gpe_sop_pull_replace_sram_32_64		(0x139C)
#define runner_d_gpe_sop_pull_replace_sram_64		(0x13EC)
#define runner_d_gpe_sop_pull_replace_sram_64_32		(0x1428)
#define runner_d_gpe_replace_pointer_32_ddr		(0x1478)
#define runner_d_gpe_replace_pointer_32_sram		(0x149C)
#define runner_d_gpe_replace_pointer_64_sram		(0x14C0)
#define runner_d_gpe_replace_16		(0x14E4)
#define runner_d_gpe_replace_32		(0x1518)
#define runner_d_gpe_replace_bits_16		(0x153C)
#define runner_d_gpe_copy_add_16_cl		(0x1568)
#define runner_d_gpe_copy_add_16_sram		(0x1574)
#define runner_d_gpe_copy_bits_16_cl		(0x15BC)
#define runner_d_gpe_copy_bits_16_sram		(0x15C8)
#define runner_d_gpe_insert_16		(0x1610)
#define runner_d_gpe_delete_16		(0x1678)
#define runner_d_gpe_decrement_8		(0x16B8)
#define runner_d_gpe_apply_icsum_16		(0x16DC)
#define runner_d_gpe_apply_icsum_nz_16		(0x1700)
#define runner_d_gpe_compute_csum_16_cl		(0x173C)
#define runner_d_gpe_compute_csum_16_sram		(0x1748)
#define runner_d_gpe_buffer_copy_16_sram		(0x1788)
#define runner_d_gpe_buffer_copy_16_ddr		(0x17B0)
#define runner_d_upstream_ingress_rate_limiter_budget_allocate		(0x1B9C)
#define runner_d_upstream_quasi_budget_allocate		(0x1C1C)
#define runner_d_schedule_free_skb_index		(0x1C7C)

#endif
