#ifndef RUNNER_C_CODE_ADDRESSES
#define RUNNER_C_CODE_ADDRESSES

#define runner_c_start_task_initialization_task		(0x14)
#define runner_c_initialization_task		(0x14)
#define runner_c_start_task_timer_scheduler_set		(0x900)
#define runner_c_timer_scheduler_set		(0x900)
#define runner_c_start_task_rx_buffer_copy_wakeup_request		(0x170)
#define runner_c_rx_buffer_copy_wakeup_request		(0x170)
#define runner_c_start_task_capwapf_cpu_processing_wakeup_request		(0xC2C)
#define runner_c_capwapf_cpu_processing_wakeup_request		(0xC2C)
#define runner_c_start_task_lan_tx_wakeup_request		(0x588)
#define runner_c_lan_tx_wakeup_request		(0x588)
#define runner_c_start_task_cpu_tx_wakeup_request		(0x12B4)
#define runner_c_cpu_tx_wakeup_request		(0x12B4)
#define runner_c_start_task_lan_enqueue_ih_wakeup_request		(0x2F8)
#define runner_c_lan_enqueue_ih_wakeup_request		(0x2F8)
#define runner_c_start_task_lan_enqueue_pd_wakeup_request		(0x33C)
#define runner_c_lan_enqueue_pd_wakeup_request		(0x33C)
#define runner_c_start_task_multicast_lan_enqueue_wakeup_request		(0x38C)
#define runner_c_multicast_lan_enqueue_wakeup_request		(0x38C)
#define runner_c_start_task_wlan_mcast_wakeup_request		(0x1C78)
#define runner_c_wlan_mcast_wakeup_request		(0x1C78)
#define runner_c_start_task_cpu_rx_int_coalesce_timer_1st_wakeup_request		(0xB74)
#define runner_c_cpu_rx_int_coalesce_timer_1st_wakeup_request		(0xB74)
#define runner_c_start_task_debug_routine		(0x88)
#define runner_c_debug_routine		(0x88)
#define runner_c_start_task_timer_7_1st_wakeup_request		(0xAE0)
#define runner_c_timer_7_1st_wakeup_request		(0xAE0)
#define runner_c_start_task_free_skb_index_wakeup_request		(0xA70)
#define runner_c_free_skb_index_wakeup_request		(0xA70)
#define runner_c_start_task_service_queue_dequeue_wakeup_request		(0x23E8)
#define runner_c_service_queue_dequeue_wakeup_request		(0x23E8)
#define runner_c_start_task_service_queue_enqueue_wakeup_request		(0x2484)
#define runner_c_service_queue_enqueue_wakeup_request		(0x2484)
#define runner_c_ds_rate_limiter_budget_allocate		(0x980)
#define runner_c_ds_service_queue_rate_limiter_budget_allocate		(0xA3C)
#define runner_c_schedule_free_skb_index		(0xA54)
#define runner_c_pps_rate_limiter_timer_wakeup_request		(0xB44)
#define runner_c_spdsvc_timer_wakeup_request		(0x1844)

#endif
