#ifndef RUNNER_D_CODE_ADDRESSES
#define RUNNER_D_CODE_ADDRESSES

#define runner_d_start_task_initialization_task		(0x14)
#define runner_d_initialization_task		(0x14)
#define runner_d_start_task_timer_scheduler_set		(0x1A54)
#define runner_d_timer_scheduler_set		(0x1A54)
#define runner_d_start_task_flow_cache_wakeup_request		(0xBD8)
#define runner_d_flow_cache_wakeup_request		(0xBD8)
#define runner_d_start_task_lan_dispatch_wakeup_request		(0x17BC)
#define runner_d_lan_dispatch_wakeup_request		(0x17BC)
#define runner_d_start_task_debug_routine		(0x6C)
#define runner_d_debug_routine		(0x6C)
#define runner_d_start_task_free_skb_index_wakeup_request		(0x1BD0)
#define runner_d_free_skb_index_wakeup_request		(0x1BD0)
#define runner_d_free_skb_index_tx_abs_done		(0x1BD0)
#define runner_d_gpe_sop_push_replace_ddr_sram_32		(0x1178)
#define runner_d_gpe_sop_push_replace_sram_32_64		(0x11E8)
#define runner_d_gpe_sop_push_replace_sram_64		(0x11FC)
#define runner_d_gpe_sop_push_replace_sram_64_32		(0x1210)
#define runner_d_gpe_sop_pull_replace_ddr_sram_32		(0x1224)
#define runner_d_gpe_sop_pull_replace_sram_32_64		(0x1294)
#define runner_d_gpe_sop_pull_replace_sram_64		(0x12E4)
#define runner_d_gpe_sop_pull_replace_sram_64_32		(0x1320)
#define runner_d_gpe_replace_pointer_32_ddr		(0x1370)
#define runner_d_gpe_replace_pointer_32_sram		(0x1394)
#define runner_d_gpe_replace_pointer_64_sram		(0x13B8)
#define runner_d_gpe_replace_16		(0x13DC)
#define runner_d_gpe_replace_32		(0x1410)
#define runner_d_gpe_replace_bits_16		(0x1434)
#define runner_d_gpe_copy_add_16_cl		(0x1460)
#define runner_d_gpe_copy_add_16_sram		(0x146C)
#define runner_d_gpe_copy_bits_16_cl		(0x14B4)
#define runner_d_gpe_copy_bits_16_sram		(0x14C0)
#define runner_d_gpe_insert_16		(0x1508)
#define runner_d_gpe_delete_16		(0x1570)
#define runner_d_gpe_decrement_8		(0x15B0)
#define runner_d_gpe_apply_icsum_16		(0x15D4)
#define runner_d_gpe_apply_icsum_nz_16		(0x15F8)
#define runner_d_gpe_compute_csum_16_cl		(0x1634)
#define runner_d_gpe_compute_csum_16_sram		(0x1640)
#define runner_d_gpe_buffer_copy_16_sram		(0x1680)
#define runner_d_gpe_buffer_copy_16_ddr		(0x16A8)
#define runner_d_upstream_ingress_rate_limiter_budget_allocate		(0x1AD4)
#define runner_d_upstream_quasi_budget_allocate		(0x1B54)
#define runner_d_schedule_free_skb_index		(0x1BB4)

#endif
