#ifndef RUNNER_D_CODE_ADDRESSES
#define RUNNER_D_CODE_ADDRESSES

#define runner_d_start_task_initialization_task		(0x14)
#define runner_d_initialization_task		(0x14)
#define runner_d_start_task_timer_scheduler_set		(0x1A88)
#define runner_d_timer_scheduler_set		(0x1A88)
#define runner_d_start_task_flow_cache_wakeup_request		(0xC30)
#define runner_d_flow_cache_wakeup_request		(0xC30)
#define runner_d_start_task_lan_dispatch_wakeup_request		(0x1840)
#define runner_d_lan_dispatch_wakeup_request		(0x1840)
#define runner_d_start_task_lan_cpu_wakeup_request		(0x154)
#define runner_d_lan_cpu_wakeup_request		(0x154)
#define runner_d_start_task_debug_routine		(0x6C)
#define runner_d_debug_routine		(0x6C)
#define runner_d_start_task_free_skb_index_wakeup_request		(0x1C04)
#define runner_d_free_skb_index_wakeup_request		(0x1C04)
#define runner_d_free_skb_index_tx_abs_done		(0x1C04)
#define runner_d_start_task_dhd_rx_complete_wakeup_request		(0x1CD8)
#define runner_d_dhd_rx_complete_wakeup_request		(0x1CD8)
#define runner_d_gpe_sop_push_replace_ddr_sram_32		(0x11F4)
#define runner_d_gpe_sop_push_replace_sram_32_64		(0x1268)
#define runner_d_gpe_sop_push_replace_sram_64		(0x127C)
#define runner_d_gpe_sop_push_replace_sram_64_32		(0x1290)
#define runner_d_gpe_sop_pull_replace_ddr_sram_32		(0x12A4)
#define runner_d_gpe_sop_pull_replace_sram_32_64		(0x1318)
#define runner_d_gpe_sop_pull_replace_sram_64		(0x1368)
#define runner_d_gpe_sop_pull_replace_sram_64_32		(0x13A4)
#define runner_d_gpe_replace_pointer_32_ddr		(0x13F4)
#define runner_d_gpe_replace_pointer_32_sram		(0x1418)
#define runner_d_gpe_replace_pointer_64_sram		(0x143C)
#define runner_d_gpe_replace_16		(0x1460)
#define runner_d_gpe_replace_32		(0x1494)
#define runner_d_gpe_replace_bits_16		(0x14B8)
#define runner_d_gpe_copy_add_16_cl		(0x14E4)
#define runner_d_gpe_copy_add_16_sram		(0x14F0)
#define runner_d_gpe_copy_bits_16_cl		(0x1538)
#define runner_d_gpe_copy_bits_16_sram		(0x1544)
#define runner_d_gpe_insert_16		(0x158C)
#define runner_d_gpe_delete_16		(0x15F4)
#define runner_d_gpe_decrement_8		(0x1634)
#define runner_d_gpe_apply_icsum_16		(0x1658)
#define runner_d_gpe_apply_icsum_nz_16		(0x167C)
#define runner_d_gpe_compute_csum_16_cl		(0x16B8)
#define runner_d_gpe_compute_csum_16_sram		(0x16C4)
#define runner_d_gpe_buffer_copy_16_sram		(0x1704)
#define runner_d_gpe_buffer_copy_16_ddr		(0x172C)
#define runner_d_upstream_ingress_rate_limiter_budget_allocate		(0x1B08)
#define runner_d_upstream_quasi_budget_allocate		(0x1B88)
#define runner_d_schedule_free_skb_index		(0x1BE8)

#endif
