.TH "cfg_simple_t" 3 "Sat Jun 3 2017" "Version 3.2" "confuse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg_simple_t \- Data structure holding the pointer to a user provided variable defined with CFG_SIMPLE_*\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <confuse\&.h>\fP
.SH "Detailed Description"
.PP 
Data structure holding the pointer to a user provided variable defined with CFG_SIMPLE_*\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for confuse from the source code\&.
