.TH "cfg_defvalue_t" 3 "Sat Jun 3 2017" "Version 3.2" "confuse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg_defvalue_t \- Data structure holding the default value given by the initialization macros\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <confuse\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long int \fBnumber\fP"
.br
.RI "\fIdefault integer value \fP"
.ti -1c
.RI "double \fBfpnumber\fP"
.br
.RI "\fIdefault floating point value \fP"
.ti -1c
.RI "\fBcfg_bool_t\fP \fBboolean\fP"
.br
.RI "\fIdefault boolean value \fP"
.ti -1c
.RI "const char * \fBstring\fP"
.br
.RI "\fIdefault string value \fP"
.ti -1c
.RI "char * \fBparsed\fP"
.br
.RI "\fIdefault value that is parsed by libConfuse, used for lists and functions \fP"
.in -1c
.SH "Detailed Description"
.PP 
Data structure holding the default value given by the initialization macros\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for confuse from the source code\&.
