.TH "cfg_value_t" 3 "Sat Jun 3 2017" "Version 3.2" "confuse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg_value_t \- Data structure holding the value of a fundamental option value\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <confuse\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long int \fBnumber\fP"
.br
.RI "\fIinteger value \fP"
.ti -1c
.RI "double \fBfpnumber\fP"
.br
.RI "\fIfloating point value \fP"
.ti -1c
.RI "\fBcfg_bool_t\fP \fBboolean\fP"
.br
.RI "\fIboolean value \fP"
.ti -1c
.RI "char * \fBstring\fP"
.br
.RI "\fIstring value \fP"
.ti -1c
.RI "\fBcfg_t\fP * \fBsection\fP"
.br
.RI "\fIsection value \fP"
.ti -1c
.RI "void * \fBptr\fP"
.br
.RI "\fIuser-defined value \fP"
.in -1c
.SH "Detailed Description"
.PP 
Data structure holding the value of a fundamental option value\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for confuse from the source code\&.
