/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: usp-record.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "usp-record.pb-c.h"
void   usp_record__record__init
                     (UspRecord__Record         *message)
{
  static const UspRecord__Record init_value = USP_RECORD__RECORD__INIT;
  *message = init_value;
}
size_t usp_record__record__get_packed_size
                     (const UspRecord__Record *message)
{
  assert(message->base.descriptor == &usp_record__record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t usp_record__record__pack
                     (const UspRecord__Record *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &usp_record__record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t usp_record__record__pack_to_buffer
                     (const UspRecord__Record *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &usp_record__record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UspRecord__Record *
       usp_record__record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UspRecord__Record *)
     protobuf_c_message_unpack (&usp_record__record__descriptor,
                                allocator, len, data);
}
void   usp_record__record__free_unpacked
                     (UspRecord__Record *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &usp_record__record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   usp_record__no_session_context_record__init
                     (UspRecord__NoSessionContextRecord         *message)
{
  static const UspRecord__NoSessionContextRecord init_value = USP_RECORD__NO_SESSION_CONTEXT_RECORD__INIT;
  *message = init_value;
}
size_t usp_record__no_session_context_record__get_packed_size
                     (const UspRecord__NoSessionContextRecord *message)
{
  assert(message->base.descriptor == &usp_record__no_session_context_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t usp_record__no_session_context_record__pack
                     (const UspRecord__NoSessionContextRecord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &usp_record__no_session_context_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t usp_record__no_session_context_record__pack_to_buffer
                     (const UspRecord__NoSessionContextRecord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &usp_record__no_session_context_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UspRecord__NoSessionContextRecord *
       usp_record__no_session_context_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UspRecord__NoSessionContextRecord *)
     protobuf_c_message_unpack (&usp_record__no_session_context_record__descriptor,
                                allocator, len, data);
}
void   usp_record__no_session_context_record__free_unpacked
                     (UspRecord__NoSessionContextRecord *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &usp_record__no_session_context_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   usp_record__session_context_record__init
                     (UspRecord__SessionContextRecord         *message)
{
  static const UspRecord__SessionContextRecord init_value = USP_RECORD__SESSION_CONTEXT_RECORD__INIT;
  *message = init_value;
}
size_t usp_record__session_context_record__get_packed_size
                     (const UspRecord__SessionContextRecord *message)
{
  assert(message->base.descriptor == &usp_record__session_context_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t usp_record__session_context_record__pack
                     (const UspRecord__SessionContextRecord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &usp_record__session_context_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t usp_record__session_context_record__pack_to_buffer
                     (const UspRecord__SessionContextRecord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &usp_record__session_context_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UspRecord__SessionContextRecord *
       usp_record__session_context_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UspRecord__SessionContextRecord *)
     protobuf_c_message_unpack (&usp_record__session_context_record__descriptor,
                                allocator, len, data);
}
void   usp_record__session_context_record__free_unpacked
                     (UspRecord__SessionContextRecord *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &usp_record__session_context_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   usp_record__web_socket_connect_record__init
                     (UspRecord__WebSocketConnectRecord         *message)
{
  static const UspRecord__WebSocketConnectRecord init_value = USP_RECORD__WEB_SOCKET_CONNECT_RECORD__INIT;
  *message = init_value;
}
size_t usp_record__web_socket_connect_record__get_packed_size
                     (const UspRecord__WebSocketConnectRecord *message)
{
  assert(message->base.descriptor == &usp_record__web_socket_connect_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t usp_record__web_socket_connect_record__pack
                     (const UspRecord__WebSocketConnectRecord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &usp_record__web_socket_connect_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t usp_record__web_socket_connect_record__pack_to_buffer
                     (const UspRecord__WebSocketConnectRecord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &usp_record__web_socket_connect_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UspRecord__WebSocketConnectRecord *
       usp_record__web_socket_connect_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UspRecord__WebSocketConnectRecord *)
     protobuf_c_message_unpack (&usp_record__web_socket_connect_record__descriptor,
                                allocator, len, data);
}
void   usp_record__web_socket_connect_record__free_unpacked
                     (UspRecord__WebSocketConnectRecord *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &usp_record__web_socket_connect_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   usp_record__mqttconnect_record__init
                     (UspRecord__MQTTConnectRecord         *message)
{
  static const UspRecord__MQTTConnectRecord init_value = USP_RECORD__MQTTCONNECT_RECORD__INIT;
  *message = init_value;
}
size_t usp_record__mqttconnect_record__get_packed_size
                     (const UspRecord__MQTTConnectRecord *message)
{
  assert(message->base.descriptor == &usp_record__mqttconnect_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t usp_record__mqttconnect_record__pack
                     (const UspRecord__MQTTConnectRecord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &usp_record__mqttconnect_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t usp_record__mqttconnect_record__pack_to_buffer
                     (const UspRecord__MQTTConnectRecord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &usp_record__mqttconnect_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UspRecord__MQTTConnectRecord *
       usp_record__mqttconnect_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UspRecord__MQTTConnectRecord *)
     protobuf_c_message_unpack (&usp_record__mqttconnect_record__descriptor,
                                allocator, len, data);
}
void   usp_record__mqttconnect_record__free_unpacked
                     (UspRecord__MQTTConnectRecord *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &usp_record__mqttconnect_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   usp_record__stompconnect_record__init
                     (UspRecord__STOMPConnectRecord         *message)
{
  static const UspRecord__STOMPConnectRecord init_value = USP_RECORD__STOMPCONNECT_RECORD__INIT;
  *message = init_value;
}
size_t usp_record__stompconnect_record__get_packed_size
                     (const UspRecord__STOMPConnectRecord *message)
{
  assert(message->base.descriptor == &usp_record__stompconnect_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t usp_record__stompconnect_record__pack
                     (const UspRecord__STOMPConnectRecord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &usp_record__stompconnect_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t usp_record__stompconnect_record__pack_to_buffer
                     (const UspRecord__STOMPConnectRecord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &usp_record__stompconnect_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UspRecord__STOMPConnectRecord *
       usp_record__stompconnect_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UspRecord__STOMPConnectRecord *)
     protobuf_c_message_unpack (&usp_record__stompconnect_record__descriptor,
                                allocator, len, data);
}
void   usp_record__stompconnect_record__free_unpacked
                     (UspRecord__STOMPConnectRecord *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &usp_record__stompconnect_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   usp_record__disconnect_record__init
                     (UspRecord__DisconnectRecord         *message)
{
  static const UspRecord__DisconnectRecord init_value = USP_RECORD__DISCONNECT_RECORD__INIT;
  *message = init_value;
}
size_t usp_record__disconnect_record__get_packed_size
                     (const UspRecord__DisconnectRecord *message)
{
  assert(message->base.descriptor == &usp_record__disconnect_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t usp_record__disconnect_record__pack
                     (const UspRecord__DisconnectRecord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &usp_record__disconnect_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t usp_record__disconnect_record__pack_to_buffer
                     (const UspRecord__DisconnectRecord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &usp_record__disconnect_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UspRecord__DisconnectRecord *
       usp_record__disconnect_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UspRecord__DisconnectRecord *)
     protobuf_c_message_unpack (&usp_record__disconnect_record__descriptor,
                                allocator, len, data);
}
void   usp_record__disconnect_record__free_unpacked
                     (UspRecord__DisconnectRecord *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &usp_record__disconnect_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue usp_record__record__payload_security__enum_values_by_number[2] =
{
  { "PLAINTEXT", "USP_RECORD__RECORD__PAYLOAD_SECURITY__PLAINTEXT", 0 },
  { "TLS12", "USP_RECORD__RECORD__PAYLOAD_SECURITY__TLS12", 1 },
};
static const ProtobufCIntRange usp_record__record__payload_security__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex usp_record__record__payload_security__enum_values_by_name[2] =
{
  { "PLAINTEXT", 0 },
  { "TLS12", 1 },
};
const ProtobufCEnumDescriptor usp_record__record__payload_security__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "usp_record.Record.PayloadSecurity",
  "PayloadSecurity",
  "UspRecord__Record__PayloadSecurity",
  "usp_record",
  2,
  usp_record__record__payload_security__enum_values_by_number,
  2,
  usp_record__record__payload_security__enum_values_by_name,
  1,
  usp_record__record__payload_security__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor usp_record__record__field_descriptors[12] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UspRecord__Record, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "to_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UspRecord__Record, to_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "from_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UspRecord__Record, from_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload_security",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(UspRecord__Record, payload_security),
    &usp_record__record__payload_security__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac_signature",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UspRecord__Record, mac_signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sender_cert",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UspRecord__Record, sender_cert),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_session_context",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UspRecord__Record, record_type_case),
    offsetof(UspRecord__Record, no_session_context),
    &usp_record__no_session_context_record__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_context",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UspRecord__Record, record_type_case),
    offsetof(UspRecord__Record, session_context),
    &usp_record__session_context_record__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "websocket_connect",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UspRecord__Record, record_type_case),
    offsetof(UspRecord__Record, websocket_connect),
    &usp_record__web_socket_connect_record__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mqtt_connect",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UspRecord__Record, record_type_case),
    offsetof(UspRecord__Record, mqtt_connect),
    &usp_record__mqttconnect_record__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stomp_connect",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UspRecord__Record, record_type_case),
    offsetof(UspRecord__Record, stomp_connect),
    &usp_record__stompconnect_record__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "disconnect",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UspRecord__Record, record_type_case),
    offsetof(UspRecord__Record, disconnect),
    &usp_record__disconnect_record__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned usp_record__record__field_indices_by_name[] = {
  11,   /* field[11] = disconnect */
  2,   /* field[2] = from_id */
  4,   /* field[4] = mac_signature */
  9,   /* field[9] = mqtt_connect */
  6,   /* field[6] = no_session_context */
  3,   /* field[3] = payload_security */
  5,   /* field[5] = sender_cert */
  7,   /* field[7] = session_context */
  10,   /* field[10] = stomp_connect */
  1,   /* field[1] = to_id */
  0,   /* field[0] = version */
  8,   /* field[8] = websocket_connect */
};
static const ProtobufCIntRange usp_record__record__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor usp_record__record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "usp_record.Record",
  "Record",
  "UspRecord__Record",
  "usp_record",
  sizeof(UspRecord__Record),
  12,
  usp_record__record__field_descriptors,
  usp_record__record__field_indices_by_name,
  1,  usp_record__record__number_ranges,
  (ProtobufCMessageInit) usp_record__record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor usp_record__no_session_context_record__field_descriptors[1] =
{
  {
    "payload",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UspRecord__NoSessionContextRecord, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned usp_record__no_session_context_record__field_indices_by_name[] = {
  0,   /* field[0] = payload */
};
static const ProtobufCIntRange usp_record__no_session_context_record__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor usp_record__no_session_context_record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "usp_record.NoSessionContextRecord",
  "NoSessionContextRecord",
  "UspRecord__NoSessionContextRecord",
  "usp_record",
  sizeof(UspRecord__NoSessionContextRecord),
  1,
  usp_record__no_session_context_record__field_descriptors,
  usp_record__no_session_context_record__field_indices_by_name,
  1,  usp_record__no_session_context_record__number_ranges,
  (ProtobufCMessageInit) usp_record__no_session_context_record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue usp_record__session_context_record__payload_sarstate__enum_values_by_number[4] =
{
  { "NONE", "USP_RECORD__SESSION_CONTEXT_RECORD__PAYLOAD_SARSTATE__NONE", 0 },
  { "BEGIN", "USP_RECORD__SESSION_CONTEXT_RECORD__PAYLOAD_SARSTATE__BEGIN", 1 },
  { "INPROCESS", "USP_RECORD__SESSION_CONTEXT_RECORD__PAYLOAD_SARSTATE__INPROCESS", 2 },
  { "COMPLETE", "USP_RECORD__SESSION_CONTEXT_RECORD__PAYLOAD_SARSTATE__COMPLETE", 3 },
};
static const ProtobufCIntRange usp_record__session_context_record__payload_sarstate__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex usp_record__session_context_record__payload_sarstate__enum_values_by_name[4] =
{
  { "BEGIN", 1 },
  { "COMPLETE", 3 },
  { "INPROCESS", 2 },
  { "NONE", 0 },
};
const ProtobufCEnumDescriptor usp_record__session_context_record__payload_sarstate__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "usp_record.SessionContextRecord.PayloadSARState",
  "PayloadSARState",
  "UspRecord__SessionContextRecord__PayloadSARState",
  "usp_record",
  4,
  usp_record__session_context_record__payload_sarstate__enum_values_by_number,
  4,
  usp_record__session_context_record__payload_sarstate__enum_values_by_name,
  1,
  usp_record__session_context_record__payload_sarstate__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor usp_record__session_context_record__field_descriptors[7] =
{
  {
    "session_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(UspRecord__SessionContextRecord, session_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(UspRecord__SessionContextRecord, sequence_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expected_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(UspRecord__SessionContextRecord, expected_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retransmit_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(UspRecord__SessionContextRecord, retransmit_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload_sar_state",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(UspRecord__SessionContextRecord, payload_sar_state),
    &usp_record__session_context_record__payload_sarstate__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payloadrec_sar_state",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(UspRecord__SessionContextRecord, payloadrec_sar_state),
    &usp_record__session_context_record__payload_sarstate__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(UspRecord__SessionContextRecord, n_payload),
    offsetof(UspRecord__SessionContextRecord, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned usp_record__session_context_record__field_indices_by_name[] = {
  2,   /* field[2] = expected_id */
  6,   /* field[6] = payload */
  4,   /* field[4] = payload_sar_state */
  5,   /* field[5] = payloadrec_sar_state */
  3,   /* field[3] = retransmit_id */
  1,   /* field[1] = sequence_id */
  0,   /* field[0] = session_id */
};
static const ProtobufCIntRange usp_record__session_context_record__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor usp_record__session_context_record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "usp_record.SessionContextRecord",
  "SessionContextRecord",
  "UspRecord__SessionContextRecord",
  "usp_record",
  sizeof(UspRecord__SessionContextRecord),
  7,
  usp_record__session_context_record__field_descriptors,
  usp_record__session_context_record__field_indices_by_name,
  1,  usp_record__session_context_record__number_ranges,
  (ProtobufCMessageInit) usp_record__session_context_record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define usp_record__web_socket_connect_record__field_descriptors NULL
#define usp_record__web_socket_connect_record__field_indices_by_name NULL
#define usp_record__web_socket_connect_record__number_ranges NULL
const ProtobufCMessageDescriptor usp_record__web_socket_connect_record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "usp_record.WebSocketConnectRecord",
  "WebSocketConnectRecord",
  "UspRecord__WebSocketConnectRecord",
  "usp_record",
  sizeof(UspRecord__WebSocketConnectRecord),
  0,
  usp_record__web_socket_connect_record__field_descriptors,
  usp_record__web_socket_connect_record__field_indices_by_name,
  0,  usp_record__web_socket_connect_record__number_ranges,
  (ProtobufCMessageInit) usp_record__web_socket_connect_record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue usp_record__mqttconnect_record__mqttversion__enum_values_by_number[2] =
{
  { "V3_1_1", "USP_RECORD__MQTTCONNECT_RECORD__MQTTVERSION__V3_1_1", 0 },
  { "V5", "USP_RECORD__MQTTCONNECT_RECORD__MQTTVERSION__V5", 1 },
};
static const ProtobufCIntRange usp_record__mqttconnect_record__mqttversion__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex usp_record__mqttconnect_record__mqttversion__enum_values_by_name[2] =
{
  { "V3_1_1", 0 },
  { "V5", 1 },
};
const ProtobufCEnumDescriptor usp_record__mqttconnect_record__mqttversion__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "usp_record.MQTTConnectRecord.MQTTVersion",
  "MQTTVersion",
  "UspRecord__MQTTConnectRecord__MQTTVersion",
  "usp_record",
  2,
  usp_record__mqttconnect_record__mqttversion__enum_values_by_number,
  2,
  usp_record__mqttconnect_record__mqttversion__enum_values_by_name,
  1,
  usp_record__mqttconnect_record__mqttversion__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor usp_record__mqttconnect_record__field_descriptors[2] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(UspRecord__MQTTConnectRecord, version),
    &usp_record__mqttconnect_record__mqttversion__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subscribed_topic",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UspRecord__MQTTConnectRecord, subscribed_topic),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned usp_record__mqttconnect_record__field_indices_by_name[] = {
  1,   /* field[1] = subscribed_topic */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange usp_record__mqttconnect_record__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor usp_record__mqttconnect_record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "usp_record.MQTTConnectRecord",
  "MQTTConnectRecord",
  "UspRecord__MQTTConnectRecord",
  "usp_record",
  sizeof(UspRecord__MQTTConnectRecord),
  2,
  usp_record__mqttconnect_record__field_descriptors,
  usp_record__mqttconnect_record__field_indices_by_name,
  1,  usp_record__mqttconnect_record__number_ranges,
  (ProtobufCMessageInit) usp_record__mqttconnect_record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue usp_record__stompconnect_record__stompversion__enum_values_by_number[1] =
{
  { "V1_2", "USP_RECORD__STOMPCONNECT_RECORD__STOMPVERSION__V1_2", 0 },
};
static const ProtobufCIntRange usp_record__stompconnect_record__stompversion__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex usp_record__stompconnect_record__stompversion__enum_values_by_name[1] =
{
  { "V1_2", 0 },
};
const ProtobufCEnumDescriptor usp_record__stompconnect_record__stompversion__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "usp_record.STOMPConnectRecord.STOMPVersion",
  "STOMPVersion",
  "UspRecord__STOMPConnectRecord__STOMPVersion",
  "usp_record",
  1,
  usp_record__stompconnect_record__stompversion__enum_values_by_number,
  1,
  usp_record__stompconnect_record__stompversion__enum_values_by_name,
  1,
  usp_record__stompconnect_record__stompversion__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor usp_record__stompconnect_record__field_descriptors[2] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(UspRecord__STOMPConnectRecord, version),
    &usp_record__stompconnect_record__stompversion__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subscribed_destination",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UspRecord__STOMPConnectRecord, subscribed_destination),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned usp_record__stompconnect_record__field_indices_by_name[] = {
  1,   /* field[1] = subscribed_destination */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange usp_record__stompconnect_record__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor usp_record__stompconnect_record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "usp_record.STOMPConnectRecord",
  "STOMPConnectRecord",
  "UspRecord__STOMPConnectRecord",
  "usp_record",
  sizeof(UspRecord__STOMPConnectRecord),
  2,
  usp_record__stompconnect_record__field_descriptors,
  usp_record__stompconnect_record__field_indices_by_name,
  1,  usp_record__stompconnect_record__number_ranges,
  (ProtobufCMessageInit) usp_record__stompconnect_record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor usp_record__disconnect_record__field_descriptors[2] =
{
  {
    "reason",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UspRecord__DisconnectRecord, reason),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reason_code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(UspRecord__DisconnectRecord, reason_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned usp_record__disconnect_record__field_indices_by_name[] = {
  0,   /* field[0] = reason */
  1,   /* field[1] = reason_code */
};
static const ProtobufCIntRange usp_record__disconnect_record__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor usp_record__disconnect_record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "usp_record.DisconnectRecord",
  "DisconnectRecord",
  "UspRecord__DisconnectRecord",
  "usp_record",
  sizeof(UspRecord__DisconnectRecord),
  2,
  usp_record__disconnect_record__field_descriptors,
  usp_record__disconnect_record__field_indices_by_name,
  1,  usp_record__disconnect_record__number_ranges,
  (ProtobufCMessageInit) usp_record__disconnect_record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
