/*
   Copyright (c) 2015 Broadcom
   All Rights Reserved

    <:label-BRCM:2015:DUAL/GPL:standard

    Unless you and Broadcom execute a separate written software license
    agreement governing use of this software, this software is licensed
    to you under the terms of the GNU General Public License version 2
    (the "GPL"), available at http://www.broadcom.com/licenses/GPLv2.php,
    with the following added to such license:

       As a special exception, the copyright holders of this software give
       you permission to link this software with independent modules, and
       to copy and distribute the resulting executable under terms of your
       choice, provided that you also meet, for each linked independent
       module, the terms and conditions of the license of that module.
       An independent module is a module which is not derived from this
       software.  The special exception does not apply to any modifications
       of the software.

    Not withstanding the above, under no circumstances may you combine
    this software in any way with any other Broadcom software provided
    under a license other than the GPL, without Broadcom's express prior
    written consent.

:>
*/


#ifndef _XRDP_UBUS_RESP_AG_H_
#define _XRDP_UBUS_RESP_AG_H_

#include "ru_types.h"

#define UBUS_RESP_PROFILING_CFG_COUNTER_ENABLE_FIELD_MASK 0x00000001
#define UBUS_RESP_PROFILING_CFG_COUNTER_ENABLE_FIELD_WIDTH 1
#define UBUS_RESP_PROFILING_CFG_COUNTER_ENABLE_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_PROFILING_CFG_COUNTER_ENABLE_FIELD;
#endif
#define UBUS_RESP_PROFILING_CFG_PROFILING_START_FIELD_MASK 0x00000002
#define UBUS_RESP_PROFILING_CFG_PROFILING_START_FIELD_WIDTH 1
#define UBUS_RESP_PROFILING_CFG_PROFILING_START_FIELD_SHIFT 1
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_PROFILING_CFG_PROFILING_START_FIELD;
#endif
#define UBUS_RESP_PROFILING_CFG_MANUAL_STOP_MODE_FIELD_MASK 0x00000004
#define UBUS_RESP_PROFILING_CFG_MANUAL_STOP_MODE_FIELD_WIDTH 1
#define UBUS_RESP_PROFILING_CFG_MANUAL_STOP_MODE_FIELD_SHIFT 2
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_PROFILING_CFG_MANUAL_STOP_MODE_FIELD;
#endif
#define UBUS_RESP_PROFILING_CFG_DO_MANUAL_STOP_FIELD_MASK 0x00000008
#define UBUS_RESP_PROFILING_CFG_DO_MANUAL_STOP_FIELD_WIDTH 1
#define UBUS_RESP_PROFILING_CFG_DO_MANUAL_STOP_FIELD_SHIFT 3
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_PROFILING_CFG_DO_MANUAL_STOP_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_PROFILING_CFG_REG;
#define UBUS_RESP_PROFILING_CFG_REG_OFFSET 0x00000100

#define UBUS_RESP_PROFILING_STATUS_PROFILING_ON_FIELD_MASK 0x00000001
#define UBUS_RESP_PROFILING_STATUS_PROFILING_ON_FIELD_WIDTH 1
#define UBUS_RESP_PROFILING_STATUS_PROFILING_ON_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_PROFILING_STATUS_PROFILING_ON_FIELD;
#endif
#define UBUS_RESP_PROFILING_STATUS_CYCLES_COUNTER_FIELD_MASK 0xFFFFFFFE
#define UBUS_RESP_PROFILING_STATUS_CYCLES_COUNTER_FIELD_WIDTH 31
#define UBUS_RESP_PROFILING_STATUS_CYCLES_COUNTER_FIELD_SHIFT 1
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_PROFILING_STATUS_CYCLES_COUNTER_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_PROFILING_STATUS_REG;
#define UBUS_RESP_PROFILING_STATUS_REG_OFFSET 0x00000104

#define UBUS_RESP_PROFILING_COUNTER_VAL_FIELD_MASK 0xFFFFFFFF
#define UBUS_RESP_PROFILING_COUNTER_VAL_FIELD_WIDTH 32
#define UBUS_RESP_PROFILING_COUNTER_VAL_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_PROFILING_COUNTER_VAL_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_PROFILING_COUNTER_REG;
#define UBUS_RESP_PROFILING_COUNTER_REG_OFFSET 0x00000108

#define UBUS_RESP_PROFILING_START_VALUE_VAL_FIELD_MASK 0xFFFFFFFF
#define UBUS_RESP_PROFILING_START_VALUE_VAL_FIELD_WIDTH 32
#define UBUS_RESP_PROFILING_START_VALUE_VAL_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_PROFILING_START_VALUE_VAL_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_PROFILING_START_VALUE_REG;
#define UBUS_RESP_PROFILING_START_VALUE_REG_OFFSET 0x0000010C

#define UBUS_RESP_PROFILING_STOP_VALUE_VAL_FIELD_MASK 0xFFFFFFFF
#define UBUS_RESP_PROFILING_STOP_VALUE_VAL_FIELD_WIDTH 32
#define UBUS_RESP_PROFILING_STOP_VALUE_VAL_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_PROFILING_STOP_VALUE_VAL_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_PROFILING_STOP_VALUE_REG;
#define UBUS_RESP_PROFILING_STOP_VALUE_REG_OFFSET 0x00000110

#define UBUS_RESP_PROFILING_CYCLE_NUM_PROFILING_CYCLES_NUM_FIELD_MASK 0xFFFFFFFF
#define UBUS_RESP_PROFILING_CYCLE_NUM_PROFILING_CYCLES_NUM_FIELD_WIDTH 32
#define UBUS_RESP_PROFILING_CYCLE_NUM_PROFILING_CYCLES_NUM_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_PROFILING_CYCLE_NUM_PROFILING_CYCLES_NUM_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_PROFILING_CYCLE_NUM_REG;
#define UBUS_RESP_PROFILING_CYCLE_NUM_REG_OFFSET 0x00000114

#define UBUS_RESP_RNR_INTR_CTRL_ISR_IST_FIELD_MASK 0xFFFFFFFF
#define UBUS_RESP_RNR_INTR_CTRL_ISR_IST_FIELD_WIDTH 32
#define UBUS_RESP_RNR_INTR_CTRL_ISR_IST_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RNR_INTR_CTRL_ISR_IST_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_RNR_INTR_CTRL_ISR_REG;
#define UBUS_RESP_RNR_INTR_CTRL_ISR_REG_OFFSET 0x00000080

#define UBUS_RESP_RNR_INTR_CTRL_ISM_ISM_FIELD_MASK 0xFFFFFFFF
#define UBUS_RESP_RNR_INTR_CTRL_ISM_ISM_FIELD_WIDTH 32
#define UBUS_RESP_RNR_INTR_CTRL_ISM_ISM_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RNR_INTR_CTRL_ISM_ISM_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_RNR_INTR_CTRL_ISM_REG;
#define UBUS_RESP_RNR_INTR_CTRL_ISM_REG_OFFSET 0x00000084

#define UBUS_RESP_RNR_INTR_CTRL_IER_IEM_FIELD_MASK 0xFFFFFFFF
#define UBUS_RESP_RNR_INTR_CTRL_IER_IEM_FIELD_WIDTH 32
#define UBUS_RESP_RNR_INTR_CTRL_IER_IEM_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RNR_INTR_CTRL_IER_IEM_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_RNR_INTR_CTRL_IER_REG;
#define UBUS_RESP_RNR_INTR_CTRL_IER_REG_OFFSET 0x00000088

#define UBUS_RESP_RNR_INTR_CTRL_ITR_IST_FIELD_MASK 0xFFFFFFFF
#define UBUS_RESP_RNR_INTR_CTRL_ITR_IST_FIELD_WIDTH 32
#define UBUS_RESP_RNR_INTR_CTRL_ITR_IST_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RNR_INTR_CTRL_ITR_IST_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_RNR_INTR_CTRL_ITR_REG;
#define UBUS_RESP_RNR_INTR_CTRL_ITR_REG_OFFSET 0x0000008C

#define UBUS_RESP_RCHK_LOCK_RCHK_LOCK_FIELD_MASK 0x00000001
#define UBUS_RESP_RCHK_LOCK_RCHK_LOCK_FIELD_WIDTH 1
#define UBUS_RESP_RCHK_LOCK_RCHK_LOCK_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RCHK_LOCK_RCHK_LOCK_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_RCHK_LOCK_REG;
#define UBUS_RESP_RCHK_LOCK_REG_OFFSET 0x00000200

#define UBUS_RESP_RCHK_ENG_CTRL_WR_ABORT_FIELD_MASK 0x00000001
#define UBUS_RESP_RCHK_ENG_CTRL_WR_ABORT_FIELD_WIDTH 1
#define UBUS_RESP_RCHK_ENG_CTRL_WR_ABORT_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RCHK_ENG_CTRL_WR_ABORT_FIELD;
#endif
#define UBUS_RESP_RCHK_ENG_CTRL_RD_ABORT_FIELD_MASK 0x00000002
#define UBUS_RESP_RCHK_ENG_CTRL_RD_ABORT_FIELD_WIDTH 1
#define UBUS_RESP_RCHK_ENG_CTRL_RD_ABORT_FIELD_SHIFT 1
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RCHK_ENG_CTRL_RD_ABORT_FIELD;
#endif
#define UBUS_RESP_RCHK_ENG_CTRL_PROT_FIELD_MASK 0x0000001C
#define UBUS_RESP_RCHK_ENG_CTRL_PROT_FIELD_WIDTH 3
#define UBUS_RESP_RCHK_ENG_CTRL_PROT_FIELD_SHIFT 2
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RCHK_ENG_CTRL_PROT_FIELD;
#endif
#define UBUS_RESP_RCHK_ENG_CTRL_PROT_MSK_FIELD_MASK 0x000000E0
#define UBUS_RESP_RCHK_ENG_CTRL_PROT_MSK_FIELD_WIDTH 3
#define UBUS_RESP_RCHK_ENG_CTRL_PROT_MSK_FIELD_SHIFT 5
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RCHK_ENG_CTRL_PROT_MSK_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_RCHK_ENG_CTRL_REG;
#define UBUS_RESP_RCHK_ENG_CTRL_REG_OFFSET 0x00000220
#define UBUS_RESP_RCHK_ENG_CTRL_REG_RAM_CNT 8

#define UBUS_RESP_RCHK_ENG_START_ADD_START_ADD_FIELD_MASK 0x0001FFFF
#define UBUS_RESP_RCHK_ENG_START_ADD_START_ADD_FIELD_WIDTH 17
#define UBUS_RESP_RCHK_ENG_START_ADD_START_ADD_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RCHK_ENG_START_ADD_START_ADD_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_RCHK_ENG_START_ADD_REG;
#define UBUS_RESP_RCHK_ENG_START_ADD_REG_OFFSET 0x00000240
#define UBUS_RESP_RCHK_ENG_START_ADD_REG_RAM_CNT 8

#define UBUS_RESP_RCHK_ENG_END_ADD_END_ADD_FIELD_MASK 0x0001FFFF
#define UBUS_RESP_RCHK_ENG_END_ADD_END_ADD_FIELD_WIDTH 17
#define UBUS_RESP_RCHK_ENG_END_ADD_END_ADD_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RCHK_ENG_END_ADD_END_ADD_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_RCHK_ENG_END_ADD_REG;
#define UBUS_RESP_RCHK_ENG_END_ADD_REG_OFFSET 0x00000260
#define UBUS_RESP_RCHK_ENG_END_ADD_REG_RAM_CNT 8

#define UBUS_RESP_RCHK_ENG_SECLEV_EN_SECLEV_EN_FIELD_MASK 0xFFFFFFFF
#define UBUS_RESP_RCHK_ENG_SECLEV_EN_SECLEV_EN_FIELD_WIDTH 32
#define UBUS_RESP_RCHK_ENG_SECLEV_EN_SECLEV_EN_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RCHK_ENG_SECLEV_EN_SECLEV_EN_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_RCHK_ENG_SECLEV_EN_REG;
#define UBUS_RESP_RCHK_ENG_SECLEV_EN_REG_OFFSET 0x00000280
#define UBUS_RESP_RCHK_ENG_SECLEV_EN_REG_RAM_CNT 8

#define UBUS_RESP_RCHK_RNR_EN_RCHK_RNR_EN_FIELD_MASK 0x0000007F
#define UBUS_RESP_RCHK_RNR_EN_RCHK_RNR_EN_FIELD_WIDTH 7
#define UBUS_RESP_RCHK_RNR_EN_RCHK_RNR_EN_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RCHK_RNR_EN_RCHK_RNR_EN_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_RCHK_RNR_EN_REG;
#define UBUS_RESP_RCHK_RNR_EN_REG_OFFSET 0x000002A0
#define UBUS_RESP_RCHK_RNR_EN_REG_RAM_CNT 8

#define UBUS_RESP_RCHK_ABORT_CAPT0_RCHK_ABORT_CAPT0_FIELD_MASK 0xFFFFFFFF
#define UBUS_RESP_RCHK_ABORT_CAPT0_RCHK_ABORT_CAPT0_FIELD_WIDTH 32
#define UBUS_RESP_RCHK_ABORT_CAPT0_RCHK_ABORT_CAPT0_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RCHK_ABORT_CAPT0_RCHK_ABORT_CAPT0_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_RCHK_ABORT_CAPT0_REG;
#define UBUS_RESP_RCHK_ABORT_CAPT0_REG_OFFSET 0x000002C0

#define UBUS_RESP_RCHK_ABORT_CAPT1_RCHK_ABORT_CAPT1_FIELD_MASK 0xFFFFFFFF
#define UBUS_RESP_RCHK_ABORT_CAPT1_RCHK_ABORT_CAPT1_FIELD_WIDTH 32
#define UBUS_RESP_RCHK_ABORT_CAPT1_RCHK_ABORT_CAPT1_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RCHK_ABORT_CAPT1_RCHK_ABORT_CAPT1_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_RCHK_ABORT_CAPT1_REG;
#define UBUS_RESP_RCHK_ABORT_CAPT1_REG_OFFSET 0x000002C4

#define UBUS_RESP_RCHK_ABORT_CAPT2_RCHK_ABORT_CAPT2_FIELD_MASK 0xFFFFFFFF
#define UBUS_RESP_RCHK_ABORT_CAPT2_RCHK_ABORT_CAPT2_FIELD_WIDTH 32
#define UBUS_RESP_RCHK_ABORT_CAPT2_RCHK_ABORT_CAPT2_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec UBUS_RESP_RCHK_ABORT_CAPT2_RCHK_ABORT_CAPT2_FIELD;
#endif
extern const ru_reg_rec UBUS_RESP_RCHK_ABORT_CAPT2_REG;
#define UBUS_RESP_RCHK_ABORT_CAPT2_REG_OFFSET 0x000002C8

extern const ru_block_rec UBUS_RESP_BLOCK;

#endif
