# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2004
# ARM Ltd.
# Philippe Robin, <philippe.robin@arm.com>

obj-y	:= lowlevel_init.o

obj-y	+= integrator.o
obj-$(CONFIG_PCI) += pci.o
obj-y += timer.o
