/* IMAGE 0 LABELS */
#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_0_aqm_timer_task_1st_wakeup_request        (0x2560)
#define image_0_budget_allocator_1st_wakeup_request        (0x1400)
#define image_0_budget_allocator_sq_1st_wakeup_request        (0x21e8)
#define image_0_buffer_cong_mgt_1st_wakeup_request        (0x1040)
#define image_0_c_common_reprocessing_wakeup_request        (0x4354)
#define image_0_c_spdsvc_analyzer_wakeup_request        (0x3d94)
#define image_0_c_spdsvc_gen_wakeup_request        (0x44c8)
#define image_0_debug_routine        (0x74)
#define image_0_debug_routine_handler        (0x4)
#define image_0_general_timer_wakeup_request        (0x42dc)
#define image_0_initialization_task        (0x8)
#define image_0_scheduling_service_queues_call_scheduler_block        (0x1d08)
#define image_0_service_queues_tx_task_wakeup_request        (0x1d08)
#define image_0_service_queues_update_fifo_read_1st_wakeup_request        (0x1a70)
#define image_0_spdt_brcm_spdsvc_rx_handler        (0x41d8)
#define image_0_spdt_udp_basic_rx_handler        (0x3ec0)
#define image_0_spdt_udp_iperf3_rx_handler        (0x3fb8)
#define image_0_spdt_unsupported_proto_rx_handler        (0x4280)
#define image_0_start_task_aqm_timer_task_1st_wakeup_request        (0x2560)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0x1400)
#define image_0_start_task_budget_allocator_sq_1st_wakeup_request        (0x21e8)
#define image_0_start_task_buffer_cong_mgt_1st_wakeup_request        (0x1040)
#define image_0_start_task_c_common_reprocessing_wakeup_request        (0x4354)
#define image_0_start_task_c_spdsvc_analyzer_wakeup_request        (0x3d94)
#define image_0_start_task_c_spdsvc_gen_wakeup_request        (0x44c8)
#define image_0_start_task_debug_routine        (0x74)
#define image_0_start_task_general_timer_wakeup_request        (0x42dc)
#define image_0_start_task_initialization_task        (0x8)
#define image_0_start_task_service_queues_tx_task_wakeup_request        (0x1d08)
#define image_0_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0x1a70)
#define image_0_start_task_spdt_brcm_spdsvc_rx_handler        (0x41d8)
#define image_0_start_task_spdt_udp_basic_rx_handler        (0x3ec0)
#define image_0_start_task_spdt_udp_iperf3_rx_handler        (0x3fb8)
#define image_0_start_task_spdt_unsupported_proto_rx_handler        (0x4280)
#define image_0_start_task_tcpspdtest_gen_wakeup_request        (0x2fa8)
#define image_0_start_task_tcpspdtest_wakeup_request        (0x2760)
#define image_0_start_task_tx_task_1st_wakeup_request        (0xaa8)
#define image_0_start_task_update_fifo_us_read_1st_wakeup_request        (0x4c0)
#define image_0_tcpspdtest_gen_wakeup_request        (0x2fa8)
#define image_0_tcpspdtest_task_upload_init        (0x2fa8)
#define image_0_tcpspdtest_wakeup_request        (0x2760)
#define image_0_tx_task_1st_wakeup_request        (0xaa8)
#define image_0_update_fifo_us_read_1st_wakeup_request        (0x4c0)

#else

#define image_0_aqm_timer_task_1st_wakeup_request        (0x958)
#define image_0_budget_allocator_1st_wakeup_request        (0x500)
#define image_0_budget_allocator_sq_1st_wakeup_request        (0x87a)
#define image_0_buffer_cong_mgt_1st_wakeup_request        (0x410)
#define image_0_c_common_reprocessing_wakeup_request        (0x10d5)
#define image_0_c_spdsvc_analyzer_wakeup_request        (0xf65)
#define image_0_c_spdsvc_gen_wakeup_request        (0x1132)
#define image_0_debug_routine        (0x1d)
#define image_0_debug_routine_handler        (0x1)
#define image_0_general_timer_wakeup_request        (0x10b7)
#define image_0_initialization_task        (0x2)
#define image_0_scheduling_service_queues_call_scheduler_block        (0x742)
#define image_0_service_queues_tx_task_wakeup_request        (0x742)
#define image_0_service_queues_update_fifo_read_1st_wakeup_request        (0x69c)
#define image_0_spdt_brcm_spdsvc_rx_handler        (0x1076)
#define image_0_spdt_udp_basic_rx_handler        (0xfb0)
#define image_0_spdt_udp_iperf3_rx_handler        (0xfee)
#define image_0_spdt_unsupported_proto_rx_handler        (0x10a0)
#define image_0_start_task_aqm_timer_task_1st_wakeup_request        (0x958)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0x500)
#define image_0_start_task_budget_allocator_sq_1st_wakeup_request        (0x87a)
#define image_0_start_task_buffer_cong_mgt_1st_wakeup_request        (0x410)
#define image_0_start_task_c_common_reprocessing_wakeup_request        (0x10d5)
#define image_0_start_task_c_spdsvc_analyzer_wakeup_request        (0xf65)
#define image_0_start_task_c_spdsvc_gen_wakeup_request        (0x1132)
#define image_0_start_task_debug_routine        (0x1d)
#define image_0_start_task_general_timer_wakeup_request        (0x10b7)
#define image_0_start_task_initialization_task        (0x2)
#define image_0_start_task_service_queues_tx_task_wakeup_request        (0x742)
#define image_0_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0x69c)
#define image_0_start_task_spdt_brcm_spdsvc_rx_handler        (0x1076)
#define image_0_start_task_spdt_udp_basic_rx_handler        (0xfb0)
#define image_0_start_task_spdt_udp_iperf3_rx_handler        (0xfee)
#define image_0_start_task_spdt_unsupported_proto_rx_handler        (0x10a0)
#define image_0_start_task_tcpspdtest_gen_wakeup_request        (0xbea)
#define image_0_start_task_tcpspdtest_wakeup_request        (0x9d8)
#define image_0_start_task_tx_task_1st_wakeup_request        (0x2aa)
#define image_0_start_task_update_fifo_us_read_1st_wakeup_request        (0x130)
#define image_0_tcpspdtest_gen_wakeup_request        (0xbea)
#define image_0_tcpspdtest_task_upload_init        (0xbea)
#define image_0_tcpspdtest_wakeup_request        (0x9d8)
#define image_0_tx_task_1st_wakeup_request        (0x2aa)
#define image_0_update_fifo_us_read_1st_wakeup_request        (0x130)

#endif


#endif

/* IMAGE 1 LABELS */
#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_1___umulsi3        (0x7464)
#define image_1_add_pbit_to_key        (0x4f3c)
#define image_1_budget_allocator_1st_wakeup_request        (0x1258)
#define image_1_buffer_cong_mgt_1st_wakeup_request        (0x1a60)
#define image_1_c_dhd_rx_complete_wakeup_request        (0x1fec)
#define image_1_c_dhd_tx_complete_wakeup_request        (0x2470)
#define image_1_check_cpu_rx_gdx_queue_occupancy        (0x1ee0)
#define image_1_ct_expect_natc_lookup        (0x4fe4)
#define image_1_ct_natc_lookup        (0x4f8c)
#define image_1_debug_routine        (0x1f0)
#define image_1_debug_routine_handler        (0x4)
#define image_1_dhd_send_entry_to_cpu_ring        (0x1f1c)
#define image_1_dos_attack_handler        (0x4a5c)
#define image_1_dynamic_code_section        (0x8)
#define image_1_dynamic_code_section_proc0        (0x8)
#define image_1_dynamic_code_section_proc1        (0x78)
#define image_1_dynamic_code_section_proc2        (0xe8)
#define image_1_dynamic_code_section_proc3        (0x158)
#define image_1_flow_policer        (0x73a4)
#define image_1_group_flow_lkp_and_fwd        (0x5070)
#define image_1_ingress_filter_action_point_update        (0x502c)
#define image_1_ingress_filters_handler        (0x4c48)
#define image_1_initialization_task        (0x1c8)
#define image_1_is_iptv_capable        (0x4ab8)
#define image_1_memcpy_abs_to_sbpm        (0x1cf4)
#define image_1_ovl_budget_allocator_1st_wakeup_request        (0x16d0)
#define image_1_parser_exception_handler        (0x48ec)
#define image_1_processing_policer_action        (0x73f4)
#define image_1_processing_wakeup_request        (0x26e0)
#define image_1_rx_cmpl_send_doorbell_activate_idma        (0x2370)
#define image_1_rxcmpl_process_rx_packet        (0x23d8)
#define image_1_spdsvc_natc_lookup        (0x4b04)
#define image_1_start_task___umulsi3        (0x7464)
#define image_1_start_task_add_pbit_to_key        (0x4f3c)
#define image_1_start_task_budget_allocator_1st_wakeup_request        (0x1258)
#define image_1_start_task_buffer_cong_mgt_1st_wakeup_request        (0x1a60)
#define image_1_start_task_c_dhd_rx_complete_wakeup_request        (0x1fec)
#define image_1_start_task_c_dhd_tx_complete_wakeup_request        (0x2470)
#define image_1_start_task_check_cpu_rx_gdx_queue_occupancy        (0x1ee0)
#define image_1_start_task_ct_expect_natc_lookup        (0x4fe4)
#define image_1_start_task_ct_natc_lookup        (0x4f8c)
#define image_1_start_task_debug_routine        (0x1f0)
#define image_1_start_task_dhd_send_entry_to_cpu_ring        (0x1f1c)
#define image_1_start_task_dos_attack_handler        (0x4a5c)
#define image_1_start_task_flow_policer        (0x73a4)
#define image_1_start_task_group_flow_lkp_and_fwd        (0x5070)
#define image_1_start_task_ingress_filter_action_point_update        (0x502c)
#define image_1_start_task_ingress_filters_handler        (0x4c48)
#define image_1_start_task_initialization_task        (0x1c8)
#define image_1_start_task_is_iptv_capable        (0x4ab8)
#define image_1_start_task_memcpy_abs_to_sbpm        (0x1cf4)
#define image_1_start_task_ovl_budget_allocator_1st_wakeup_request        (0x16d0)
#define image_1_start_task_parser_exception_handler        (0x48ec)
#define image_1_start_task_processing_policer_action        (0x73f4)
#define image_1_start_task_processing_wakeup_request        (0x26e0)
#define image_1_start_task_rx_cmpl_send_doorbell_activate_idma        (0x2370)
#define image_1_start_task_rxcmpl_process_rx_packet        (0x23d8)
#define image_1_start_task_spdsvc_natc_lookup        (0x4b04)
#define image_1_start_task_tx_task_1st_wakeup_request        (0xa78)
#define image_1_start_task_update_fifo_us_read_1st_wakeup_request        (0x1790)
#define image_1_tx_task_1st_wakeup_request        (0xa78)
#define image_1_update_fifo_us_read_1st_wakeup_request        (0x1790)

#else

#define image_1___umulsi3        (0x1d19)
#define image_1_add_pbit_to_key        (0x13cf)
#define image_1_budget_allocator_1st_wakeup_request        (0x496)
#define image_1_buffer_cong_mgt_1st_wakeup_request        (0x698)
#define image_1_c_dhd_rx_complete_wakeup_request        (0x7fb)
#define image_1_c_dhd_tx_complete_wakeup_request        (0x91c)
#define image_1_check_cpu_rx_gdx_queue_occupancy        (0x7b8)
#define image_1_ct_expect_natc_lookup        (0x13f9)
#define image_1_ct_natc_lookup        (0x13e3)
#define image_1_debug_routine        (0x7c)
#define image_1_debug_routine_handler        (0x1)
#define image_1_dhd_send_entry_to_cpu_ring        (0x7c7)
#define image_1_dos_attack_handler        (0x1297)
#define image_1_dynamic_code_section        (0x2)
#define image_1_dynamic_code_section_proc0        (0x2)
#define image_1_dynamic_code_section_proc1        (0x1e)
#define image_1_dynamic_code_section_proc2        (0x3a)
#define image_1_dynamic_code_section_proc3        (0x56)
#define image_1_flow_policer        (0x1ce9)
#define image_1_group_flow_lkp_and_fwd        (0x141c)
#define image_1_ingress_filter_action_point_update        (0x140b)
#define image_1_ingress_filters_handler        (0x1312)
#define image_1_initialization_task        (0x72)
#define image_1_is_iptv_capable        (0x12ae)
#define image_1_memcpy_abs_to_sbpm        (0x73d)
#define image_1_ovl_budget_allocator_1st_wakeup_request        (0x5b4)
#define image_1_parser_exception_handler        (0x123b)
#define image_1_processing_policer_action        (0x1cfd)
#define image_1_processing_wakeup_request        (0x9b8)
#define image_1_rx_cmpl_send_doorbell_activate_idma        (0x8dc)
#define image_1_rxcmpl_process_rx_packet        (0x8f6)
#define image_1_spdsvc_natc_lookup        (0x12c1)
#define image_1_start_task___umulsi3        (0x1d19)
#define image_1_start_task_add_pbit_to_key        (0x13cf)
#define image_1_start_task_budget_allocator_1st_wakeup_request        (0x496)
#define image_1_start_task_buffer_cong_mgt_1st_wakeup_request        (0x698)
#define image_1_start_task_c_dhd_rx_complete_wakeup_request        (0x7fb)
#define image_1_start_task_c_dhd_tx_complete_wakeup_request        (0x91c)
#define image_1_start_task_check_cpu_rx_gdx_queue_occupancy        (0x7b8)
#define image_1_start_task_ct_expect_natc_lookup        (0x13f9)
#define image_1_start_task_ct_natc_lookup        (0x13e3)
#define image_1_start_task_debug_routine        (0x7c)
#define image_1_start_task_dhd_send_entry_to_cpu_ring        (0x7c7)
#define image_1_start_task_dos_attack_handler        (0x1297)
#define image_1_start_task_flow_policer        (0x1ce9)
#define image_1_start_task_group_flow_lkp_and_fwd        (0x141c)
#define image_1_start_task_ingress_filter_action_point_update        (0x140b)
#define image_1_start_task_ingress_filters_handler        (0x1312)
#define image_1_start_task_initialization_task        (0x72)
#define image_1_start_task_is_iptv_capable        (0x12ae)
#define image_1_start_task_memcpy_abs_to_sbpm        (0x73d)
#define image_1_start_task_ovl_budget_allocator_1st_wakeup_request        (0x5b4)
#define image_1_start_task_parser_exception_handler        (0x123b)
#define image_1_start_task_processing_policer_action        (0x1cfd)
#define image_1_start_task_processing_wakeup_request        (0x9b8)
#define image_1_start_task_rx_cmpl_send_doorbell_activate_idma        (0x8dc)
#define image_1_start_task_rxcmpl_process_rx_packet        (0x8f6)
#define image_1_start_task_spdsvc_natc_lookup        (0x12c1)
#define image_1_start_task_tx_task_1st_wakeup_request        (0x29e)
#define image_1_start_task_update_fifo_us_read_1st_wakeup_request        (0x5e4)
#define image_1_tx_task_1st_wakeup_request        (0x29e)
#define image_1_update_fifo_us_read_1st_wakeup_request        (0x5e4)

#endif


#endif

/* IMAGE 2 LABELS */
#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_2___umulsi3        (0x69e8)
#define image_2_add_pbit_to_key        (0x4238)
#define image_2_c_cpu_recycle_wakeup_request        (0x67d8)
#define image_2_c_cpu_tx_wakeup_request        (0x860)
#define image_2_check_cpu_rx_gdx_queue_occupancy        (0x824)
#define image_2_cpu_recycle_int_coalescing        (0x694c)
#define image_2_cpu_tx_send_pd_to_recycle        (0x1950)
#define image_2_cpu_tx_sync_tasks        (0x19bc)
#define image_2_ct_expect_natc_lookup        (0x42e0)
#define image_2_ct_natc_lookup        (0x4288)
#define image_2_debug_routine        (0x3b0)
#define image_2_debug_routine_handler        (0x4)
#define image_2_dos_attack_handler        (0x3d58)
#define image_2_dynamic_code_section        (0x8)
#define image_2_dynamic_code_section_proc0        (0x8)
#define image_2_dynamic_code_section_proc1        (0x78)
#define image_2_dynamic_code_section_proc2        (0xe8)
#define image_2_dynamic_code_section_proc3        (0x158)
#define image_2_dynamic_code_section_proc4        (0x1c8)
#define image_2_dynamic_code_section_proc5        (0x238)
#define image_2_dynamic_code_section_proc6        (0x2a8)
#define image_2_dynamic_code_section_proc7        (0x318)
#define image_2_flow_policer        (0x66a0)
#define image_2_general_timer_wakeup_request        (0x6760)
#define image_2_group_flow_lkp_and_fwd        (0x436c)
#define image_2_ingress_filter_action_point_update        (0x4328)
#define image_2_ingress_filters_handler        (0x3f44)
#define image_2_initialization_task        (0x388)
#define image_2_is_iptv_capable        (0x3db4)
#define image_2_memcpy_abs_to_fpm        (0x664)
#define image_2_memcpy_abs_to_sbpm        (0x478)
#define image_2_parser_exception_handler        (0x3be8)
#define image_2_processing_policer_action        (0x66f0)
#define image_2_processing_wakeup_request        (0x19dc)
#define image_2_spdsvc_natc_lookup        (0x3e00)
#define image_2_start_task___umulsi3        (0x69e8)
#define image_2_start_task_add_pbit_to_key        (0x4238)
#define image_2_start_task_c_cpu_recycle_wakeup_request        (0x67d8)
#define image_2_start_task_c_cpu_tx_wakeup_request        (0x860)
#define image_2_start_task_check_cpu_rx_gdx_queue_occupancy        (0x824)
#define image_2_start_task_cpu_recycle_int_coalescing        (0x694c)
#define image_2_start_task_cpu_tx_send_pd_to_recycle        (0x1950)
#define image_2_start_task_cpu_tx_sync_tasks        (0x19bc)
#define image_2_start_task_ct_expect_natc_lookup        (0x42e0)
#define image_2_start_task_ct_natc_lookup        (0x4288)
#define image_2_start_task_debug_routine        (0x3b0)
#define image_2_start_task_dos_attack_handler        (0x3d58)
#define image_2_start_task_flow_policer        (0x66a0)
#define image_2_start_task_general_timer_wakeup_request        (0x6760)
#define image_2_start_task_group_flow_lkp_and_fwd        (0x436c)
#define image_2_start_task_ingress_filter_action_point_update        (0x4328)
#define image_2_start_task_ingress_filters_handler        (0x3f44)
#define image_2_start_task_initialization_task        (0x388)
#define image_2_start_task_is_iptv_capable        (0x3db4)
#define image_2_start_task_memcpy_abs_to_fpm        (0x664)
#define image_2_start_task_memcpy_abs_to_sbpm        (0x478)
#define image_2_start_task_parser_exception_handler        (0x3be8)
#define image_2_start_task_processing_policer_action        (0x66f0)
#define image_2_start_task_processing_wakeup_request        (0x19dc)
#define image_2_start_task_spdsvc_natc_lookup        (0x3e00)

#else

#define image_2___umulsi3        (0x1a7a)
#define image_2_add_pbit_to_key        (0x108e)
#define image_2_c_cpu_recycle_wakeup_request        (0x19f6)
#define image_2_c_cpu_tx_wakeup_request        (0x218)
#define image_2_check_cpu_rx_gdx_queue_occupancy        (0x209)
#define image_2_cpu_recycle_int_coalescing        (0x1a53)
#define image_2_cpu_tx_send_pd_to_recycle        (0x654)
#define image_2_cpu_tx_sync_tasks        (0x66f)
#define image_2_ct_expect_natc_lookup        (0x10b8)
#define image_2_ct_natc_lookup        (0x10a2)
#define image_2_debug_routine        (0xec)
#define image_2_debug_routine_handler        (0x1)
#define image_2_dos_attack_handler        (0xf56)
#define image_2_dynamic_code_section        (0x2)
#define image_2_dynamic_code_section_proc0        (0x2)
#define image_2_dynamic_code_section_proc1        (0x1e)
#define image_2_dynamic_code_section_proc2        (0x3a)
#define image_2_dynamic_code_section_proc3        (0x56)
#define image_2_dynamic_code_section_proc4        (0x72)
#define image_2_dynamic_code_section_proc5        (0x8e)
#define image_2_dynamic_code_section_proc6        (0xaa)
#define image_2_dynamic_code_section_proc7        (0xc6)
#define image_2_flow_policer        (0x19a8)
#define image_2_general_timer_wakeup_request        (0x19d8)
#define image_2_group_flow_lkp_and_fwd        (0x10db)
#define image_2_ingress_filter_action_point_update        (0x10ca)
#define image_2_ingress_filters_handler        (0xfd1)
#define image_2_initialization_task        (0xe2)
#define image_2_is_iptv_capable        (0xf6d)
#define image_2_memcpy_abs_to_fpm        (0x199)
#define image_2_memcpy_abs_to_sbpm        (0x11e)
#define image_2_parser_exception_handler        (0xefa)
#define image_2_processing_policer_action        (0x19bc)
#define image_2_processing_wakeup_request        (0x677)
#define image_2_spdsvc_natc_lookup        (0xf80)
#define image_2_start_task___umulsi3        (0x1a7a)
#define image_2_start_task_add_pbit_to_key        (0x108e)
#define image_2_start_task_c_cpu_recycle_wakeup_request        (0x19f6)
#define image_2_start_task_c_cpu_tx_wakeup_request        (0x218)
#define image_2_start_task_check_cpu_rx_gdx_queue_occupancy        (0x209)
#define image_2_start_task_cpu_recycle_int_coalescing        (0x1a53)
#define image_2_start_task_cpu_tx_send_pd_to_recycle        (0x654)
#define image_2_start_task_cpu_tx_sync_tasks        (0x66f)
#define image_2_start_task_ct_expect_natc_lookup        (0x10b8)
#define image_2_start_task_ct_natc_lookup        (0x10a2)
#define image_2_start_task_debug_routine        (0xec)
#define image_2_start_task_dos_attack_handler        (0xf56)
#define image_2_start_task_flow_policer        (0x19a8)
#define image_2_start_task_general_timer_wakeup_request        (0x19d8)
#define image_2_start_task_group_flow_lkp_and_fwd        (0x10db)
#define image_2_start_task_ingress_filter_action_point_update        (0x10ca)
#define image_2_start_task_ingress_filters_handler        (0xfd1)
#define image_2_start_task_initialization_task        (0xe2)
#define image_2_start_task_is_iptv_capable        (0xf6d)
#define image_2_start_task_memcpy_abs_to_fpm        (0x199)
#define image_2_start_task_memcpy_abs_to_sbpm        (0x11e)
#define image_2_start_task_parser_exception_handler        (0xefa)
#define image_2_start_task_processing_policer_action        (0x19bc)
#define image_2_start_task_processing_wakeup_request        (0x677)
#define image_2_start_task_spdsvc_natc_lookup        (0xf80)

#endif


#endif

/* IMAGE 3 LABELS */
#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_3_add_pbit_to_key        (0x2efc)
#define image_3_c_cpu_recycle_wakeup_request        (0x6518)
#define image_3_c_cpu_rx_copy_wakeup_request        (0x58d0)
#define image_3_c_cpu_rx_wakeup_request        (0x5424)
#define image_3_check_cpu_rx_gdx_queue_occupancy        (0x664)
#define image_3_cpu_recycle_int_coalescing        (0x668c)
#define image_3_cpu_rx_int_coalescing        (0x5820)
#define image_3_cpu_rx_meter_budget_allocator        (0x586c)
#define image_3_ct_expect_natc_lookup        (0x2fa4)
#define image_3_ct_natc_lookup        (0x2f4c)
#define image_3_debug_routine        (0x3b0)
#define image_3_debug_routine_handler        (0x4)
#define image_3_dos_attack_handler        (0x2a1c)
#define image_3_dynamic_code_section        (0x8)
#define image_3_dynamic_code_section_proc0        (0x8)
#define image_3_dynamic_code_section_proc1        (0x78)
#define image_3_dynamic_code_section_proc2        (0xe8)
#define image_3_dynamic_code_section_proc3        (0x158)
#define image_3_dynamic_code_section_proc4        (0x1c8)
#define image_3_dynamic_code_section_proc5        (0x238)
#define image_3_dynamic_code_section_proc6        (0x2a8)
#define image_3_dynamic_code_section_proc7        (0x318)
#define image_3_flow_policer        (0x5364)
#define image_3_general_timer_wakeup_request        (0x671c)
#define image_3_get_pd_from_fifo        (0x66b8)
#define image_3_group_flow_lkp_and_fwd        (0x3030)
#define image_3_ingress_filter_action_point_update        (0x2fec)
#define image_3_ingress_filters_handler        (0x2c08)
#define image_3_initialization_task        (0x388)
#define image_3_is_iptv_capable        (0x2a78)
#define image_3_memcpy_abs_to_sbpm        (0x478)
#define image_3_packet_cso_rnr_calc        (0x63a4)
#define image_3_parser_exception_handler        (0x28ac)
#define image_3_processing_policer_action        (0x53b4)
#define image_3_processing_wakeup_request        (0x6a0)
#define image_3_spdsvc_natc_lookup        (0x2ac4)
#define image_3_start_task_add_pbit_to_key        (0x2efc)
#define image_3_start_task_c_cpu_recycle_wakeup_request        (0x6518)
#define image_3_start_task_c_cpu_rx_copy_wakeup_request        (0x58d0)
#define image_3_start_task_c_cpu_rx_wakeup_request        (0x5424)
#define image_3_start_task_check_cpu_rx_gdx_queue_occupancy        (0x664)
#define image_3_start_task_cpu_recycle_int_coalescing        (0x668c)
#define image_3_start_task_cpu_rx_int_coalescing        (0x5820)
#define image_3_start_task_cpu_rx_meter_budget_allocator        (0x586c)
#define image_3_start_task_ct_expect_natc_lookup        (0x2fa4)
#define image_3_start_task_ct_natc_lookup        (0x2f4c)
#define image_3_start_task_debug_routine        (0x3b0)
#define image_3_start_task_dos_attack_handler        (0x2a1c)
#define image_3_start_task_flow_policer        (0x5364)
#define image_3_start_task_general_timer_wakeup_request        (0x671c)
#define image_3_start_task_get_pd_from_fifo        (0x66b8)
#define image_3_start_task_group_flow_lkp_and_fwd        (0x3030)
#define image_3_start_task_ingress_filter_action_point_update        (0x2fec)
#define image_3_start_task_ingress_filters_handler        (0x2c08)
#define image_3_start_task_initialization_task        (0x388)
#define image_3_start_task_is_iptv_capable        (0x2a78)
#define image_3_start_task_memcpy_abs_to_sbpm        (0x478)
#define image_3_start_task_packet_cso_rnr_calc        (0x63a4)
#define image_3_start_task_parser_exception_handler        (0x28ac)
#define image_3_start_task_processing_policer_action        (0x53b4)
#define image_3_start_task_processing_wakeup_request        (0x6a0)
#define image_3_start_task_spdsvc_natc_lookup        (0x2ac4)

#else

#define image_3_add_pbit_to_key        (0xbbf)
#define image_3_c_cpu_recycle_wakeup_request        (0x1946)
#define image_3_c_cpu_rx_copy_wakeup_request        (0x1634)
#define image_3_c_cpu_rx_wakeup_request        (0x1509)
#define image_3_check_cpu_rx_gdx_queue_occupancy        (0x199)
#define image_3_cpu_recycle_int_coalescing        (0x19a3)
#define image_3_cpu_rx_int_coalescing        (0x1608)
#define image_3_cpu_rx_meter_budget_allocator        (0x161b)
#define image_3_ct_expect_natc_lookup        (0xbe9)
#define image_3_ct_natc_lookup        (0xbd3)
#define image_3_debug_routine        (0xec)
#define image_3_debug_routine_handler        (0x1)
#define image_3_dos_attack_handler        (0xa87)
#define image_3_dynamic_code_section        (0x2)
#define image_3_dynamic_code_section_proc0        (0x2)
#define image_3_dynamic_code_section_proc1        (0x1e)
#define image_3_dynamic_code_section_proc2        (0x3a)
#define image_3_dynamic_code_section_proc3        (0x56)
#define image_3_dynamic_code_section_proc4        (0x72)
#define image_3_dynamic_code_section_proc5        (0x8e)
#define image_3_dynamic_code_section_proc6        (0xaa)
#define image_3_dynamic_code_section_proc7        (0xc6)
#define image_3_flow_policer        (0x14d9)
#define image_3_general_timer_wakeup_request        (0x19c7)
#define image_3_get_pd_from_fifo        (0x19ae)
#define image_3_group_flow_lkp_and_fwd        (0xc0c)
#define image_3_ingress_filter_action_point_update        (0xbfb)
#define image_3_ingress_filters_handler        (0xb02)
#define image_3_initialization_task        (0xe2)
#define image_3_is_iptv_capable        (0xa9e)
#define image_3_memcpy_abs_to_sbpm        (0x11e)
#define image_3_packet_cso_rnr_calc        (0x18e9)
#define image_3_parser_exception_handler        (0xa2b)
#define image_3_processing_policer_action        (0x14ed)
#define image_3_processing_wakeup_request        (0x1a8)
#define image_3_spdsvc_natc_lookup        (0xab1)
#define image_3_start_task_add_pbit_to_key        (0xbbf)
#define image_3_start_task_c_cpu_recycle_wakeup_request        (0x1946)
#define image_3_start_task_c_cpu_rx_copy_wakeup_request        (0x1634)
#define image_3_start_task_c_cpu_rx_wakeup_request        (0x1509)
#define image_3_start_task_check_cpu_rx_gdx_queue_occupancy        (0x199)
#define image_3_start_task_cpu_recycle_int_coalescing        (0x19a3)
#define image_3_start_task_cpu_rx_int_coalescing        (0x1608)
#define image_3_start_task_cpu_rx_meter_budget_allocator        (0x161b)
#define image_3_start_task_ct_expect_natc_lookup        (0xbe9)
#define image_3_start_task_ct_natc_lookup        (0xbd3)
#define image_3_start_task_debug_routine        (0xec)
#define image_3_start_task_dos_attack_handler        (0xa87)
#define image_3_start_task_flow_policer        (0x14d9)
#define image_3_start_task_general_timer_wakeup_request        (0x19c7)
#define image_3_start_task_get_pd_from_fifo        (0x19ae)
#define image_3_start_task_group_flow_lkp_and_fwd        (0xc0c)
#define image_3_start_task_ingress_filter_action_point_update        (0xbfb)
#define image_3_start_task_ingress_filters_handler        (0xb02)
#define image_3_start_task_initialization_task        (0xe2)
#define image_3_start_task_is_iptv_capable        (0xa9e)
#define image_3_start_task_memcpy_abs_to_sbpm        (0x11e)
#define image_3_start_task_packet_cso_rnr_calc        (0x18e9)
#define image_3_start_task_parser_exception_handler        (0xa2b)
#define image_3_start_task_processing_policer_action        (0x14ed)
#define image_3_start_task_processing_wakeup_request        (0x1a8)
#define image_3_start_task_spdsvc_natc_lookup        (0xab1)

#endif


#endif

/* IMAGE 4 LABELS */
#ifndef IMAGE_4_CODE_ADDRESSES
#define IMAGE_4_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_4___umulhisi3        (0x65fc)
#define image_4_add_pbit_to_key        (0x40d4)
#define image_4_c_dhd_timer_wakeup_request        (0x770)
#define image_4_c_dhd_tx_post_update_fifo_wakeup_request        (0x7f8)
#define image_4_c_dhd_tx_post_wakeup_request        (0x844)
#define image_4_check_cpu_rx_gdx_queue_occupancy        (0x664)
#define image_4_ct_expect_natc_lookup        (0x417c)
#define image_4_ct_natc_lookup        (0x4124)
#define image_4_debug_routine        (0x3b0)
#define image_4_debug_routine_handler        (0x4)
#define image_4_dhd_send_entry_to_cpu_ring        (0x6a0)
#define image_4_dhd_tx_get_bq_index        (0x16b8)
#define image_4_dhd_tx_post_drop_packet        (0x15c4)
#define image_4_dhd_tx_post_flow_ring_get_info        (0x13fc)
#define image_4_dhd_tx_put_bq_index        (0x1728)
#define image_4_dos_attack_handler        (0x3bf4)
#define image_4_dynamic_code_section        (0x8)
#define image_4_dynamic_code_section_proc0        (0x8)
#define image_4_dynamic_code_section_proc1        (0x78)
#define image_4_dynamic_code_section_proc2        (0xe8)
#define image_4_dynamic_code_section_proc3        (0x158)
#define image_4_dynamic_code_section_proc4        (0x1c8)
#define image_4_dynamic_code_section_proc5        (0x238)
#define image_4_dynamic_code_section_proc6        (0x2a8)
#define image_4_dynamic_code_section_proc7        (0x318)
#define image_4_flow_policer        (0x653c)
#define image_4_group_flow_lkp_and_fwd        (0x4208)
#define image_4_ingress_filter_action_point_update        (0x41c4)
#define image_4_ingress_filters_handler        (0x3de0)
#define image_4_initialization_task        (0x388)
#define image_4_is_iptv_capable        (0x3c50)
#define image_4_memcpy_abs_to_sbpm        (0x478)
#define image_4_parser_exception_handler        (0x3a84)
#define image_4_processing_policer_action        (0x658c)
#define image_4_processing_wakeup_request        (0x1878)
#define image_4_spdsvc_natc_lookup        (0x3c9c)
#define image_4_start_task___umulhisi3        (0x65fc)
#define image_4_start_task_add_pbit_to_key        (0x40d4)
#define image_4_start_task_c_dhd_timer_wakeup_request        (0x770)
#define image_4_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x7f8)
#define image_4_start_task_c_dhd_tx_post_wakeup_request        (0x844)
#define image_4_start_task_check_cpu_rx_gdx_queue_occupancy        (0x664)
#define image_4_start_task_ct_expect_natc_lookup        (0x417c)
#define image_4_start_task_ct_natc_lookup        (0x4124)
#define image_4_start_task_debug_routine        (0x3b0)
#define image_4_start_task_dhd_send_entry_to_cpu_ring        (0x6a0)
#define image_4_start_task_dhd_tx_get_bq_index        (0x16b8)
#define image_4_start_task_dhd_tx_post_drop_packet        (0x15c4)
#define image_4_start_task_dhd_tx_post_flow_ring_get_info        (0x13fc)
#define image_4_start_task_dhd_tx_put_bq_index        (0x1728)
#define image_4_start_task_dos_attack_handler        (0x3bf4)
#define image_4_start_task_flow_policer        (0x653c)
#define image_4_start_task_group_flow_lkp_and_fwd        (0x4208)
#define image_4_start_task_ingress_filter_action_point_update        (0x41c4)
#define image_4_start_task_ingress_filters_handler        (0x3de0)
#define image_4_start_task_initialization_task        (0x388)
#define image_4_start_task_is_iptv_capable        (0x3c50)
#define image_4_start_task_memcpy_abs_to_sbpm        (0x478)
#define image_4_start_task_parser_exception_handler        (0x3a84)
#define image_4_start_task_processing_policer_action        (0x658c)
#define image_4_start_task_processing_wakeup_request        (0x1878)
#define image_4_start_task_spdsvc_natc_lookup        (0x3c9c)
#define image_4_start_task_tx_mirror        (0x1790)
#define image_4_tx_mirror        (0x1790)

#else

#define image_4___umulhisi3        (0x197f)
#define image_4_add_pbit_to_key        (0x1035)
#define image_4_c_dhd_timer_wakeup_request        (0x1dc)
#define image_4_c_dhd_tx_post_update_fifo_wakeup_request        (0x1fe)
#define image_4_c_dhd_tx_post_wakeup_request        (0x211)
#define image_4_check_cpu_rx_gdx_queue_occupancy        (0x199)
#define image_4_ct_expect_natc_lookup        (0x105f)
#define image_4_ct_natc_lookup        (0x1049)
#define image_4_debug_routine        (0xec)
#define image_4_debug_routine_handler        (0x1)
#define image_4_dhd_send_entry_to_cpu_ring        (0x1a8)
#define image_4_dhd_tx_get_bq_index        (0x5ae)
#define image_4_dhd_tx_post_drop_packet        (0x571)
#define image_4_dhd_tx_post_flow_ring_get_info        (0x4ff)
#define image_4_dhd_tx_put_bq_index        (0x5ca)
#define image_4_dos_attack_handler        (0xefd)
#define image_4_dynamic_code_section        (0x2)
#define image_4_dynamic_code_section_proc0        (0x2)
#define image_4_dynamic_code_section_proc1        (0x1e)
#define image_4_dynamic_code_section_proc2        (0x3a)
#define image_4_dynamic_code_section_proc3        (0x56)
#define image_4_dynamic_code_section_proc4        (0x72)
#define image_4_dynamic_code_section_proc5        (0x8e)
#define image_4_dynamic_code_section_proc6        (0xaa)
#define image_4_dynamic_code_section_proc7        (0xc6)
#define image_4_flow_policer        (0x194f)
#define image_4_group_flow_lkp_and_fwd        (0x1082)
#define image_4_ingress_filter_action_point_update        (0x1071)
#define image_4_ingress_filters_handler        (0xf78)
#define image_4_initialization_task        (0xe2)
#define image_4_is_iptv_capable        (0xf14)
#define image_4_memcpy_abs_to_sbpm        (0x11e)
#define image_4_parser_exception_handler        (0xea1)
#define image_4_processing_policer_action        (0x1963)
#define image_4_processing_wakeup_request        (0x61e)
#define image_4_spdsvc_natc_lookup        (0xf27)
#define image_4_start_task___umulhisi3        (0x197f)
#define image_4_start_task_add_pbit_to_key        (0x1035)
#define image_4_start_task_c_dhd_timer_wakeup_request        (0x1dc)
#define image_4_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x1fe)
#define image_4_start_task_c_dhd_tx_post_wakeup_request        (0x211)
#define image_4_start_task_check_cpu_rx_gdx_queue_occupancy        (0x199)
#define image_4_start_task_ct_expect_natc_lookup        (0x105f)
#define image_4_start_task_ct_natc_lookup        (0x1049)
#define image_4_start_task_debug_routine        (0xec)
#define image_4_start_task_dhd_send_entry_to_cpu_ring        (0x1a8)
#define image_4_start_task_dhd_tx_get_bq_index        (0x5ae)
#define image_4_start_task_dhd_tx_post_drop_packet        (0x571)
#define image_4_start_task_dhd_tx_post_flow_ring_get_info        (0x4ff)
#define image_4_start_task_dhd_tx_put_bq_index        (0x5ca)
#define image_4_start_task_dos_attack_handler        (0xefd)
#define image_4_start_task_flow_policer        (0x194f)
#define image_4_start_task_group_flow_lkp_and_fwd        (0x1082)
#define image_4_start_task_ingress_filter_action_point_update        (0x1071)
#define image_4_start_task_ingress_filters_handler        (0xf78)
#define image_4_start_task_initialization_task        (0xe2)
#define image_4_start_task_is_iptv_capable        (0xf14)
#define image_4_start_task_memcpy_abs_to_sbpm        (0x11e)
#define image_4_start_task_parser_exception_handler        (0xea1)
#define image_4_start_task_processing_policer_action        (0x1963)
#define image_4_start_task_processing_wakeup_request        (0x61e)
#define image_4_start_task_spdsvc_natc_lookup        (0xf27)
#define image_4_start_task_tx_mirror        (0x5e4)
#define image_4_tx_mirror        (0x5e4)

#endif


#endif

/* COMMON LABELS */
#ifndef COMMON_CODE_ADDRESSES
#define COMMON_CODE_ADDRESSES

#define INVALID_LABEL_ADDRESS 0xFFFFFF

#ifndef PC_ADDRESS_INST_IND


#else


#endif


#endif

