#ifndef RUNNER_B_CODE_ADDRESSES
#define RUNNER_B_CODE_ADDRESSES

#define runner_b_start_task_initialization_task		(0x14)
#define runner_b_initialization_task		(0x14)
#define runner_b_start_task_timer_scheduler_set		(0x1F40)
#define runner_b_timer_scheduler_set		(0x1F40)
#define runner_b_start_task_cpu_rx_wakeup_request		(0xADC)
#define runner_b_cpu_rx_wakeup_request		(0xADC)
#define runner_b_start_task_cpu_tx_wakeup_request		(0x1B7C)
#define runner_b_cpu_tx_wakeup_request		(0x1B7C)
#define runner_b_start_task_policer_budget_allocator_1st_wakeup_request		(0x2408)
#define runner_b_policer_budget_allocator_1st_wakeup_request		(0x2408)
#define runner_b_start_task_rate_control_budget_allocator_1st_wakeup_request		(0x1A5C)
#define runner_b_rate_control_budget_allocator_1st_wakeup_request		(0x1A5C)
#define runner_b_start_task_wan_interworking_enqueue_wakeup_request		(0x168)
#define runner_b_wan_interworking_enqueue_wakeup_request		(0x168)
#define runner_b_start_task_wan_tx_wakeup_request		(0x44C)
#define runner_b_wan_tx_wakeup_request		(0x44C)
#define runner_b_start_task_debug_routine		(0x8C)
#define runner_b_debug_routine		(0x8C)
#define runner_b_start_task_spdsvc_timer_1st_wakeup_request		(0x1EA0)
#define runner_b_spdsvc_timer_1st_wakeup_request		(0x1EA0)
#define runner_b_start_task_free_skb_index_wakeup_request		(0x20D4)
#define runner_b_free_skb_index_wakeup_request		(0x20D4)
#define runner_b_start_task_dhd_tx_post		(0x2564)
#define runner_b_dhd_tx_post		(0x2564)
#define runner_b_cpu_rx_meter_budget_allocate		(0x1FC0)
#define runner_b_upstream_rate_limiter_budget_allocate		(0x200C)
#define runner_b_schedule_free_skb_index		(0x20B8)

#endif
