#ifndef RUNNER_A_CODE_ADDRESSES
#define RUNNER_A_CODE_ADDRESSES

#define runner_a_start_task_initialization_task		(0x14)
#define runner_a_initialization_task		(0x14)
#define runner_a_start_task_timer_scheduler_set		(0x23D8)
#define runner_a_timer_scheduler_set		(0x23D8)
#define runner_a_start_task_cpu_rx_wakeup_request		(0x14A8)
#define runner_a_cpu_rx_wakeup_request		(0x14A8)
#define runner_a_start_task_flow_cache_wakeup_request		(0xCC0)
#define runner_a_flow_cache_wakeup_request		(0xCC0)
#define runner_a_start_task_cpu_tx_wakeup_request		(0x1AE4)
#define runner_a_cpu_tx_wakeup_request		(0x1AE4)
#define runner_a_start_task_policer_budget_allocator_1st_wakeup_request		(0x24F4)
#define runner_a_policer_budget_allocator_1st_wakeup_request		(0x24F4)
#define runner_a_start_task_wan_cpu_wakeup_request		(0x1B4)
#define runner_a_wan_cpu_wakeup_request		(0x1B4)
#define runner_a_start_task_wan_normal_wakeup_request		(0x370)
#define runner_a_wan_normal_wakeup_request		(0x370)
#define runner_a_start_task_downstream_multicast_wakeup_request		(0x1E50)
#define runner_a_downstream_multicast_wakeup_request		(0x1E50)
#define runner_a_start_task_debug_routine		(0xD8)
#define runner_a_debug_routine		(0xD8)
#define runner_a_start_task_free_skb_index_wakeup_request		(0x24C0)
#define runner_a_free_skb_index_wakeup_request		(0x24C0)
#define runner_a_free_skb_index_tx_abs_done		(0x24C0)
#define runner_a_start_task_dhd_tx_post		(0x3014)
#define runner_a_dhd_tx_post		(0x3014)
#define runner_a_start_task_dhd_tx_complete_wakeup_request		(0x3310)
#define runner_a_dhd_tx_complete_wakeup_request		(0x3310)
#define runner_a_start_task_ipsec_ds_wakeup_request		(0x28F4)
#define runner_a_ipsec_ds_wakeup_request		(0x28F4)
#define runner_a_start_task_ethwan2_normal_wakeup_request		(0x210)
#define runner_a_ethwan2_normal_wakeup_request		(0x210)
#define runner_a_fc_modpkt_sop_push_replace_16		(0x1114)
#define runner_a_fc_modpkt_sop_pull_replace_16		(0x1128)
#define runner_a_fc_modpkt_replace_16		(0x1158)
#define runner_a_fc_modpkt_replace_pointer_16		(0x119C)
#define runner_a_fc_modpkt_replace_32		(0x11EC)
#define runner_a_fc_modpkt_replace_bits_16		(0x1224)
#define runner_a_fc_modpkt_copy_add_16		(0x1254)
#define runner_a_fc_modpkt_copy_bits_16		(0x1298)
#define runner_a_fc_modpkt_insert_16		(0x130C)
#define runner_a_fc_modpkt_delete_16		(0x135C)
#define runner_a_fc_modpkt_decrement_8		(0x1398)
#define runner_a_fc_modpkt_apply_icsum_16		(0x13BC)
#define runner_a_fc_modpkt_apply_icsum_nz_16		(0x13E4)
#define runner_a_fc_modpkt_compute_csum_16		(0x1438)
#define runner_a_fc_modpkt_end		(0x1488)
#define runner_a_cpu_rx_meter_budget_allocate		(0x2458)
#define runner_a_schedule_free_skb_index		(0x24A4)

#endif
