#ifndef RUNNER_D_CODE_ADDRESSES
#define RUNNER_D_CODE_ADDRESSES

#define runner_d_start_task_initialization_task		(0x14)
#define runner_d_initialization_task		(0x14)
#define runner_d_start_task_timer_scheduler_set		(0x12B4)
#define runner_d_timer_scheduler_set		(0x12B4)
#define runner_d_start_task_flow_cache_wakeup_request		(0x8B4)
#define runner_d_flow_cache_wakeup_request		(0x8B4)
#define runner_d_start_task_lan_dispatch_wakeup_request		(0x10A0)
#define runner_d_lan_dispatch_wakeup_request		(0x10A0)
#define runner_d_start_task_lan_cpu_wakeup_request		(0x1A0)
#define runner_d_lan_cpu_wakeup_request		(0x1A0)
#define runner_d_start_task_lan_normal_wakeup_request		(0x1D4)
#define runner_d_lan_normal_wakeup_request		(0x1D4)
#define runner_d_start_task_debug_routine		(0xC4)
#define runner_d_debug_routine		(0xC4)
#define runner_d_start_task_free_skb_index_wakeup_request		(0x1430)
#define runner_d_free_skb_index_wakeup_request		(0x1430)
#define runner_d_free_skb_index_tx_abs_done		(0x1430)
#define runner_d_start_task_dhd_rx_complete_wakeup_request		(0x1504)
#define runner_d_dhd_rx_complete_wakeup_request		(0x1504)
#define runner_d_fc_modpkt_sop_push_replace_16		(0xD04)
#define runner_d_fc_modpkt_sop_pull_replace_16		(0xD18)
#define runner_d_fc_modpkt_replace_16		(0xD48)
#define runner_d_fc_modpkt_replace_pointer_16		(0xD8C)
#define runner_d_fc_modpkt_replace_32		(0xDDC)
#define runner_d_fc_modpkt_replace_bits_16		(0xE14)
#define runner_d_fc_modpkt_copy_add_16		(0xE44)
#define runner_d_fc_modpkt_copy_bits_16		(0xE88)
#define runner_d_fc_modpkt_insert_16		(0xEFC)
#define runner_d_fc_modpkt_delete_16		(0xF4C)
#define runner_d_fc_modpkt_decrement_8		(0xF88)
#define runner_d_fc_modpkt_apply_icsum_16		(0xFAC)
#define runner_d_fc_modpkt_apply_icsum_nz_16		(0xFD4)
#define runner_d_fc_modpkt_compute_csum_16		(0x1028)
#define runner_d_fc_modpkt_end		(0x1078)
#define runner_d_upstream_ingress_rate_limiter_budget_allocate		(0x1334)
#define runner_d_upstream_quasi_budget_allocate		(0x13B4)
#define runner_d_schedule_free_skb_index		(0x1414)

#endif
