#
# USB armory MkI board Makefile
# http://inversepath.com/usbarmory
#
# Copyright (C) 2015, Inverse Path
# Andrej Rosano <andrej@inversepath.com>
#
# SPDX-License-Identifier:|____GPL-2.0+

obj-y	:= usbarmory.o
