include ../common.mak

all:

install:
	install -d $(INSTALLDIR)/usr/sbin

	install -m 0700 acme.sh $(INSTALLDIR)/usr/sbin
	install -D -m 0700 dnsapi/dns_asusapi.sh $(INSTALLDIR)/usr/sbin/dnsapi/dns_asusapi.sh

clean:

