/*
    <:copyright-BRCM:2013:DUAL/GPL:standard
    
       Copyright (c) 2013 Broadcom 
       All Rights Reserved
    
    Unless you and Broadcom execute a separate written software license
    agreement governing use of this software, this software is licensed
    to you under the terms of the GNU General Public License version 2
    (the "GPL"), available at http://www.broadcom.com/licenses/GPLv2.php,
    with the following added to such license:
    
       As a special exception, the copyright holders of this software give
       you permission to link this software with independent modules, and
       to copy and distribute the resulting executable under terms of your
       choice, provided that you also meet, for each linked independent
       module, the terms and conditions of the license of that module.
       An independent module is a module which is not derived from this
       software.  The special exception does not apply to any modifications
       of the software.
    
    Not withstanding the above, under no circumstances may you combine
    this software in any way with any other Broadcom software provided
    under a license other than the GPL, without Broadcom's express prior
    written consent.
    
    :> 
*/

/*  File automatically generated by Reggae at 15/01/2013  09:25:30   */

/* Addresses for Multiple blocks and/or functions */

#include "rdp_subsystem_common.h"
#include "rdp_dma.h"

uint32_t DMA_REGS_CONFIG_SOURCE_ARRAY [ 2 ] =
{
	DMA_REGS_0_CONFIG_SOURCE_ADDRESS,
	DMA_REGS_1_CONFIG_SOURCE_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_CONFIG_SOURCE_ARRAY);

uint32_t DMA_REGS_CONFIG_MALLOC_ARRAY [ 2 ] =
{
	DMA_REGS_0_CONFIG_MALLOC_ADDRESS,
	DMA_REGS_1_CONFIG_MALLOC_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_CONFIG_MALLOC_ARRAY);

uint32_t DMA_REGS_CONFIG_READ_BASE_ARRAY [ 2 ] =
{
	DMA_REGS_0_CONFIG_READ_BASE_ADDRESS,
	DMA_REGS_1_CONFIG_READ_BASE_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_CONFIG_READ_BASE_ARRAY);

uint32_t DMA_REGS_CONFIG_U_THRESH_ARRAY [ 2 ] =
{
	DMA_REGS_0_CONFIG_U_THRESH_ADDRESS,
	DMA_REGS_1_CONFIG_U_THRESH_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_CONFIG_U_THRESH_ARRAY);

uint32_t DMA_REGS_CONFIG_PRI_ARRAY [ 2 ] =
{
	DMA_REGS_0_CONFIG_PRI_ADDRESS,
	DMA_REGS_1_CONFIG_PRI_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_CONFIG_PRI_ARRAY);

uint32_t DMA_REGS_CONFIG_WEIGHT_ARRAY [ 2 ] =
{
	DMA_REGS_0_CONFIG_WEIGHT_ADDRESS,
	DMA_REGS_1_CONFIG_WEIGHT_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_CONFIG_WEIGHT_ARRAY);

uint32_t DMA_REGS_CONFIG_BB_ROUTE_ARRAY [ 2 ] =
{
	DMA_REGS_0_CONFIG_BB_ROUTE_ADDRESS,
	DMA_REGS_1_CONFIG_BB_ROUTE_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_CONFIG_BB_ROUTE_ARRAY);

uint32_t DMA_REGS_CONFIG_PTRRST_ARRAY [ 2 ] =
{
	DMA_REGS_0_CONFIG_PTRRST_ADDRESS,
	DMA_REGS_1_CONFIG_PTRRST_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_CONFIG_PTRRST_ARRAY);

uint32_t DMA_REGS_CONFIG_MEM_SEL_ARRAY [ 2 ] =
{
	DMA_REGS_0_CONFIG_MEM_SEL_ADDRESS,
	DMA_REGS_1_CONFIG_MEM_SEL_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_CONFIG_MEM_SEL_ARRAY);

uint32_t DMA_REGS_DEBUG_NEMPTY_ARRAY [ 2 ] =
{
	DMA_REGS_0_DEBUG_NEMPTY_ADDRESS,
	DMA_REGS_1_DEBUG_NEMPTY_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_DEBUG_NEMPTY_ARRAY);

uint32_t DMA_REGS_DEBUG_URGNT_ARRAY [ 2 ] =
{
	DMA_REGS_0_DEBUG_URGNT_ADDRESS,
	DMA_REGS_1_DEBUG_URGNT_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_DEBUG_URGNT_ARRAY);

uint32_t DMA_REGS_DEBUG_SELSRC_ARRAY [ 2 ] =
{
	DMA_REGS_0_DEBUG_SELSRC_ADDRESS,
	DMA_REGS_1_DEBUG_SELSRC_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_DEBUG_SELSRC_ARRAY);

uint32_t DMA_REGS_DEBUG_REQ_CNT_RX_ARRAY [ 2 ] =
{
	DMA_REGS_0_DEBUG_REQ_CNT_RX_ADDRESS,
	DMA_REGS_1_DEBUG_REQ_CNT_RX_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_DEBUG_REQ_CNT_RX_ARRAY);

uint32_t DMA_REGS_DEBUG_REQ_CNT_TX_ARRAY [ 2 ] =
{
	DMA_REGS_0_DEBUG_REQ_CNT_TX_ADDRESS,
	DMA_REGS_1_DEBUG_REQ_CNT_TX_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_DEBUG_REQ_CNT_TX_ARRAY);

uint32_t DMA_REGS_DEBUG_REQ_CNT_RX_ACC_ARRAY [ 2 ] =
{
	DMA_REGS_0_DEBUG_REQ_CNT_RX_ACC_ADDRESS,
	DMA_REGS_1_DEBUG_REQ_CNT_RX_ACC_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_DEBUG_REQ_CNT_RX_ACC_ARRAY);

uint32_t DMA_REGS_DEBUG_REQ_CNT_TX_ACC_ARRAY [ 2 ] =
{
	DMA_REGS_0_DEBUG_REQ_CNT_TX_ACC_ADDRESS,
	DMA_REGS_1_DEBUG_REQ_CNT_TX_ACC_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_DEBUG_REQ_CNT_TX_ACC_ARRAY);

uint32_t DMA_REGS_DEBUG_RDADD_ARRAY [ 2 ] =
{
	DMA_REGS_0_DEBUG_RDADD_ADDRESS,
	DMA_REGS_1_DEBUG_RDADD_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_DEBUG_RDADD_ARRAY);

uint32_t DMA_REGS_DEBUG_RDVALID_ARRAY [ 2 ] =
{
	DMA_REGS_0_DEBUG_RDVALID_ADDRESS,
	DMA_REGS_1_DEBUG_RDVALID_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_DEBUG_RDVALID_ARRAY);

uint32_t DMA_REGS_DEBUG_RDDATA_ARRAY [ 2 ] =
{
	DMA_REGS_0_DEBUG_RDDATA_ADDRESS,
	DMA_REGS_1_DEBUG_RDDATA_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_DEBUG_RDDATA_ARRAY);

uint32_t DMA_REGS_DEBUG_RDDATARDY_ARRAY [ 2 ] =
{
	DMA_REGS_0_DEBUG_RDDATARDY_ADDRESS,
	DMA_REGS_1_DEBUG_RDDATARDY_ADDRESS
} ;

EXPORT_SYMBOL(DMA_REGS_DEBUG_RDDATARDY_ARRAY);
