/* IMAGE 0 LABELS */
#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_0_budget_allocator_1st_wakeup_request        (0x664)
#define image_0_budget_allocator_sq_1st_wakeup_request        (0x14fc)
#define image_0_debug_routine        (0x84)
#define image_0_debug_routine_handler        (0x4)
#define image_0_ds_tx_task_wakeup_request        (0x334)
#define image_0_flush_task_1st_wakeup_request        (0x9b0)
#define image_0_ghost_reporting_1st_wakeup_request        (0xc7c)
#define image_0_initialization_task        (0x8)
#define image_0_service_queues_tx_task_wakeup_request        (0x1310)
#define image_0_service_queues_update_fifo_read_1st_wakeup_request        (0x1088)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0x664)
#define image_0_start_task_budget_allocator_sq_1st_wakeup_request        (0x14fc)
#define image_0_start_task_debug_routine        (0x84)
#define image_0_start_task_ds_tx_task_wakeup_request        (0x334)
#define image_0_start_task_flush_task_1st_wakeup_request        (0x9b0)
#define image_0_start_task_ghost_reporting_1st_wakeup_request        (0xc7c)
#define image_0_start_task_initialization_task        (0x8)
#define image_0_start_task_service_queues_tx_task_wakeup_request        (0x1310)
#define image_0_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0x1088)
#define image_0_start_task_update_fifo_ds_read_1st_wakeup_request        (0x150)
#define image_0_update_fifo_ds_read_1st_wakeup_request        (0x150)

#else

#define image_0_budget_allocator_1st_wakeup_request        (0x199)
#define image_0_budget_allocator_sq_1st_wakeup_request        (0x53f)
#define image_0_debug_routine        (0x21)
#define image_0_debug_routine_handler        (0x1)
#define image_0_ds_tx_task_wakeup_request        (0xcd)
#define image_0_flush_task_1st_wakeup_request        (0x26c)
#define image_0_ghost_reporting_1st_wakeup_request        (0x31f)
#define image_0_initialization_task        (0x2)
#define image_0_service_queues_tx_task_wakeup_request        (0x4c4)
#define image_0_service_queues_update_fifo_read_1st_wakeup_request        (0x422)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0x199)
#define image_0_start_task_budget_allocator_sq_1st_wakeup_request        (0x53f)
#define image_0_start_task_debug_routine        (0x21)
#define image_0_start_task_ds_tx_task_wakeup_request        (0xcd)
#define image_0_start_task_flush_task_1st_wakeup_request        (0x26c)
#define image_0_start_task_ghost_reporting_1st_wakeup_request        (0x31f)
#define image_0_start_task_initialization_task        (0x2)
#define image_0_start_task_service_queues_tx_task_wakeup_request        (0x4c4)
#define image_0_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0x422)
#define image_0_start_task_update_fifo_ds_read_1st_wakeup_request        (0x54)
#define image_0_update_fifo_ds_read_1st_wakeup_request        (0x54)

#endif


#endif

/* IMAGE 1 LABELS */
#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_1_action_exception        (0x22bc)
#define image_1_action_gpe        (0x22a8)
#define image_1_common_reprocessing_wakeup_request        (0x5ccc)
#define image_1_cpu_recycle_wakeup_request        (0x44e8)
#define image_1_cpu_rx_copy_wakeup_request        (0x3234)
#define image_1_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x4428)
#define image_1_cpu_rx_wakeup_request        (0x40e8)
#define image_1_debug_routine        (0x3168)
#define image_1_debug_routine_handler        (0x4)
#define image_1_gpe_apply_icsum_16        (0x26dc)
#define image_1_gpe_apply_icsum_nz_16        (0x2700)
#define image_1_gpe_buffer_copy_16_ddr        (0x27b4)
#define image_1_gpe_buffer_copy_16_sram        (0x2788)
#define image_1_gpe_compute_csum_16_cl        (0x273c)
#define image_1_gpe_compute_csum_16_sram        (0x2748)
#define image_1_gpe_copy_add_16_cl        (0x2568)
#define image_1_gpe_copy_add_16_sram        (0x2574)
#define image_1_gpe_copy_bits_16_cl        (0x25bc)
#define image_1_gpe_copy_bits_16_sram        (0x25c8)
#define image_1_gpe_decrement_8        (0x26b8)
#define image_1_gpe_delete_16        (0x2678)
#define image_1_gpe_insert_16        (0x2610)
#define image_1_gpe_replace_16        (0x24e4)
#define image_1_gpe_replace_32        (0x2518)
#define image_1_gpe_replace_add_packet_length_cl        (0x27e4)
#define image_1_gpe_replace_bits_16        (0x253c)
#define image_1_gpe_replace_pointer_32_sram        (0x249c)
#define image_1_gpe_replace_pointer_64_sram        (0x24c0)
#define image_1_gpe_sop_pull_replace_ddr_sram_32        (0x237c)
#define image_1_gpe_sop_pull_replace_sram_32_64        (0x23c0)
#define image_1_gpe_sop_pull_replace_sram_64        (0x2410)
#define image_1_gpe_sop_pull_replace_sram_64_32        (0x244c)
#define image_1_gpe_sop_push_replace_ddr_sram_32        (0x22fc)
#define image_1_gpe_sop_push_replace_sram_32_64        (0x2340)
#define image_1_gpe_sop_push_replace_sram_64        (0x2354)
#define image_1_gpe_sop_push_replace_sram_64_32        (0x2368)
#define image_1_initialization_task        (0x8)
#define image_1_interrupt_coalescing_1st_wakeup_request        (0x463c)
#define image_1_processing_check_wlan_llcsnap        (0x948)
#define image_1_processing_done        (0xaec)
#define image_1_processing_wakeup_request        (0x44)
#define image_1_spdsvc_gen_wakeup_request        (0x5848)
#define image_1_start_task_common_reprocessing_wakeup_request        (0x5ccc)
#define image_1_start_task_cpu_recycle_wakeup_request        (0x44e8)
#define image_1_start_task_cpu_rx_copy_wakeup_request        (0x3234)
#define image_1_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x4428)
#define image_1_start_task_cpu_rx_wakeup_request        (0x40e8)
#define image_1_start_task_debug_routine        (0x3168)
#define image_1_start_task_initialization_task        (0x8)
#define image_1_start_task_interrupt_coalescing_1st_wakeup_request        (0x463c)
#define image_1_start_task_processing_wakeup_request        (0x44)
#define image_1_start_task_spdsvc_gen_wakeup_request        (0x5848)
#define image_1_tcam_cmd_dst_ip        (0x2aa0)
#define image_1_tcam_cmd_dst_ipv6_masked        (0x2afc)
#define image_1_tcam_cmd_dst_mac        (0x2b94)
#define image_1_tcam_cmd_dst_port        (0x2b50)
#define image_1_tcam_cmd_ethertype        (0x28ac)
#define image_1_tcam_cmd_gem_flow        (0x29bc)
#define image_1_tcam_cmd_generic_l2        (0x2bc0)
#define image_1_tcam_cmd_generic_l3        (0x2bf4)
#define image_1_tcam_cmd_generic_l4        (0x2c30)
#define image_1_tcam_cmd_ic_submit        (0x2838)
#define image_1_tcam_cmd_ingress_port        (0x29a4)
#define image_1_tcam_cmd_inner_pbit        (0x290c)
#define image_1_tcam_cmd_inner_tpid        (0x2894)
#define image_1_tcam_cmd_inner_vid        (0x28dc)
#define image_1_tcam_cmd_ip_protocol        (0x293c)
#define image_1_tcam_cmd_ipv6_label        (0x29d4)
#define image_1_tcam_cmd_l3_protocol        (0x2954)
#define image_1_tcam_cmd_network_layer        (0x2984)
#define image_1_tcam_cmd_outer_pbit        (0x28f4)
#define image_1_tcam_cmd_outer_tpid        (0x287c)
#define image_1_tcam_cmd_outer_vid        (0x28c4)
#define image_1_tcam_cmd_src_ip        (0x2a08)
#define image_1_tcam_cmd_src_ipv6_masked        (0x2a64)
#define image_1_tcam_cmd_src_mac        (0x2b68)
#define image_1_tcam_cmd_src_port        (0x2b38)
#define image_1_tcam_cmd_tos        (0x296c)
#define image_1_tcam_cmd_vlan_num        (0x2924)

#else

#define image_1_action_exception        (0x8af)
#define image_1_action_gpe        (0x8aa)
#define image_1_common_reprocessing_wakeup_request        (0x1733)
#define image_1_cpu_recycle_wakeup_request        (0x113a)
#define image_1_cpu_rx_copy_wakeup_request        (0xc8d)
#define image_1_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x110a)
#define image_1_cpu_rx_wakeup_request        (0x103a)
#define image_1_debug_routine        (0xc5a)
#define image_1_debug_routine_handler        (0x1)
#define image_1_gpe_apply_icsum_16        (0x9b7)
#define image_1_gpe_apply_icsum_nz_16        (0x9c0)
#define image_1_gpe_buffer_copy_16_ddr        (0x9ed)
#define image_1_gpe_buffer_copy_16_sram        (0x9e2)
#define image_1_gpe_compute_csum_16_cl        (0x9cf)
#define image_1_gpe_compute_csum_16_sram        (0x9d2)
#define image_1_gpe_copy_add_16_cl        (0x95a)
#define image_1_gpe_copy_add_16_sram        (0x95d)
#define image_1_gpe_copy_bits_16_cl        (0x96f)
#define image_1_gpe_copy_bits_16_sram        (0x972)
#define image_1_gpe_decrement_8        (0x9ae)
#define image_1_gpe_delete_16        (0x99e)
#define image_1_gpe_insert_16        (0x984)
#define image_1_gpe_replace_16        (0x939)
#define image_1_gpe_replace_32        (0x946)
#define image_1_gpe_replace_add_packet_length_cl        (0x9f9)
#define image_1_gpe_replace_bits_16        (0x94f)
#define image_1_gpe_replace_pointer_32_sram        (0x927)
#define image_1_gpe_replace_pointer_64_sram        (0x930)
#define image_1_gpe_sop_pull_replace_ddr_sram_32        (0x8df)
#define image_1_gpe_sop_pull_replace_sram_32_64        (0x8f0)
#define image_1_gpe_sop_pull_replace_sram_64        (0x904)
#define image_1_gpe_sop_pull_replace_sram_64_32        (0x913)
#define image_1_gpe_sop_push_replace_ddr_sram_32        (0x8bf)
#define image_1_gpe_sop_push_replace_sram_32_64        (0x8d0)
#define image_1_gpe_sop_push_replace_sram_64        (0x8d5)
#define image_1_gpe_sop_push_replace_sram_64_32        (0x8da)
#define image_1_initialization_task        (0x2)
#define image_1_interrupt_coalescing_1st_wakeup_request        (0x118f)
#define image_1_processing_check_wlan_llcsnap        (0x252)
#define image_1_processing_done        (0x2bb)
#define image_1_processing_wakeup_request        (0x11)
#define image_1_spdsvc_gen_wakeup_request        (0x1612)
#define image_1_start_task_common_reprocessing_wakeup_request        (0x1733)
#define image_1_start_task_cpu_recycle_wakeup_request        (0x113a)
#define image_1_start_task_cpu_rx_copy_wakeup_request        (0xc8d)
#define image_1_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x110a)
#define image_1_start_task_cpu_rx_wakeup_request        (0x103a)
#define image_1_start_task_debug_routine        (0xc5a)
#define image_1_start_task_initialization_task        (0x2)
#define image_1_start_task_interrupt_coalescing_1st_wakeup_request        (0x118f)
#define image_1_start_task_processing_wakeup_request        (0x11)
#define image_1_start_task_spdsvc_gen_wakeup_request        (0x1612)
#define image_1_tcam_cmd_dst_ip        (0xaa8)
#define image_1_tcam_cmd_dst_ipv6_masked        (0xabf)
#define image_1_tcam_cmd_dst_mac        (0xae5)
#define image_1_tcam_cmd_dst_port        (0xad4)
#define image_1_tcam_cmd_ethertype        (0xa2b)
#define image_1_tcam_cmd_gem_flow        (0xa6f)
#define image_1_tcam_cmd_generic_l2        (0xaf0)
#define image_1_tcam_cmd_generic_l3        (0xafd)
#define image_1_tcam_cmd_generic_l4        (0xb0c)
#define image_1_tcam_cmd_ic_submit        (0xa0e)
#define image_1_tcam_cmd_ingress_port        (0xa69)
#define image_1_tcam_cmd_inner_pbit        (0xa43)
#define image_1_tcam_cmd_inner_tpid        (0xa25)
#define image_1_tcam_cmd_inner_vid        (0xa37)
#define image_1_tcam_cmd_ip_protocol        (0xa4f)
#define image_1_tcam_cmd_ipv6_label        (0xa75)
#define image_1_tcam_cmd_l3_protocol        (0xa55)
#define image_1_tcam_cmd_network_layer        (0xa61)
#define image_1_tcam_cmd_outer_pbit        (0xa3d)
#define image_1_tcam_cmd_outer_tpid        (0xa1f)
#define image_1_tcam_cmd_outer_vid        (0xa31)
#define image_1_tcam_cmd_src_ip        (0xa82)
#define image_1_tcam_cmd_src_ipv6_masked        (0xa99)
#define image_1_tcam_cmd_src_mac        (0xada)
#define image_1_tcam_cmd_src_port        (0xace)
#define image_1_tcam_cmd_tos        (0xa5b)
#define image_1_tcam_cmd_vlan_num        (0xa49)

#endif


#endif

/* IMAGE 2 LABELS */
#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_2_action_exception        (0x23c8)
#define image_2_action_gpe        (0x23b4)
#define image_2_cpu_recycle_wakeup_request        (0x3974)
#define image_2_cpu_tx_read_ring_indices        (0x3274)
#define image_2_cpu_tx_wakeup_request        (0x3274)
#define image_2_debug_routine        (0x44)
#define image_2_debug_routine_handler        (0x4)
#define image_2_gpe_apply_icsum_16        (0x27e8)
#define image_2_gpe_apply_icsum_nz_16        (0x280c)
#define image_2_gpe_buffer_copy_16_ddr        (0x28c0)
#define image_2_gpe_buffer_copy_16_sram        (0x2894)
#define image_2_gpe_compute_csum_16_cl        (0x2848)
#define image_2_gpe_compute_csum_16_sram        (0x2854)
#define image_2_gpe_copy_add_16_cl        (0x2674)
#define image_2_gpe_copy_add_16_sram        (0x2680)
#define image_2_gpe_copy_bits_16_cl        (0x26c8)
#define image_2_gpe_copy_bits_16_sram        (0x26d4)
#define image_2_gpe_decrement_8        (0x27c4)
#define image_2_gpe_delete_16        (0x2784)
#define image_2_gpe_insert_16        (0x271c)
#define image_2_gpe_replace_16        (0x25f0)
#define image_2_gpe_replace_32        (0x2624)
#define image_2_gpe_replace_add_packet_length_cl        (0x28f0)
#define image_2_gpe_replace_bits_16        (0x2648)
#define image_2_gpe_replace_pointer_32_sram        (0x25a8)
#define image_2_gpe_replace_pointer_64_sram        (0x25cc)
#define image_2_gpe_sop_pull_replace_ddr_sram_32        (0x2488)
#define image_2_gpe_sop_pull_replace_sram_32_64        (0x24cc)
#define image_2_gpe_sop_pull_replace_sram_64        (0x251c)
#define image_2_gpe_sop_pull_replace_sram_64_32        (0x2558)
#define image_2_gpe_sop_push_replace_ddr_sram_32        (0x2408)
#define image_2_gpe_sop_push_replace_sram_32_64        (0x244c)
#define image_2_gpe_sop_push_replace_sram_64        (0x2460)
#define image_2_gpe_sop_push_replace_sram_64_32        (0x2474)
#define image_2_initialization_task        (0x8)
#define image_2_interrupt_coalescing_1st_wakeup_request        (0x3ac8)
#define image_2_processing_check_wlan_llcsnap        (0xa54)
#define image_2_processing_done        (0xbf8)
#define image_2_processing_wakeup_request        (0x150)
#define image_2_start_task_cpu_recycle_wakeup_request        (0x3974)
#define image_2_start_task_cpu_tx_wakeup_request        (0x3274)
#define image_2_start_task_debug_routine        (0x44)
#define image_2_start_task_initialization_task        (0x8)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request        (0x3ac8)
#define image_2_start_task_processing_wakeup_request        (0x150)
#define image_2_tcam_cmd_dst_ip        (0x2bac)
#define image_2_tcam_cmd_dst_ipv6_masked        (0x2c08)
#define image_2_tcam_cmd_dst_mac        (0x2ca0)
#define image_2_tcam_cmd_dst_port        (0x2c5c)
#define image_2_tcam_cmd_ethertype        (0x29b8)
#define image_2_tcam_cmd_gem_flow        (0x2ac8)
#define image_2_tcam_cmd_generic_l2        (0x2ccc)
#define image_2_tcam_cmd_generic_l3        (0x2d00)
#define image_2_tcam_cmd_generic_l4        (0x2d3c)
#define image_2_tcam_cmd_ic_submit        (0x2944)
#define image_2_tcam_cmd_ingress_port        (0x2ab0)
#define image_2_tcam_cmd_inner_pbit        (0x2a18)
#define image_2_tcam_cmd_inner_tpid        (0x29a0)
#define image_2_tcam_cmd_inner_vid        (0x29e8)
#define image_2_tcam_cmd_ip_protocol        (0x2a48)
#define image_2_tcam_cmd_ipv6_label        (0x2ae0)
#define image_2_tcam_cmd_l3_protocol        (0x2a60)
#define image_2_tcam_cmd_network_layer        (0x2a90)
#define image_2_tcam_cmd_outer_pbit        (0x2a00)
#define image_2_tcam_cmd_outer_tpid        (0x2988)
#define image_2_tcam_cmd_outer_vid        (0x29d0)
#define image_2_tcam_cmd_src_ip        (0x2b14)
#define image_2_tcam_cmd_src_ipv6_masked        (0x2b70)
#define image_2_tcam_cmd_src_mac        (0x2c74)
#define image_2_tcam_cmd_src_port        (0x2c44)
#define image_2_tcam_cmd_tos        (0x2a78)
#define image_2_tcam_cmd_vlan_num        (0x2a30)

#else

#define image_2_action_exception        (0x8f2)
#define image_2_action_gpe        (0x8ed)
#define image_2_cpu_recycle_wakeup_request        (0xe5d)
#define image_2_cpu_tx_read_ring_indices        (0xc9d)
#define image_2_cpu_tx_wakeup_request        (0xc9d)
#define image_2_debug_routine        (0x11)
#define image_2_debug_routine_handler        (0x1)
#define image_2_gpe_apply_icsum_16        (0x9fa)
#define image_2_gpe_apply_icsum_nz_16        (0xa03)
#define image_2_gpe_buffer_copy_16_ddr        (0xa30)
#define image_2_gpe_buffer_copy_16_sram        (0xa25)
#define image_2_gpe_compute_csum_16_cl        (0xa12)
#define image_2_gpe_compute_csum_16_sram        (0xa15)
#define image_2_gpe_copy_add_16_cl        (0x99d)
#define image_2_gpe_copy_add_16_sram        (0x9a0)
#define image_2_gpe_copy_bits_16_cl        (0x9b2)
#define image_2_gpe_copy_bits_16_sram        (0x9b5)
#define image_2_gpe_decrement_8        (0x9f1)
#define image_2_gpe_delete_16        (0x9e1)
#define image_2_gpe_insert_16        (0x9c7)
#define image_2_gpe_replace_16        (0x97c)
#define image_2_gpe_replace_32        (0x989)
#define image_2_gpe_replace_add_packet_length_cl        (0xa3c)
#define image_2_gpe_replace_bits_16        (0x992)
#define image_2_gpe_replace_pointer_32_sram        (0x96a)
#define image_2_gpe_replace_pointer_64_sram        (0x973)
#define image_2_gpe_sop_pull_replace_ddr_sram_32        (0x922)
#define image_2_gpe_sop_pull_replace_sram_32_64        (0x933)
#define image_2_gpe_sop_pull_replace_sram_64        (0x947)
#define image_2_gpe_sop_pull_replace_sram_64_32        (0x956)
#define image_2_gpe_sop_push_replace_ddr_sram_32        (0x902)
#define image_2_gpe_sop_push_replace_sram_32_64        (0x913)
#define image_2_gpe_sop_push_replace_sram_64        (0x918)
#define image_2_gpe_sop_push_replace_sram_64_32        (0x91d)
#define image_2_initialization_task        (0x2)
#define image_2_interrupt_coalescing_1st_wakeup_request        (0xeb2)
#define image_2_processing_check_wlan_llcsnap        (0x295)
#define image_2_processing_done        (0x2fe)
#define image_2_processing_wakeup_request        (0x54)
#define image_2_start_task_cpu_recycle_wakeup_request        (0xe5d)
#define image_2_start_task_cpu_tx_wakeup_request        (0xc9d)
#define image_2_start_task_debug_routine        (0x11)
#define image_2_start_task_initialization_task        (0x2)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request        (0xeb2)
#define image_2_start_task_processing_wakeup_request        (0x54)
#define image_2_tcam_cmd_dst_ip        (0xaeb)
#define image_2_tcam_cmd_dst_ipv6_masked        (0xb02)
#define image_2_tcam_cmd_dst_mac        (0xb28)
#define image_2_tcam_cmd_dst_port        (0xb17)
#define image_2_tcam_cmd_ethertype        (0xa6e)
#define image_2_tcam_cmd_gem_flow        (0xab2)
#define image_2_tcam_cmd_generic_l2        (0xb33)
#define image_2_tcam_cmd_generic_l3        (0xb40)
#define image_2_tcam_cmd_generic_l4        (0xb4f)
#define image_2_tcam_cmd_ic_submit        (0xa51)
#define image_2_tcam_cmd_ingress_port        (0xaac)
#define image_2_tcam_cmd_inner_pbit        (0xa86)
#define image_2_tcam_cmd_inner_tpid        (0xa68)
#define image_2_tcam_cmd_inner_vid        (0xa7a)
#define image_2_tcam_cmd_ip_protocol        (0xa92)
#define image_2_tcam_cmd_ipv6_label        (0xab8)
#define image_2_tcam_cmd_l3_protocol        (0xa98)
#define image_2_tcam_cmd_network_layer        (0xaa4)
#define image_2_tcam_cmd_outer_pbit        (0xa80)
#define image_2_tcam_cmd_outer_tpid        (0xa62)
#define image_2_tcam_cmd_outer_vid        (0xa74)
#define image_2_tcam_cmd_src_ip        (0xac5)
#define image_2_tcam_cmd_src_ipv6_masked        (0xadc)
#define image_2_tcam_cmd_src_mac        (0xb1d)
#define image_2_tcam_cmd_src_port        (0xb11)
#define image_2_tcam_cmd_tos        (0xa9e)
#define image_2_tcam_cmd_vlan_num        (0xa8c)

#endif


#endif

/* IMAGE 3 LABELS */
#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_3_budget_allocator_1st_wakeup_request        (0xe48)
#define image_3_debug_routine        (0xcc)
#define image_3_debug_routine_handler        (0x4)
#define image_3_epon_tx_task_wakeup_request        (0xb44)
#define image_3_epon_update_fifo_read_1st_wakeup_request        (0x1774)
#define image_3_flush_task_1st_wakeup_request        (0x1330)
#define image_3_gpon_control_wakeup_request        (0x198)
#define image_3_initialization_task        (0x8)
#define image_3_ovl_budget_allocator_1st_wakeup_request        (0x1224)
#define image_3_start_task_budget_allocator_1st_wakeup_request        (0xe48)
#define image_3_start_task_debug_routine        (0xcc)
#define image_3_start_task_epon_tx_task_wakeup_request        (0xb44)
#define image_3_start_task_epon_update_fifo_read_1st_wakeup_request        (0x1774)
#define image_3_start_task_flush_task_1st_wakeup_request        (0x1330)
#define image_3_start_task_gpon_control_wakeup_request        (0x198)
#define image_3_start_task_initialization_task        (0x8)
#define image_3_start_task_ovl_budget_allocator_1st_wakeup_request        (0x1224)
#define image_3_start_task_tx_task_1st_wakeup_request        (0x598)
#define image_3_start_task_update_fifo_us_read_1st_wakeup_request        (0x14e4)
#define image_3_start_task_wan_tx_ddr_read_1st_wakeup_request        (0x12e0)
#define image_3_start_task_wan_tx_psram_write_1st_wakeup_request        (0x1308)
#define image_3_tx_task_1st_wakeup_request        (0x598)
#define image_3_update_fifo_us_read_1st_wakeup_request        (0x14e4)
#define image_3_wan_tx_ddr_read_1st_wakeup_request        (0x12e0)
#define image_3_wan_tx_psram_write_1st_wakeup_request        (0x1308)

#else

#define image_3_budget_allocator_1st_wakeup_request        (0x392)
#define image_3_debug_routine        (0x33)
#define image_3_debug_routine_handler        (0x1)
#define image_3_epon_tx_task_wakeup_request        (0x2d1)
#define image_3_epon_update_fifo_read_1st_wakeup_request        (0x5dd)
#define image_3_flush_task_1st_wakeup_request        (0x4cc)
#define image_3_gpon_control_wakeup_request        (0x66)
#define image_3_initialization_task        (0x2)
#define image_3_ovl_budget_allocator_1st_wakeup_request        (0x489)
#define image_3_start_task_budget_allocator_1st_wakeup_request        (0x392)
#define image_3_start_task_debug_routine        (0x33)
#define image_3_start_task_epon_tx_task_wakeup_request        (0x2d1)
#define image_3_start_task_epon_update_fifo_read_1st_wakeup_request        (0x5dd)
#define image_3_start_task_flush_task_1st_wakeup_request        (0x4cc)
#define image_3_start_task_gpon_control_wakeup_request        (0x66)
#define image_3_start_task_initialization_task        (0x2)
#define image_3_start_task_ovl_budget_allocator_1st_wakeup_request        (0x489)
#define image_3_start_task_tx_task_1st_wakeup_request        (0x166)
#define image_3_start_task_update_fifo_us_read_1st_wakeup_request        (0x539)
#define image_3_start_task_wan_tx_ddr_read_1st_wakeup_request        (0x4b8)
#define image_3_start_task_wan_tx_psram_write_1st_wakeup_request        (0x4c2)
#define image_3_tx_task_1st_wakeup_request        (0x166)
#define image_3_update_fifo_us_read_1st_wakeup_request        (0x539)
#define image_3_wan_tx_ddr_read_1st_wakeup_request        (0x4b8)
#define image_3_wan_tx_psram_write_1st_wakeup_request        (0x4c2)

#endif


#endif

/* IMAGE 4 LABELS */
#ifndef IMAGE_4_CODE_ADDRESSES
#define IMAGE_4_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_4_action_exception        (0x22bc)
#define image_4_action_gpe        (0x22a8)
#define image_4_debug_routine        (0x3168)
#define image_4_debug_routine_handler        (0x4)
#define image_4_dhd_mcast_wakeup_request        (0x35a8)
#define image_4_dhd_timer_1st_wakeup_request        (0x3bd0)
#define image_4_dhd_tx_post_update_fifo_wakeup_request        (0x3d78)
#define image_4_dhd_tx_post_wakeup_request        (0x3dd0)
#define image_4_gpe_apply_icsum_16        (0x26dc)
#define image_4_gpe_apply_icsum_nz_16        (0x2700)
#define image_4_gpe_buffer_copy_16_ddr        (0x27b4)
#define image_4_gpe_buffer_copy_16_sram        (0x2788)
#define image_4_gpe_compute_csum_16_cl        (0x273c)
#define image_4_gpe_compute_csum_16_sram        (0x2748)
#define image_4_gpe_copy_add_16_cl        (0x2568)
#define image_4_gpe_copy_add_16_sram        (0x2574)
#define image_4_gpe_copy_bits_16_cl        (0x25bc)
#define image_4_gpe_copy_bits_16_sram        (0x25c8)
#define image_4_gpe_decrement_8        (0x26b8)
#define image_4_gpe_delete_16        (0x2678)
#define image_4_gpe_insert_16        (0x2610)
#define image_4_gpe_replace_16        (0x24e4)
#define image_4_gpe_replace_32        (0x2518)
#define image_4_gpe_replace_add_packet_length_cl        (0x27e4)
#define image_4_gpe_replace_bits_16        (0x253c)
#define image_4_gpe_replace_pointer_32_sram        (0x249c)
#define image_4_gpe_replace_pointer_64_sram        (0x24c0)
#define image_4_gpe_sop_pull_replace_ddr_sram_32        (0x237c)
#define image_4_gpe_sop_pull_replace_sram_32_64        (0x23c0)
#define image_4_gpe_sop_pull_replace_sram_64        (0x2410)
#define image_4_gpe_sop_pull_replace_sram_64_32        (0x244c)
#define image_4_gpe_sop_push_replace_ddr_sram_32        (0x22fc)
#define image_4_gpe_sop_push_replace_sram_32_64        (0x2340)
#define image_4_gpe_sop_push_replace_sram_64        (0x2354)
#define image_4_gpe_sop_push_replace_sram_64_32        (0x2368)
#define image_4_initialization_task        (0x8)
#define image_4_processing_check_wlan_llcsnap        (0x948)
#define image_4_processing_done        (0xaec)
#define image_4_processing_wakeup_request        (0x44)
#define image_4_start_task_debug_routine        (0x3168)
#define image_4_start_task_dhd_mcast_wakeup_request        (0x35a8)
#define image_4_start_task_dhd_timer_1st_wakeup_request        (0x3bd0)
#define image_4_start_task_dhd_tx_post_update_fifo_wakeup_request        (0x3d78)
#define image_4_start_task_dhd_tx_post_wakeup_request        (0x3dd0)
#define image_4_start_task_initialization_task        (0x8)
#define image_4_start_task_processing_wakeup_request        (0x44)
#define image_4_tcam_cmd_dst_ip        (0x2aa0)
#define image_4_tcam_cmd_dst_ipv6_masked        (0x2afc)
#define image_4_tcam_cmd_dst_mac        (0x2b94)
#define image_4_tcam_cmd_dst_port        (0x2b50)
#define image_4_tcam_cmd_ethertype        (0x28ac)
#define image_4_tcam_cmd_gem_flow        (0x29bc)
#define image_4_tcam_cmd_generic_l2        (0x2bc0)
#define image_4_tcam_cmd_generic_l3        (0x2bf4)
#define image_4_tcam_cmd_generic_l4        (0x2c30)
#define image_4_tcam_cmd_ic_submit        (0x2838)
#define image_4_tcam_cmd_ingress_port        (0x29a4)
#define image_4_tcam_cmd_inner_pbit        (0x290c)
#define image_4_tcam_cmd_inner_tpid        (0x2894)
#define image_4_tcam_cmd_inner_vid        (0x28dc)
#define image_4_tcam_cmd_ip_protocol        (0x293c)
#define image_4_tcam_cmd_ipv6_label        (0x29d4)
#define image_4_tcam_cmd_l3_protocol        (0x2954)
#define image_4_tcam_cmd_network_layer        (0x2984)
#define image_4_tcam_cmd_outer_pbit        (0x28f4)
#define image_4_tcam_cmd_outer_tpid        (0x287c)
#define image_4_tcam_cmd_outer_vid        (0x28c4)
#define image_4_tcam_cmd_src_ip        (0x2a08)
#define image_4_tcam_cmd_src_ipv6_masked        (0x2a64)
#define image_4_tcam_cmd_src_mac        (0x2b68)
#define image_4_tcam_cmd_src_port        (0x2b38)
#define image_4_tcam_cmd_tos        (0x296c)
#define image_4_tcam_cmd_vlan_num        (0x2924)

#else

#define image_4_action_exception        (0x8af)
#define image_4_action_gpe        (0x8aa)
#define image_4_debug_routine        (0xc5a)
#define image_4_debug_routine_handler        (0x1)
#define image_4_dhd_mcast_wakeup_request        (0xd6a)
#define image_4_dhd_timer_1st_wakeup_request        (0xef4)
#define image_4_dhd_tx_post_update_fifo_wakeup_request        (0xf5e)
#define image_4_dhd_tx_post_wakeup_request        (0xf74)
#define image_4_gpe_apply_icsum_16        (0x9b7)
#define image_4_gpe_apply_icsum_nz_16        (0x9c0)
#define image_4_gpe_buffer_copy_16_ddr        (0x9ed)
#define image_4_gpe_buffer_copy_16_sram        (0x9e2)
#define image_4_gpe_compute_csum_16_cl        (0x9cf)
#define image_4_gpe_compute_csum_16_sram        (0x9d2)
#define image_4_gpe_copy_add_16_cl        (0x95a)
#define image_4_gpe_copy_add_16_sram        (0x95d)
#define image_4_gpe_copy_bits_16_cl        (0x96f)
#define image_4_gpe_copy_bits_16_sram        (0x972)
#define image_4_gpe_decrement_8        (0x9ae)
#define image_4_gpe_delete_16        (0x99e)
#define image_4_gpe_insert_16        (0x984)
#define image_4_gpe_replace_16        (0x939)
#define image_4_gpe_replace_32        (0x946)
#define image_4_gpe_replace_add_packet_length_cl        (0x9f9)
#define image_4_gpe_replace_bits_16        (0x94f)
#define image_4_gpe_replace_pointer_32_sram        (0x927)
#define image_4_gpe_replace_pointer_64_sram        (0x930)
#define image_4_gpe_sop_pull_replace_ddr_sram_32        (0x8df)
#define image_4_gpe_sop_pull_replace_sram_32_64        (0x8f0)
#define image_4_gpe_sop_pull_replace_sram_64        (0x904)
#define image_4_gpe_sop_pull_replace_sram_64_32        (0x913)
#define image_4_gpe_sop_push_replace_ddr_sram_32        (0x8bf)
#define image_4_gpe_sop_push_replace_sram_32_64        (0x8d0)
#define image_4_gpe_sop_push_replace_sram_64        (0x8d5)
#define image_4_gpe_sop_push_replace_sram_64_32        (0x8da)
#define image_4_initialization_task        (0x2)
#define image_4_processing_check_wlan_llcsnap        (0x252)
#define image_4_processing_done        (0x2bb)
#define image_4_processing_wakeup_request        (0x11)
#define image_4_start_task_debug_routine        (0xc5a)
#define image_4_start_task_dhd_mcast_wakeup_request        (0xd6a)
#define image_4_start_task_dhd_timer_1st_wakeup_request        (0xef4)
#define image_4_start_task_dhd_tx_post_update_fifo_wakeup_request        (0xf5e)
#define image_4_start_task_dhd_tx_post_wakeup_request        (0xf74)
#define image_4_start_task_initialization_task        (0x2)
#define image_4_start_task_processing_wakeup_request        (0x11)
#define image_4_tcam_cmd_dst_ip        (0xaa8)
#define image_4_tcam_cmd_dst_ipv6_masked        (0xabf)
#define image_4_tcam_cmd_dst_mac        (0xae5)
#define image_4_tcam_cmd_dst_port        (0xad4)
#define image_4_tcam_cmd_ethertype        (0xa2b)
#define image_4_tcam_cmd_gem_flow        (0xa6f)
#define image_4_tcam_cmd_generic_l2        (0xaf0)
#define image_4_tcam_cmd_generic_l3        (0xafd)
#define image_4_tcam_cmd_generic_l4        (0xb0c)
#define image_4_tcam_cmd_ic_submit        (0xa0e)
#define image_4_tcam_cmd_ingress_port        (0xa69)
#define image_4_tcam_cmd_inner_pbit        (0xa43)
#define image_4_tcam_cmd_inner_tpid        (0xa25)
#define image_4_tcam_cmd_inner_vid        (0xa37)
#define image_4_tcam_cmd_ip_protocol        (0xa4f)
#define image_4_tcam_cmd_ipv6_label        (0xa75)
#define image_4_tcam_cmd_l3_protocol        (0xa55)
#define image_4_tcam_cmd_network_layer        (0xa61)
#define image_4_tcam_cmd_outer_pbit        (0xa3d)
#define image_4_tcam_cmd_outer_tpid        (0xa1f)
#define image_4_tcam_cmd_outer_vid        (0xa31)
#define image_4_tcam_cmd_src_ip        (0xa82)
#define image_4_tcam_cmd_src_ipv6_masked        (0xa99)
#define image_4_tcam_cmd_src_mac        (0xada)
#define image_4_tcam_cmd_src_port        (0xace)
#define image_4_tcam_cmd_tos        (0xa5b)
#define image_4_tcam_cmd_vlan_num        (0xa49)

#endif


#endif

/* IMAGE 5 LABELS */
#ifndef IMAGE_5_CODE_ADDRESSES
#define IMAGE_5_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_5_action_exception        (0x22bc)
#define image_5_action_gpe        (0x22a8)
#define image_5_debug_routine        (0x3168)
#define image_5_debug_routine_handler        (0x4)
#define image_5_dhd_rx_complete_wakeup_request        (0x3660)
#define image_5_dhd_tx_complete_wakeup_request        (0x3314)
#define image_5_gpe_apply_icsum_16        (0x26dc)
#define image_5_gpe_apply_icsum_nz_16        (0x2700)
#define image_5_gpe_buffer_copy_16_ddr        (0x27b4)
#define image_5_gpe_buffer_copy_16_sram        (0x2788)
#define image_5_gpe_compute_csum_16_cl        (0x273c)
#define image_5_gpe_compute_csum_16_sram        (0x2748)
#define image_5_gpe_copy_add_16_cl        (0x2568)
#define image_5_gpe_copy_add_16_sram        (0x2574)
#define image_5_gpe_copy_bits_16_cl        (0x25bc)
#define image_5_gpe_copy_bits_16_sram        (0x25c8)
#define image_5_gpe_decrement_8        (0x26b8)
#define image_5_gpe_delete_16        (0x2678)
#define image_5_gpe_insert_16        (0x2610)
#define image_5_gpe_replace_16        (0x24e4)
#define image_5_gpe_replace_32        (0x2518)
#define image_5_gpe_replace_add_packet_length_cl        (0x27e4)
#define image_5_gpe_replace_bits_16        (0x253c)
#define image_5_gpe_replace_pointer_32_sram        (0x249c)
#define image_5_gpe_replace_pointer_64_sram        (0x24c0)
#define image_5_gpe_sop_pull_replace_ddr_sram_32        (0x237c)
#define image_5_gpe_sop_pull_replace_sram_32_64        (0x23c0)
#define image_5_gpe_sop_pull_replace_sram_64        (0x2410)
#define image_5_gpe_sop_pull_replace_sram_64_32        (0x244c)
#define image_5_gpe_sop_push_replace_ddr_sram_32        (0x22fc)
#define image_5_gpe_sop_push_replace_sram_32_64        (0x2340)
#define image_5_gpe_sop_push_replace_sram_64        (0x2354)
#define image_5_gpe_sop_push_replace_sram_64_32        (0x2368)
#define image_5_initialization_task        (0x8)
#define image_5_processing_check_wlan_llcsnap        (0x948)
#define image_5_processing_done        (0xaec)
#define image_5_processing_wakeup_request        (0x44)
#define image_5_start_task_debug_routine        (0x3168)
#define image_5_start_task_dhd_rx_complete_wakeup_request        (0x3660)
#define image_5_start_task_dhd_tx_complete_wakeup_request        (0x3314)
#define image_5_start_task_initialization_task        (0x8)
#define image_5_start_task_processing_wakeup_request        (0x44)
#define image_5_tcam_cmd_dst_ip        (0x2aa0)
#define image_5_tcam_cmd_dst_ipv6_masked        (0x2afc)
#define image_5_tcam_cmd_dst_mac        (0x2b94)
#define image_5_tcam_cmd_dst_port        (0x2b50)
#define image_5_tcam_cmd_ethertype        (0x28ac)
#define image_5_tcam_cmd_gem_flow        (0x29bc)
#define image_5_tcam_cmd_generic_l2        (0x2bc0)
#define image_5_tcam_cmd_generic_l3        (0x2bf4)
#define image_5_tcam_cmd_generic_l4        (0x2c30)
#define image_5_tcam_cmd_ic_submit        (0x2838)
#define image_5_tcam_cmd_ingress_port        (0x29a4)
#define image_5_tcam_cmd_inner_pbit        (0x290c)
#define image_5_tcam_cmd_inner_tpid        (0x2894)
#define image_5_tcam_cmd_inner_vid        (0x28dc)
#define image_5_tcam_cmd_ip_protocol        (0x293c)
#define image_5_tcam_cmd_ipv6_label        (0x29d4)
#define image_5_tcam_cmd_l3_protocol        (0x2954)
#define image_5_tcam_cmd_network_layer        (0x2984)
#define image_5_tcam_cmd_outer_pbit        (0x28f4)
#define image_5_tcam_cmd_outer_tpid        (0x287c)
#define image_5_tcam_cmd_outer_vid        (0x28c4)
#define image_5_tcam_cmd_src_ip        (0x2a08)
#define image_5_tcam_cmd_src_ipv6_masked        (0x2a64)
#define image_5_tcam_cmd_src_mac        (0x2b68)
#define image_5_tcam_cmd_src_port        (0x2b38)
#define image_5_tcam_cmd_tos        (0x296c)
#define image_5_tcam_cmd_vlan_num        (0x2924)

#else

#define image_5_action_exception        (0x8af)
#define image_5_action_gpe        (0x8aa)
#define image_5_debug_routine        (0xc5a)
#define image_5_debug_routine_handler        (0x1)
#define image_5_dhd_rx_complete_wakeup_request        (0xd98)
#define image_5_dhd_tx_complete_wakeup_request        (0xcc5)
#define image_5_gpe_apply_icsum_16        (0x9b7)
#define image_5_gpe_apply_icsum_nz_16        (0x9c0)
#define image_5_gpe_buffer_copy_16_ddr        (0x9ed)
#define image_5_gpe_buffer_copy_16_sram        (0x9e2)
#define image_5_gpe_compute_csum_16_cl        (0x9cf)
#define image_5_gpe_compute_csum_16_sram        (0x9d2)
#define image_5_gpe_copy_add_16_cl        (0x95a)
#define image_5_gpe_copy_add_16_sram        (0x95d)
#define image_5_gpe_copy_bits_16_cl        (0x96f)
#define image_5_gpe_copy_bits_16_sram        (0x972)
#define image_5_gpe_decrement_8        (0x9ae)
#define image_5_gpe_delete_16        (0x99e)
#define image_5_gpe_insert_16        (0x984)
#define image_5_gpe_replace_16        (0x939)
#define image_5_gpe_replace_32        (0x946)
#define image_5_gpe_replace_add_packet_length_cl        (0x9f9)
#define image_5_gpe_replace_bits_16        (0x94f)
#define image_5_gpe_replace_pointer_32_sram        (0x927)
#define image_5_gpe_replace_pointer_64_sram        (0x930)
#define image_5_gpe_sop_pull_replace_ddr_sram_32        (0x8df)
#define image_5_gpe_sop_pull_replace_sram_32_64        (0x8f0)
#define image_5_gpe_sop_pull_replace_sram_64        (0x904)
#define image_5_gpe_sop_pull_replace_sram_64_32        (0x913)
#define image_5_gpe_sop_push_replace_ddr_sram_32        (0x8bf)
#define image_5_gpe_sop_push_replace_sram_32_64        (0x8d0)
#define image_5_gpe_sop_push_replace_sram_64        (0x8d5)
#define image_5_gpe_sop_push_replace_sram_64_32        (0x8da)
#define image_5_initialization_task        (0x2)
#define image_5_processing_check_wlan_llcsnap        (0x252)
#define image_5_processing_done        (0x2bb)
#define image_5_processing_wakeup_request        (0x11)
#define image_5_start_task_debug_routine        (0xc5a)
#define image_5_start_task_dhd_rx_complete_wakeup_request        (0xd98)
#define image_5_start_task_dhd_tx_complete_wakeup_request        (0xcc5)
#define image_5_start_task_initialization_task        (0x2)
#define image_5_start_task_processing_wakeup_request        (0x11)
#define image_5_tcam_cmd_dst_ip        (0xaa8)
#define image_5_tcam_cmd_dst_ipv6_masked        (0xabf)
#define image_5_tcam_cmd_dst_mac        (0xae5)
#define image_5_tcam_cmd_dst_port        (0xad4)
#define image_5_tcam_cmd_ethertype        (0xa2b)
#define image_5_tcam_cmd_gem_flow        (0xa6f)
#define image_5_tcam_cmd_generic_l2        (0xaf0)
#define image_5_tcam_cmd_generic_l3        (0xafd)
#define image_5_tcam_cmd_generic_l4        (0xb0c)
#define image_5_tcam_cmd_ic_submit        (0xa0e)
#define image_5_tcam_cmd_ingress_port        (0xa69)
#define image_5_tcam_cmd_inner_pbit        (0xa43)
#define image_5_tcam_cmd_inner_tpid        (0xa25)
#define image_5_tcam_cmd_inner_vid        (0xa37)
#define image_5_tcam_cmd_ip_protocol        (0xa4f)
#define image_5_tcam_cmd_ipv6_label        (0xa75)
#define image_5_tcam_cmd_l3_protocol        (0xa55)
#define image_5_tcam_cmd_network_layer        (0xa61)
#define image_5_tcam_cmd_outer_pbit        (0xa3d)
#define image_5_tcam_cmd_outer_tpid        (0xa1f)
#define image_5_tcam_cmd_outer_vid        (0xa31)
#define image_5_tcam_cmd_src_ip        (0xa82)
#define image_5_tcam_cmd_src_ipv6_masked        (0xa99)
#define image_5_tcam_cmd_src_mac        (0xada)
#define image_5_tcam_cmd_src_port        (0xace)
#define image_5_tcam_cmd_tos        (0xa5b)
#define image_5_tcam_cmd_vlan_num        (0xa49)

#endif


#endif

/* COMMON LABELS */
#ifndef COMMON_CODE_ADDRESSES
#define COMMON_CODE_ADDRESSES

#define INVALID_LABEL_ADDRESS 0xFFFFFF

#ifndef PC_ADDRESS_INST_IND

#define TCAM_CMD_DST_IP_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2aa0, 0x2bac, INVALID_LABEL_ADDRESS, 0x2aa0, 0x2aa0}
#define TCAM_CMD_DST_IPV6_MASKED_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2afc, 0x2c08, INVALID_LABEL_ADDRESS, 0x2afc, 0x2afc}
#define TCAM_CMD_DST_MAC_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2b94, 0x2ca0, INVALID_LABEL_ADDRESS, 0x2b94, 0x2b94}
#define TCAM_CMD_DST_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2b50, 0x2c5c, INVALID_LABEL_ADDRESS, 0x2b50, 0x2b50}
#define TCAM_CMD_ETHERTYPE_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x28ac, 0x29b8, INVALID_LABEL_ADDRESS, 0x28ac, 0x28ac}
#define TCAM_CMD_GEM_FLOW_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x29bc, 0x2ac8, INVALID_LABEL_ADDRESS, 0x29bc, 0x29bc}
#define TCAM_CMD_GENERIC_L2_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2bc0, 0x2ccc, INVALID_LABEL_ADDRESS, 0x2bc0, 0x2bc0}
#define TCAM_CMD_GENERIC_L3_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2bf4, 0x2d00, INVALID_LABEL_ADDRESS, 0x2bf4, 0x2bf4}
#define TCAM_CMD_GENERIC_L4_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2c30, 0x2d3c, INVALID_LABEL_ADDRESS, 0x2c30, 0x2c30}
#define TCAM_CMD_IC_SUBMIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2838, 0x2944, INVALID_LABEL_ADDRESS, 0x2838, 0x2838}
#define TCAM_CMD_INGRESS_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x29a4, 0x2ab0, INVALID_LABEL_ADDRESS, 0x29a4, 0x29a4}
#define TCAM_CMD_INNER_PBIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x290c, 0x2a18, INVALID_LABEL_ADDRESS, 0x290c, 0x290c}
#define TCAM_CMD_INNER_TPID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2894, 0x29a0, INVALID_LABEL_ADDRESS, 0x2894, 0x2894}
#define TCAM_CMD_INNER_VID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x28dc, 0x29e8, INVALID_LABEL_ADDRESS, 0x28dc, 0x28dc}
#define TCAM_CMD_IP_PROTOCOL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x293c, 0x2a48, INVALID_LABEL_ADDRESS, 0x293c, 0x293c}
#define TCAM_CMD_IPV6_LABEL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x29d4, 0x2ae0, INVALID_LABEL_ADDRESS, 0x29d4, 0x29d4}
#define TCAM_CMD_L3_PROTOCOL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2954, 0x2a60, INVALID_LABEL_ADDRESS, 0x2954, 0x2954}
#define TCAM_CMD_NETWORK_LAYER_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2984, 0x2a90, INVALID_LABEL_ADDRESS, 0x2984, 0x2984}
#define TCAM_CMD_OUTER_PBIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x28f4, 0x2a00, INVALID_LABEL_ADDRESS, 0x28f4, 0x28f4}
#define TCAM_CMD_OUTER_TPID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x287c, 0x2988, INVALID_LABEL_ADDRESS, 0x287c, 0x287c}
#define TCAM_CMD_OUTER_VID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x28c4, 0x29d0, INVALID_LABEL_ADDRESS, 0x28c4, 0x28c4}
#define TCAM_CMD_SRC_IP_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2a08, 0x2b14, INVALID_LABEL_ADDRESS, 0x2a08, 0x2a08}
#define TCAM_CMD_SRC_IPV6_MASKED_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2a64, 0x2b70, INVALID_LABEL_ADDRESS, 0x2a64, 0x2a64}
#define TCAM_CMD_SRC_MAC_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2b68, 0x2c74, INVALID_LABEL_ADDRESS, 0x2b68, 0x2b68}
#define TCAM_CMD_SRC_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2b38, 0x2c44, INVALID_LABEL_ADDRESS, 0x2b38, 0x2b38}
#define TCAM_CMD_TOS_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x296c, 0x2a78, INVALID_LABEL_ADDRESS, 0x296c, 0x296c}
#define TCAM_CMD_VLAN_NUM_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2924, 0x2a30, INVALID_LABEL_ADDRESS, 0x2924, 0x2924}

#else

#define TCAM_CMD_DST_IP_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xaa8, 0xaeb, INVALID_LABEL_ADDRESS, 0xaa8, 0xaa8}
#define TCAM_CMD_DST_IPV6_MASKED_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xabf, 0xb02, INVALID_LABEL_ADDRESS, 0xabf, 0xabf}
#define TCAM_CMD_DST_MAC_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xae5, 0xb28, INVALID_LABEL_ADDRESS, 0xae5, 0xae5}
#define TCAM_CMD_DST_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xad4, 0xb17, INVALID_LABEL_ADDRESS, 0xad4, 0xad4}
#define TCAM_CMD_ETHERTYPE_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa2b, 0xa6e, INVALID_LABEL_ADDRESS, 0xa2b, 0xa2b}
#define TCAM_CMD_GEM_FLOW_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa6f, 0xab2, INVALID_LABEL_ADDRESS, 0xa6f, 0xa6f}
#define TCAM_CMD_GENERIC_L2_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xaf0, 0xb33, INVALID_LABEL_ADDRESS, 0xaf0, 0xaf0}
#define TCAM_CMD_GENERIC_L3_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xafd, 0xb40, INVALID_LABEL_ADDRESS, 0xafd, 0xafd}
#define TCAM_CMD_GENERIC_L4_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb0c, 0xb4f, INVALID_LABEL_ADDRESS, 0xb0c, 0xb0c}
#define TCAM_CMD_IC_SUBMIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa0e, 0xa51, INVALID_LABEL_ADDRESS, 0xa0e, 0xa0e}
#define TCAM_CMD_INGRESS_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa69, 0xaac, INVALID_LABEL_ADDRESS, 0xa69, 0xa69}
#define TCAM_CMD_INNER_PBIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa43, 0xa86, INVALID_LABEL_ADDRESS, 0xa43, 0xa43}
#define TCAM_CMD_INNER_TPID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa25, 0xa68, INVALID_LABEL_ADDRESS, 0xa25, 0xa25}
#define TCAM_CMD_INNER_VID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa37, 0xa7a, INVALID_LABEL_ADDRESS, 0xa37, 0xa37}
#define TCAM_CMD_IP_PROTOCOL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa4f, 0xa92, INVALID_LABEL_ADDRESS, 0xa4f, 0xa4f}
#define TCAM_CMD_IPV6_LABEL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa75, 0xab8, INVALID_LABEL_ADDRESS, 0xa75, 0xa75}
#define TCAM_CMD_L3_PROTOCOL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa55, 0xa98, INVALID_LABEL_ADDRESS, 0xa55, 0xa55}
#define TCAM_CMD_NETWORK_LAYER_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa61, 0xaa4, INVALID_LABEL_ADDRESS, 0xa61, 0xa61}
#define TCAM_CMD_OUTER_PBIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa3d, 0xa80, INVALID_LABEL_ADDRESS, 0xa3d, 0xa3d}
#define TCAM_CMD_OUTER_TPID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa1f, 0xa62, INVALID_LABEL_ADDRESS, 0xa1f, 0xa1f}
#define TCAM_CMD_OUTER_VID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa31, 0xa74, INVALID_LABEL_ADDRESS, 0xa31, 0xa31}
#define TCAM_CMD_SRC_IP_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa82, 0xac5, INVALID_LABEL_ADDRESS, 0xa82, 0xa82}
#define TCAM_CMD_SRC_IPV6_MASKED_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa99, 0xadc, INVALID_LABEL_ADDRESS, 0xa99, 0xa99}
#define TCAM_CMD_SRC_MAC_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xada, 0xb1d, INVALID_LABEL_ADDRESS, 0xada, 0xada}
#define TCAM_CMD_SRC_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xace, 0xb11, INVALID_LABEL_ADDRESS, 0xace, 0xace}
#define TCAM_CMD_TOS_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa5b, 0xa9e, INVALID_LABEL_ADDRESS, 0xa5b, 0xa5b}
#define TCAM_CMD_VLAN_NUM_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa49, 0xa8c, INVALID_LABEL_ADDRESS, 0xa49, 0xa49}

#endif


#endif

