#
# Menlosystems M53Menlo
# Copyright (C) 2012-2017 Marek Vasut <marex@denx.de>
# Copyright (C) 2014-2017 Olaf Mandel <o.mandel@menlosystems.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= m53menlo.o
