# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2012-2013, Guennadi Liakhovetski <lg@denx.de>
# (C) Copyright 2012-2013 Freescale Semiconductor, Inc.
# Copyright (C) 2013, Boundary Devices <info@boundarydevices.com>

ifdef CONFIG_SPL_BUILD
obj-y  := ot1200.o ot1200_spl.o
else
obj-y  := ot1200.o
endif
