# SPDX-License-Identifier: GPL-2.0+
#
# Makefile
#
# Copyright (C) 2014 Hannes Schmelzer <oe5hpm@oevsv.at> -
# Bernecker & Rainer Industrielektronik GmbH - http://www.br-automation.com/

obj-$(CONFIG_SPL_BUILD) += mux.o
obj-y	+= ../common/br_resetc.o
obj-y	+= ../common/common.o
obj-y	+= board.o
