# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2013-2015, Freescale Semiconductor, Inc.

obj-y   := clock.o
obj-y   += lpddr2.o
obj-y   += s32v234evb.o

#########################################################################
