# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2008 Extreme Engineering Solutions, Inc.
# Copyright 2004 Freescale Semiconductor.
# (C) Copyright 2001-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-y	+= xpedite520x.o
obj-y	+= ddr.o
obj-y	+= law.o
obj-y	+= tlb.o
