# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-y	+= lowlevel_init.o
obj-y	+= reset.o
obj-y	+= timer.o
obj-y	+= clock.o
obj-y	+= cpu.o
obj-y	+= at91rm9200_devices.o
