# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_SPL_BUILD) += ddr3_dfs.o
obj-$(CONFIG_SPL_BUILD) += ddr3_dqs.o
obj-$(CONFIG_SPL_BUILD) += ddr3_hw_training.o
obj-$(CONFIG_SPL_BUILD) += ddr3_init.o
obj-$(CONFIG_SPL_BUILD) += ddr3_pbs.o
obj-$(CONFIG_SPL_BUILD) += ddr3_read_leveling.o
obj-$(CONFIG_SPL_BUILD) += ddr3_sdram.o
obj-$(CONFIG_SPL_BUILD) += ddr3_spd.o
obj-$(CONFIG_SPL_BUILD) += ddr3_write_leveling.o
obj-$(CONFIG_SPL_BUILD) += xor.o
