;-------------------------------
; GDM configuration file
;-------------------------------
;
; This is a sample configuration file for GDM.
;

;
; Global settings
;
pid_file=/tmp/gar/gdm.pid
mqtt_url=mqtt://127.0.0.1:3881
wan=eth1
data_expire=1800

;
; SQLite database settings
;
[database]
file_path=/tmp/ark/gdm.db
cache_size=10
max_page_count=1000
page_size=1024
max_length=10240

[log]
enable = false
file = /tmp/log/gdm.log
level = 6
size = 1024                     ; KB
rotate = 3                      ; default 3 files
