# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2011
# Stefan Herbrechtsmeier <stefan@herbrechtsmeier.net>
#
# Based on Kirkwood support:
# (C) Copyright 2009
# Marvell Semiconductor <www.marvell.com>
# Written-by: Prafulla Wadaskar <prafulla@marvell.com>

obj-y	:= dns325.o
