# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2010
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-y	+= boot.o
obj-y	+= sdram_elpida.o
obj-y	+= hwinit.o
obj-y	+= emif.o
obj-y	+= prcm-regs.o
obj-y	+= hw_data.o
