obj-$(CONFIG_BCMBCA_OTP) += bcm_otp.o
obj-$(CONFIG_BCMBCA_OTP) += otp_map_cmn.o
obj-$(CONFIG_BCMBCA_OTP) += otp_hw.o
obj-$(CONFIG_OTP_SOTP) += sotp_hw.o
obj-$(CONFIG_OTP_LOCK) += otp_hw_cpu_lock.o
obj-$(CONFIG_OTP_V2) += otp_hw_ecc.o
obj-$(CONFIG_OTP_SKP) += skp_hw.o
obj-$(CONFIG_OTP_SKO) += sko_hw.o
