# SPDX-License-Identifier: GPL-2.0+
#
# Makefile for siemens CORVUS (AT91SAM9G45) based board
# (C) Copyright 2013 Siemens AG
#
# Based on:
# U-Boot file: board/atmel/at91sam9m10g45ek/Makefile
#
# (C) Copyright 2003-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008
# Stelian Pop <stelian@popies.net>
# Lead Tech Design <www.leadtechdesign.com>

obj-y += board.o
