#! /bin/sh

APPS_MOUNTED_PATH=`tcapi get Apps_Entry apps_mounted_path`
APPS_INSTALL_FOLDER=`tcapi get Apps_Entry apps_install_folder`
APPS_INSTALL_PATH=$APPS_MOUNTED_PATH/$APPS_INSTALL_FOLDER

mv -f /opt/tmp/bin/* $APPS_INSTALL_PATH/bin/
chmod -R 777 $APPS_INSTALL_PATH/bin










