/*
 * rdpa user ioctl define header file.
 * This header file is generated automatically. Do not edit!
 */
#ifndef _RDPA_SYSTEM_USER_IOCTL_H_
#define _RDPA_SYSTEM_USER_IOCTL_H_

enum
{
	RDPA_SYSTEM_DRV,
	RDPA_SYSTEM_GET,
	RDPA_SYSTEM_INIT_CFG_GET,
	RDPA_SYSTEM_INIT_CFG_SET,
	RDPA_SYSTEM_CFG_GET,
	RDPA_SYSTEM_CFG_SET,
	RDPA_SYSTEM_SW_VERSION_GET,
	RDPA_SYSTEM_CLOCK_GATE_GET,
	RDPA_SYSTEM_CLOCK_GATE_SET,
	RDPA_SYSTEM_DROP_PRECEDENCE_GET,
	RDPA_SYSTEM_DROP_PRECEDENCE_SET,
	RDPA_SYSTEM_DROP_PRECEDENCE_GET_NEXT,
	RDPA_SYSTEM_TPID_DETECT_GET,
	RDPA_SYSTEM_TPID_DETECT_SET,
	RDPA_SYSTEM_TOD_GET,
	RDPA_SYSTEM_CPU_REASON_TO_TC_GET,
	RDPA_SYSTEM_CPU_REASON_TO_TC_SET,
	RDPA_SYSTEM_IPV4_HOST_ADDRESS_TABLE_GET,
	RDPA_SYSTEM_IPV4_HOST_ADDRESS_TABLE_ADD,
	RDPA_SYSTEM_IPV4_HOST_ADDRESS_TABLE_DELETE,
	RDPA_SYSTEM_IPV4_HOST_ADDRESS_TABLE_FIND,
	RDPA_SYSTEM_IPV6_HOST_ADDRESS_TABLE_GET,
	RDPA_SYSTEM_IPV6_HOST_ADDRESS_TABLE_ADD,
	RDPA_SYSTEM_IPV6_HOST_ADDRESS_TABLE_DELETE,
	RDPA_SYSTEM_IPV6_HOST_ADDRESS_TABLE_FIND,
	RDPA_SYSTEM_QM_CFG_GET,
	RDPA_SYSTEM_QM_CFG_SET,
	RDPA_SYSTEM_PACKET_BUFFER_CFG_GET,
	RDPA_SYSTEM_PACKET_BUFFER_CFG_SET,
	RDPA_SYSTEM_HIGH_PRIO_TC_THRESHOLD_GET,
	RDPA_SYSTEM_HIGH_PRIO_TC_THRESHOLD_SET,
	RDPA_SYSTEM_COUNTER_CFG_GET,
	RDPA_SYSTEM_COUNTER_CFG_SET,
	RDPA_SYSTEM_SYSTEM_RESOURCES_GET,
};

#endif /* _RDPA_SYSTEM_USER_IOCTL_H_ */
