/*
 * rdpa user ioctl define header file.
 * This header file is generated automatically. Do not edit!
 */
#ifndef _RDPA_EGRESS_TM_USER_IOCTL_H_
#define _RDPA_EGRESS_TM_USER_IOCTL_H_

enum
{
	RDPA_EGRESS_TM_DRV,
	RDPA_EGRESS_TM_GET,
	RDPA_EGRESS_TM_DIR_GET,
	RDPA_EGRESS_TM_DIR_SET,
	RDPA_EGRESS_TM_INDEX_GET,
	RDPA_EGRESS_TM_INDEX_SET,
	RDPA_EGRESS_TM_LEVEL_GET,
	RDPA_EGRESS_TM_LEVEL_SET,
	RDPA_EGRESS_TM_MODE_GET,
	RDPA_EGRESS_TM_MODE_SET,
	RDPA_EGRESS_TM_OVERALL_RL_GET,
	RDPA_EGRESS_TM_OVERALL_RL_SET,
	RDPA_EGRESS_TM_SERVICE_QUEUE_GET,
	RDPA_EGRESS_TM_SERVICE_QUEUE_SET,
	RDPA_EGRESS_TM_RL_GET,
	RDPA_EGRESS_TM_RL_SET,
	RDPA_EGRESS_TM_RL_RATE_MODE_GET,
	RDPA_EGRESS_TM_RL_RATE_MODE_SET,
	RDPA_EGRESS_TM_NUM_QUEUES_GET,
	RDPA_EGRESS_TM_NUM_QUEUES_SET,
	RDPA_EGRESS_TM_NUM_SP_ELEMENTS_GET,
	RDPA_EGRESS_TM_NUM_SP_ELEMENTS_SET,
	RDPA_EGRESS_TM_QUEUE_CFG_GET,
	RDPA_EGRESS_TM_QUEUE_CFG_SET,
	RDPA_EGRESS_TM_QUEUE_CFG_DELETE,
	RDPA_EGRESS_TM_QUEUE_STATISTICS_GET,
	RDPA_EGRESS_TM_QUEUE_STATISTICS_GET_NEXT,
	RDPA_EGRESS_TM_QUEUE_STAT_GET,
	RDPA_EGRESS_TM_QUEUE_STAT_SET,
	RDPA_EGRESS_TM_QUEUE_STAT_GET_NEXT,
	RDPA_EGRESS_TM_QUEUE_OCCUPANCY_GET,
	RDPA_EGRESS_TM_QUEUE_OCCUPANCY_GET_NEXT,
	RDPA_EGRESS_TM_SUBSIDIARY_GET,
	RDPA_EGRESS_TM_SUBSIDIARY_SET,
	RDPA_EGRESS_TM_SUBSIDIARY_FIND,
	RDPA_EGRESS_TM_WEIGHT_GET,
	RDPA_EGRESS_TM_WEIGHT_SET,
	RDPA_EGRESS_TM_QUEUE_LOCATION_GET,
};

#endif /* _RDPA_EGRESS_TM_USER_IOCTL_H_ */
