.TH ASEQDUMP 1 "19 Feb 2005"

.SH NAME
aseqdump \- show the events received at an ALSA sequencer port

.SH SYNOPSIS
.B aseqdump
[\fI\-p client:port,...\fP]

.SH DESCRIPTION
.B aseqdump
is a command-line utility that prints the sequencer events it receives as text.

To stop receiving, press Ctrl+C.

.SH OPTIONS

.TP
.I \-h,\-\-help
Prints a list of options.

.TP
.I \-V,\-\-version
Prints the current version.

.TP
.I \-l,\-\-list
Prints a list of possible input ports.

.TP
.I \-p,\-\-port=client:port,...
Sets the sequencer port(s) from which events are received.

A client can be specified by its number, its name, or a prefix of its
name.  A port is specified by its number; for port 0 of a client, the
":0" part of the port specification can be omitted.

.SH AUTHOR
Clemens Ladisch <clemens@ladisch.de>
