.TH "CAPNG_CLEAR" "3" "Sept 2020" "Red Hat" "Libcap-ng API"
.SH NAME
capng_clear \- clear chosen capabilities set
.SH "SYNOPSIS"
.B #include <cap-ng.h>
.sp
void capng_clear(capng_select_t set);

.SH "DESCRIPTION"

capng_clear sets to 0 all bits in the selected posix capabilities set. The options are CAPNG_SELECT_CAPS for the traditional capabilities, CAPNG_SELECT_BOUNDS for the bounding set, CAPNG_SELECT_BOTH if clearing both is desired, CAPNG_SELECT_AMBIENT if only operating on the ambient capabilities, or CAPNG_SELECT_ALL if clearing all is desired.

.SH "RETURN VALUE"

None.

.SH "SEE ALSO"

.BR capabilities (7) 

.SH AUTHOR
Steve Grubb
