function reorder
{
	(( x[1] < x && (x=x[1], x[1]=$x) ))
	echo "${x[@]}"
}

x=(123 456)
reorder
x=(456 123)
reorder

unset x
unset -f reorder

function reorder
{
	(( x[1] < x[0] && (x=x[1], x[1]=$x) ))
	echo "${x[@]}"
}

x=(123 456)
reorder
x=(456 123)
reorder

unset x
unset -f reorder

function reorder
{
	(( x[1] < x[0] && (x[0]=x[1], x[1]=$x) ))
	echo "${x[@]}"
}

x=(123 456)
reorder
x=(456 123)
reorder

unset -f reorder

n=0 ; (( (a[n]=++n)<7&&a[0])); echo "${a[@]:1}"

n=0 a="(a[n]=++n)<7&&a[0]"; ((a[0])); echo "${a[@]:1}"

n=0 a="(a[n]=n++)<7&&a"; ((a)); echo "${a[@]:1}"

# bugs with lvalue caching and pointer aliasing through bash-4.2
echo $(( a=(y[0] + y[1]) & 0xff, b=(y[2] + y[3]) & 0xff, a << 8 | b))
echo $a, $b
((a = y[0], b = 1 ))
echo $a, $b
