# problems with fix for posix interp 217 introduced in bash-4.2

declare -ax array
array[$(( $( echo -n 1001 ) - 1001 ))]=1 

echo ${array[0]}
echo ${array[@]}

unset 'array[0]'
array[$( echo -n 1001 ) - 1001 ]=1 
echo ${array[0]}

unset 'array[0]'
array[$(( 1001 - $( echo -n 1001 ) ))]=1 
echo ${array[0]}
array[$(( 1001 - $( echo -n 1001 ) ))]=1 
echo ${array[0]}

unset 'array[0]'
array[1001 - $( echo -n 1001 )]=1 
echo ${array[0]}
