# problems with associative array keys with ] and unbalanced [ ]
# fixed after bash-4.2

declare -A foo

foo=(["version[agent]"]=version.agent)

echo ${!foo[@]}
echo ${foo[@]}

unset foo
declare -A foo
foo["version[agent]"]=version.agent

echo ${!foo[@]}
echo ${foo[@]}

declare foo["foo[bar]"]=bowl

echo ${!foo[@]}
echo ${foo[@]}

declare -A array2["foo[bar]"]=bleh

array2["foobar]"]=bleh
array2["foo"]=bbb

echo ${!array2[@]}
echo ${array2[@]}

declare -A foo
foo=( ['ab]']=bar )

echo ${!foo[@]}
echo ${foo[@]}
