# problem with bash-4.x versions before bash-4.2.  required posix interp
swap32_posix()
{
        local funcname=swap32_posix
        local arg
        for arg in "$@"; do
                echo $((
                        ($arg & 4278190080) >> 24 |
                        ($arg & 16711680) >> 8 |
                        ($arg & 65280) << 8 |
                        ($arg & 255) << 24
                ))
        done
}

type swap32_posix
