recho """"a
recho a""""

recho """"

recho """"b
recho b""""

recho """"""c
recho c""""""

recho """"""c""""
recho """"c""""""

recho """"""""c
recho c""""""""

# BASH BUG: spurious DEL characters appear on empty variable interpolation.
# BASH 4.2.8(1)-release

a=''

recho correct "$a" # correct empty output line
recho correct "$a""$a" # correct empty output line
recho correct "$a""$a""$a" # correct empty output line
recho XwrongX "$a""$a""$a""$a" # spurious two DEL chars appear at line end
recho correct a"$a" # correct single "a" on line
recho XwrongX a"$a""$a" # spurious DEL char appears at line end
recho correct a"$a$a" # correct single "a" on line
recho correct a"$a$a$a$a" # correct single "a" on line
