var=$'x\001y\177z'

recho "$var"
recho $var

declare -p var
recho $(declare -p var)

declare -p var | sed -n l

recho ${var@Q}
recho ${var@P}
echo ${var@A}

unset array
array=( [$'x\001y\177z']=foo )	# should be error
echo ${array[@]@A}

unset array
declare -a array=([0]=$'x\001y\177z')
declare -p array

unset array
array=( "$var" )
recho ${array[@]}
echo ${array[@]@A}

unset array
declare -A array
array=( [$'x\001y\177z']=$'a\242b\002c' )
echo ${array[@]@A}
