#
# Test that redirections attached to shell functions are printed correctly.
# This was a bug in all bash versions before bash-2.04.
#
f()
{
	echo f-x
	echo f-y
} >&2

type f
export -f f
${THIS_SH} -c 'echo subshell; type f'

f2()
{
	echo f2-a
	f3()
	{
		echo f3-a
		echo f3-b
	} >&2
	f3
}

type f2

export -f f2
${THIS_SH} -c 'echo subshell; type f2'

f4()
{
	echo f4-a
	f5()
	{
		echo f5-a
		echo f5-b
	} >&2
	f5
} 2>&1

type f4
export -f f4
${THIS_SH} -c 'echo subshell; type f4'

testgrp()
{
	echo testgrp-a
	{ echo tg-x; echo tg-y; } >&2
	echo testgrp-b
}
type testgrp

export -f testgrp
${THIS_SH} -c 'echo subshell; type testgrp'
