# Problems with variables that expand to 0x7f and quoted nulls in the same
# expansion -- affects bash versions 4.0-post 4.2
a=x
b=
del=$'\x7f'

set ""

recho ${undef-"x$*y"}
recho "x$*y"
recho x"$*"y
recho x"$del"y

recho ${undef-"$@"}
recho "$@"
recho "${@}"
recho ${undef-"$*"}
recho "$*"
recho "${*}"

recho "$del${a#x}"
recho "$del ${a#x}"
recho " $del${a#x}"

recho " $del$b"
recho " $del${b}"
recho " $del${b#x}"
recho " $del${a#x}"

recho " $del${a%x}"
recho " $del${a:0:0}"
recho " $del"${a:0:0}
recho " $del""${a:0:0}"
recho " $del${a}"
recho " $del"
recho " ${del}${a:0:0}"
recho " ${del:0:1}${a:0:0}"
recho " ${del:0:1}${a}"
recho "${del:0:1}${a#d}"
recho "${del:0:1}${a#x}"
recho " ${del:0:1} ${a}"
recho "${del:0:1} ${a#d}"
recho "${del:0:1} ${a#x}"
