declare -n ref=XXX[0]
mapfile ref <<< $'1\n2'
declare -p XXX[0]

unset -n ref

declare -n ref=XXX[0]
declare -A ref
ref[foo]=bar
declare -p XXX[0]

unset -n ref
unset XXX

typeset -n ref=XXX[0]
typeset ref=4

typeset -p ref XXX

unset -n ref
unset XXX

declare -n ref=XXX[0]
ref+=([2]=x)
declare -p ref XXX[0]
unset -n ref

declare -n ref=XXX[0]
read -a ref <<< "A B C"
declare -p XXX[0]
unset -n ref

declare -n ref=XXX[0]
unset ref
ref=()
declare -p ref

coproc ref { :; }; declare -p ${!ref}
wait

unset -n ref

declare -n ref=var[123]
unset ref
declare ref=
declare -p ref ${!ref} var

unset ref 
declare ref+=
declare -p ref ${!ref} var

declare +t ref
ref=X
declare -p ref ${!ref} var
