# tests sourcing non-regular files, fixed post-3.2

: ${TMPDIR:=/tmp}

TMPFN=$TMPDIR/foo-$$

rm -f $TMPFN
echo "echo one - OK" > $TMPFN
. $TMPFN
echo $?
rm -f $TMPFN

# non-regular readable file
. /dev/null
echo $?

# FIFO or pipe via /dev/fd
. <(echo "echo two - OK")
echo $?

# pipe
if [ -e /dev/stdin ]; then
echo "echo three - OK" | . /dev/stdin
echo $?
else
# no /dev/stdin, just fake it
echo "three - OK" ; echo 0
fi

# FIFO
mkfifo $TMPDIR/fifo-$$
echo "echo four - OK" > $TMPDIR/fifo-$$ &
sleep 1		# allow the child echo to execute
. $TMPDIR/fifo-$$
echo $?
rm -f $TMPDIR/fifo-$$
