. ./test-glue-functions

export LANG=en_US.UTF-8

printf '%s\n' "$(printf '\uff')" | od -b | _intl_normalize_spaces
printf '%s\n' $'\uff' | od -b | _intl_normalize_spaces

printf '\uff'\\n | od -b | _intl_normalize_spaces
echo $'\uff' | od -b | _intl_normalize_spaces

printf '\uffff'\\n | od -b | _intl_normalize_spaces
echo $'\uffff' | od -b | _intl_normalize_spaces

printf '\Ufffffffe'\\n | od -b | _intl_normalize_spaces
echo $'\Ufffffffe' | od -b | _intl_normalize_spaces

printf '\Uffffffff'\\n | od -b | _intl_normalize_spaces
echo $'\Uffffffff' | od -b | _intl_normalize_spaces

LC_CTYPE=C printf '\uff'\\n | od -b | _intl_normalize_spaces
LC_CTYPE=ru_RU.CP1251 printf '\uff'\\n | od -b | _intl_normalize_spaces
LC_CTYPE=en_US.UTF-8 printf '\uff'\\n | od -b | _intl_normalize_spaces

echo -e '\u0041 \u00a3 \u0152' | od -b | _intl_normalize_spaces
