.TH DEVLINK\-DEV 8 "5 Jan 2021" "iproute2" "Linux"
.SH NAME
vdpa-dev \- vdpa device configuration
.SH SYNOPSIS
.sp
.ad l
.in +8
.ti -8
.B vdpa
.B dev
.RI "[ " OPTIONS " ] "
.RI  " { " COMMAND | " "
.BR help " }"
.sp

.ti -8
.IR OPTIONS " := { "
\fB\-V\fR[\fIersion\fR]
}

.ti -8
.B vdpa dev show
.RI "[ " DEV " ]"

.ti -8
.B vdpa dev help

.ti -8
.B vdpa dev add
.B name
.I NAME
.B mgmtdev
.I MGMTDEV

.ti -8
.B vdpa dev del
.I DEV

.SH "DESCRIPTION"
.SS vdpa dev show - display vdpa device attributes

.PP
.I "DEV"
- specifies the vdpa device to show.
If this argument is omitted all devices are listed.

.in +4
Format is:
.in +2
VDPA_DEVICE_NAME

.SS vdpa dev add - add a new vdpa device.

.TP
.BI name " NAME"
Name of the new vdpa device to add.

.TP
.BI mgmtdev " MGMTDEV"
Name of the management device to use for device addition.

.SS vdpa dev del - Delete the vdpa device.

.PP
.I "DEV"
- specifies the vdpa device to delete.

.SH "EXAMPLES"
.PP
vdpa dev show
.RS 4
Shows the all vdpa devices on the system.
.RE
.PP
vdpa dev show foo
.RS 4
Shows the specified vdpa device.
.RE
.PP
vdpa dev add name foo mgmtdev vdpa_sim_net
.RS 4
Add the vdpa device named foo on the management device vdpa_sim_net.
.RE
.PP
vdpa dev del foo
.RS 4
Delete the vdpa device named foo which was previously created.
.RE

.SH SEE ALSO
.BR vdpa (8),
.BR vdpa-mgmtdev (8),
.br

.SH AUTHOR
Parav Pandit <parav@nvidia.com>
