.TH DEVLINK\-DEV 8 "5 Jan 2021" "iproute2" "Linux"
.SH NAME
vdpa-dev \- vdpa management device view
.SH SYNOPSIS
.sp
.ad l
.in +8
.ti -8
.B vdpa
.B mgmtdev
.RI  " { " COMMAND | " "
.BR help " }"
.sp

.ti -8
.IR OPTIONS " := { "
\fB\-V\fR[\fIersion\fR]
}

.ti -8
.B vdpa mgmtdev show
.RI "[ " MGMTDEV " ]"

.ti -8
.B vdpa mgmtdev help

.SH "DESCRIPTION"
.SS vdpa mgmtdev show - display vdpa management device attributes

.PP
.I "MGMTDEV"
- specifies the vdpa management device to show.
If this argument is omitted all management devices are listed.

.SH "EXAMPLES"
.PP
vdpa mgmtdev show
.RS 4
Shows all the vdpa management devices on the system.
.RE
.PP
vdpa mgmtdev show bar
.RS 4
Shows the specified vdpa management device.
.RE

.SH SEE ALSO
.BR vdpa (8),
.BR vdpa-dev (8),
.br

.SH AUTHOR
Parav Pandit <parav@nvidia.com>
