.TH VDPA 8 "5 Jan 2021" "iproute2" "Linux"
.SH NAME
vdpa \- vdpa management tool
.SH SYNOPSIS
.sp
.ad l
.in +8
.ti -8
.B vdpa
.RI "[ " OPTIONS " ] { " dev | mgmtdev " } { " COMMAND " | "
.BR help " }"
.sp

.SH OPTIONS

.TP
.BR "\-V" , " --Version"
Print the version of the
.B vdpa
utility and exit.

.TP
.BR "\-j" , " --json"
Generate JSON output.

.TP
.BR "\-p" , " --pretty"
When combined with -j generate a pretty JSON output.

.SS
.I OBJECT

.TP
.B dev
- vdpa device.

.TP
.B mgmtdev
- vdpa management device.

.SS
.I COMMAND

Specifies the action to perform on the object.
The set of possible actions depends on the object type.
It is possible to
.B show
(or
.B list
) objects. The
.B help
command is available for all objects. It prints
out a list of available commands and argument syntax conventions.
.sp
If no command is given, some default command is assumed.
Usually it is
.B show
or, if the objects of this class cannot be listed,
.BR "help" .

.SH EXIT STATUS
Exit status is 0 if command was successful or a positive integer upon failure.

.SH SEE ALSO
.BR vdpa-dev (8),
.BR vdpa-mgmtdev (8),
.br

.SH REPORTING BUGS
Report any bugs to the Network Developers mailing list
.B <netdev@vger.kernel.org>
where the development and maintenance is primarily done.
You do not have to be subscribed to the list to send a message there.

.SH AUTHOR
Parav Pandit <parav@nvidia.com>
