# Generated code - generated by:
# /projects/firepath_tools/work/dsargean/arm_modelling/aug_dongle_work/kudu-17.10.204.4/src/dongle/make/wl/drf_log_prof_parser.py -n 0 -t /projects/firepath_tools/work/dsargean/arm_modelling/aug_dongle_work/kudu-17.10.204.4/build/dongle/../.. -f 'components/**/*.c' -l /projects/firepath_tools2_scratch/rkharche/wlan_KUDU_REL_17_10_204_4/artefacts/heuristic_all/drf.log -s /projects/firepath_tools/work/dsargean/arm_modelling/aug_dongle_work/kudu-17.10.204.4/src/dongle/make/wl/drf_structs.txt -b /projects/firepath_tools/work/dsargean/arm_modelling/aug_dongle_work/kudu-17.10.204.4/build/dongle/6715b0-ram/config_pcie_fdap_release
CFILES_PROF_ARCS    += $(addprefix $(SRCBASE)/wl/sys/ , wl_rte.c wlc.c wlc_11h.c \
    wlc_act_frame.c wlc_akm_ie.c wlc_ampdu.c wlc_ampdu_cmn.c wlc_ampdu_rx.c wlc_amsdu.c wlc_ap.c \
    wlc_apps.c wlc_assoc.c wlc_bmac.c wlc_bs_data.c wlc_bsscfg.c wlc_btcx.c wlc_cac.c wlc_cfp.c \
    wlc_csa.c wlc_csimon.c wlc_csrestrict.c wlc_event_utils.c wlc_fbt.c wlc_fifo.c wlc_frag.c \
    wlc_he.c wlc_ht.c wlc_ie_mgmt.c wlc_ie_mgmt_vs.c wlc_l2_filter.c wlc_lq.c wlc_macdbg.c \
    wlc_mbss.c wlc_mfp.c wlc_modesw.c wlc_murx.c wlc_musched.c wlc_mutx.c wlc_nar.c wlc_obss.c \
    wlc_perf_utils.c wlc_pktc.c wlc_pm.c wlc_pmq.c wlc_prot.c wlc_prot_g.c wlc_prot_n.c wlc_pspretend.c \
    wlc_qoscfg.c wlc_rate_sel.c wlc_ratelinkmem.c wlc_rrm.c wlc_rspec.c wlc_rx.c wlc_rx_report.c \
    wlc_scb.c wlc_scb_ratesel.c wlc_sqs.c wlc_stamon.c wlc_stf.c wlc_taf.c wlc_taf_ias.c \
    wlc_test.c wlc_tpc.c wlc_twt.c wlc_tx.c wlc_txbf.c wlc_txc.c wlc_txs.c wlc_txtime.c \
    wlc_ulmu.c wlc_utils.c wlc_vasip.c wlc_vht.c wlc_wds.c wlc_wnm.c wlc_dtpc.c wlc_eht.c \
    wlc_lsa.c wlc_mlo.c wlc_rx_report.c wlc_sbf.c wlc_spp.c wlc_stf_mimops.c wlc_sts_xfer.c )
CFILES_PROF_ARCS    += $(addprefix $(SRCBASE)/wl/keymgmt/src/ , km_alloc.c km_b4m4.c \
    km_key.c km_key_aes.c km_key_tkip.c km_key_wep.c km_notify.c km_scb.c km_tkip.c km_util.c )
CFILES_PROF_ARCS    += $(SRCBASE)/wl/mbo_oce/src/wlc_mbo_ap.c

# wlc_bmac.c doesn't quite work with -fsanitize, to be investigated later.
CFILES_SANITIZE    = $(filter-out wlc_bmac.c,$(CFILES_PROF_ARCS))
