.\" Copyright (c) 2011-2018 Tuxera Inc.
.\"
.TH APFSINFO 8 "October 2018" "Tuxera APFS Info 3020.7.28.4"
.SH NAME
apfsinfo \- Tool for listing volumes in an APFS container.
.SH SYNOPSIS
.B apfsinfo
.I volume
.SH DESCRIPTION
\fBapfsinfo\fR is a tool which displays the volumes stored in an APFS container.
.PP
The \fIvolume\fR can be either a block device or an image file.
.SH EXAMPLES
Show volumes in /dev/sda2:
.RS
.sp
.B apfsinfo /dev/sda2
.sp
.RE
.SH EXIT CODES
Exit code 0 means success, and everything else means error.
.SH KNOWN ISSUES
No known issues.
.sp
Please see:
.RS
http://www.tuxera.com/support/
.RE
for info on commercial support services.
.SH AUTHORS
.B apfsinfo
was written in 2018 by Simon Gander for Tuxera Inc.
