.\"                                      Hey, EMACS: -*- nroff -*-
.\" alsaconf.8 is copyright 2003 by Jordi Mallach <jordi@debian.org>
.\" 
.\" This is free documentation, see the latest version of the GNU
.\" General Public License for copying conditions. There is NO warranty.
.TH ALSACONF 8 "15 mars 2005"

.SH NOM
alsaconf \- outil de configuration pour ALSA (architecture de son avancée de Linux)
.\" configuration tool for the Advanced Linux Sound Architecture

.SH SYNOPSIS
.B alsaconf
.RI [ options ]

.SH DESCRIPTION
Cette page de manuel documente brièvement la commande 
.B alsaconf.

.PP
\fBAlsaconf\fP 
est un simple script shell qui essaye de détecter les cartes son sur votre
système et écrit un fichier de configuration adéquat pour ALSA. Il va
essayer de deviner quelle distribution GNU/Linux vous utilisez, et agira
conformément aux standards de cette distribution, si un support spécifique
est disponible.

.PP
Alsaconf va écrire un fragment de code modutils qui peut être ensuite
utilisé par modutils pour charger les paramètres corrects de votre carte
son. 

.SH OPTIONS
Alsaconf accepte les options suivantes\ :

.TP
.B \-l, \-\-legacy
Cherche seulement les anciennes cartes non-isapnp

.TP
.B \-m, \-\-modinfo
Lit les descriptions de modules au lieu de lire une base de données de
carte

.TP
.B \-s, \-\-sound\-wav\-file
Utilise le fichier wav spécifié comme son de test

.TP
.B \-u, \-\-uid uid
Choisit l'uid pour les périphériques ALSA (valeur par défaut\ = 0)

.TP
.B \-g, \-\-gid gid
Choisit le gid pour les périphériques ALSA (valeur par défaut\ = 0)

.TP
.B \-d, \-\-devmode mode
Choisit le mode du périphérique pour les périphériques ALSA (valeur par
défaut\ : 0666)

.TP
.B \-r, \-\-strict
Choisit le mode de périphérique strict (équivaut à -g\ 17 -d\ 0660)

.TP
.B \-L, \-\-log
Mise en journal dans /tmp/alsaconf.log

.TP
.B \-p, \-\-probe card-name
Teste une ancienne carte non-isapnp et affiche les options du module

.TP
.B \-h, \-\-help
Affiche ce message d'aide


.SH POUR DEBIAN EXCLUSIVEMENT
Sous Debian, le gid par défaut des fichiers de périphériques est 29 (qui
correspond au groupe audio) et le mode par défaut des périphériques est
0660.

Pour le paquetage de base ALSA, voir aussi
.I /usr/share/doc/alsa-base/

.SH VOIR AUSSI
\fB
alsamixer(1),
amixer(1),
aplay(1),
arecord(1)
\fP

.SH PAGE D'ACCUEIL
http://www.alsa-project.org/

.SH AUTEUR
Le script alsaconf fut écrit par
Takashi Iwai <tiwai@suse.de>,
Bernd Kaindl <bk@suse.de> et
Jan Ondrej (SAL) <ondrejj@salstar.sk>

Cette page de manuel fut écrite par Jordi Mallach <jordi@debian.org>, pour
le système Debian (mais elle peut être utilisée par d'autres).

.SH TRADUCTION
Baptiste Mélès 2005.

N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
