# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2017
# Mario Six,  Guntermann & Drunck GmbH, mario.six@gdsys.cc
#

obj-$(CONFIG_AXI) += axi-uclass.o
obj-$(CONFIG_IHS_AXI) += ihs_axi.o
obj-$(CONFIG_SANDBOX) += axi-emul-uclass.o
obj-$(CONFIG_SANDBOX) += sandbox_store.o
obj-$(CONFIG_AXI_SANDBOX) += axi_sandbox.o
