# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_BOOTCOUNT_GENERIC)	+= bootcount.o
obj-$(CONFIG_BOOTCOUNT_AT91)	+= bootcount_at91.o
obj-$(CONFIG_BOOTCOUNT_AM33XX)	+= bootcount_davinci.o
obj-$(CONFIG_BOOTCOUNT_RAM)	+= bootcount_ram.o
obj-$(CONFIG_BOOTCOUNT_ENV)	+= bootcount_env.o
obj-$(CONFIG_BOOTCOUNT_I2C)	+= bootcount_i2c.o
obj-$(CONFIG_BOOTCOUNT_EXT)	+= bootcount_ext.o

obj-$(CONFIG_DM_BOOTCOUNT)      += bootcount-uclass.o
obj-$(CONFIG_DM_BOOTCOUNT_RTC)  += rtc.o
