
 
#define SUPPORT_ETHWAN 1
 
#define SUPPORT_ETHLAG_LAN_ONLY 1
 
#define SUPPORT_TMCTL 1
 
#define SUPPORT_ARCHERCTL 1
 
#define DMP_X_BROADCOM_COM_L2TPAC_1 1
 
#define DMP_X_BROADCOM_COM_L2TPAC_2 1
 
#define SUPPORT_GRE_TUNNEL 1
 
#define SUPPORT_IPSEC 1
 
#define DMP_X_BROADCOM_COM_IPSEC_1 1
 
#define SUPPORT_IPV6 1
 
#define DMP_X_BROADCOM_COM_DEV2_IPV6_1 1
 
#define DMP_DEVICE2_DSLITE_1 1
 
#define DMP_DEVICE2_DSLITE_2 1
 
#define DMP_DEVICE2_IPV6RD_1 1
 
#define DMP_DEVICE2_IPV6INTERFACE_1 1
 
#define DMP_DEVICE2_IPV6ROUTING_1 1
 
#define DMP_DEVICE2_DHCPV6CLIENT_1 1
 
#define DMP_DEVICE2_DHCPV6CLIENTSERVERIDENTITY_1 1
 
#define DMP_DEVICE2_DHCPV6SERVER_1 1
 
#define DMP_DEVICE2_DHCPV6SERVERADV_1 1
 
#define DMP_DEVICE2_DHCPV6SERVERCLIENTINFO_1 1
 
#define DMP_DEVICE2_NEIGHBORDISCOVERY_1 1
 
#define DMP_DEVICE2_ROUTERADVERTISEMENT_1 1
 
#define DMP_DEVICE2_MAPBASIC_1 1
 
#define DMP_DEVICE2_MAPADV_1 1
 
#define SUPPORT_MAP 1
 
#define SUPPORT_CPU_MEMORY_WEB_PAGE 1
 
#define SUPPORT_JQPLOT 1
 
#define SUPPORT_WEB_SOCKETS 1
 
#define SUPPORT_HTTPD 1
 
#define SUPPORT_HTTPD_BASIC_SSL 1
 
#define SUPPORT_CLI_CMD 1
 
#define CLI_CMD_EDIT 1
 
#define SUPPORT_TELNETD 1
 
#define SUPPORT_SSHD 1
 
#define SUPPORT_EBTABLES 1
 
#define SUPPORT_TOD 1
 
#define DMP_X_BROADCOM_COM_ACCESSTIMERESTRICTION_1 1
 
#define SUPPORT_URLFILTER 1
 
#define SUPPORT_POLICYROUTING 1
 
#define SUPPORT_DNSPROXY 1
 
#define DMP_X_BROADCOM_COM_DNSPROXY_1 1
 
#define SUPPORT_IPP 1
 
#define DMP_X_BROADCOM_COM_IPPRINTING_1 1
 
#define DMP_X_BROADCOM_COM_DLNA_1 1
 
#define SUPPORT_BLOGCTL 1
 
#define SUPPORT_FCCTL 1
 
#define SUPPORT_NTPD 1
 
#define SUPPORT_ETHSWCTL 1
 
#define SUPPORT_PWRMNGT 1
 
#define DMP_X_BROADCOM_COM_PWRMNGT_1 1
 
#define SUPPORT_DDR_SELF_REFRESH_PWRSAVE 1
 
#define SUPPORT_ETH_PWRSAVE 1
 
#define SUPPORT_ENERGY_EFFICIENT_ETHERNET 1
 
#define SUPPORT_ETH_DEEP_GREEN_MODE 1
 
#define SUPPORT_STORAGESERVICE 1
 
#define DMP_STORAGESERVICE_1 1
 
#define SUPPORT_NTFS_3G 1
 
#define SUPPORT_SAMBA 1
 
#define DMP_X_BROADCOM_COM_MCAST_1 1
 
#define DMP_X_BROADCOM_COM_IGMPSNOOP_1 1
 
#define DMP_X_BROADCOM_COM_MLDSNOOP_1 1
 
#define SUPPORT_IGMP 1
 
#define DMP_X_BROADCOM_COM_IGMP_1 1
 
#define SUPPORT_MLD 1
 
#define DMP_X_BROADCOM_COM_MLD_1 1
 
#define SUPPORT_NF_NAT 1
 
#define SUPPORT_NF_FIREWALL 1
 
#define SUPPORT_PPTP 1
 
#define SUPPORT_SIP 1
 
#define SUPPORT_NF_MANGLE 1
 
#define SUPPORT_INTF_GROUPING 1
 
#define SUPPORT_VLANCTL 1
 
#define SUPPORT_LANVLAN 1
 
#define SUPPORT_CMS_ALLOW_REAL_HW_SWITCHING 1
 
#define SUPPORT_QOS 1
 
#define SUPPORT_RATE_LIMIT 1
 
#define SUPPORT_DEBUG_TOOLS 1
 
#define SUPPORT_CERT 1
 
#define DMP_X_BROADCOM_COM_DIGITALCERTIFICATES_1 1
 
#define SUPPORT_RIP 1
 
#define COMPRESSED_CONFIG_FILE 1
 
#define CMS_CONFIG_COMPAT 1

 

//  -DSUPPORT_ETHWAN -DSUPPORT_ETHLAG_LAN_ONLY -DSUPPORT_TMCTL -DSUPPORT_ARCHERCTL -DDMP_X_BROADCOM_COM_L2TPAC_1 -DDMP_X_BROADCOM_COM_L2TPAC_2 -DSUPPORT_GRE_TUNNEL -DSUPPORT_IPSEC -DDMP_X_BROADCOM_COM_IPSEC_1 -DSUPPORT_IPV6 -DDMP_X_BROADCOM_COM_DEV2_IPV6_1 -DDMP_DEVICE2_DSLITE_1 -DDMP_DEVICE2_DSLITE_2 -DDMP_DEVICE2_IPV6RD_1 -DDMP_DEVICE2_IPV6INTERFACE_1 -DDMP_DEVICE2_IPV6ROUTING_1 -DDMP_DEVICE2_DHCPV6CLIENT_1 -DDMP_DEVICE2_DHCPV6CLIENTSERVERIDENTITY_1 -DDMP_DEVICE2_DHCPV6SERVER_1 -DDMP_DEVICE2_DHCPV6SERVERADV_1 -DDMP_DEVICE2_DHCPV6SERVERCLIENTINFO_1 -DDMP_DEVICE2_NEIGHBORDISCOVERY_1 -DDMP_DEVICE2_ROUTERADVERTISEMENT_1 -DDMP_DEVICE2_MAPBASIC_1 -DDMP_DEVICE2_MAPADV_1 -DSUPPORT_MAP -DSUPPORT_CPU_MEMORY_WEB_PAGE -DSUPPORT_JQPLOT -DSUPPORT_WEB_SOCKETS -DSUPPORT_HTTPD -DSUPPORT_HTTPD_BASIC_SSL -DSUPPORT_CLI_CMD -DCLI_CMD_EDIT -DSUPPORT_TELNETD -DSUPPORT_SSHD -DSUPPORT_EBTABLES -DSUPPORT_TOD -DDMP_X_BROADCOM_COM_ACCESSTIMERESTRICTION_1 -DSUPPORT_URLFILTER -DSUPPORT_POLICYROUTING -DSUPPORT_DNSPROXY -DDMP_X_BROADCOM_COM_DNSPROXY_1 -DSUPPORT_IPP -DDMP_X_BROADCOM_COM_IPPRINTING_1 -DDMP_X_BROADCOM_COM_DLNA_1 -DSUPPORT_BLOGCTL -DSUPPORT_FCCTL -DSUPPORT_NTPD -DSUPPORT_ETHSWCTL -DSUPPORT_PWRMNGT -DDMP_X_BROADCOM_COM_PWRMNGT_1 -DSUPPORT_DDR_SELF_REFRESH_PWRSAVE -DSUPPORT_ETH_PWRSAVE -DSUPPORT_ENERGY_EFFICIENT_ETHERNET -DSUPPORT_ETH_DEEP_GREEN_MODE -DSUPPORT_STORAGESERVICE -DDMP_STORAGESERVICE_1 -DSUPPORT_NTFS_3G -DSUPPORT_SAMBA -DDMP_X_BROADCOM_COM_MCAST_1 -DDMP_X_BROADCOM_COM_IGMPSNOOP_1 -DDMP_X_BROADCOM_COM_MLDSNOOP_1 -DSUPPORT_IGMP -DDMP_X_BROADCOM_COM_IGMP_1 -DSUPPORT_MLD -DDMP_X_BROADCOM_COM_MLD_1 -DSUPPORT_NF_NAT -DSUPPORT_NF_FIREWALL -DSUPPORT_PPTP -DSUPPORT_SIP -DSUPPORT_NF_MANGLE -DSUPPORT_INTF_GROUPING -DSUPPORT_VLANCTL -DSUPPORT_LANVLAN -DSUPPORT_CMS_ALLOW_REAL_HW_SWITCHING -DSUPPORT_QOS -DSUPPORT_RATE_LIMIT -DSUPPORT_DEBUG_TOOLS -DSUPPORT_CERT -DDMP_X_BROADCOM_COM_DIGITALCERTIFICATES_1 -DSUPPORT_RIP -DCOMPRESSED_CONFIG_FILE -DCMS_CONFIG_COMPAT

