// SPDX-License-Identifier: GPL-2.0+
/*
   Copyright (c) 2015 Broadcom Corporation
   All Rights Reserved

*/
/* THIS FILE IS GENERATED USING AN AUTOMATED SCRIPT... PLEASE DO NOT EDIT THIS FILE DIRECTLY !!! */

#ifndef MERLIN16_SHORTFIN_API_REG_DUMP_H
#define MERLIN16_SHORTFIN_API_REG_DUMP_H

#include "merlin16_shortfin_usr_includes.h"

#define MERLIN16_SHORTFIN_REG_DUMP_SECTIONS  (10)
#define MERLIN16_SHORTFIN_REG_PLL_START      (0xd0b0)
#define MERLIN16_SHORTFIN_REG_UC_START       (0xffff)
extern const uint16_t merlin16_shortfin_reg_dump_arr[MERLIN16_SHORTFIN_REG_DUMP_SECTIONS][2];

#endif /* SERDES_API_REG_DUMP_H */

