#ifndef __CFG_STRING_H__
#define __CFG_STRING_H__

/* string for data */
#define CFG_STR_FEATURE		"feature"
#define CFG_STR_PRIVATE_FEATURE		"private_feature"
#define CFG_STR_CONTROL_FEATURE		"control_feature"
#define CFG_STR_CFGVER		"cfg_ver"
#define CFG_STR_CFGALL		"cfg_all"
#define CFG_STR_SWMODE		"sw_mode"
#define CFG_STR_VENDOR		"vendor"
#define CFG_STR_BWCAP		"bwcap"		/* 0 - old, 1 - new */
#define CFG_STR_MAC			"mac"
#define CFG_STR_ALIAS		"alias"
#define CFG_STR_PAP2G		"pap2g"
#define CFG_STR_PAP5G		"pap5g"
#define CFG_STR_PAP5G1		"pap5g1"
#define CFG_STR_RSSI2G		"rssi2g"
#define CFG_STR_RSSI5G		"rssi5g"
#define CFG_STR_AP2G		"ap2g"
#define CFG_STR_AP5G		"ap5g"
#define CFG_STR_AP5G1		"ap5g1"
#define CFG_STR_APDWB		"apdwb"
#define CFG_STR_WIRED_MAC	"wired_mac"
#define CFG_STR_FWVER		"fwver"
#define CFG_STR_NEW_FWVER		"newfwver"
#define CFG_STR_STA2G		"sta2g"
#define CFG_STR_STA5G		"sta5g"
#define CFG_STR_STA2G_TRAFFIC		"sta2g_traffic"
#define CFG_STR_STA5G_TRAFFIC		"sta5g_traffic"
#define CFG_STR_NOTIFY_TYPE	"notify_type"
#define CFG_STR_IP			"ip"
#define CFG_STR_RSSI		"rssi"
#define CFG_STR_TYPE		"type"
#define CFG_STR_STATUS		"status"
#define CFG_STR_ID			"id"
#define CFG_STR_RE_MAC		"re_mac"
#define CFG_STR_NEW_RE_MAC	"new_re_mac"
#define CFG_STR_MODEL_NAME	"model_name"
#define CFG_STR_TIMESTAMP	"ts"
#define CFG_STR_TIMESTAMP_ETH	"ts_eth"
#define CFG_STR_COST		"cost"
#define CFG_STR_PATH		"re_path"
#ifdef RTCONFIG_BHCOST_OPT
#define CFG_STR_PATH_V2	"re_path_v2"
#define CFG_STR_PATH_V3	"re_path_v3"
#endif
#define CFG_STR_CHANNEL	"channel"
#define CFG_STR_FWSTATUS	"fwStatus"
#define CFG_STR_GROUPID	"groupid"
#define CFG_STR_ONLINE		"online"
#define CFG_STR_LEVEL		"level"
#define CFG_STR_BANDNUM		"cfg_bandnum"
#define CFG_ACTION_SCRIPT	"action_script"
#define CFG_STR_CURRENT_CHANNEL	"cur_channel"
#define CFG_STR_CONFIG		"config"
#define CFG_STR_SOURCE		"source"
#define CFG_STR_OB_PATH	"ob_path"
#define CFG_STR_OB_KEY		"ob_key"
#define CFG_STR_OB_GROUP		"ob_group"
#define CFG_STR_ETHER_LIST	"ether_list"
#define CFG_STR_SMART_CONNECT	"cfg_smart_connect"
#define CFG_STR_TERRITORY_CODE 	"cfg_territory_code"
#define CFG_STR_CAPABILITY 	"capability"
#define CFG_STR_CHANSPEC 	"chanspec"
#define CFG_STR_BANDWIDTH	"bandwidth"
#define CFG_STR_2G 	"2G"
#define CFG_STR_5G 	"5G"
#define CFG_STR_5G1 	"5G1"
#define CFG_STR_RE_NUMBER       "re_num"
#define CFG_STR_APLIST "aplist"
#define CFG_STR_DUAL_BAND_LIST	"db_list"
#define CFG_STR_DUAL_BAND_CAP		"db_cap"
#define CFG_STR_IS_RE	"is_re"
#define CFG_STR_TRIBAND_RE	"triband_re"
#define CFG_STR_REBOOT_TIME		"reboot_time"
#define CFG_STR_CONN_TIMEOUT		"conn_timeout"
#define CFG_STR_TRAFFIC_TIMEOUT	"traffic_timeout"
#define CFG_STR_FAIL_RESULT	"fail_result"
#define CFG_STR_PAP2G_SSID		"pap2g_ssid"
#define CFG_STR_PAP5G_SSID		"pap5g_ssid"
#define CFG_STR_AP2G_SSID		"ap2g_ssid"
#define CFG_STR_AP5G_SSID		"ap5g_ssid"
#define CFG_STR_AP5G1_SSID		"ap5g1_ssid"
#define CFG_STR_WIRED_PORT	"wired_port"
#define CFG_STR_WAN_PORT_COUNT	"wan_port_count"
#define CFG_STR_LAN_PORT_COUNT	"lan_port_count"
#define CFG_STR_WAN_PORT	"wan_port"
#define CFG_STR_LAN_PORT	"lan_port"
#define CFG_STR_LINK_RATE		"link_rate"
#define CFG_STR_WLC_LLDP_COST_STAT  "lldp_wlc_cost_stat"
#define CFG_STR_ETH_LLDP_COST_STAT  "lldp_eth_cost_stat"
#if defined(RTCONFIG_AMAS_WGN)
#define CFG_STR_WGN_CTRL_FEATURE	"guest_network"
#define CFG_STR_WGN_WO_VLAN 		"wgn_without_vlan"
#define CFG_STR_WGN_WLOFF_VIFS		"cfg_wgn_wloff_vifs"
#define CFG_STR_SYNC_NODE_X_Y		"cfg_wl%d.%d_sync_node"
#define CFG_STR_SYNC_NODE_2G_G1		"cfg_wl0.1_sync_node"
#define CFG_STR_SYNC_NODE_2G_G2		"cfg_wl0.2_sync_node"
#define CFG_STR_SYNC_NODE_2G_G3		"cfg_wl0.3_sync_node"
#define CFG_STR_SYNC_NODE_5G_G1		"cfg_wl1.1_sync_node"
#define CFG_STR_SYNC_NODE_5G_G2		"cfg_wl1.2_sync_node"
#define CFG_STR_SYNC_NODE_5G_G3		"cfg_wl1.3_sync_node"
#define CFG_STR_SYNC_NODE_5G1_G1	"cfg_wl2.1_sync_node"
#define CFG_STR_SYNC_NODE_5G1_G2	"cfg_wl2.2_sync_node"
#define CFG_STR_SYNC_NODE_5G1_G3	"cfg_wl2.3_sync_node"

#define CFG_STR_BSS_ONOFF_X_Y		"cfg_wl%d.%d_bss_enabled"
#define CFG_STR_BSS_ONOFF_2G_G1		"cfg_wl0.1_bss_enabled"
#define CFG_STR_BSS_ONOFF_2G_G2		"cfg_wl0.2_bss_enabled"
#define CFG_STR_BSS_ONOFF_2G_G3		"cfg_wl0.3_bss_enabled"
#define CFG_STR_BSS_ONOFF_5G_G1		"cfg_wl1.1_bss_enabled"
#define CFG_STR_BSS_ONOFF_5G_G2		"cfg_wl1.2_bss_enabled"
#define CFG_STR_BSS_ONOFF_5G_G3		"cfg_wl1.3_bss_enabled"
#define CFG_STR_BSS_ONOFF_5G1_G1	"cfg_wl2.1_bss_enabled"
#define CFG_STR_BSS_ONOFF_5G1_G2	"cfg_wl2.2_bss_enabled"
#define CFG_STR_BSS_ONOFF_5G1_G3	"cfg_wl2.3_bss_enabled"

#define CFG_STR_GUEST_IFNAMES_2G	"cfg_guest_ifnames_2g"
#define CFG_STR_GUEST_IFNAMES_5G	"cfg_guest_ifnames_5g"
#define CFG_STR_GUEST_IFNAMES_5GH	"cfg_guest_ifnames_5gh"

#define CFG_STR_GUEST_VLANS_2G		"cfg_guest_vlans_2g"
#define CFG_STR_GUEST_VLANS_5G		"cfg_guest_vlans_5g"
#define CFG_STR_GUEST_VLANS_5GH		"cfg_guest_vlans_5gh"
#endif	/* RTCONFIG_AMAS_WGN */
#define CFG_STR_HASH_BUNDLE_KEY		"hash_bundle_key"
#define CFG_STR_CHANGED_CONFIG		"changed_config"
#define CFG_ACTION_ID	"action_id"
#define CFG_DATA	"data"
#define CFG_STR_STA		"sta"
#define CFG_BLOCK_TIME	"block_time"
#define CFG_TARGET_AP	"target_ap"
#define CFG_STA_BINDING_LIST	"sta_binding_list"
#define CFG_STR_BAND_NUM		"band_num"
#ifdef RTCONFIG_FRONTHAUL_DWB
#define CFG_STR_BACKHUAL_STATUS "backhual_status"
#endif
#ifdef ONBOARDING_VIA_VIF
#define CFG_STR_VIF_STATUS		"vif_status"
#define CFG_STR_OB_VIA_VIF		"ob_via_vif"
#endif
#define CFG_STR_LEVEL		"level"
#define CFG_STR_MAXLEVEL		"maxlevel"
#define CFG_STR_TCODE		"tcode"
#ifdef RTCONFIG_NBR_RPT
#define CFG_STR_NBR_DATA		"nbr_data"
#define CFG_STR_NBR_LIST		"nbr_list"
#define CFG_STR_NBR_VERSION	"nbr_version"
#endif
#define CFG_STR_PREFER_AP		"prefer_ap"
#define CFG_STR_WLC_TARGET_BSSID	"amas_wlc_target_bssid"
#define CFG_STR_WLC0_TARGET_BSSID	"amas_wlc0_target_bssid"
#define CFG_STR_WLC1_TARGET_BSSID	"amas_wlc1_target_bssid"
#define CFG_STR_WLC2_TARGET_BSSID	"amas_wlc2_target_bssid"
#endif /* __CFG_STRING_H__ */
