# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2019 Baylibre, SAS
# Jerome Brunet <jbrunet@baylibre.com>

obj-$(CONFIG_CLK_MESON_GX) += gxbb.o
obj-$(CONFIG_CLK_MESON_AXG) += axg.o
obj-$(CONFIG_CLK_MESON_G12A) += g12a.o

