# TOOLPREFIX is for cross compiling

CC=$(TOOLPREFIX)gcc
LD=$(TOOLPREFIX)ld
AR=$(TOOLPREFIX)ar
RANLIB=$(TOOLPREFIX)ranlib

PCI_ARCH_I386=yes
PCI_OS_WINDOWS=yes
PCI_HAVE_PM_INTEL_CONF=yes

PCILIB=$(LIBNAME).a
PCILIBPC=$(LIBNAME).pc
