/*
   Copyright (c) 2015 Broadcom
   All Rights Reserved

    <:label-BRCM:2015:DUAL/GPL:standard

    Unless you and Broadcom execute a separate written software license
    agreement governing use of this software, this software is licensed
    to you under the terms of the GNU General Public License version 2
    (the "GPL"), available at http://www.broadcom.com/licenses/GPLv2.php,
    with the following added to such license:

       As a special exception, the copyright holders of this software give
       you permission to link this software with independent modules, and
       to copy and distribute the resulting executable under terms of your
       choice, provided that you also meet, for each linked independent
       module, the terms and conditions of the license of that module.
       An independent module is a module which is not derived from this
       software.  The special exception does not apply to any modifications
       of the software.

    Not withstanding the above, under no circumstances may you combine
    this software in any way with any other Broadcom software provided
    under a license other than the GPL, without Broadcom's express prior
    written consent.

:>
*/


#ifndef _XRDP_DQM_AG_H_
#define _XRDP_DQM_AG_H_

#include "ru_types.h"

#define DQM_TOKEN_FIFO_VALUE_TOKEN_FIELD_MASK 0xFFFFFFFF
#define DQM_TOKEN_FIFO_VALUE_TOKEN_FIELD_WIDTH 32
#define DQM_TOKEN_FIFO_VALUE_TOKEN_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_TOKEN_FIFO_VALUE_TOKEN_FIELD;
#endif
extern const ru_reg_rec DQM_TOKEN_FIFO_VALUE_REG;
#define DQM_TOKEN_FIFO_VALUE_REG_OFFSET 0x00000080

extern const ru_block_rec DQM_TOKEN_FIFO_BLOCK;

#define DQM_MAX_ENTRIES_WORDS_MAX_FIELD_MASK 0x0007FFFF
#define DQM_MAX_ENTRIES_WORDS_MAX_FIELD_WIDTH 19
#define DQM_MAX_ENTRIES_WORDS_MAX_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_MAX_ENTRIES_WORDS_MAX_FIELD;
#endif
extern const ru_reg_rec DQM_MAX_ENTRIES_WORDS_REG;
#define DQM_MAX_ENTRIES_WORDS_REG_OFFSET 0x00000034

#define DQM_FPM_ADDR_FPMADDRESS_FIELD_MASK 0xFFFFFFFF
#define DQM_FPM_ADDR_FPMADDRESS_FIELD_WIDTH 32
#define DQM_FPM_ADDR_FPMADDRESS_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_FPM_ADDR_FPMADDRESS_FIELD;
#endif
extern const ru_reg_rec DQM_FPM_ADDR_REG;
#define DQM_FPM_ADDR_REG_OFFSET 0x0000004C

#define DQM_IRQ_STS_POPEMPTYQ_FIELD_MASK 0x00000001
#define DQM_IRQ_STS_POPEMPTYQ_FIELD_WIDTH 1
#define DQM_IRQ_STS_POPEMPTYQ_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_IRQ_STS_POPEMPTYQ_FIELD;
#endif
#define DQM_IRQ_STS_PUSHFULLQ_FIELD_MASK 0x00000002
#define DQM_IRQ_STS_PUSHFULLQ_FIELD_WIDTH 1
#define DQM_IRQ_STS_PUSHFULLQ_FIELD_SHIFT 1
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_IRQ_STS_PUSHFULLQ_FIELD;
#endif
extern const ru_reg_rec DQM_IRQ_STS_REG;
#define DQM_IRQ_STS_REG_OFFSET 0x00000050

#define DQM_IRQ_MSK_POPEMPTYQ_FIELD_MASK 0x00000001
#define DQM_IRQ_MSK_POPEMPTYQ_FIELD_WIDTH 1
#define DQM_IRQ_MSK_POPEMPTYQ_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_IRQ_MSK_POPEMPTYQ_FIELD;
#endif
#define DQM_IRQ_MSK_PUSHFULLQ_FIELD_MASK 0x00000002
#define DQM_IRQ_MSK_PUSHFULLQ_FIELD_WIDTH 1
#define DQM_IRQ_MSK_PUSHFULLQ_FIELD_SHIFT 1
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_IRQ_MSK_PUSHFULLQ_FIELD;
#endif
extern const ru_reg_rec DQM_IRQ_MSK_REG;
#define DQM_IRQ_MSK_REG_OFFSET 0x00000054

#define DQM_BUF_SIZE_POOL_0_SIZE_FIELD_MASK 0x00000003
#define DQM_BUF_SIZE_POOL_0_SIZE_FIELD_WIDTH 2
#define DQM_BUF_SIZE_POOL_0_SIZE_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_BUF_SIZE_POOL_0_SIZE_FIELD;
#endif
extern const ru_reg_rec DQM_BUF_SIZE_REG;
#define DQM_BUF_SIZE_REG_OFFSET 0x00000058

#define DQM_BUF_BASE_BASE_FIELD_MASK 0xFFFFFFFF
#define DQM_BUF_BASE_BASE_FIELD_WIDTH 32
#define DQM_BUF_BASE_BASE_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_BUF_BASE_BASE_FIELD;
#endif
extern const ru_reg_rec DQM_BUF_BASE_REG;
#define DQM_BUF_BASE_REG_OFFSET 0x0000005C

#define DQM_TOKENS_USED_COUNT_FIELD_MASK 0xFFFFFFFF
#define DQM_TOKENS_USED_COUNT_FIELD_WIDTH 32
#define DQM_TOKENS_USED_COUNT_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_TOKENS_USED_COUNT_FIELD;
#endif
extern const ru_reg_rec DQM_TOKENS_USED_REG;
#define DQM_TOKENS_USED_REG_OFFSET 0x00000064

#define DQM_NUM_PUSHED_COUNT_FIELD_MASK 0xFFFFFFFF
#define DQM_NUM_PUSHED_COUNT_FIELD_WIDTH 32
#define DQM_NUM_PUSHED_COUNT_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_NUM_PUSHED_COUNT_FIELD;
#endif
extern const ru_reg_rec DQM_NUM_PUSHED_REG;
#define DQM_NUM_PUSHED_REG_OFFSET 0x00000068

#define DQM_NUM_POPPED_COUNT_FIELD_MASK 0xFFFFFFFF
#define DQM_NUM_POPPED_COUNT_FIELD_WIDTH 32
#define DQM_NUM_POPPED_COUNT_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_NUM_POPPED_COUNT_FIELD;
#endif
extern const ru_reg_rec DQM_NUM_POPPED_REG;
#define DQM_NUM_POPPED_REG_OFFSET 0x0000006C

#define DQM_DIAG_SEL_SEL_FIELD_MASK 0x000000FF
#define DQM_DIAG_SEL_SEL_FIELD_WIDTH 8
#define DQM_DIAG_SEL_SEL_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_DIAG_SEL_SEL_FIELD;
#endif
extern const ru_reg_rec DQM_DIAG_SEL_REG;
#define DQM_DIAG_SEL_REG_OFFSET 0x00000070

#define DQM_DIAG_DATA_DATA_FIELD_MASK 0xFFFFFFFF
#define DQM_DIAG_DATA_DATA_FIELD_WIDTH 32
#define DQM_DIAG_DATA_DATA_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_DIAG_DATA_DATA_FIELD;
#endif
extern const ru_reg_rec DQM_DIAG_DATA_REG;
#define DQM_DIAG_DATA_REG_OFFSET 0x00000074

#define DQM_IRQ_TST_POPEMPTYQTST_FIELD_MASK 0x00000001
#define DQM_IRQ_TST_POPEMPTYQTST_FIELD_WIDTH 1
#define DQM_IRQ_TST_POPEMPTYQTST_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_IRQ_TST_POPEMPTYQTST_FIELD;
#endif
#define DQM_IRQ_TST_PUSHFULLQTST_FIELD_MASK 0x00000002
#define DQM_IRQ_TST_PUSHFULLQTST_FIELD_WIDTH 1
#define DQM_IRQ_TST_PUSHFULLQTST_FIELD_SHIFT 1
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_IRQ_TST_PUSHFULLQTST_FIELD;
#endif
extern const ru_reg_rec DQM_IRQ_TST_REG;
#define DQM_IRQ_TST_REG_OFFSET 0x00000078

#define DQM_TOKEN_FIFO_STATUS_RD_LOC_FIELD_MASK 0x0000000F
#define DQM_TOKEN_FIFO_STATUS_RD_LOC_FIELD_WIDTH 4
#define DQM_TOKEN_FIFO_STATUS_RD_LOC_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_TOKEN_FIFO_STATUS_RD_LOC_FIELD;
#endif
#define DQM_TOKEN_FIFO_STATUS_LEVEL_FIELD_MASK 0x00001F00
#define DQM_TOKEN_FIFO_STATUS_LEVEL_FIELD_WIDTH 5
#define DQM_TOKEN_FIFO_STATUS_LEVEL_FIELD_SHIFT 8
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_TOKEN_FIFO_STATUS_LEVEL_FIELD;
#endif
#define DQM_TOKEN_FIFO_STATUS_EMPTY_FIELD_MASK 0x00010000
#define DQM_TOKEN_FIFO_STATUS_EMPTY_FIELD_WIDTH 1
#define DQM_TOKEN_FIFO_STATUS_EMPTY_FIELD_SHIFT 16
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_TOKEN_FIFO_STATUS_EMPTY_FIELD;
#endif
#define DQM_TOKEN_FIFO_STATUS_FULL_FIELD_MASK 0x00020000
#define DQM_TOKEN_FIFO_STATUS_FULL_FIELD_WIDTH 1
#define DQM_TOKEN_FIFO_STATUS_FULL_FIELD_SHIFT 17
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_TOKEN_FIFO_STATUS_FULL_FIELD;
#endif
extern const ru_reg_rec DQM_TOKEN_FIFO_STATUS_REG;
#define DQM_TOKEN_FIFO_STATUS_REG_OFFSET 0x0000007C

#define DQM_NUM_POPPED_NO_COMMIT_COUNT_FIELD_MASK 0xFFFFFFFF
#define DQM_NUM_POPPED_NO_COMMIT_COUNT_FIELD_WIDTH 32
#define DQM_NUM_POPPED_NO_COMMIT_COUNT_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_NUM_POPPED_NO_COMMIT_COUNT_FIELD;
#endif
extern const ru_reg_rec DQM_NUM_POPPED_NO_COMMIT_REG;
#define DQM_NUM_POPPED_NO_COMMIT_REG_OFFSET 0x000000C0

#define DQM_QSMDATA_DATA_FIELD_MASK 0xFFFFFFFF
#define DQM_QSMDATA_DATA_FIELD_WIDTH 32
#define DQM_QSMDATA_DATA_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_QSMDATA_DATA_FIELD;
#endif
extern const ru_reg_rec DQM_QSMDATA_REG;
#define DQM_QSMDATA_REG_OFFSET 0x00020000
#define DQM_QSMDATA_REG_RAM_CNT 43008

#define DQM_STATUS_Q_AVL_TKN_SPACE_FIELD_MASK 0x0007FFFF
#define DQM_STATUS_Q_AVL_TKN_SPACE_FIELD_WIDTH 19
#define DQM_STATUS_Q_AVL_TKN_SPACE_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_STATUS_Q_AVL_TKN_SPACE_FIELD;
#endif
#define DQM_STATUS_NEXT_LINE_DATA_IS_LOCAL_FIELD_MASK 0x40000000
#define DQM_STATUS_NEXT_LINE_DATA_IS_LOCAL_FIELD_WIDTH 1
#define DQM_STATUS_NEXT_LINE_DATA_IS_LOCAL_FIELD_SHIFT 30
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_STATUS_NEXT_LINE_DATA_IS_LOCAL_FIELD;
#endif
#define DQM_STATUS_CURR_LINE_DATA_IS_LOCAL_FIELD_MASK 0x80000000
#define DQM_STATUS_CURR_LINE_DATA_IS_LOCAL_FIELD_WIDTH 1
#define DQM_STATUS_CURR_LINE_DATA_IS_LOCAL_FIELD_SHIFT 31
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_STATUS_CURR_LINE_DATA_IS_LOCAL_FIELD;
#endif
extern const ru_reg_rec DQM_STATUS_REG;
#define DQM_STATUS_REG_OFFSET 0x00000800
#define DQM_STATUS_REG_RAM_CNT 448

#define DQM_HEAD_PTR_Q_HEAD_PTR_FIELD_MASK 0x0FFFFFFF
#define DQM_HEAD_PTR_Q_HEAD_PTR_FIELD_WIDTH 28
#define DQM_HEAD_PTR_Q_HEAD_PTR_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_HEAD_PTR_Q_HEAD_PTR_FIELD;
#endif
extern const ru_reg_rec DQM_HEAD_PTR_REG;
#define DQM_HEAD_PTR_REG_OFFSET 0x00001000
#define DQM_HEAD_PTR_REG_RAM_CNT 448

#define DQM_TAIL_PTR_Q_TAIL_PTR_FIELD_MASK 0x0FFFFFFF
#define DQM_TAIL_PTR_Q_TAIL_PTR_FIELD_WIDTH 28
#define DQM_TAIL_PTR_Q_TAIL_PTR_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_TAIL_PTR_Q_TAIL_PTR_FIELD;
#endif
extern const ru_reg_rec DQM_TAIL_PTR_REG;
#define DQM_TAIL_PTR_REG_OFFSET 0x00001004
#define DQM_TAIL_PTR_REG_RAM_CNT 448

#define DQM_WORD0_DATA_FIELD_MASK 0xFFFFFFFF
#define DQM_WORD0_DATA_FIELD_WIDTH 32
#define DQM_WORD0_DATA_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_WORD0_DATA_FIELD;
#endif
extern const ru_reg_rec DQM_WORD0_REG;
#define DQM_WORD0_REG_OFFSET 0x00006000
#define DQM_WORD0_REG_RAM_CNT 448

#define DQM_WORD1_DATA_FIELD_MASK 0xFFFFFFFF
#define DQM_WORD1_DATA_FIELD_WIDTH 32
#define DQM_WORD1_DATA_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_WORD1_DATA_FIELD;
#endif
extern const ru_reg_rec DQM_WORD1_REG;
#define DQM_WORD1_REG_OFFSET 0x00006004
#define DQM_WORD1_REG_RAM_CNT 448

#define DQM_WORD2_DATA_FIELD_MASK 0xFFFFFFFF
#define DQM_WORD2_DATA_FIELD_WIDTH 32
#define DQM_WORD2_DATA_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_WORD2_DATA_FIELD;
#endif
extern const ru_reg_rec DQM_WORD2_REG;
#define DQM_WORD2_REG_OFFSET 0x00006008
#define DQM_WORD2_REG_RAM_CNT 448

#define DQM_DQMOL_SIZE_Q_TKN_SIZE_FIELD_MASK 0x00000003
#define DQM_DQMOL_SIZE_Q_TKN_SIZE_FIELD_WIDTH 2
#define DQM_DQMOL_SIZE_Q_TKN_SIZE_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_DQMOL_SIZE_Q_TKN_SIZE_FIELD;
#endif
#define DQM_DQMOL_SIZE_Q_DISABLE_OFFLOAD_FIELD_MASK 0x00000008
#define DQM_DQMOL_SIZE_Q_DISABLE_OFFLOAD_FIELD_WIDTH 1
#define DQM_DQMOL_SIZE_Q_DISABLE_OFFLOAD_FIELD_SHIFT 3
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_DQMOL_SIZE_Q_DISABLE_OFFLOAD_FIELD;
#endif
#define DQM_DQMOL_SIZE_MAX_ENTRIES_FIELD_MASK 0x007FFFF0
#define DQM_DQMOL_SIZE_MAX_ENTRIES_FIELD_WIDTH 19
#define DQM_DQMOL_SIZE_MAX_ENTRIES_FIELD_SHIFT 4
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_DQMOL_SIZE_MAX_ENTRIES_FIELD;
#endif
extern const ru_reg_rec DQM_DQMOL_SIZE_REG;
#define DQM_DQMOL_SIZE_REG_OFFSET 0x00002000
#define DQM_DQMOL_SIZE_REG_RAM_CNT 448

#define DQM_DQMOL_CFGA_Q_START_ADDR_FIELD_MASK 0x0000FFFF
#define DQM_DQMOL_CFGA_Q_START_ADDR_FIELD_WIDTH 16
#define DQM_DQMOL_CFGA_Q_START_ADDR_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_DQMOL_CFGA_Q_START_ADDR_FIELD;
#endif
#define DQM_DQMOL_CFGA_Q_SIZE_FIELD_MASK 0xFFFF0000
#define DQM_DQMOL_CFGA_Q_SIZE_FIELD_WIDTH 16
#define DQM_DQMOL_CFGA_Q_SIZE_FIELD_SHIFT 16
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_DQMOL_CFGA_Q_SIZE_FIELD;
#endif
extern const ru_reg_rec DQM_DQMOL_CFGA_REG;
#define DQM_DQMOL_CFGA_REG_OFFSET 0x00002004
#define DQM_DQMOL_CFGA_REG_RAM_CNT 448

#define DQM_DQMOL_CFGB_ENABLE_FIELD_MASK 0x80000000
#define DQM_DQMOL_CFGB_ENABLE_FIELD_WIDTH 1
#define DQM_DQMOL_CFGB_ENABLE_FIELD_SHIFT 31
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_DQMOL_CFGB_ENABLE_FIELD;
#endif
extern const ru_reg_rec DQM_DQMOL_CFGB_REG;
#define DQM_DQMOL_CFGB_REG_OFFSET 0x00002008
#define DQM_DQMOL_CFGB_REG_RAM_CNT 448

#define DQM_DQMOL_PUSHTOKEN_TOKEN_FIELD_MASK 0xFFFFFFFF
#define DQM_DQMOL_PUSHTOKEN_TOKEN_FIELD_WIDTH 32
#define DQM_DQMOL_PUSHTOKEN_TOKEN_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_DQMOL_PUSHTOKEN_TOKEN_FIELD;
#endif
extern const ru_reg_rec DQM_DQMOL_PUSHTOKEN_REG;
#define DQM_DQMOL_PUSHTOKEN_REG_OFFSET 0x00002010
#define DQM_DQMOL_PUSHTOKEN_REG_RAM_CNT 448

#define DQM_DQMOL_PUSHTOKENNEXT_TOKEN_FIELD_MASK 0xFFFFFFFF
#define DQM_DQMOL_PUSHTOKENNEXT_TOKEN_FIELD_WIDTH 32
#define DQM_DQMOL_PUSHTOKENNEXT_TOKEN_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_DQMOL_PUSHTOKENNEXT_TOKEN_FIELD;
#endif
extern const ru_reg_rec DQM_DQMOL_PUSHTOKENNEXT_REG;
#define DQM_DQMOL_PUSHTOKENNEXT_REG_OFFSET 0x00002014
#define DQM_DQMOL_PUSHTOKENNEXT_REG_RAM_CNT 448

#define DQM_DQMOL_POPTOKEN_TOKEN_FIELD_MASK 0xFFFFFFFF
#define DQM_DQMOL_POPTOKEN_TOKEN_FIELD_WIDTH 32
#define DQM_DQMOL_POPTOKEN_TOKEN_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_DQMOL_POPTOKEN_TOKEN_FIELD;
#endif
extern const ru_reg_rec DQM_DQMOL_POPTOKEN_REG;
#define DQM_DQMOL_POPTOKEN_REG_OFFSET 0x00002018
#define DQM_DQMOL_POPTOKEN_REG_RAM_CNT 448

#define DQM_DQMOL_POPTOKENNEXT_TOKEN_FIELD_MASK 0xFFFFFFFF
#define DQM_DQMOL_POPTOKENNEXT_TOKEN_FIELD_WIDTH 32
#define DQM_DQMOL_POPTOKENNEXT_TOKEN_FIELD_SHIFT 0
#if RU_INCLUDE_FIELD_DB
extern const ru_field_rec DQM_DQMOL_POPTOKENNEXT_TOKEN_FIELD;
#endif
extern const ru_reg_rec DQM_DQMOL_POPTOKENNEXT_REG;
#define DQM_DQMOL_POPTOKENNEXT_REG_OFFSET 0x0000201C
#define DQM_DQMOL_POPTOKENNEXT_REG_RAM_CNT 448

extern const ru_block_rec DQM_BLOCK;

#endif
