#!/usr/bin/env perl
use strict;
use warnings;
use bytes;
use FindBin qw($Bin);
use lib "$Bin/../PerlLib";
use BRCM::SBI_UTIL;
use Getopt::Long;

my $in;
my $out;
my $h;
my $usage = qq[usage: $0 Converts base64 modulus to a binary
	--in file of base64 modulus if specified otherwise standard input will be read from
	--out output filename if specified otherwise will stream to standard output 
	];

GetOptions("in:s", \$in,"out:s",\$out, "help", \$h); 
if ($h) {
	die ($usage);
}
my $obj = BRCM::SBI_UTIL->new();
my $data = $obj->mod2bin((!$in ?  <STDIN> : $obj->f2var($in)));
$out ? $obj->fdump($out, $data) : print STDOUT $data ;

