#!/bin/sh

# Abort on error.
set -e

symlink_match()
{
	local SYMLINK="$1"
	local SYMLINK_TARGET="$2"

	[ "$(readlink "$SYMLINK")" = "$SYMLINK_TARGET" ] || \
	[ "$(readlink -f "$SYMLINK")" = "$SYMLINK_TARGET" ]
}

SYMLINK=/usr/share/doc/comerr-dev
SYMLINK_TARGET=libcomerr2
SYMLINK_TARGET2=libcom-err2

if [ "$1" = "install" -o "$1" = "upgrade" ] &&
   [ -n "$2" ] && [ -h "$SYMLINK" ]
then
    if symlink_match "$SYMLINK" "$SYMLINK_TARGET" ||
       symlink_match "$SYMLINK" "$SYMLINK_TARGET2"
    then
	mv -f "$SYMLINK" "${SYMLINK}.dpkg-backup"
    fi
fi

#DEBHELPER#

exit 0
