#!/bin/sh

# Abort on error.
set -e

symlink_match()
{
	local SYMLINK="$1"
	local SYMLINK_TARGET="$2"

	[ "$(readlink "$SYMLINK")" = "$SYMLINK_TARGET" ] || \
	[ "$(readlink -f "$SYMLINK")" = "$SYMLINK_TARGET" ]
}

SYMLINK=/usr/share/doc/ss-dev
SYMLINK_TARGET=libss2

if [ "$1" = "purge" ] && [ -h "${SYMLINK}.dpkg-backup" ]
then
    rm -f "${SYMLINK}.dpkg-backup"
fi
if [ "$1" = "abort-install" -o "$1" = "abort-upgrade" ] &&
   [ -n "$2" ] && [ ! -e "$SYMLINK" ] && [ -h "${SYMLINK}.dpkg-backup" ] &&
   symlink_match "${SYMLINK}.dpkg-backup" "$SYMLINK_TARGET"
then
    echo "Restoring backup of $SYMLINK ..."
    mv "${SYMLINK}.dpkg-backup" "$SYMLINK"
fi

#DEBHELPER#

exit 0
