/* IGNORE_BCM_KF_EXCEPTION */
/* this file is automatically generated from top level Makefile */
#ifndef __BCM_SWVERSION_H__
#define __BCM_SWVERSION_H__
#define BCM_REL_VERSION 5
#define BCM_REL_RELEASE 2
#define BCM_REL_PATCH 4
#define BCM_SW_VERSIONCODE (5*65536+2*256+4)
#define BCM_SW_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))
#endif
