# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2010  Eric C. Cooper <ecc@cmu.edu>
#
# Based on sheevaplug/Makefile originally written by
# Prafulla Wadaskar <prafulla@marvell.com>
# (C) Copyright 2009
# Marvell Semiconductor <www.marvell.com>

obj-y	:= dockstar.o
