#ifndef __WLCSM_DM_MNGR_STRUCTOFF_H__  
#define __WLCSM_DM_MNGR_STRUCTOFF_H__ 


/*!\file wlcsm_dm_mngr_structoff.h 
 * \brief Automatically generated header file wlcsm_dm_mngr_structoff.h
 */


/* DO NOT INCLUDE THIS HEADER FILE DIRECTLY, INSTEAD INCLUDE wlcsm_lib_dm.h */

#define WLMNGR_DATA_POS_WIFI    (2600)
extern WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI[5];
#define WLMNGR_DATA_POS_WIFI_RADIO    (2601)
extern WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_RADIO[148];
#define WLMNGR_DATA_POS_WIFI_RADIO_STATS    (2602)
extern WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_RADIO_STATS[13];
#define WLMNGR_DATA_POS_WIFI_SSID    (2605)
extern WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_SSID[18];
#define WLMNGR_DATA_POS_WIFI_SSID_STATS    (2606)
extern WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_SSID_STATS[21];
#define WLMNGR_DATA_POS_WIFI_ACCESS_POINT    (2607)
extern WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_ACCESS_POINT[24];
#define WLMNGR_DATA_POS_WIFI_ACCESS_POINT_SECURITY    (2608)
extern WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_ACCESS_POINT_SECURITY[28];
#define WLMNGR_DATA_POS_WIFI_ACCESS_POINT_WPS    (2609)
extern WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_ACCESS_POINT_WPS[8];
#define WLMNGR_DATA_POS_WIFI_ASSOCIATED_DEVICE    (2610)
extern WLCSM_MNGR_NAME_OFFSET  g_WLMNGR_STRUCT_DEV2_WIFI_ASSOCIATED_DEVICE[4];
extern unsigned int g_WLMNGR_OIDS[6];
extern unsigned int g_WLMNGR_OIDS_NUM;
extern unsigned int g_WLMNGR_RUNTIME_OIDS[3];
extern unsigned int g_WLMNGR_RUNTIME_OIDS_NUM;
extern WLCSM_DM_OID_MAPPING g_WLMNGR_OID_MAPPER[9];


#endif

