.TH IW 8 "7 June 2012" "iw" "Linux"
.SH NAME
iw \- show / manipulate wireless devices and their configuration
.SH SYNOPSIS

.ad l
.in +8
.ti -8
.B iw
.RI [ " OPTIONS " ] " " { "
.BR help " [ "
.RI ""command " ]"
.BR "|"
.RI ""OBJECT " " COMMAND " }"
.sp

.ti -8
.IR OBJECT " := { "
.BR dev " | " phy " | " reg " }"
.sp

.ti -8
.IR OPTIONS " := { --version | --debug }"

.SH OPTIONS

.TP
.BR " --version"
print version information and exit.

.TP
.BR " --debug"
enable netlink message debugging.

.SH IW - COMMAND SYNTAX

.SS
.I OBJECT

.TP
.B dev <interface name>
- network interface.

.TP
.B phy <phy name>
- wireless hardware device (by name).
.TP
.B phy#<phy index>
- wireless hardware device (by index).

.TP
.B reg
- regulatory agent.

.SS
.I COMMAND

Specifies the action to perform on the object.
The set of possible actions depends on the object type.
.B iw help
will print all supported commands, while
.B iw help command
will print the help for all matching commands.

.SH SEE ALSO
.BR ip (8),
.BR crda (8),
.BR regdbdump (8),
.BR regulatory.bin (5)

.BR http://wireless.kernel.org/en/users/Documentation/iw
