#
# Copyright 2018 NXP
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-$(CONFIG_IMX8M_DRAM) += helper.o ddrphy_utils.o ddrphy_train.o ddrphy_csr.o
obj-$(CONFIG_IMX8M_LPDDR4) += lpddr4_init.o
obj-$(CONFIG_IMX8M_DDR4) += ddr4_init.o
endif
