#!/bin/bash

# Copy BUILD_NAME/SDK specific binary blobs from new GPL to development repo

#
# Usage: enter the new GPL directory then run this script.
#        Then run by specifying the BUILD_NAME number as argument.
#        REPO will contain the location of your local repository

BUILD_NAME=$1
REPO=/home/merlin/amng

echo "*** Copying platform-specific files..."
if [ "$BUILD_NAME" == "RT-AC88U" ] || [ "$BUILD_NAME" == "RT-AC3100" ] || [ "$BUILD_NAME" == "RT-AC5300" ]
then
	SDK="_7114"
	ARCH="_arm"
	HND=""

	cp release/src/router/ctf_arm/bcm_7114_gmac3/* $REPO/release/src/router/ctf_arm/bcm_7114_gmac3/
	cp release/src/router/wl_arm_7114/prebuilt/* $REPO/release/src/router/wl_arm_7114/prebuilt/$BUILD_NAME/
	cp release/src/router/envram_bin/envram$ARCH$SDK/* $REPO/release/src/router/envram_bin/envram$ARCH$SDK/
	cp release/src-rt-7.14.114.x/src/wl/exe/prebuilt/* $REPO/release/src-rt-7.14.114.x/src/wl/exe/prebuilt/$BUILD_NAME/
	cp -a release/src/router/tuxera/broadcom$ARCH$SDK/* $REPO/release/src/router/tuxera/broadcom$ARCH$SDK/
	if [ -d "release/src/router/ookla_speedtest/prebuild/" ]
	then
		cp release/src/router/ookla_speedtest/prebuild/ookla $REPO/release/src/router/ookla_speedtest/OOKLA-36521/ookla-BCM7.x-6.x
	else
		cp release/src/router/ookla_speedtest/OOKLA-36521/ookla-BCM7.x-6.x $REPO/release/src/router/ookla_speedtest/OOKLA-36521/
	fi

elif [ "$BUILD_NAME" == "RT-AC3200" ]
then
	SDK="_7"
	ARCH="_arm"
	HND=""

	cp release/src/router/ctf_arm/bcm7/* $REPO/release/src/router/ctf_arm/bcm7/
	cp release/src/router/wl_arm_7/prebuilt/* $REPO/release/src/router/wl_arm_7/prebuilt/
	cp release/src-rt-7.x.main/src/wl/exe/prebuilt/* $REPO/release/src-rt-7.x.main/src/wl/exe/prebuilt/
	cp -a release/src/router/tuxera/broadcom$ARCH$SDK/* $REPO/release/src/router/tuxera/broadcom$ARCH$SDK/
	cp release/src/router/ookla_speedtest/OOKLA-36521/ookla-BCM7.x-6.x $REPO/release/src/router/ookla_speedtest/OOKLA-36521/

elif [ "$BUILD_NAME" == "RT-AC56U" ] || [ "$BUILD_NAME" == "RT-AC68U" ] || [ "$BUILD_NAME" == "RT-AC87U" ]
then
	SDK=""
	ARCH="_arm"
	HND=""

	cp release/src/router/ctf_arm/bcm6/* $REPO/release/src/router/ctf_arm/bcm6/
	cp release/src/router/wl_arm/prebuilt/* $REPO/release/src/router/wl_arm/prebuilt/$BUILD_NAME/
	cp release/src-rt-6.x.4708/wl/exe/prebuilt/* $REPO/release/src-rt-6.x.4708/wl/exe/prebuilt/
	cp -a release/src/router/tuxera/broadcom$ARCH$SDK/* $REPO/release/src/router/tuxera/broadcom$ARCH$SDK/
	if [ -d "release/src/router/ookla_speedtest/prebuild/" ]
	then
		cp release/src/router/ookla_speedtest/prebuild/ookla $REPO/release/src/router/ookla_speedtest/OOKLA-36521/ookla-BCM7.x-6.x
	else
		cp release/src/router/ookla_speedtest/OOKLA-36521/ookla-BCM7.x-6.x $REPO/release/src/router/ookla_speedtest/OOKLA-36521/
	fi

elif [ "$BUILD_NAME" == "RT-AC86U" ] || [ "$BUILD_NAME" == "GT-AC2900" ]
then
	SDK="_94908hnd"
	ARCH="_arm"
	HND="_hnd"

	cp release/src/router/hnd_extra/prebuilt/* $REPO/release/src/router/hnd_extra/prebuilt/$BUILD_NAME/
	aarch64-buildroot-linux-gnu-strip --strip-unneeded $REPO/release/src/router/hnd_extra/prebuilt/$BUILD_NAME/*.o
	arm-brcm-linux-uclibcgnueabi-strip $REPO/release/src/router/hnd_extra/prebuilt/$BUILD_NAME/wl
	cp release/src/router/envram_bin/envram$ARCH$SDK/* $REPO/release/src/router/envram_bin/envram$ARCH$SDK/
	cp release/src-rt-5.02hnd/wl/exe/prebuilt/* $REPO/release/src-rt-5.02hnd/wl/exe/prebuilt/
	cp release/src/router/rdpactl/prebuilt/* $REPO/release/src/router/rdpactl/prebuilt/
	cp release/src/router/pwrctl_lib/prebuilt/* $REPO/release/src/router/pwrctl_lib/prebuilt/
	cp release/src/router/bcm_flasher/prebuilt/* $REPO/release/src/router/bcm_flasher/prebuilt/
	cp release/src/router/bcmmcastctl/prebuilt/* $REPO/release/src/router/bcmmcastctl/prebuilt/
	cp release/src/router/bcmtm_lib/prebuilt/* $REPO/release/src/router/bcmtm_lib/prebuilt/
	cp release/src/router/pwrctl/prebuilt/* $REPO/release/src/router/pwrctl/prebuilt/
	cp release/src/router/ethswctl/prebuilt/* $REPO/release/src/router/ethswctl/prebuilt/
	cp release/src/router/wlcsm/prebuilt/* $REPO/release/src/router/wlcsm/prebuilt/
	cp release/src/router/fcctl_lib/prebuilt/* $REPO/release/src/router/fcctl_lib/prebuilt/
	cp release/src/router/swmdk/prebuilt/* $REPO/release/src/router/swmdk/prebuilt/
	cp release/src/router/vlanctl_lib/prebuilt/* $REPO/release/src/router/vlanctl_lib/prebuilt/
	cp release/src/router/mcpctl/prebuilt/* $REPO/release/src/router/mcpctl/prebuilt/
	cp release/src/router/dnsspoof/prebuilt/* $REPO/release/src/router/dnsspoof/prebuilt/
	cp release/src/router/stlport/prebuilt/* $REPO/release/src/router/stlport/prebuilt/
	cp release/src/router/tmctl/prebuilt/* $REPO/release/src/router/tmctl/prebuilt/
	cp release/src/router/mdk/prebuilt/* $REPO/release/src/router/mdk/prebuilt/
	cp release/src/router/ethctl/prebuilt/* $REPO/release/src/router/ethctl/prebuilt/
	cp release/src/router/appeventd/prebuilt/* $REPO/release/src/router/appeventd/prebuilt/
	cp release/src/router/bcm_boardctl/prebuilt/* $REPO/release/src/router/bcm_boardctl/prebuilt/
	cp release/src/router/mcpd/prebuilt/* $REPO/release/src/router/mcpd/prebuilt/
	cp release/src/router/prebuilt/* $REPO/release/src/router/prebuilt/
	cp release/src/router/ethswctl_lib/prebuilt/* $REPO/release/src/router/ethswctl_lib/prebuilt/
	cp release/src/router/bcmtm/prebuilt/* $REPO/release/src/router/bcmtm/prebuilt/
	cp release/src/router/bcm_flashutil/prebuilt/* $REPO/release/src/router/bcm_flashutil/prebuilt/
	cp release/src/router/ethctl_lib/prebuilt/* $REPO/release/src/router/ethctl_lib/prebuilt/
	cp release/src/router/bcm_boot_launcher/prebuilt/* $REPO/release/src/router/bcm_boot_launcher/prebuilt/
	cp release/src/router/bpmctl/prebuilt/* $REPO/release/src/router/bpmctl/prebuilt/
	cp release/src/router/vpmstats/prebuilt/* $REPO/release/src/router/vpmstats/prebuilt/
	cp release/src/router/wlan/util/prebuilt/* $REPO/release/src/router/wlan/util/prebuilt/
	cp release/src/router/wlan/nvram/prebuilt/* $REPO/release/src/router/wlan/nvram/prebuilt/
	cp release/src/router/bcmmcast/prebuilt/* $REPO/release/src/router/bcmmcast/prebuilt/
	cp release/src/router/vlanctl/prebuilt/* $REPO/release/src/router/vlanctl/prebuilt/
	cp release/src/router/fcctl/prebuilt/* $REPO/release/src/router/fcctl/prebuilt/
	cp release/src/router/tmctl_lib/prebuilt/* $REPO/release/src/router/tmctl_lib/prebuilt/
	cp release/src/router/bridgeutil/prebuilt/* $REPO/release/src/router/bridgeutil/prebuilt/
	cp -a release/src/router/tuxera/broadcom$ARCH$HND/* $REPO/release/src/router/tuxera/broadcom$ARCH$HND/
	if [ -d "release/src/router/ookla_speedtest/prebuild/" ]
	then
		cp release/src/router/ookla_speedtest/prebuild/ookla $REPO/release/src/router/ookla_speedtest/OOKLA-36521/ookla-HND
	else
		cp release/src/router/ookla_speedtest/OOKLA-36521/ookla-HND $REPO/release/src/router/ookla_speedtest/OOKLA-36521/
	fi

elif [ "$BUILD_NAME" == "RT-AX88U" ] || [ "$BUILD_NAME" == "RT-AX92U" ]
then
	SDK="_axhnd"
	ARCH="_arm"
	HND="_axhnd"

	cp release/src-rt-5.02axhnd/wl/exe/prebuilt/* $REPO/release/src-rt-5.02axhnd/wl/exe/prebuilt/
	cp -a release/src/router/tuxera/broadcom_arm_ax/* $REPO/release/src/router/tuxera/broadcom_arm_ax/
	if [ -d "release/src/router/ookla_speedtest/prebuild/" ]
	then
		cp release/src/router/ookla_speedtest/prebuild/ookla $REPO/release/src/router/ookla_speedtest/OOKLA-36521/ookla-AXHND
	else
		cp release/src/router/ookla_speedtest/OOKLA-36521/ookla-AXHND $REPO/release/src/router/ookla_speedtest/OOKLA-36521/
	fi

elif [ "$BUILD_NAME" == "RT-AX56U" ] || [ "$BUILD_NAME" == "RT-AX58U" ]
then
	SDK="_6750hnd"
	ARCH="_arm"
	HND="_6750hnd"

	cp release/src-rt-5.02axhnd.675x/wl/exe/prebuilt/* $REPO/release/src-rt-5.02axhnd.675x/wl/exe/prebuilt/
	cp -a release/src/router/tuxera/broadcom_arm_ax_6750/* $REPO/release/src/router/tuxera/broadcom_arm_ax_6750/
	if [ -d "release/src/router/ookla_speedtest/prebuild/" ]
	then
		cp release/src/router/ookla_speedtest/prebuild/ookla $REPO/release/src/router/ookla_speedtest/OOKLA-36521/ookla-AXHND
	else
		cp release/src/router/ookla_speedtest/OOKLA-36521/ookla-AXHND $REPO/release/src/router/ookla_speedtest/OOKLA-36521/
	fi

elif [ "$BUILD_NAME" == "RT-AX86U" ]
then
	SDK="_axhnd"
	ARCH="_arm"
	HND="_axhnd"

	cp release/src-rt-5.02p1axhnd.675x/wl/exe/prebuilt/* $REPO/release/src-rt-5.02p1axhnd.675x/wl/exe/prebuilt/
	cp -a release/src/router/tuxera/broadcom_arm_ax/* $REPO/release/src/router/tuxera/broadcom_arm_ax/
	if [ -d "release/src/router/ookla_speedtest/prebuild/" ]
	then
		cp release/src/router/ookla_speedtest/prebuild/ookla $REPO/release/src/router/ookla_speedtest/OOKLA-36521/ookla-AXHND
	else
		cp release/src/router/ookla_speedtest/OOKLA-36521/ookla-AXHND $REPO/release/src/router/ookla_speedtest/OOKLA-36521/
	fi

else
	echo "Unrecognized BUILD_NAME!"
	exit
fi


# Common to all

echo "*** Copying common files..."
cp release/src/router/lighttpd-1.4.39/prebuild/* $REPO/release/src/router/lighttpd-1.4.39/prebuild/$BUILD_NAME/
cp release/src/router/httpd/prebuild/* $REPO/release/src/router/httpd/prebuild/$BUILD_NAME/
cp release/src/router/rc/prebuild/* $REPO/release/src/router/rc/prebuild/$BUILD_NAME/
cp release/src/router/shared/prebuild/* $REPO/release/src/router/shared/prebuild/$BUILD_NAME/
cp release/src/router/sw-hw-auth/prebuild/* $REPO/release/src/router/sw-hw-auth/prebuild/$BUILD_NAME/
cp release/src/router/bwdpi_source/asus/prebuild/* $REPO/release/src/router/bwdpi_source/asus/prebuild/$BUILD_NAME/
cp release/src/router/bwdpi_source/asus_sql/prebuild/* $REPO/release/src/router/bwdpi_source/asus_sql/prebuild/$BUILD_NAME/
cp release/src/router/bwdpi_source/prebuild/* $REPO/release/src/router/bwdpi_source/prebuild/$BUILD_NAME/
cp release/src/router/dropbox_client/prebuild/* $REPO/release/src/router/dropbox_client/prebuild/$BUILD_NAME/
cp release/src/router/ftpclient/prebuild/* $REPO/release/src/router/ftpclient/prebuild/$BUILD_NAME/
cp release/src/router/protect_srv/prebuild/* $REPO/release/src/router/protect_srv/prebuild/$BUILD_NAME/
cp release/src/router/protect_srv/lib/prebuild/* $REPO/release/src/router/protect_srv/lib/prebuild/$BUILD_NAME/
cp release/src/router/sambaclient/prebuild/* $REPO/release/src/router/sambaclient/prebuild/$BUILD_NAME/
cp release/src/router/u2ec/prebuild/* $REPO/release/src/router/u2ec/prebuild/$BUILD_NAME/
cp release/src/router/wlc_nt/prebuild/* $REPO/release/src/router/wlc_nt/prebuild/$BUILD_NAME/
cp release/src/router/networkmap/prebuild/* $REPO/release/src/router/networkmap/prebuild/$BUILD_NAME/
cp release/src/router/nt_center/prebuild/* $REPO/release/src/router/nt_center/prebuild/$BUILD_NAME/
cp release/src/router/nt_center/actMail/prebuild/* $REPO/release/src/router/nt_center/actMail/prebuild/$BUILD_NAME/
cp release/src/router/nt_center/lib/prebuild/* $REPO/release/src/router/nt_center/lib/prebuild/$BUILD_NAME/
cp release/src/router/webdav_client/prebuild/* $REPO/release/src/router/webdav_client/prebuild/$BUILD_NAME/
cp release/src/router/usbclient/prebuild/* $REPO/release/src/router/usbclient/prebuild/$BUILD_NAME/
cp release/src/router/asuswebstorage/prebuild/* $REPO/release/src/router/asuswebstorage/prebuild/$BUILD_NAME/
cp release/src/router/inotify/prebuild/* $REPO/release/src/router/inotify/prebuild/$BUILD_NAME/
cp release/src/router/libletsencrypt/prebuild/* $REPO/release/src/router/libletsencrypt/prebuild/$BUILD_NAME/
cp release/src/router/libbcm/prebuilt/* $REPO/release/src/router/libbcm/prebuilt/$BUILD_NAME/

# Common to most
echo "*** Copying optional files - ignore errors"
cp release/src/router/dblog/daemon/prebuild/* $REPO/release/src/router/dblog/daemon/prebuild/$BUILD_NAME/
cp release/src/router/dblog/commands/prebuild/* $REPO/release/src/router/dblog/commands/prebuild/$BUILD_NAME/
cp release/src/router/ahs/prebuild/* $REPO/release/src/router/ahs/prebuild/$BUILD_NAME/
cp release/src/router/asd/prebuild/* $REPO/release/src/router/asd/prebuild/$BUILD_NAME/
cp release/src/router/libasc/prebuild/* $REPO/release/src/router/libasc/prebuild/$BUILD_NAME/
cp release/src/router/amas-utils/prebuild/* $REPO/release/src/router/amas-utils/prebuild/$BUILD_NAME/
cp release/src/router/cfg_mnt/prebuild/* $REPO/release/src/router/cfg_mnt/prebuild/$BUILD_NAME/
cp release/src/router/aaews/prebuild/* $REPO/release/src/router/aaews/prebuild/$BUILD_NAME/
cp release/src/router/asusnatnl/natnl/prebuild/* $REPO/release/src/router/asusnatnl/natnl/prebuild/$BUILD_NAME/
cp release/src/router/libasuslog/prebuild/* $REPO/release/src/router/libasuslog/prebuild/$BUILD_NAME/
cp release/src/router/sysstate/log_daemon/prebuild/* $REPO/release/src/router/sysstate/log_daemon/prebuild/$BUILD_NAME/
cp release/src/router/sysstate/commands/prebuild/* $REPO/release/src/router/sysstate/commands/prebuild/$BUILD_NAME/
cp release/src/router/wb/prebuild/* $REPO/release/src/router/wb/prebuild/$BUILD_NAME/
cp release/src/router/eventd/prebuilt/* $REPO/release/src/router/eventd/prebuilt/$BUILD_NAME/

echo "*** Copying exceptions and special cases..."

# HND exceptions
if [ "$HND" == "" ]
then
	cp release/src/router/et$ARCH$SDK/prebuilt/* $REPO/release/src/router/et$ARCH$SDK/prebuilt/
	cp release/src/router/emf$ARCH$SDK/*.o $REPO/release/src/router/emf$ARCH$SDK/
	cp release/src/router/emf$ARCH$SDK/emfconf/prebuilt/* $REPO/release/src/router/emf$ARCH$SDK/emfconf/prebuilt/
	cp release/src/router/emf$ARCH$SDK/igsconf/prebuilt/* $REPO/release/src/router/emf$ARCH$SDK/igsconf/prebuilt/
fi

# On AX these are in router-sysdep
if [ "$BUILD_NAME" != "RT-AX88U" ] && [ "$BUILD_NAME" != "RT-AX92U" ] && [ "$BUILD_NAME" != "RT-AX56U" ] && [ "$BUILD_NAME" != "RT-AX58U" ] && [ "$BUILD_NAME" != "RT-AX86U" ]
then
	cp release/src/router/acsd$ARCH$SDK/prebuilt/* $REPO/release/src/router/acsd$ARCH$SDK/prebuilt/
	cp release/src/router/eapd$ARCH$SDK/linux/prebuilt/* $REPO/release/src/router/eapd$ARCH$SDK/linux/prebuilt/
	cp -a release/src/router/libupnp$ARCH$SDK/* $REPO/release/src/router/libupnp$ARCH$SDK/
	cp release/src/router/nas$ARCH$SDK/nas/prebuilt/* $REPO/release/src/router/nas$ARCH$SDK/nas/prebuilt/
	cp release/src/router/wlconf$ARCH$SDK/prebuilt/* $REPO/release/src/router/wlconf$ARCH$SDK/prebuilt/
	cp release/src/router/wps$ARCH$SDK/prebuilt/* $REPO/release/src/router/wps$ARCH$SDK/prebuilt/
	cp release/src/router/wlceventd/prebuilt/* $REPO/release/src/router/wlceventd/prebuilt/$BUILD_NAME/
	cp release/src/router/dhd_monitor/prebuilt/* $REPO/release/src/router/dhd_monitor/prebuilt/$BUILD_NAME/
fi


# Model-specific
if [ "$BUILD_NAME" == "RT-AC88U" ]
then
	cp release/src/router/rtl_bin/prebuilt/* $REPO/release/src/router/rtl_bin/prebuilt/
fi
if [ "$BUILD_NAME" == "GT-AC2900" ]
then
        cp release/src/router/aura_sw/prebuild/* $REPO/release/src/router/aura_sw/prebuild/$BUILD_NAME/
fi

# Anything newer than SDK6
if [ "$SDK" != "" ]
then
		cp release/src/router/bsd/prebuilt/* $REPO/release/src/router/bsd/prebuilt/$BUILD_NAME/
		cp release/src/router/dhd/prebuilt/* $REPO/release/src/router/dhd/prebuilt/$BUILD_NAME/
fi
