#ifndef RUNNER_C_CODE_ADDRESSES
#define RUNNER_C_CODE_ADDRESSES

#define runner_c_start_task_initialization_task		(0x14)
#define runner_c_initialization_task		(0x14)
#define runner_c_start_task_timer_scheduler_set		(0xEF4)
#define runner_c_timer_scheduler_set		(0xEF4)
#define runner_c_start_task_eth_tx_scheduling_wakeup_request		(0xA48)
#define runner_c_eth_tx_scheduling_wakeup_request		(0xA48)
#define runner_c_start_task_eth_tx_wakeup_request		(0xA90)
#define runner_c_eth_tx_wakeup_request		(0xA90)
#define runner_c_start_task_cpu_tx_wakeup_request		(0x1044)
#define runner_c_cpu_tx_wakeup_request		(0x1044)
#define runner_c_start_task_lan_enqueue_runner_A_wakeup_request		(0x1AC)
#define runner_c_lan_enqueue_runner_A_wakeup_request		(0x1AC)
#define runner_c_start_task_lan_enqueue_runner_B_wakeup_request		(0x1C0)
#define runner_c_lan_enqueue_runner_B_wakeup_request		(0x1C0)
#define runner_c_start_task_lan_enqueue_ds_wakeup_request		(0x58C)
#define runner_c_lan_enqueue_ds_wakeup_request		(0x58C)
#define runner_c_start_task_debug_routine		(0xC4)
#define runner_c_debug_routine		(0xC4)
#define runner_c_start_task_service_queue_enqueue_wakeup_request		(0x484)
#define runner_c_service_queue_enqueue_wakeup_request		(0x484)
#define runner_c_start_task_gso_wakeup_request		(0x2D84)
#define runner_c_gso_wakeup_request		(0x2D84)
#define runner_c_start_task_wlan_mcast_wakeup_request		(0x1F28)
#define runner_c_wlan_mcast_wakeup_request		(0x1F28)
#define runner_c_ds_rate_limiter_budget_allocate		(0xF6C)
#define runner_c_ds_rate_limiter_budget_allocate_loop		(0xF6C)
#define runner_c_ds_service_queue_rate_limiter_budget_allocate		(0x1030)

#endif
