/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 *  Copyright: (c) 2020 Broadcom.
 *  All rights reserved.
 *
 * <:label-BRCM:2022:DUAL/GPL:standard
 * 
 * Unless you and Broadcom execute a separate written software license
 * agreement governing use of this software, this software is licensed
 * to you under the terms of the GNU General Public License version 2
 * (the "GPL"), available at http://www.broadcom.com/licenses/GPLv2.php,
 * with the following added to such license:
 * 
 *    As a special exception, the copyright holders of this software give
 *    you permission to link this software with independent modules, and
 *    to copy and distribute the resulting executable under terms of your
 *    choice, provided that you also meet, for each linked independent
 *    module, the terms and conditions of the license of that module.
 *    An independent module is a module which is not derived from this
 *    software.  The special exception does not apply to any modifications
 *    of the software.
 * 
 * Not withstanding the above, under no circumstances may you combine
 * this software in any way with any other Broadcom software provided
 * under a license other than the GPL, without Broadcom's express prior
 * written consent.
 * 
 * :>
 *
 * File:        allfields.h
 * Purpose:     Field declarations for memory and registers
 * Supports:    bcm56070_a0, bcm96888
 */


#ifndef _SOC_ALLFIELDS_H
#define _SOC_ALLFIELDS_H

#include "macsec_defs.h"

#include <soc/field.h>

extern soc_field_info_t soc_ESEC_MIB_MISCm_fields[];
extern soc_field_info_t soc_ESEC_MIB_ROLLOVER_FIFOm_fields[];
extern soc_field_info_t soc_ESEC_MIB_SAm_fields[];
extern soc_field_info_t soc_ESEC_MIB_SCm_fields[];
extern soc_field_info_t soc_ESEC_MIB_SC_CTRLm_fields[];
extern soc_field_info_t soc_ESEC_MIB_SC_UNCTRLm_fields[];
extern soc_field_info_t soc_ESEC_MISC_COUNTERSm_fields[];
extern soc_field_info_t soc_ESEC_SA_EXPIRE_STATUSm_fields[];
extern soc_field_info_t soc_ESEC_SA_HASH_TABLEm_fields[];
extern soc_field_info_t soc_ESEC_SA_TABLEm_fields[];
extern soc_field_info_t soc_ESEC_SC_TABLEm_fields[];
extern soc_field_info_t soc_ISEC_MIB_ROLLOVER_FIFOm_fields[];
extern soc_field_info_t soc_ISEC_MIB_SAm_fields[];
extern soc_field_info_t soc_ISEC_MIB_SCm_fields[];
extern soc_field_info_t soc_ISEC_MIB_SP_CTRL_1m_fields[];
extern soc_field_info_t soc_ISEC_MIB_SP_CTRL_2m_fields[];
extern soc_field_info_t soc_ISEC_MIB_SP_UNCTRLm_fields[];
extern soc_field_info_t soc_ISEC_PORT_COUNTERSm_fields[];
extern soc_field_info_t soc_ISEC_SA_EXPIRE_STATUSm_fields[];
extern soc_field_info_t soc_ISEC_SCTCAM_HIT_COUNTm_fields[];
extern soc_field_info_t soc_ISEC_SC_TABLEm_fields[];
extern soc_field_info_t soc_ISEC_SC_TCAMm_fields[];
extern soc_field_info_t soc_ISEC_SPTCAM_HIT_COUNTm_fields[];
extern soc_field_info_t soc_ISEC_SP_TCAM_KEYm_fields[];
extern soc_field_info_t soc_ISEC_SP_TCAM_MASKm_fields[];
extern soc_field_info_t soc_MACSEC_TDM_2_CALENDARm_fields[];
extern soc_field_info_t soc_MACSEC_TDM_CALENDARm_fields[];
extern soc_field_info_t soc_SUB_PORT_MAP_TABLEm_fields[];
extern soc_field_info_t soc_SUB_PORT_POLICY_TABLEm_fields[];

#endif  /* !_SOC_ALLFIELDS_H */

