/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 *  Copyright: (c) 2020 Broadcom.
 *  All rights reserved.
 *
 * <:label-BRCM:2022:DUAL/GPL:standard
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as published by
 * the Free Software Foundation (the "GPL").
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * 
 * A copy of the GPL is available at http://www.broadcom.com/licenses/GPLv2.php, or by
 * writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 * 
 * :>
 *
 * File:        intenum.h
*/
  
#ifndef _SOC_INTENUM_6888_H
#define _SOC_INTENUM_6888_H

typedef enum soc_mem_int_e
{
    SOC_MEM_INT_ESEC_MIB_MISCm,
    SOC_MEM_INT_ESEC_MIB_ROLLOVER_FIFOm,
    SOC_MEM_INT_ESEC_MIB_SAm,
    SOC_MEM_INT_ESEC_MIB_SCm,
    SOC_MEM_INT_ESEC_MIB_SC_CTRLm,
    SOC_MEM_INT_ESEC_MIB_SC_UNCTRLm,
    SOC_MEM_INT_ESEC_SA_EXPIRE_STATUSm,
    SOC_MEM_INT_ESEC_SA_HASH_TABLEm,
    SOC_MEM_INT_ESEC_SA_TABLEm,
    SOC_MEM_INT_ESEC_SC_TABLEm,
    SOC_MEM_INT_ISEC_MIB_ROLLOVER_FIFOm,
    SOC_MEM_INT_ISEC_MIB_SAm,
    SOC_MEM_INT_ISEC_MIB_SCm,
    SOC_MEM_INT_ISEC_MIB_SP_CTRL_1m,
    SOC_MEM_INT_ISEC_MIB_SP_CTRL_2m,
    SOC_MEM_INT_ISEC_MIB_SP_UNCTRLm,
    SOC_MEM_INT_ISEC_PORT_COUNTERSm,
    SOC_MEM_INT_ISEC_SA_EXPIRE_STATUSm,
    SOC_MEM_INT_ISEC_SA_HASH_TABLEm,
    SOC_MEM_INT_ISEC_SA_TABLEm,
    SOC_MEM_INT_ISEC_SCTCAM_HIT_COUNTm,
    SOC_MEM_INT_ISEC_SC_TABLEm,
    SOC_MEM_INT_ISEC_SC_TCAMm,
    SOC_MEM_INT_ISEC_SPTCAM_HIT_COUNTm,
    SOC_MEM_INT_ISEC_SP_TCAM_KEYm,
    SOC_MEM_INT_ISEC_SP_TCAM_MASKm,
    SOC_MEM_INT_MACSEC_TDM_2_CALENDARm,
    SOC_MEM_INT_MACSEC_TDM_CALENDARm,
    SOC_MEM_INT_SUB_PORT_MAP_TABLEm,
    SOC_MEM_INT_SUB_PORT_POLICY_TABLEm
} soc_mem_int_t; 

#endif












