.TH HCIATTACH 1 "Jan 22 2002" BlueZ "Linux System Administration"
.SH NAME
hciattach \- attach serial devices via UART HCI to BlueZ stack
.SH SYNOPSIS
.B hciattach
.RB [\| \-b \|]
.RB [\| \-n \|]
.RB [\| \-p \|]
.RB [\| \-t
.IR timeout \|]
.RB [\| \-s
.IR speed \|]
.RB [\| \-l \|]
.RB [\| \-r \|]
.I tty
.IR type \||\| id
.I speed
.I flow
.I bdaddr
.SH DESCRIPTION
.LP
Hciattach is used to attach a serial UART to the Bluetooth stack as HCI
transport interface.
.SH OPTIONS
.TP
.B \-b
Send break.
.TP
.B \-n
Don't detach from controlling terminal.
.TP
.B \-p
Print the PID when detaching.
.TP
.BI \-t " timeout"
Specify an initialization timeout.  (Default is 5 seconds.)
.TP
.BI \-s " speed"
Specify an initial speed instead of the hardware default.
.TP
.B \-l
List all available configurations.
.TP
.B \-r
Set the HCI device into raw mode (the kernel and bluetoothd will ignore it).
.TP
.I tty
This specifies the serial device to attach. A leading
.B /dev
can be omitted. Examples:
.B /dev/ttyS1
.B ttyS2
.TP
.IR type \||\| id
The
.I type
or
.I id
of the Bluetooth device that is to be attached, i.e. vendor or other device
specific identifier. Currently supported types are
.RS
.TP
.B type
.B description
.TP
.B any
Unspecified HCI_UART interface, no vendor specific options
.TP
.B ericsson
Ericsson based modules
.TP
.B digi
Digianswer based cards
.TP
.B xircom
Xircom PCMCIA cards: Credit Card Adapter and Real Port Adapter
.TP
.B csr
CSR Casira serial adapter or BrainBoxes serial dongle (BL642)
.TP
.B bboxes
BrainBoxes PCMCIA card (BL620)
.TP
.B swave
Silicon Wave kits
.TP
.B bcsp
Serial adapters using CSR chips with BCSP serial protocol
.TP
.B ath3k
Atheros AR300x based serial Bluetooth device
.TP
.B intel
Intel Bluetooth device
.RE

Supported IDs are (manufacturer id, product id)
.RS
.TP
.B 0x0105, 0x080a
Xircom PCMCIA cards: Credit Card Adapter and Real Port Adapter
.TP
.B 0x0160, 0x0002
BrainBoxes PCMCIA card (BL620)
.RE

.TP
.I speed
The
.I speed
specifies the UART speed to use. Baudrates higher than 115.200bps require
vendor specific initializations that are not implemented for all types of
devices. In general the following speeds are supported:

.B 9600, 19200, 38400, 57600, 115200, 230400, 460800, 921600

Supported vendor devices are automatically initialised to their respective
best settings.
.TP
.I flow
If the keyword
.I flow
is appended to the list of options then hardware flow control is forced on
the serial link (
.B CRTSCTS
). All above mentioned device types have
.B flow
set by default. To force no flow control use
.B noflow
instead.
.TP
.I sleep
Enables hardware specific power management feature. If
.I sleep
is appended to the list of options then this feature is enabled. To disable
this feature use
.B nosleep
instead.
All above mentioned device types have
.B nosleep
set by default.

Note: This option will only be valid for hardware which support
hardware specific power management enable option from host.
.TP
.I bdaddr
The
.I bdaddr
specifies the Bluetooth Address to use.  Some devices (like the STLC2500)
do not store the Bluetooth address in hardware memory.  Instead it must
be uploaded during the initialization process.  If this argument
is specified, then the address will be used to initialize the device.
Otherwise, a default address will be used.

.SH AUTHORS
Written by Maxim Krasnyansky <maxk@qualcomm.com>
.PP
Manual page by Nils Faerber <nils@kernelconcepts.de>
