.TH RCTEST 1 "Jul 6 2009" BlueZ ""
.SH NAME
rctest \- RFCOMM testing
.SH SYNOPSIS
.B rctest
<\fImode\fR> [\fIoptions\fR] [\fIbdaddr\fR]

.SH DESCRIPTION
.LP
.B
rctest
is used to test RFCOMM communications on the BlueZ stack

.SH MODES
.TP
.B -r
listen and receive
.TP
.B -w
listen and send
.TP
.B -d
listen and dump incoming data
.TP
.B -s
connect and send
.TP
.B -u
connect and receive
.TP
.B -n
connect and be silent
.TP
.B -c
connect, disconnect, connect, ...
.TP
.B -m
multiple connects

.SH OPTIONS
.TP
.BI -b\  bytes
send/receive \fIbytes\fR bytes
.TP
.BI -i\  device
select the specified \fIdevice\fR
.TP
.BI -P\  channel
select the specified \fIchannel\fR
.TP
.BI -U\  uuid
select the specified \fIuuid\fR
.TP
.BI -L\  seconds
enable SO_LINGER options for \fIseconds\fR
.TP
.BI -W\  seconds
enable deferred setup for \fIseconds\fR
.TP
.BI -B\  filename
use data packets from \fIfilename\fR
.TP
.BI -N\  num
send \fInum\fR frames
.TP
.BI -C\  num
send \fInum\fR frames before delay (default: 1)
.TP
.BI -D\  milliseconds
delay \fImilliseconds\fR after sending \fInum\fR frames (default: 0)
.TP
.B -A
request authentication
.TP
.B -E
request encryption
.TP
.B -S
secure connection
.TP
.B -M
become master
.TP
.B -T
enable timestamps

.SH AUTHORS
Written by Marcel Holtmann <marcel@holtmann.org> and Maxim Krasnyansky
<maxk@qualcomm.com>, man page by Filippo Giunchedi <filippo@debian.org>
.PP
