#ifndef RUNNER_C_CODE_ADDRESSES
#define RUNNER_C_CODE_ADDRESSES

#define runner_c_start_task_initialization_task		(0x14)
#define runner_c_initialization_task		(0x14)
#define runner_c_start_task_timer_scheduler_set		(0x790)
#define runner_c_timer_scheduler_set		(0x790)
#define runner_c_start_task_lan_tx_wakeup_request		(0x430)
#define runner_c_lan_tx_wakeup_request		(0x430)
#define runner_c_start_task_cpu_tx_wakeup_request		(0xAB0)
#define runner_c_cpu_tx_wakeup_request		(0xAB0)
#define runner_c_start_task_lan_enqueue_ih_wakeup_request		(0x1C4)
#define runner_c_lan_enqueue_ih_wakeup_request		(0x1C4)
#define runner_c_start_task_lan_enqueue_pd_wakeup_request		(0x208)
#define runner_c_lan_enqueue_pd_wakeup_request		(0x208)
#define runner_c_start_task_multicast_lan_enqueue_wakeup_request		(0x258)
#define runner_c_multicast_lan_enqueue_wakeup_request		(0x258)
#define runner_c_start_task_wlan_mcast_wakeup_request		(0x2DC0)
#define runner_c_wlan_mcast_wakeup_request		(0x2DC0)
#define runner_c_start_task_cpu_rx_int_coalesce_timer_1st_wakeup_request		(0x9F8)
#define runner_c_cpu_rx_int_coalesce_timer_1st_wakeup_request		(0x9F8)
#define runner_c_start_task_debug_routine		(0xDC)
#define runner_c_debug_routine		(0xDC)
#define runner_c_start_task_gso_wakeup_request		(0x1CA0)
#define runner_c_gso_wakeup_request		(0x1CA0)
#define runner_c_start_task_timer_7_1st_wakeup_request		(0x964)
#define runner_c_timer_7_1st_wakeup_request		(0x964)
#define runner_c_start_task_free_skb_index_wakeup_request		(0x900)
#define runner_c_free_skb_index_wakeup_request		(0x900)
#define runner_c_start_task_service_queue_dequeue_wakeup_request		(0x36F8)
#define runner_c_service_queue_dequeue_wakeup_request		(0x36F8)
#define runner_c_start_task_service_queue_enqueue_wakeup_request		(0x37C8)
#define runner_c_service_queue_enqueue_wakeup_request		(0x37C8)
#define runner_c_ds_rate_limiter_budget_allocate		(0x810)
#define runner_c_ds_service_queue_rate_limiter_budget_allocate		(0x8CC)
#define runner_c_schedule_free_skb_index		(0x8E4)
#define runner_c_pps_rate_limiter_timer_wakeup_request		(0x9C8)
#define runner_c_spdsvc_timer_wakeup_request		(0xF88)

#endif
