#ifndef RUNNER_D_CODE_ADDRESSES
#define RUNNER_D_CODE_ADDRESSES

#define runner_d_start_task_initialization_task		(0x14)
#define runner_d_initialization_task		(0x14)
#define runner_d_start_task_timer_scheduler_set		(0x1BE0)
#define runner_d_timer_scheduler_set		(0x1BE0)
#define runner_d_start_task_flow_cache_wakeup_request		(0xD84)
#define runner_d_flow_cache_wakeup_request		(0xD84)
#define runner_d_start_task_lan_dispatch_wakeup_request		(0x19C0)
#define runner_d_lan_dispatch_wakeup_request		(0x19C0)
#define runner_d_start_task_lan_cpu_wakeup_request		(0x154)
#define runner_d_lan_cpu_wakeup_request		(0x154)
#define runner_d_start_task_lan_normal_wakeup_request		(0x19C)
#define runner_d_lan_normal_wakeup_request		(0x19C)
#define runner_d_start_task_debug_routine		(0x6C)
#define runner_d_debug_routine		(0x6C)
#define runner_d_start_task_free_skb_index_wakeup_request		(0x1D5C)
#define runner_d_free_skb_index_wakeup_request		(0x1D5C)
#define runner_d_free_skb_index_tx_abs_done		(0x1D5C)
#define runner_d_start_task_dhd_rx_complete_wakeup_request		(0x1EC4)
#define runner_d_dhd_rx_complete_wakeup_request		(0x1EC4)
#define runner_d_gpe_sop_push_replace_ddr_sram_32		(0x1374)
#define runner_d_gpe_sop_push_replace_sram_32_64		(0x13E8)
#define runner_d_gpe_sop_push_replace_sram_64		(0x13FC)
#define runner_d_gpe_sop_push_replace_sram_64_32		(0x1410)
#define runner_d_gpe_sop_pull_replace_ddr_sram_32		(0x1424)
#define runner_d_gpe_sop_pull_replace_sram_32_64		(0x1498)
#define runner_d_gpe_sop_pull_replace_sram_64		(0x14E8)
#define runner_d_gpe_sop_pull_replace_sram_64_32		(0x1524)
#define runner_d_gpe_replace_pointer_32_ddr		(0x1574)
#define runner_d_gpe_replace_pointer_32_sram		(0x1598)
#define runner_d_gpe_replace_pointer_64_sram		(0x15BC)
#define runner_d_gpe_replace_16		(0x15E0)
#define runner_d_gpe_replace_32		(0x1614)
#define runner_d_gpe_replace_bits_16		(0x1638)
#define runner_d_gpe_copy_add_16_cl		(0x1664)
#define runner_d_gpe_copy_add_16_sram		(0x1670)
#define runner_d_gpe_copy_bits_16_cl		(0x16B8)
#define runner_d_gpe_copy_bits_16_sram		(0x16C4)
#define runner_d_gpe_insert_16		(0x170C)
#define runner_d_gpe_delete_16		(0x1774)
#define runner_d_gpe_decrement_8		(0x17B4)
#define runner_d_gpe_apply_icsum_16		(0x17D8)
#define runner_d_gpe_apply_icsum_nz_16		(0x17FC)
#define runner_d_gpe_compute_csum_16_cl		(0x1838)
#define runner_d_gpe_compute_csum_16_sram		(0x1844)
#define runner_d_gpe_buffer_copy_16_sram		(0x1884)
#define runner_d_gpe_buffer_copy_16_ddr		(0x18AC)
#define runner_d_upstream_ingress_rate_limiter_budget_allocate		(0x1C60)
#define runner_d_upstream_quasi_budget_allocate		(0x1CE0)
#define runner_d_schedule_free_skb_index		(0x1D40)

#endif
