/*
   Copyright (c) 2015 Broadcom
   All Rights Reserved

    <:label-BRCM:2015:DUAL/GPL:standard

    Unless you and Broadcom execute a separate written software license
    agreement governing use of this software, this software is licensed
    to you under the terms of the GNU General Public License version 2
    (the "GPL"), available at http://www.broadcom.com/licenses/GPLv2.php,
    with the following added to such license:

       As a special exception, the copyright holders of this software give
       you permission to link this software with independent modules, and
       to copy and distribute the resulting executable under terms of your
       choice, provided that you also meet, for each linked independent
       module, the terms and conditions of the license of that module.
       An independent module is a module which is not derived from this
       software.  The special exception does not apply to any modifications
       of the software.

    Not withstanding the above, under no circumstances may you combine
    this software in any way with any other Broadcom software provided
    under a license other than the GPL, without Broadcom's express prior
    written consent.

:>
*/



/* This is an automated file. Do not edit its contents. */


#include "rdd.h"
#include "ru_types.h"

#include "rdd_data_structures_auto.h"

/* >>>RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xd00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_REGISTERS_BUFFER_ADDRESS_ARR */
uint32_t RDD_REGISTERS_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xd40,
	0x640,
	0x900,
};
/* <<<RDD_REGISTERS_BUFFER_ADDRESS_ARR */


/* >>>RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xdc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */
uint32_t RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xde2,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xde4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */


/* >>>RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xde6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xde7,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xde8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_FPM_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xdf0,
	0xb30,
	0xa70,
};
/* <<<RDD_FPM_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_TASK_IDX_ADDRESS_ARR */
uint32_t RDD_TASK_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xdfc,
	0xb3c,
	0x764,
};
/* <<<RDD_TASK_IDX_ADDRESS_ARR */


/* >>>RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xe00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1500,
	0x6c0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR */
uint32_t RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1520,
	0x160,
	0x980,
};
/* <<<RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1540,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */


/* >>>RDD_SRAM_DUMMY_STORE_ADDRESS_ARR */
uint32_t RDD_SRAM_DUMMY_STORE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1554,
	0xb49,
	0x9ed,
};
/* <<<RDD_SRAM_DUMMY_STORE_ADDRESS_ARR */


/* >>>RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1555,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1558,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1560,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1580,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x15a0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1600,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */
uint32_t RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */


/* >>>RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR */
uint32_t RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1c00,
	0xc00,
	0x400,
};
/* <<<RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x0,
	0x800,
};
/* <<<RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x100,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR */
uint32_t RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x140,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x180,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x200,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_SCRATCH_ADDRESS_ARR */
uint32_t RDD_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x290,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2b0,
	0x9b0,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2c0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x300,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x380,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3f8,
	0x768,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x400,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x600,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x6e0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x6f0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x6fc,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x700,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x728,
	0xa60,
};
/* <<<RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x730,
	0xa20,
};
/* <<<RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x740,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x760,
	0xa30,
};
/* <<<RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x770,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */


/* >>>RDD_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x780,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_TO_TC_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_TO_TC_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x7a0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_TO_TC_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x7e0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x7f0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_RX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_RX_FLOW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x800,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_TC_TO_CPU_RXQ_ADDRESS_ARR */
uint32_t RDD_TC_TO_CPU_RXQ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xa80,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TC_TO_CPU_RXQ_ADDRESS_ARR */


/* >>>RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR */
uint32_t RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xac0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xb00,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xb28,
	0xa68,
};
/* <<<RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xb40,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xb48,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_COUNTER_MAX_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_COUNTER_MAX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xb4a,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_COUNTER_MAX_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xb4c,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xb4e,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR */


/* >>>RDD_MAC_TYPE_ADDRESS_ARR */
uint32_t RDD_MAC_TYPE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xb50,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_MAC_TYPE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xb80,
	0xb00,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xe00,
	0xb80,
};
/* <<<RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xe80,
	0xc00,
};
/* <<<RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR */


/* >>>RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3000,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x0,
};
/* <<<RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_TX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_TX_FLOW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x600,
};
/* <<<RDD_TX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR */
uint32_t RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x740,
};
/* <<<RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR */


/* >>>RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x770,
};
/* <<<RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_RING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_RING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x780,
};
/* <<<RDD_CPU_TX_RING_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_REPLY_ADDRESS_ARR */
uint32_t RDD_FPM_REPLY_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x9a0,
};
/* <<<RDD_FPM_REPLY_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x9c0,
};
/* <<<RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x9e0,
};
/* <<<RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_CORE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_CORE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x9ec,
};
/* <<<RDD_CORE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x9f0,
};
/* <<<RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa00,
};
/* <<<RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa40,
};
/* <<<RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa80,
};
/* <<<RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR */

