# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
# (C) Copyright 2010
# Ilya Yanok, Emcraft Systems, yanok@emcraft.com

obj-y	:= mpc8308_p1m.o sdram.o
